### ISSUE TITLE
Concurrent call contract, transaction number on block is always 1?

### ISSUE THREAD

**Issue by woyinzf** [web3j/web3j#102]
Concurrent call contract, transaction number on block is always 1

Debug code found, web3j Async class in the "runAsync" method asyncPool config is always 3

The following is my screenshot
1: my concurrency call; 	2,3,4: is web3j involved in the method; 	5. block on the number of transactions

<img width="1228" alt="1" src="https://user-images.githubusercontent.com/13416056/27022653-82679f12-4f81-11e7-9c9e-ec2963fef8c7.png">
<img width="1005" alt="2" src="https://user-images.githubusercontent.com/13416056/27022654-8271efe4-4f81-11e7-9b3e-bc58e36add19.png">
<img width="1028" alt="3" src="https://user-images.githubusercontent.com/13416056/27022655-827cddc8-4f81-11e7-94eb-8d08c7320746.png">
<img width="765" alt="4" src="https://user-images.githubusercontent.com/13416056/27022656-82899f72-4f81-11e7-8d0a-4032161f1176.png">
<img width="839" alt="5" src="https://user-images.githubusercontent.com/13416056/27022677-9c27636a-4f81-11e7-9c84-eafd43e6193e.png">

How do I increase the number of transactions on a block when calling a contract?

**Comment by conor10** [comment]
By default web3j queries your Geth/Parity node for the next nonce prior to sending each transaction. These will not necessarily be updated following each submitted request. See https://github.com/web3j/web3j/issues/54 for details - I'm assuming you're using the most recent version of web3j?

Please consider using the FastRawTransactionManager instead - see https://github.com/web3j/web3j/blob/master/src/integration-test/java/org/web3j/protocol/scenarios/FastRawTransactionManagerIT.java.
