### ISSUE TITLE
how to create a whisper message?

### ISSUE THREAD

**Issue by MrFanLee** [web3j/web3j#1021]
## Feature description_
how to create a whisper message?

##and how to receive the message?

**Comment by MrFanLee** [comment]
i use shhpost like these：

        ShhPost conPost = new ShhPost("0xb9cc8dbf9e2008f37f5b0a9c467020d658ba908c",
                "0xdc2841c89cdbe8b278cefd8fd6a71ed94eef629c",
                Arrays.asList("0x776869737065722d636861742d636c69656e74", "0x4d5a695276454c39425154466b61693532"),
                "0xabcd",
                new BigInteger("64"),
                new BigInteger("64"));
        admin.shhPost(conPost).send().messageSent();

but it shows a exception：
Exception in thread "main" java.lang.NullPointerException
	at org.web3j.protocol.core.methods.response.ShhPost.messageSent(ShhPost.java:11)

and geth shows：
invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go value of type hexutil.Bytes
invalid argument 0: json: cannot unmarshal string into Go struct field NewMessage.ttl of type uint32

**Comment by MrFanLee** [comment]
As i kown, Whisper v5 is reaching its end of life and will be deleted from geth on March the 1st. Please use v6. So does web3J use the V6? In this version, shhpost RPC works like this: shh_post
Creates a whisper message and injects it into the network for distribution.

Parameters
Object. Post options object with the following properties:
symKeyID - String: ID of symmetric key for message encryption.
pubKey - String: public key for message encryption.
sig - String (optional): ID of the signing key.
ttl - Number: Time-to-live in seconds.
topic - String 4 Bytes (mandatory when key is symmetric): Message topic.
payload - String: Payload to be encrypted.
padding - String (optional): Optional padding (byte array of arbitrary length).
powTime - Number: Maximal time in seconds to be spent on proof of work.
powTarget - Number: Minimal PoW target required for this message.
targetPeer - String (optional): Optional peer ID (for peer-to-peer message only).
Either symKeyID or pubKey must be present. Can not be both.

Returns
Boolean: true on success and an error on failure.

It seems different from the version which web3J used.

**Comment by codingchili** [comment]
Trying to create a new shh identity with `web3.shhNewIdentity().sendAsync()` gives me the following error in the geth log,

```console
WARN [10-23|19:24:18.348] Served shh_newIdentity                   reqid=0   t=20.048µs err="the method shh_newIdentity does not exist/is not available"
WARN [10-23|19:24:18.385] Served shh_post                          reqid=1   t=90.925µs err="invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go value of type hexutil.Bytes"
```
the post probably fails because I didn't supply an address.

running latest release, build.gradle
```groovy
compile 'org.web3j:core:4.5.5'
```

reproducer invoking the api,
```
web3.shhNewIdentity().sendAsync()
```

geth 1.9.6, started with
```
geth --testnet --graphql --shh --rpcapi admin,miner,eth,web3 --rpc console
```

Related
https://github.com/ethereum/web3.js/issues/874

Seems that shh_newIdentity was replaced in Geth 1.6.1.

**Comment by codingchili** [comment]
It would also appear as if the test cases for newIdentity, newGroup and version has been disabled at least 3 years ago due to this. Is support for whisper being dropped? maybe remove the API's until it's fixed?

**Comment by MrFanLee** [comment]
你好，已收到你的来信，谢谢通知。
