### ISSUE TITLE
Release web3j-android

### ISSUE THREAD

**Issue by angerborn** [web3j/web3j#1030]
There's a branch for the 4.3.0-android release, but there's nothing under https://github.com/web3j/web3j/releases and nothing on maven central https://search.maven.org/search?q=g:org.web3j%20AND%20a:core&core=gav

Was there a problem creating the release, was it forgotten or was it buried below more important tasks? (Or am I just not looking in the right place?)

**Comment by iikirilov** [comment]
Mainly buried - partly forgotten. I would like someone from the community to pick up this work - it requires merging all PRs labelled "merge-to-android" to an android branch.

It will mean we skip a few version on the android side.

**Comment by Water-bamboo** [comment]
Would you please release 4.3-android?

**Comment by om26er** [comment]
I see a new tag for Android, so I guess the Android version has finally progressed https://github.com/web3j/web3j/releases/tag/v4.6.0-android ?

**Comment by AlexandrouR** [comment]
4.6.0 android version can be found [here](https://mvnrepository.com/artifact/org.web3j/core/4.6.0-android)
