### ISSUE TITLE
Release 4.5.1 artifacts missing for brew install

### ISSUE THREAD

**Issue by openwhalereef** [web3j/web3j#1037]
# _Bug_title_
_brew install web3j fails._

## Steps To Reproduce
_brew install web3j._

### Expected behavior
_web3j should be installed successfully on a mac that has brew (homebrew) installed and working._

### Actual behavior
_Download failed: https://github.com/web3j/web3j/releases/download/v4.5.1/web3j-4.5.1.zip._

## Environment
_Describe the environment in which the issue occurs_
- Web3j version: 4.5.1 (latest)
- Java or Android version
- Operating System: Mac OSX Mojave

## Additional context
Just make the artifact available as in the previous releases and it will work!

**Comment by openwhalereef** [comment]
Now there is a checksum mismatch
`ChecksumMismatchError: SHA256 mismatch`

**Comment by AlexandrouR** [comment]
@openwhalereef There is a PR to fix that once that it merged it will be fixed

**Comment by openwhalereef** [comment]
Warning: Some installed formulae are not readable:
  web3j: /usr/local/Homebrew/Library/Taps/web3j/homebrew-web3j/web3j.rb:5: syntax error, unexpected <<, expecting keyword_end
<<<<<<< HEAD
  ^
/usr/local/Homebrew/Library/Taps/web3j/homebrew-web3j/web3j.rb:9: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Taps/web3j/homebrew-web3j/web3j.rb:13: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Change web3j version to ${VERSION}
  ^
/usr/local/Homebrew/Library/Taps/web3j/homebrew-web3j/web3j.rb:13: `${' is not allowed as a global variable name
/usr/local/Homebrew/Library/Taps/web3j/homebrew-web3j/web3j.rb:13: syntax error, unexpected end-of-input, expecting keyword_end
>>>>>>> Change web3j version to ${VERSION}
                                 ^

**Comment by openwhalereef** [comment]
@AlexandrouR looks like merge conflicts were not resolved properly.

**Comment by AlexandrouR** [comment]
@openwhalereef 
`cd /usr/local/Homebrew/Library/Taps/web3j/homebrew-web3j`
`git reset --hard origin/master` 
that should do the trick
