### ISSUE TITLE
Leading Zeros of Function Code Removed in Transaction

### ISSUE THREAD

**Issue by mawenpeng** [web3j/web3j#104]
@conor10 
I have a contract function signature: writeUserMapOplog(bytes32,address,bytes32,uint256)

After encoding it should be 0x00f6da93.

> web3.sha3("writeUserMapOplog(bytes32,address,bytes32,uint256)").substring(0,10)
"0x00f6da93"

But when I run it in a transaction, it fails.
I observed that in transaction input, the leading zeros removed.
> eth.getTransaction("0x...................")
{
......
input: "0x**f6da93**61616130303030303030303030303030303030303030303030303030303030300000000000000000000000008e82930455612bb1815caffb1e006cda961df8196262623030303030303030303030303030303030303030303030303030303030000000000000000000000000000000000000000000000000000000000000000a",
  nonce: 725,
......
}

I debugged the code, found the leading zeros removed in org.web3j.tx.RawTransactionManager, method

> 

    public EthSendTransaction signAndSend(RawTransaction rawTransaction)
            throws IOException {

        byte[] signedMessage;

        if (chainId > ChainId.NONE) {
            signedMessage = TransactionEncoder.signMessage(rawTransaction, chainId, credentials);
        } else {
            signedMessage = TransactionEncoder.signMessage(rawTransaction, credentials);
        }

        String hexValue = Numeric.toHexString(signedMessage);

        return web3j.ethSendRawTransaction(hexValue).send();
    }

Further more, it should be removed in TransactionEncoder.signMessage.

Thanks.

**Comment by conor10** [comment]
Fixed.
