### ISSUE TITLE
Where is 4.5.5?

### ISSUE THREAD

**Issue by mslinn** [web3j/web3j#1053]
I subscribe to new releases, and received an email that [v4.5.5](https://github.com/web3j/web3j/releases/tag/v4.5.5) was released 2 days ago. I see the git tag for that version exists, and I see the [GitHub releases page](https://github.com/web3j/web3j/releases/tag/v4.5.5) for that version exists, but [Maven Central only shows releases up to 4.5.4](https://repo1.maven.org/maven2/org/web3j/utils/).

**Comment by iikirilov** [comment]
takes about 3 days to sync to maven central :/ if you need it - use bintray jcenter.

https://bintray.com/web3j/maven/org.web3j

**Comment by mslinn** [comment]
Still don't see the library, and neither resolver works for 4.5.5.

**Comment by antonydenyer** [comment]
Hi @mslinn we're in the process of reviewing where and how we publish artifacts. At the moment we're using the sonatype gateway which according to bintray

> the Maven Central gateway at Sonatype fluctuates. This operation may take several minutes depending on the weather.

in our own experience, this seems to be down more often than not for us so consequently, you have to regularly go back and check that it synced manually. Then once it's synced it still takes a couple of days before it actually shows up on mvnrepository.

It's a pain as we want to be able to release as regularly as possible but these kinds of things make it painful.
