### ISSUE TITLE
How pass array of types in Function for FunctionEncoder

### ISSUE THREAD

**Issue by helderjnpinto** [web3j/web3j#1068]
# _Issue_title_
how i can encode correctly the function call with correct parameters. 
The address types will get as uint160.
The uint256 parameters is correct type.

## _Issue_description_
solidity: 
- safeBatchTransfer(address[], uint256[])

Java: 
```
org.web3j.abi.datatypes.Address _gasManager =
    new org.web3j.abi.datatypes.Address(gasManager.toString());
// batch transfer
List<org.web3j.abi.datatypes.Address> listAddresses = new ArrayList<>();
List<Uint256> listAmounts = new ArrayList<>();

listAddresses.add( new org.web3j.abi.datatypes.Address(miningBeneficiary.toString()));
listAddresses.add( new org.web3j.abi.datatypes.Address(gasManager.toString()));

listAmounts.add(new Uint256(minerFee));
listAmounts.add(new Uint256(additionalFeeToCharge));

List<Type> encodedInput = new ArrayList<>();

encodedInput.add(listAddresses);
encodedInput.add(listAmounts);

transferFunctionCall = new Function(
    "safeBatchTransfer",
    encodedInput,
    Collections.emptyList());

// FunctionEncoder.encode(transferFunctionCall) <- cause an error
```
## _Issue_context_
Print with evaluation 
![image](https://user-images.githubusercontent.com/12281088/66599439-21bcf280-eb9b-11e9-86db-7e3b15e2d5ae.png)

**Comment by helderjnpinto** [comment]
With DynamicArray the result encoded not crash and i think is correct 
` inputParameters.add(new DynamicArray(listAddresses));
        inputParameters.add(new DynamicArray(listAmounts));
        transferFunctionCall = new Function(
            "safeBatchTransfer",
            inputParameters,
            Collections.emptyList());`
but this method is deprecated. 
What is the alternative to this?

**Comment by AlexandrouR** [comment]
```
 List<Type> inputParameters = new ArrayList<>();
 inputParameters.add(new DynamicArray<>(Address.class, listAddresses));
 inputParameters.add(new DynamicArray<>(Uint256.class, listAmounts));
 Function test = new Function(
 "safeBatchTransfer",
  inputParameters,
  Collections.emptyList());
```

The right way to do it is with a DynamicArray.
You can check the example I provided which features a constructor that is not deprecated.

**Comment by helderjnpinto** [comment]
@AlexandrouR thank you!

**Comment by helderjnpinto** [comment]
If i make the build or run in intellij all run fine, but when i try to build a docker image show this. 
![image](https://user-images.githubusercontent.com/12281088/67016766-a1454700-f0f0-11e9-9108-e6c9e565f195.png)
