### ISSUE TITLE
Android release seems to be packaged with the wrong files

### ISSUE THREAD

**Issue by DomAmato** [web3j/web3j#1069]
# Android release seems to be packaged with the wrong files
If you browse the files that gradle pulls down when you add `'org.web3j:core:4.2.0-android'` to your project it seems to have the files from the master branch and not the android branch...

Here is the latest commit history to Sign.java in the crypto package: https://github.com/web3j/web3j/blob/1b343b2f690d48b608e4833b5850709a4547301c/crypto/src/main/java/org/web3j/crypto/Sign.java

And here is the files that gradle pulls down.
![AndroidGradleFiles](https://user-images.githubusercontent.com/6936055/66727890-7ebce080-ee07-11e9-9aea-3af3daf459e3.png)

## Steps To Reproduce
Install the android package and inspect the files

### Expected behavior
It should have the android specific class implementations

### Actual behavior
It does not have the android specific classes

## Environment
_Describe the environment in which the issue occurs_
- Web3j version: 4.20
- Android version
- Operating System: WIndows 10 but irrelevant

## Additional context
I think its pretty clear what the problem is

**Comment by AlexandrouR** [comment]
As the latest version for android is 4.6 this issue is no longer relevant.
