### ISSUE TITLE
Can't create Credentials with WalletUtils.loadCredentials?

### ISSUE THREAD

**Issue by libbytron** [web3j/web3j#107]
Credentials credentials = WalletUtils.loadCredentials(
					"password", 
					"path/to/wallet/file");

gives "Default constructor cannot handle exception type CipherException thrown by implicit super constructor. Must define an explicit constructor"

**Comment by conor10** [comment]
What JDK version are you using?

**Comment by conor10** [comment]
Hi - are you still having this issue?

**Comment by conor10** [comment]
Closing as no updates.
