### ISSUE TITLE
Android Web3j.build Error

### ISSUE THREAD

**Issue by seansanders** [web3j/web3j#1075]
# Android Web3j.build Error
The issue I am running into is that web3j's build symbol is not being recognized. It appears even though adding in the dependency does not work.

## Steps To Reproduce
1) Create a empty activity android studio project. 
2) In the build.gradle (Module:app) add the line "implementation ('org.web3j:core:4.1.0-android')" to the file and sync.
3) In the build.gradle() (Project:[ProjectName]) add mavenCentral() to the repository section.
4) Add to your main function under onCreate  in the Main function the following code:

```package com.example.adsmartcontract;
import androidx.appcompat.app.AppCompatActivity;
import android.os.Bundle;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.http.HttpService;
import android.util.Log;

public class MainActivity extends AppCompatActivity {
    private Web3j web3j;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        web3j = new Web3j.build(new HttpService());

        Log.d("ETH", web3j.ethAccounts().toString());

    }
}
```
### Expected behavior
I am expecting not to have an error with the build symbol not being recognized.

### Actual behavior
Symbol build cannot be recognized.

## Environment
I am currently running Android Studio on Ubuntu 19.04 with Java SDK 1.8. 
- Web3j version is org.web3j:core:4.1.0-android
- Java or Android version is androidx.appcompat:appcompat:1.0.2
- Operating System Ubuntu Linux 19.04

## Additional context
I am assuming it could be a problem with the library, but I have tried a lot of fixes, but nothing seems to fix the bug. 

Error is displaying as follows in red:
![ErrorAndroid](https://user-images.githubusercontent.com/11840058/67299043-24341c00-f4ba-11e9-9513-f300831f8645.png)

**Comment by AlexandrouR** [comment]
` web3j = Web3j.build() ` not new Web3j.build()

**Comment by seansanders** [comment]
AlexandrouR, I tried that variation, but Web3jFactory is not being recognized for some reason. 
It also appears that web3jfactory is no longer recognized for the implementation of org.web3j:core:4.1.0-android. 
I also tried doing the following import: **import org.web3j.protocol.Web3jFactory**. 

This appears to be a bizarre issue.

**Comment by seansanders** [comment]
I ended up fixing the issue by using Web3j.build(new HttpService("http://localhost:8545"));
I am unsure how I exactly fixed this, but it was quite a strange issue.
Thanks to everyone for their help.
