### ISSUE TITLE
why RemoteFunctionCall cannot resolved in 4.2.0-android?

### ISSUE THREAD

**Issue by parcool** [web3j/web3j#1092]
##### step:
* copy the contract code form [etherscan.io](https://etherscan.io/address/0xdac17f958d2ee523a2206206994597c13d831ec7#code)
* `$ solcjs USDP.sol --bin --abi --optimize -o .`
* `$ web3j solidity generate --javaTypes -b ~/USDP_sol_TetherToken.bin -a ~/USDP_sol_TetherToken.abi -o ~ -p com.test.mywallet.stablecoin.eth.usdt`
* copy it to my project.

anyone can help me?

**Comment by seansanders** [comment]
I actually had this error myself. 
What I found I had to do was be sure to include in my build.gradle file implementation('org.web3j:core:4.5.6'). 
This will have to be placed in your dependencies location. 
Also, as a side note, be sure to enable the permissions for internet access in your andoridManifest.xml file. 
It seems like your wrapper web3j command is correct.

**Comment by AlexandrouR** [comment]
@parcool is this still an issue?

**Comment by Struka9** [comment]
> @parcool is this still an issue?

I think it is, just tried and seems to be missing from 4.2.0-android

**Comment by sonh** [comment]
I has the same issue when using only "org.web3j:core:4.2.0-android"

**Comment by kuabhish** [comment]
Same problem I am also facing.

**Comment by AlexandrouR** [comment]
This issue is no longer relevant as the latest android version is 4.6.0 therefore this should be fixed. If however, the issue persists please create a new issue.
