### ISSUE TITLE
Estimating gas fee of an ERC20 token transfer returns "gas required exceeds allowance or always failing transaction"

### ISSUE THREAD

**Issue by chess-equality** [web3j/web3j#1095]
# _Bug title_
As with the title, I'm getting the error "gas required exceeds allowance or always failing transaction".

## Steps To Reproduce
I'm trying to use `Transaction.createContractTransaction` along with `web3j.ethEstimateGas` to estimate the gas fee (I'm using Kotlin by the way):

```
val function = Function(MyToken.FUNC_TRANSFER, listOf(Address(destination), Uint256(amount)), emptyList())
val txData: String = FunctionEncoder.encode(function)

logger.info(">>>>>>>>>> txData = $txData")

val ethGasPrice: EthGasPrice = web3j.ethGasPrice().sendAsync().get()
val transaction: Transaction = Transaction.createContractTransaction(
		credentials.address,
		nonce,
		ethGasPrice.gasPrice,
		DefaultGasProvider.GAS_LIMIT,
		amount,
		txData)

val ethEstimateGas = web3j.ethEstimateGas(transaction).sendAsync().get()
```

### Expected behavior
I should get the estimated gas fee.

## Environment
_Describe the environment in which the issue occurs_
- Web3j version: 4.5.5
- Java or Android version: GraalVM 19.2.1 (JDK 1.8.0_232)
- Operating System: Linux Lite 4.6

**Comment by SweeXordious** [comment]
Hello,
Instead of using the `createContractTransaction`, use the `createFunctionCallTransaction`.
The code should look something like that

```
    val transaction = Transaction.createFunctionCallTransaction(credentials.address,
        BigInteger.ONE,  ethGasPrice.gasPrice, DefaultGasProvider.GAS_LIMIT, contractAddress, BigInteger.valueOf(10000000000), txData)
```

**Comment by AlexandrouR** [comment]
@chess-equality is this still an issue?
