### ISSUE TITLE
Version 4.5.7 adds dependency on LGPL trove4j

### ISSUE THREAD

**Issue by ajsutton** [web3j/web3j#1105]
# _Issue_title_
Version 4.5.7 adds a dependency on the LGPL module trove4j.

## _Issue_description_
When upgrading from version 4.5.6 to 4.5.7 and additional transitive dependency on trove4j which is licensed under the LGPL license. While it's most likely within the terms of the license to use LGPL from an apache2 project (there is some debate), it makes a lot of enterprise customers very nervous. As a result it's common for Apache 2 projects to avoid LGPL dependencies.

## _Issue_context_
The LGPL dependency will prevent Hyperledger Besu from upgrading to 4.5.7.

The dependency appears to come in via ktlint which may not actually be needed on the production class path:

```
+--- org.web3j:utils:4.5.7
     |    |    |    |    |    +--- org.bouncycastle:bcprov-jdk15on:1.61 -> 1.64
     |    |    |    |    |    \--- com.github.shyiko:ktlint:0.31.0
     |    |    |    |    |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 -> 1.3.50
     |    |    |    |    |         |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50
     |    |    |    |    |         |    \--- org.jetbrains:annotations:13.0
     |    |    |    |    |         +--- com.github.shyiko.ktlint:ktlint-core:0.31.0
     |    |    |    |    |         |    \--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.21
     |    |    |    |    |         |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 -> 1.3.50 (*)
     |    |    |    |    |         |         +--- org.jetbrains.kotlin:kotlin-script-runtime:1.3.21
     |    |    |    |    |         |         +--- org.jetbrains.kotlin:kotlin-reflect:1.3.21
     |    |    |    |    |         |         |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 -> 1.3.50 (*)
     |    |    |    |    |         |         \--- org.jetbrains.intellij.deps:trove4j:1.0.20181211           <<<<<<<<
```

**Comment by antonydenyer** [comment]
That has been removed in master already (https://github.com/web3j/web3j/commit/24675bdabd28005053476b8d35482a56206be324#diff-c197962302397baf3a4cc36463dce5eaL64). The dependency should now only get pulled when you run `./gradlew spotlessCheck` and should not end up in the implementation. 

We should be release 4.5.8 this week.

That being said It looks like we could do with a tidy up of some of the other dependencies.

**Comment by antonydenyer** [comment]
Fixed in https://github.com/hyperledger/besu/pull/225

We will be adding a license check in due course so we don't get caught out again.
