### ISSUE TITLE
indexed string event parameter mapped to byte array

### ISSUE THREAD

**Issue by ppeinsold** [web3j/web3j#1109]
# _Issue_title_
_A clear and concise description of what the issue is._
I have a question regarding events and filter. I have a .sol contract which fires an event defined like this:
`event myEvent(address userAddress, string indexed userId);`
before that the event was defined like that:
`event myEvent(address userAddress, string userId);`

I indexed the userId parameter so that I can filter the events afterwards.
Then I created the .java file of the contract with "web3j solidity generate ..."

## _Issue_description_
_Please describe what are you trying to do and why it doesn't work_
The strange thing now is, that since I indexed the parameter the event returns the userId not as normal string anymore, but as byte array. In the generate contract wrapper it is also defines as byte array:
`typedResponse.userId = (byte[]) eventValues.getIndexedValues().get(1).getValue();` 
Why does it return String when its not indexed and byte[] when its indexed? And how do I get the correct string again from that byte array value?

## _Issue_context_
_Please provide additional information that might be helpful_
Wrapper class was generated with web3j version 4.5.5

What I already tried to is subscribe to my event like this:
` 
contract.myEventEventFlowable(filter).subscribe(event -> {

            final byte[] id = event.userId;
            String test1 = new String(id); //THIS DOES NOT WORK
            test1 = StringUtils.newStringUsAscii(id); //THIS DOES NOT WORK
            test1 = StringUtils.newStringUtf8(id); //THIS DOES NOT WORK
        });
`

Very grateful for any help!

**Comment by ppeinsold** [comment]
Just a follow up: I "solved" by simply add the non-indexed userId additionally to the indexed userId. So my event definition now looks like:
`event myEvent(address userAddress, string indexed userId, string userId);`

It feels a bit "hacky" but it was the simplest solution for now. Still interested in a better answer to my original question.

**Comment by iikirilov** [comment]
@ppeinsold you cannot have dynamic index parameters. An index parameter is 256 bits fixed length so if you put something dynamic or bigger it will store `keccak(value)` rather than `value`

Closing as this is a non-issue

**Comment by RealDeanZhao** [comment]
I met the same problem, thanks for pointing out it is not an issue. I will add the non-indexed para to the event.
