### ISSUE TITLE
WebSocketService with authentication

### ISSUE THREAD

**Issue by Ippolo** [web3j/web3j#1112]
# Issue
I am trying to connect via websocket to a Geth node on the cloud that requires authentication, but I can't manage to connect.

# Description
I have username, password and an authentication header string given by my provider that looks like :
> {Authentication: Basic ZTB3ZnVpc......}

What I am trying to do to connect is pass the authentication header to the WebSocketClient instance in this way:

>String wsEndpoint = "wss://e0sa5vimp0-e0hikfbg6t-wss.de0-aws.kaleido.io";
URI uri = new URI(wsEndpoint);
Map<String, String> headers = new HashMap<>();
headers.put("Authentication", "Basic ZTB3ZnVpc......");
WebSocketClient  webSocketClient = new WebSocketClient(uri, headers);
WebSocketService service = new WebSocketService(webSocketClient, false);
Web3j web3j = Web3j.build(service);

But I can't manage to connect. I am connecting successfully to the same node using OkHttp, I can't find any usefull documentation on how to connect via websocket with authentication, so I am not sure I am doing it the right way.

**Comment by AlexandrouR** [comment]
@Ippolo you can have a look at https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/CustomHeaderClientExample.java

**Comment by Ippolo** [comment]
@AlexandrouR as you can see in the example I provided on the first message I am setting the authentication header in the same way, but I can't manage to connect to the node with Web3j WebSocketService

**Comment by josh-richardson** [comment]
Hi @Ippolo - I'm not having any issues connecting to our authenticated Rinkeby node over a websocket, using the following code:

```java
String wsEndpoint = "wss://rinkeby.geth.epirus.web3labs.com/ws";
URI uri = new URI(wsEndpoint);
Map<String, String> headers = new HashMap<>();
headers.put("Authorization", "Basic <base64 encoded un/pw>");
WebSocketClient webSocketClient = new WebSocketClient(uri, headers);
WebSocketService service = new WebSocketService(webSocketClient, true);
Web3j web3j = Web3j.build(service);
System.out.println("Connected");
service.connect();
EthBlock result = web3j.ethGetBlockByNumber(DefaultBlockParameterName.LATEST, false).send();
System.out.println("Sent request");
System.out.println(result.getBlock().getNumberRaw());
```

It strikes me that in your example, you're adding a header by the name of `Authentication` - but HTTP basic tends to use `Authorization` if you're using a geth instance behind a simple nginx-style proxy.
