### ISSUE TITLE
when toAddress is 0x00211e7e624178e5bc57f9d1e6115ad65f3e76b8 ,raw transaction broadcast fail

### ISSUE THREAD

**Issue by yangchunhe** [web3j/web3j#112]
RawTransaction rawTransaction  = RawTransaction.createEtherTransaction( nonce, DEFAULT_GAS_PRICE, GAS_LIMIT, toAddress, value);

// sign & send our transaction
byte[] signedMessage = TransactionEncoder.signMessage(rawTransaction, credentials);

ethSendTransaction = web3j.ethSendRawTransaction(transHex).sendAsync().get();

ethSendRawTransaction result is :  rlp: input string too short for common.Address, decoding into (types.Transaction)(types.txdata).Recipient

if toAddress is other addresss ,is ok! why?

**Comment by conor10** [comment]
Fixed.
