### ISSUE TITLE
Int40 do not work for negative values

### ISSUE THREAD

**Issue by jimy74** [web3j/web3j#1136]
I got a broken test when updating from 4.2.0 to 4.5.11.

Every types encoding/decoding is fine but not int40, passing a negative value to encode and then read it back is not working.

Example :

I got a smart contract with the method :

    function passAndGetBackInt40(int40 _value) public view returns (int40) {
        return _value;
    }

When I call it I pass the value "-25" encoded and it must return the same decoded value.
It work for int8, int16, int24 and int32 but for a unknown reason it do not return -25 anymore for int40, but it return "1099511627751".

Any idea/fix on that? can someone give a try? I think something has break in the latest releases.

**Comment by jimy74** [comment]
I saw that in the code...

Someone failed to code the case int40 and uint40, need a fix and a new release soon...


            case "int24":
                return primitives ? Int.class : Int24.class;
            case "uint32":
                return primitives ? Long.class : Uint32.class;
            case "int32":
                return primitives ? Int.class : Int32.class;
            case "uint40":
                return primitives ? Long.class : Int40.class;
            case "int40":
                return primitives ? Long.class : Uint40.class;
            case "uint48":
                return primitives ? Long.class : Uint48.class;
            case "int48":
                return primitives ? Long.class : Int48.class;

**Comment by cfelde** [comment]
Fixed by #1137 merge
