### ISSUE TITLE
check address

### ISSUE THREAD

**Issue by prettyCoders** [web3j/web3j#1138]
# _Issue_title_
_A clear and concise description of what the issue is._

## _Issue_description_
_Please describe what are you trying to do and why it doesn't work_

## _Issue_context_
_Please provide additional information that might be helpful_

**Comment by prettyCoders** [comment]
How to check the address is valid

**Comment by josh-richardson** [comment]
This is not the correct venue for support questions. I don't believe Web3j currently has this functionality, however you may find the following helpful: https://github.com/assafY/web3j/blob/bd23fe222d6965ad3c12ceb33930e30a6756352c/core/src/main/java/org/web3j/utils/Account.java
