### ISSUE TITLE
How to correctly generate wrapper classes

### ISSUE THREAD

**Issue by caicaicai** [web3j/web3j#1139]
Why the wrapper class produced by the tool(web3j solidity generate), all the return value of the  method is the “RemoteFunctionCall TransactionReceipt ” type even if it is read data method(add view annotation), not the type I defined.
I read a lot of example articles and they all return the type you want. For example “RemoteCall Uint256 ”.

Am I missing something? Is it a version problem? I followed the steps of the document exactly.

I tried a lot, the way of scripting, the way of maven plugin. ALL not work.

All of the java wrapper class return value of a method is the “RemoteFunctionCall TransactionReceipt ”， I'm confused and don't know how to use it.

Even the simplest contract,it won't work.

**Comment by cfelde** [comment]
Call .send() to execute the call: https://docs.web3j.io/smart_contracts/#invoking-transactions-and-events

**Comment by caicaicai** [comment]
My problem is that my generated wrapper class methods only have transactions, but what I need are constant methods. I don't know how the conversion tool works. Although my protocol uses a const method, it still let me convert it into transactions.

**Comment by caicaicai** [comment]
finally. I use "web3j truffle generate" from truffle build json file. I got what I wanted.
