### ISSUE TITLE
missing 0x prefix for hex data

### ISSUE THREAD

**Issue by bilthon** [web3j/web3j#114]
I get this error in android using the version 2.2.1 when trying to send a transaction using the `RawTransaction`  class. Here's my code:

```java
RawTransaction rawTransaction  = RawTransaction.createEtherTransaction(nonce, gasPrice, gasLimit, destination, value);
byte[] signedMessage = TransactionEncoder.signMessage(rawTransaction, credentials);
String hexValue = Hex.toHexString(signedMessage);
EthSendTransaction ethSendTransaction = web3.ethSendRawTransaction(hexValue).send()
```

I'm getting around this by just placing a `0x` at the beginning of the string returned by `Hex.toHexString(signedMessage)`. I'm not sure if this is expected behavior, but if it is then the README description should be updated to reflect the correct usage.

**Comment by PeterJames12** [comment]
@bilthon what does mean this arguments createEtherTransaction(nonce, gasPrice, gasLimit, destination, value); i know only gasLimit and destination, about other i don't have a clue

**Comment by bilthon** [comment]
The nonce is just a transaction counter. The gas price is just that, how much you're willing to pay for every unit of gas. And the value is of course how much you're transferring.

**Comment by PeterJames12** [comment]
@bilthon thanks a lot, i have one more question, look i use this code Web3j web3 = Web3j.build(new HttpService()); // defaults to http://localhost:8545/
Credentials credentials = WalletUtils.loadCredentials("password", "/path/to/walletfile");
TransactionReceipt transactionReceipt = Transfer.sendFunds(
web3, credentials, "0x...", BigDecimal.valueOf(1.0), Convert.Unit.ETHER);
why i have this exception com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

Thanks

**Comment by conor10** [comment]
@PeterJames12 please can you use the [web3j Gitter channel](gitter.im/web3j/web3j) to ask questions, rather than asking them on existing issues?

If you do encounter an actual issue with web3j, a new issue should be raised. But please ensure you have spent sufficient time reading the documentation and running existing examples before doing so.

**Comment by conor10** [comment]
@bilthon see the following example https://github.com/web3j/web3j/blob/master/src/integration-test/java/org/web3j/protocol/scenarios/CreateRawTransactionIT.java#L47.

Although I would recommend you use a [smart-contract wrapper](https://docs.web3j.io/smart_contracts.html#solidity-smart-contract-wrappers) instead.

The documentation should be clear - see https://docs.web3j.io/transactions.html#signing-transactions. Please let me know if you think it should change (or feel free to submit a PR with amendments :)

Please reopen this issue if you see fit.
