### ISSUE TITLE
generateBip39Wallet

### ISSUE THREAD

**Issue by hamidbayati** [web3j/web3j#1149]
hi
good time
 i use web3j (version 4.5.12)
when i wanna create new wallet with  WalletUtils.generateBip39Wallet, my app is crashed
please tell me a solution or fix this bug
i  must create wallet with this function (WalletUtils.generateBip39Wallet)

app works on android 9 but it crashes on android 7

my code : 

```
val dirPath = AndroidApplication.context.getFilesDir().getAbsolutePath();
                val file = File(dirPath)
                val seedWords = WalletUtils.generateBip39Wallet("", file).mnemonic
```

log cat : 

``` 
Process: com.carchain, PID: 13367
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/format/DateTimeFormatter;
        at org.web3j.crypto.WalletUtils.getWalletFileName(WalletUtils.java:177)
        at org.web3j.crypto.WalletUtils.generateWalletFile(WalletUtils.java:86)
        at org.web3j.crypto.WalletUtils.generateBip39Wallet(WalletUtils.java:117)
```

**Comment by cfelde** [comment]
Sounds like this might fit better over at https://community.web3labs.com/

**Comment by psabadac** [comment]
Use  coreLibraryDesugaringEnabled = true under compileOptions and add
coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5' as a dependecy
