### ISSUE TITLE
[Urgent]Update ENS registry contract address 

### ISSUE THREAD

**Issue by jtomtan** [web3j/web3j#1152]
According to https://medium.com/the-ethereum-name-service/ens-registry-migration-bug-fix-new-features-64379193a5a and https://docs.ens.domains/ens-migration/guide-for-dapp-developers, ENS registry contract address should be updated from:

0x314159265dd8dbb310642f98f50c066173c1259b

to:

0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e

Since this is un urgent update, hope this can be done in we3j as soon as possible.

**Comment by antonydenyer** [comment]
Fixed in #1153
