### ISSUE TITLE
Requests with HttpService to Infura Endpoint lead to "Invalid response received: 404; 404 page not found"

### ISSUE THREAD

**Issue by rw026** [web3j/web3j#1155]
## Steps To Reproduce
Since I changed my version of web3j from `4.5.11` to `4.5.14` any of my http requests lead to this error. For example:
```java
EthFilter ethFilter = new EthFilter(DefaultBlockParameterName.EARLIEST,
                    DefaultBlockParameterName.LATEST, myToken.getContractAddress());
ethFilter.addSingleTopic(EventEncoder.encode(MyToken.TRANSFER_EVENT));
EthLog transferEventLog = web3j.ethGetLogs(ethFilter).send();
```

### Expected behavior
The response should contain the EthLog

### Actual behavior
`org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: 404; 404 page not found`

## Environment
My application uses Spring Boot version 2.2.4.RELEASE
- Web3j version: 4.5.14
- Java 11
- Ubuntu 18.04

**Comment by cfelde** [comment]
Doesn't look like Web3j bug, more config issue or similar. Probably a better fit for https://community.web3labs.com/
