### ISSUE TITLE
web3j-cli version not found in the newest release version.

### ISSUE THREAD

**Issue by 1172510217** [web3j/web3j#1158]
# _Issue_title_
_web3j-cli version not found in the newest release version._

## _Issue_description_
_O..., I run with a terrible issue with the download of the new release version of the web3j, I can not find the command line version in the source file. I can just find the bin and lib source in the old release version. Hope your reply sincerely_

**Comment by 1172510217** [comment]
I mean  if the old 3.0.0 cli version functions well with the newest realease version in android studio. If so, i can just download the 3.0.0 cli version.

**Comment by josh-richardson** [comment]
You should be able to install the latest version of the CLI from this repository: https://github.com/web3j/web3j-installer

**Comment by 1172510217** [comment]
Thanks, josh. It helps a lot. After the command line trying, I download the tar file directly.
