### ISSUE TITLE
How to dealing with two-dimensional arrays？

### ISSUE THREAD

**Issue by qq1012827513** [web3j/web3j#1160]
# How to dealing with two-dimensional arrays？

## The return value of the contract：
        address payable[] memory _addrs,
        uint8[5][] memory _datas,
        uint[] memory _blockTimes

**The generated code** ：
```
Arrays.<TypeReference<?>>asList(new TypeReference<DynamicArray<Address>>() {
                }, new TypeReference<DynamicArray<StaticArray5<Uint8>>>() {
                }, new TypeReference<DynamicArray<Uint256>>() {
                })
```

## exception
java.lang.UnsupportedOperationException: Unable to access parameterized type xxx.datatypes.DynamicArray<xxx.datatypes.generated.StaticArray5<xxx.datatypes.generated.Uint8>>

**Comment by qq1012827513** [comment]
Nested arrays do not seem to be supported

**Comment by EAOE3** [comment]
Was an answer for this issue ever found ?

**Comment by qinzhaoyang** [comment]
I came across something like, It is written as follows:
                List<Type> types = FunctionReturnDecoder.decode(input, Utils.convert(Arrays.asList(
                        new TypeReference<DynamicArray<Address>>() {},
                        new TypeReference.StaticArrayTypeReference<DynamicArray<Address>>(2) {},
                        new TypeReference.StaticArrayTypeReference<DynamicArray<Uint32>>(2) {},
                        new TypeReference<DynamicArray<Uint256>>() {},
                        new TypeReference<DynamicArray<Uint256>>() {},
                        new TypeReference<DynamicArray<Uint256>>() {}
                )));

**Comment by qinzhaoyang** [comment]
I came across something like, It is written as follows:
`                List<Type> types = FunctionReturnDecoder.decode(input, Utils.convert(Arrays.asList(
                        new TypeReference<DynamicArray<Address>>() {},
                        new TypeReference.StaticArrayTypeReference<DynamicArray<Address>>(2) {},
                        new TypeReference.StaticArrayTypeReference<DynamicArray<Uint32>>(2) {},
                        new TypeReference<DynamicArray<Uint256>>() {},
                        new TypeReference<DynamicArray<Uint256>>() {},
                        new TypeReference<DynamicArray<Uint256>>() {}
                )));`

**Comment by qinzhaoyang** [comment]
I came across something like, It is written as follows:
```
                List<Type> types = FunctionReturnDecoder.decode(input, Utils.convert(Arrays.asList(
                        new TypeReference<DynamicArray<Address>>() {},
                        new TypeReference.StaticArrayTypeReference<DynamicArray<Address>>(2) {},
                        new TypeReference.StaticArrayTypeReference<DynamicArray<Uint32>>(2) {},
                        new TypeReference<DynamicArray<Uint256>>() {},
                        new TypeReference<DynamicArray<Uint256>>() {},
                        new TypeReference<DynamicArray<Uint256>>() {}
                )));
```
