### ISSUE TITLE
web3j + solc 0.6.3

### ISSUE THREAD

**Issue by fatimaleal** [web3j/web3j#1161]
If I use the solc 0.6.3 version as solidity compiler,  calling a smart contract function is different. It does not allow to read directly the value of a get function of a smart contract. With solc 0.6.3 the "contract.get().send();" is returning a TransactionReceipt. However, e.g., with solc 0.5.16 is working well.

Do you know how to circumvent this?

Thank you

**Comment by NicolaGessa** [comment]
Hello, I have the same issue: using web3j and  solc version 0.5 I generate the Java wrapper for a contract, and  I can call in  Java the function contract.printHello().send() and have a string value in return. 

With solc version 0.6 I receive a TransactionReceipt{...} and I don't know how to have the return value.

Is there any suggestion or comment to solve this issue?

I posted the same issue here:
https://github.com/ethereum/solidity/issues/8376
but up to now I have no solution

(I don't want to go back to version 5 of solc)

thanks a  lot

I use:
solc: Version: 0.6.3+commit.8dda9521.Linux.g++
web3j: 4.5.14

**Comment by killingdjef** [comment]
I'm having this exact same issue. Is web3j not compatible with solidity 0.6.+?

**Comment by killingdjef** [comment]
Fixed this issue by using 4.5.16!

@fatimaleal @NicolaGessa

**Comment by dfsantamaria** [comment]
I'm experiencing the same issue (web3j 4.5.16 and solc 0.6.3) with view methods.

**Comment by fatimaleal** [comment]
I'm using web3j 4.5.16 and solc 0.6.4 and it works fine.

**Comment by dfsantamaria** [comment]
Same problem with 0.6.4. Second problem, if I compile from command line or remix, i get a bytecode that is different from the one obtained from web3j and web3j-maven-plugin (4.5.11)
