### ISSUE TITLE
please tell me how to get command web3j

### ISSUE THREAD

**Issue by 01jiagnwei01** [web3j/web3j#1162]
# please tell me how to get command web3j
please tell me how to get command web3j

## I want to use command but can`t get the command . please pack it
I want to use command but can`t get the command . please pack it

## _Issue_context_
_Please provide additional information that might be helpful_

**Comment by 1172510217** [comment]
This issue may helps, https://github.com/web3j/web3j/issues/1158

**Comment by AlexandrouR** [comment]
@01jiagnwei01 did @1172510217 answer solved you issue ?
