### ISSUE TITLE
SignStructedData Error

### ISSUE THREAD

**Issue by fengzeyan** [web3j/web3j#1164]
# StructuredDataEncoder hashStructuredData runtime exception
## Steps To Reproduce
String message="{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"}],\"Person\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"wallet\",\"type\":\"address\"}],\"Mail\":[{\"name\":\"from\",\"type\":\"Person\"},{\"name\":\"to\",\"type\":\"Person\"},{\"name\":\"contents\",\"type\":\"string\"}]},\"primaryType\":\"Mail\",\"domain\":{\"name\":\"Ether Mail\",\"version\":\"1\",\"verifyingContract\":\"0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC\"},\"message\":{\"from\":{\"name\":\"Cow\",\"wallet\":\"0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826\"},\"to\":{\"name\":\"Bob\",\"wallet\":\"0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB\"},\"contents\":\"Hello, Bob!\"}}";
        StructuredDataEncoder encoder = new StructuredDataEncoder(message);
        byte[] bytes = encoder.hashStructuredData();

## Environment
- Web3j version 4.5.12
- Android 
- Pixel 2

## Additional context
    java.lang.RuntimeException: Received an invalid argument for which no constructor exists for the ABI Class Uint256
        at org.web3j.crypto.StructuredDataEncoder.encodeData(StructuredDataEncoder.java:334)
        at org.web3j.crypto.StructuredDataEncoder.hashDomain(StructuredDataEncoder.java:365)
        at org.web3j.crypto.StructuredDataEncoder.hashStructuredData(StructuredDataEncoder.java:409)

**Comment by SweeXordious** [comment]
Hello,
I have tried this and i think that the **chainId** field is missing under **domain**.
This is the correct format for a valid structured data: 

```
{
  "types": {
    "EIP712Domain": [
      {"name": "name", "type": "string"},
      {"name": "version", "type": "string"},
      {"name": "chainId", "type": "uint256"},
      {"name": "verifyingContract", "type": "address"}
    ],
    "Person": [
      {"name": "name", "type": "string"},
      {"name": "wallet", "type": "address"}
    ],
    "Mail": [
      {"name": "from", "type": "Person"},
      {"name": "to", "type": "Person"},
      {"name": "contents", "type": "string"}
    ]
  },
  "primaryType": "Mail",
  "domain": {
    "name": "Ether Mail",
    "version": "1",
    "chainId": 1,
    "verifyingContract": "0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC"
  },
  "message": {
    "from": {
      "name": "Cow",
      "wallet": "0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826"
    },
    "to": {
      "name": "Bob",
      "wallet": "0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB"
    },
    "contents": "Hello, Bob!"
  }
}
```

**Comment by zhangjun725** [comment]
> # StructuredDataEncoder hashStructuredData runtime exception
> ## Steps To Reproduce
> String message="{"types":{"EIP712Domain":[{"name":"name","type":"string"},{"name":"version","type":"string"},{"name":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}],"Person":[{"name":"name","type":"string"},{"name":"wallet","type":"address"}],"Mail":[{"name":"from","type":"Person"},{"name":"to","type":"Person"},{"name":"contents","type":"string"}]},"primaryType":"Mail","domain":{"name":"Ether Mail","version":"1","verifyingContract":"0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC"},"message":{"from":{"name":"Cow","wallet":"0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826"},"to":{"name":"Bob","wallet":"0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB"},"contents":"Hello, Bob!"}}";
> StructuredDataEncoder encoder = new StructuredDataEncoder(message);
> byte[] bytes = encoder.hashStructuredData();
> 
> ## Environment
> * Web3j version 4.5.12
> * Android
> * Pixel 2
> 
> ## Additional context
> ```
> java.lang.RuntimeException: Received an invalid argument for which no constructor exists for the ABI Class Uint256
>     at org.web3j.crypto.StructuredDataEncoder.encodeData(StructuredDataEncoder.java:334)
>     at org.web3j.crypto.StructuredDataEncoder.hashDomain(StructuredDataEncoder.java:365)
>     at org.web3j.crypto.StructuredDataEncoder.hashStructuredData(StructuredDataEncoder.java:409)
> ```

 这个问题后来怎么解决的
