### ISSUE TITLE
Integration Issue with Private Blockchain

### ISSUE THREAD

**Issue by cameron444** [web3j/web3j#117]
I wanted to share an issue I am encountering trying to get a simple contract to deploy on my private blockchain through web3j. After the reading the docs I have executed these steps. 
1. created registrar.sol file (simple hash table) :

```
pragma solidity ^0.4.11;
contract Registrar_Contract{
    struct info {
        address account;
        address summary_contract;
    }
    mapping(string => info) participants;
    function add_participant(string ID, address account,address summary_contract) public {
        participants[ID]=info(account,summary_contract);
    }
    function get_account(string ID) constant returns (address){
        return participants[ID].account;
    }
 
}

```
2. compiled the .sol file into a bin and abi file using solc
 $ solc registrar.sol --bin --abi --optimize -o ./

3. used web3j solidity generate to create java wrapper
$ web3j solidity generate ./Registrar_Contract.bin ./Registrar_Contract.abi -o ./ -p src

4. added wrapper to java project. 

5. started node and ran these commands with these parameters
 > $ geth --datadir "$ethereum_home/youtube1-a" --port 30304 --nodiscover --networkid 1234 --rpc --rpcport "8545" --rpccorsdomain "*" --rpcapi "db,eth,net,web3" console 2>console.log

> miner.start(1)
> web3.eth.defaultAccount=eth.accounts[0]
> personal.unlockAccount(eth.accounts[0])
* entered password succesfully

6. ran the following project:
```
Web3j web3 = Web3j.build(new HttpService());
            Credentials credentials= WalletUtils.loadCredentials("password","pathtokeystore");
            Future<Registrar_Contract> registrar_future=Registrar_Contract.deploy(web3,credentials,BigInteger.valueOf(800000),BigInteger.valueOf(800000),BigInteger.valueOf(80000000));
            //public static Future<Registrar_Contract> deploy(Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit, BigInteger initialWeiValue) {
            Registrar_Contract registrar_contract= registrar_future.get();

            System.out.println("valid? : " +registrar_contract.isValid());
            System.out.println("address ? : " + registrar_contract.getContractAddress());
```
The result of this is:
valid? : false
address ? : 0xd7a9b8e88d63caa277ec4019eb660fe82c6a8c4f

This is places an invalid contract which I cannot sucessfully interact with (it returns 0x0 ) on the blockchain and when I do this on the testnet and look it up on etherscan I get this error when it shows the contract:

> [Contract 0xf074cf8a692c9e70203be3f0cd4b05eb91ef6b71 Created]  
>  Warning! Error encountered during contract execution [Bad instruction] 

I have tested doing this using the web3 javascript with on the geth console using the online solidity remix compiler and it works perfectly so I am curious as to why it won't work with web3j java. I have also tested a simple greeter from ethereum.org and have had the same problem.

**Comment by cameron444** [comment]
^ I took out the info on the the loadCredentials method but have double checked that the parameters are correct.

**Comment by conor10** [comment]
Please can you use the following gas price and gas limit values in your deployment (you can import them from (Contract and ManagedTransaction respectively):

```java
static final BigInteger GAS_PRICE = BigInteger.valueOf(20_000_000_000L);
static final BigInteger GAS_LIMIT = BigInteger.valueOf(4_300_000);
```

**Comment by cameron444** [comment]
Hey Conor thanks for the response,  I added those attributes and am getting the same kind of errors.
Here is the new code:
```
 Web3j web3 = Web3j.build(new HttpService());
 Credentials credentials= WalletUtils.loadCredentials("password","path");
Future<Registrar_Contract> registrar_future=Registrar_Contract.deploy(web3,credentials,GAS_PRICE,GAS_LIMIT,INITIAL_WEI);
        Registrar_Contract registrar_contract= registrar_future.get();

        System.out.println("valid? : " +registrar_contract.isValid());
        System.out.println("address ? : " + registrar_contract.getContractAddress());
```
I set initial WEI to the same as the gas limit even though it should not matter for this kind of contract based on my understanding of ethereum. Here is my console:

> valid? : false
> address ? : 0x826c6c01a8de820ad08eedd38547bdf56c08c98e


I deployed this one to the testnet and found its address and it looks identical to my previous problem with the bad instruction. 

https://ropsten.etherscan.io/tx/0xa70a5b48db0626d7093ba92d0c46950e7693c17501214e16e64541a2597804e3

**Comment by conor10** [comment]
You shouldn't be sending any initial Wei to the contract unless you're using the *payable* keyword on your contract methods. In your case this value should be zero.

**Comment by cameron444** [comment]
That worked, thank very much you for your help.
