### ISSUE TITLE
error processing bcprov-jdk15on-1.61

### ISSUE THREAD

**Issue by xumoyan** [web3j/web3j#1171]
error processing bcprov-jdk15on-1.61

eip712 
use api('org.web3j:core:4.4.0') 

StructuredDataEncoder structuredDataEncoder = new StructuredDataEncoder(jsonMessageInString);

Unable to access ValidationException

4.0 and up
error processing bcprov-jdk15on-1.61

what should i do？

**Comment by AlexandrouR** [comment]
@xumoyan is this still an issue with the latest web3j version?
