### ISSUE TITLE
web3j generate java code  from compound Comptroller contract abi has error

### ISSUE THREAD

**Issue by ocoderr** [web3j/web3j#1182]
# _Bug_title_
web3j generate java code  from compound Comptroller contract abi has error

## Steps To Reproduce
Comptroller ABI  https://compound.finance/docs/abi/mainnet/Comptroller

web3j solidity generate  -a=Comptroller.abi -o=/src/main/java -p=com.compound.eth.contract

### Expected behavior
 generate valid java code.

### Actual behavior
web3j  generate java class have error 

## Environment
_Describe the environment in which the issue occurs_
- Web3j version
Version: 4.5.16
Build timestamp: 2020-03-06 14:13:49.943 UTC

- Java or Android version
Java 1.8

- Operating System
macos

## Additional context

web3j output :
Warning: Duplicate field(s) found: [FUNC__SETCLOSEFACTOR, FUNC_PAUSEGUARDIAN, FUNC_LIQUIDATEBORROWVERIFY, FUNC__SETBORROWPAUSED, FUNC_ENTERMARKETS, FUNC_TRANSFERGUARDIANPAUSED, FUNC_ADMIN, FUNC_SEIZEALLOWED, FUNC_MINTALLOWED, FUNC__BORROWGUARDIANPAUSED, FUNC__SETMAXASSETS, FUNC__SETTRANSFERPAUSED, FUNC_LIQUIDATECALCULATESEIZETOKENS, FUNC_LIQUIDATEBORROWALLOWED, FUNC_REPAYBORROWVERIFY, FUNC_EXITMARKET, FUNC__MINTGUARDIANPAUSED, FUNC_REDEEMALLOWED, FUNC_MARKETS, FUNC__SETPRICEORACLE, FUNC__SETMINTPAUSED, FUNC_SEIZEGUARDIANPAUSED, FUNC_REDEEMVERIFY, FUNC__BECOME, FUNC_GETASSETSIN, FUNC__SETLIQUIDATIONINCENTIVE, FUNC_CHECKMEMBERSHIP, FUNC_SEIZEVERIFY, FUNC__SETSEIZEPAUSED, FUNC_ORACLE, FUNC_BORROWALLOWED, FUNC_TRANSFERALLOWED, FUNC_ACCOUNTASSETS, FUNC_MINTVERIFY, FUNC_BORROWGUARDIANPAUSED, FUNC_MINTGUARDIANPAUSED, FUNC__SETPAUSEGUARDIAN, FUNC_PENDINGCOMPTROLLERIMPLEMENTATION, FUNC_LIQUIDATIONINCENTIVEMANTISSA, FUNC_PENDINGADMIN, FUNC_MAXASSETS, FUNC_TRANSFERVERIFY, FUNC_COMPTROLLERIMPLEMENTATION, FUNC_BORROWVERIFY, FUNC_GETACCOUNTLIQUIDITY, FUNC_ISCOMPTROLLER, FUNC_CLOSEFACTORMANTISSA, FUNC_REPAYBORROWALLOWED, FUNC__SETCOLLATERALFACTOR, FUNC__SUPPORTMARKET]. Please don't use names which will be the same in uppercase.

**Comment by AlexandrouR** [comment]
@ocoderr This is not really a but a warning displayed by the CLI. Using the latest version of CLI this is resolved. There are some warnings still but fewer and also the generation of the wrappers is not stopped.
