### ISSUE TITLE
web3j cli is not in sync with android version of web3j

### ISSUE THREAD

**Issue by kuabhish** [web3j/web3j#1186]
Hello,

I am trying to make an app in android. 
In the build.gradle file in app directory. i wrote the appropriate version of android (4.2.0 android)

and then to create the smart contract wrapper i installled the webj cli latest  version (4.5.16). Then with it's help i created a java wrapper. which had a lot of errors.

then I tried the even the oldest version of web3j cli.(4.5.4).
even that didn't work.

What should I do?

**Comment by AlexandrouR** [comment]
what solidity version are you using in your smart contract?

**Comment by kuabhish** [comment]
> what solidity version are you using in your smart contract?

pragma solidity >=0.4.24 <0.7.0; -- in smart contract code ..
and solc --- version was -0.5.16

**Comment by AlexandrouR** [comment]
@kuabhish  could you post some of the errors ?

**Comment by iikirilov** [comment]
if you in this situation please use - https://github.com/web3j/web3j/releases/download/v4.1.0/web3j-4.1.0.zip

this is known issue and will be resolved with the next release of web3j-android
