### ISSUE TITLE
Setting pollinginterval has no effect

### ISSUE THREAD

**Issue by beyonderyue** [web3j/web3j#1187]
web3j 4.5.17

code:
```
HttpService httpService = new HttpService("http://localhost:8545");
Web3j web3j = Web3j.build(httpService, 3000, Async.defaultExecutorService());
long now = System.currentTimeMillis();
CompletableFuture<TransactionReceipt> tr = Transfer.sendFunds(web3j, rich, address, BigDecimal.ONE, Convert.Unit.ETHER).sendAsync();
 TransactionReceipt transactionReceipt = tr.get();
System.out.println(System.currentTimeMillis() - now);
```
No matter what pollinginterval I set, always print about 15 seconds. 
It means that setting pollinginterval has no effect..
I have checked, but I can't find the reason.

Thank you

**Comment by AlexandrouR** [comment]
@beyonderyue the polling interval there is used in the code when working with the reactive API implementation you can have a look at the `JsonRpc2_0Web3j` class and notice that the polling interval value is assigned to a class member called `blockTime` this block time is used by `web3jRx`. 

You could use the `PollingTransactionReceiptProcessor`  as such:
``
PollingTransactionReceiptProcessor pollingTransactionReceiptProcessor = new PollingTransactionReceiptProcessor(web3j,3000,10);
pollingTransactionReceiptProcessor.waitForTransactionReceipt(Transfer.sendFunds(web3j, credentials, receiver, BigDecimal.ONE, Convert.Unit.KWEI).send().getTransactionHash());``

Let me know if it worked

**Comment by beyonderyue** [comment]
Yes, it worked
