### ISSUE TITLE
FilterException leads to the thread pool of the scheduler halt silently

### ISSUE THREAD

**Issue by Mingela** [web3j/web3j#1196]
# FilterException leads to the thread pool of the scheduler halt (almost) silently
Thread pool executor stops executing task on polling blocks in case of the eth node connectivity problem. 
Partially related to https://github.com/web3j/web3j/issues/359

## Steps To Reproduce
Restart or shut down the node during subscription of a form like
```
web3.replayPastAndFutureBlocksFlowable(
            DefaultBlockParameter.valueOf(1),
            true
        ).toObservable()
```

### Expected behavior
Either keep restarting or push an error to the flowable/observable so a client could handle that

### Actual behavior
There are two possible cases from my experience:
- When received 'connection timed out' the task gets retried and everything is ok https://github.com/web3j/web3j/blob/baba7a80732354926ff0cd7efd67921c4c30ea67/core/src/main/java/org/web3j/protocol/core/filters/Filter.java#L97
- When received 'ClientConnectionException: Invalid response received: 502; Bad Gateway' we go there https://github.com/web3j/web3j/blob/baba7a80732354926ff0cd7efd67921c4c30ea67/core/src/main/java/org/web3j/protocol/core/filters/Filter.java#L189 and die

## Environment
- Web3j: 4.4.1
- Java: 8 + Kotlin 1.3.61
- Operating System: Ubuntu 18.04.3 LTS

## Additional context
Tried a workaround of subclassing the executor with overriding `afterExecute` to rethrow an exception and a thread factory with handling of uncaught exception but it didn't work since every time it is a `CancellationException` and you cannot indicate a true reason for that. It can appear while working normally as well.

**Comment by zxgangandy** [comment]
U can use the "shutdown" method to close the thread pool;

**Comment by Mingela** [comment]
> U can use the "shutdown" method to close the thread pool;

can you elaborate on that? I don't think it is a convenient way to handle the state

**Comment by XuanYuan1122** [comment]
The same problem. Did somebody find solution?
