### ISSUE TITLE
Android-4.2.0 fails mapping

### ISSUE THREAD

**Issue by Evert0x** [web3j/web3j#1202]
# _Issue_title_
Jackson errors when connecting to infura endpoint

## _Issue_description_
_Please describe what are you trying to do and why it doesn't work_

I get this exception for every action through web3j that is connecting to my Httpclient (Infura endpoint)

`com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class com.fasterxml.jackson.databind.util.LRUMap and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.web3j.protocol.core.Request["web3jService"]->org.web3j.protocol.http.HttpService["objectMapper"]->com.fasterxml.jackson.databind.ObjectMapper["_deserializationConfig"]->com.fasterxml.jackson.databind.DeserializationConfig["_base"]->com.fasterxml.jackson.databind.cfg.BaseSettings["_classIntrospector"]->com.fasterxml.jackson.databind.introspect.BasicClassIntrospector["_cachedFCA"])`

For example with this code 
Web3j web3 = Web3j.build(new HttpService("https://mainnet.infura.io/v3/MYTOKEN"));
try {
    Web3ClientVersion web3ClientVersion = web3.web3ClientVersion().send();
} catch (IOException e) {
     e.printStackTrace();
}

## _Issue_context_
_Please provide additional information that might be helpful_
Using Android 8.1.0.
`<uses-permission android:name="android.permission.INTERNET" />` is set

**Comment by iikirilov** [comment]
please use - https://github.com/web3j/web3j/releases/download/v4.1.0/web3j-4.1.0.zip

this is known issue and we are working on updating the web3j-android release

**Comment by iikirilov** [comment]
Are you using web3j-android? Also which version of web3j-cli are you using to generate the contract wrappers?

**Comment by Evert0x** [comment]
Fixed :).

I'm using web3j-android 4.2.0, I had to add `minifyEnabled false` to my gradle. Like this https://github.com/Evert0x/Telegram/commit/5cbbaa2f726e19b97e65ee9f6a380debb9163ca7#diff-3700629783fb7209df0b9e49538cd538
