### ISSUE TITLE
Can not import wallet from private key non-interactively

### ISSUE THREAD

**Issue by danielimkk** [web3j/web3j#1211]
# _Bug_title_
Can not import wallet from private key non-interactively

## Steps To Reproduce
web3j wallet fromkey <private-key> < password-file.txt

### Expected behavior
I expected an address to be created as it happens in interactive mode

### Actual behavior
In fact I recieve an exception:
`Exception in thread "main" java.lang.NullPointerException`
        `at org.web3j.console.ConsoleDevice.readLine(ConsoleDevice.java:29)`
        `at org.web3j.console.KeyImporter.run(KeyImporter.java:66)`
        `at org.web3j.console.KeyImporter.main(KeyImporter.java:39)`
        `at org.web3j.console.WalletRunner.main(WalletRunner.java:42)`
        `at org.web3j.console.WalletRunner.run(WalletRunner.java:24)`
        `at org.web3j.console.Runner.main(Runner.java:63)`

## Environment
_Describe the environment in which the issue occurs_
- Web3j version:  4.5.16
- Java
- Centos

## Additional context
Hey there! Is it possible to import an account non-interactively. I couldn`t find any docs describing the option flags that could be applied. Please could you tell me if it is possible or not to import the account non-interactively

**Comment by AlexandrouR** [comment]
@danieldietrich Hey, there is no way currently to create a wallet file non-interactively. However, I tried to generate a wallet with web3j-CLI using the command web3j wallet fromkey <file-name> and the wallet was generated successfully. You can create credentials programmatically using the Credentials class.
