### ISSUE TITLE
cannot unmarshal invalid hex string into Go struct field SendTxArgs.data of type hexutil.Bytes

### ISSUE THREAD

**Issue by w25193** [web3j/web3j#1214]
when i use
`Transaction transaction = new Transaction(from,BigInteger.valueOf(1),
                BigInteger.valueOf(2),
                BigInteger.valueOf(1),
                to,BigInteger.valueOf(1),
                content);`
there has an error like this
`cannot unmarshal invalid hex string into Go struct field SendTxArgs.data of type hexutil.Bytes"`

here is my code
`from = "0x"+"4826a23c0e30c6b2d7c2fb6f6c8a2b42bbdf75fa";
        to = "0x"+ "92eaef2c075c4eff2fb28857667b80a7ca66bb16";`

**Comment by AlexandrouR** [comment]
@w25193 Hey, is this still an issue? If so are you sending your transaction to your own node?
