### ISSUE TITLE
Deploy smart contract that uses libraries

### ISSUE THREAD

**Issue by mgomezcuesta** [web3j/web3j#1215]
## Allow deploing smart contract that uses libraries
I have a smart contract that uses a library with public methods. Then, I have no way to deploy this contract. 
* Is there a way to link the library to smart contract? 
* Otherwise, is there a workaround? 
* Otherwise, what is the planned date to allow that? Thank you

**Comment by AlexandrouR** [comment]
@mgomezcuesta if your contract uses a library then you need to download the files and import them from your project scope. If however, you are using a library like openzeppelin then this should be no issue If you use the latest web3j plugin.
