### ISSUE TITLE
"Header byte out of range" with Metamask + Ledger

### ISSUE THREAD

**Issue by meisser** [web3j/web3j#1219]
When trying to verify a message signed by a ledger nano with the latest firmware (1.6) and ethereum app (1.3.6), the Sign.signedPrefixedMessageToKey method throws the following error:

: java.security.SignatureException: Header byte out of range: 1
java.lang.RuntimeException: java.security.SignatureException: Header byte out of range: 1

In my case, I'm calling signedPrefixedMessageToKey with the following parameters:
message = [72, 101, 108, 108, 111, 44, 32, 114, 105, 103, 104, 116, 32, 110, 111, 119, 32, 105, 116, 32, 105, 115, 32, 50, 48, 50, 48, 45, 48, 54, 45, 48, 53, 84, 49, 54, 58, 50, 50, 58, 48, 53, 46, 48, 50, 50, 90, 32, 105, 110, 32, 71, 114, 101, 101, 110, 119, 105, 99, 104, 32, 97, 110, 100, 32, 73, 32, 119, 97, 110, 116, 32, 116, 111, 32, 108, 111, 103, 32, 105, 110, 46]
signatureData.r = [68, -52, -92, 20, -24, 13, -98, 7, -77, 90, 49, 69, 56, -44, 6, 53, 77, 108, 3, -14, 74, 91, -21, -78, 9, 3, -25, 20, -26, -107, -71, -44]
signatureData.s = [89, -42, 63, -59, 120, -23, -121, 47, -42, -123, -64, 122, 116, 49, -68, -88, -49, -115, -77, -79, -93, -41, 60, 104, -33, 111, -4, 0, -64, 73, -7, -72]
signatureData.v = [0]

This fails as v is expected to be at least 27.

I guess this also could be a bug in Ledger Nano. However, as a work-around, it suffices to add 27 to the v parameter and everything works fine.

The expected public key when calling the method with the test data starts with 0x963ec454...

-> I suggest we also support v values between 0 and 4 in web3j. That way, it also works with the current version of ledger nano.

**Comment by kronrod** [comment]
This is actually related to this issue reported on Ganache:
https://github.com/trufflesuite/ganache-cli/issues/757

Web3J should support both format.s

**Comment by alinturbut** [comment]
@meisser any news with this one? We are having similar issue
