### ISSUE TITLE
Can't run Command Line Tools version 2.2.2

### ISSUE THREAD

**Issue by banannn** [web3j/web3j#122]
I am trying to use Command Line Tools version 2.2.2, but the file structure in zip file is totally different than in previous version.
Looks like it is whole project inside zip (https://pastebin.com/VSXg8mcw), instead of libs and scripts like in previous versions.

How can I use Command Line Tools from the latest release?

**Comment by conor10** [comment]
It's because you download the web3j source for the latest release. I didn't upload new command line tools for version 2.2.2, as the changes between releases didn't effect them.

Please download 2.2.1 from https://github.com/web3j/web3j/releases/tag/v2.2.1.
