### ISSUE TITLE
Main Program hangs  with Infura and QuikNode

### ISSUE THREAD

**Issue by dfsantamaria** [web3j/web3j#1220]
I'm using Web3j 5.0.0 with Infura to load a contract. After the contract is correctly loaded, the main program hangs 5 minutes before terminating. 

Just loading, for instance, the contract "0xfc4445d9A149570c7e5b2B613252D2E284d1720F" on ropsten through a infura endpoint, hangs the program. The problem seems someway related to issue #1085 .

Tested with Java 8,11,13, and Web3j above 4.15.17.

Simple Test:

`String the_service=nodeAddress;
          Web3j web3 = Web3j.build(new HttpService(the_service));
          CompletableFuture<EthGetBalance> balance = web3.ethGetBalance(walletAddress, DefaultBlockParameterName.LATEST).sendAsync(); 
          BigInteger amount =  balance.get().getBalance();
          System.out.println(amount);`

  
Edit: The main program hangs infinitely. 
Edit: The problem arises with a simple Transfer.sendFunds or balance checking.
Edit: The problem arises also with a QuikNode.io node, not only infura.
Edit: Sample added.

**Comment by dfsantamaria** [comment]
Here a minimal example showing the problem: https://github.com/dfsantamaria/Web3JLoopTest.git

**Comment by razzbee** [comment]
Suddenly facing same issue,with balance and and fetching latest block

**Comment by razzbee** [comment]
I use openethereum, or parity.,.

**Comment by AlexandrouR** [comment]
@dfsantamaria  the latest version is 4.8.4 the 5.0.0 one was a mistake. For me, the execution time of the whole example you provided on the rinkeby network is 1 minute and and the same time for mainnet. Could you please try with the latest version of web3j and let me know.

**Comment by dfsantamaria** [comment]
> @dfsantamaria the latest version is 4.8.4 the 5.0.0 one was a mistake. For me, the execution time of the whole example you provided on the rinkeby network is 1 minute and and the same time for mainnet. Could you please try with the latest version of web3j and let me know.

Yes, now it seems to work. Using web sockets, it closes one minutes after a close call. I consider the issue closed.
