### ISSUE TITLE
codegen ignores view functions without return value

### ISSUE THREAD

**Issue by luziusmeisser** [web3j/web3j#1227]
## Description
When using codegen to generate the Java representation of a smart contract, functions that are "view" and have no return value are not generated.

You might ask why one would want to call a function that does not alter the state and returns no value? That's because it is often interesting to find out whether a function call succeeds or fails.

My use case is a smart contract with a very expensive, start altering method. Along with that, I provided a view-only "check" method that performs the same checks as the expensive method so the user can use "check" verify to have everything done correctly before calling the actual method, thereby saving some gas and reducing network load.

## Steps To Reproduce

1. Create a contract with a public function called "check" that is view and has no return value.
2. Compile it
3. Use SolidityFunctionWrapperGenerator to generate a Java representation of the contract

### Expected behavior
Example.java contains a function call check

### Actual behavior
Example.java does not contain a function called check

## Environment
I'm using Solidity 6.9 and Web3j 5.0.0.

## Additional context

Example contract:

pragma solidity >=0.6;
contract Example {
    function check() public view {
        require(msg.sender == address(0x123123));
    }
}

**Comment by SweeXordious** [comment]
Hello @luziusmeisser,
Sorry for the late reply.

Could you please try again using the web3j `4.8.4` version? The `5.0.0` is an old mistake release.

For the issue, I will take a look on it and get back to you.
