### ISSUE TITLE
FunctionEncoder.encodeParameters is private static function

### ISSUE THREAD

**Issue by bhauman** [web3j/web3j#123]
FunctionEncoder.encodeParameters
https://github.com/web3j/web3j/blob/master/src/main/java/org/web3j/abi/FunctionEncoder.java#L40

is a static function and also a helpful utility, why lock it away as a private function?

If you are wondering why I would like to use it: I'm writing a testing utility and I'd like independent control over the function signature and the parameters supplied to it, so that I can send bad data to the contract.

**Comment by bhauman** [comment]
Let me add the same sentiment for the `TypeEncoder.encode` function, I understand you may want to shift things around a bit but these methods would be super helpful for API consumers.

**Comment by conor10** [comment]
Hi @bhauman, no problem, I'd be happy to open up. PR's are always welcome, not matter how trivial :)

**Comment by conor10** [comment]
Done.

**Comment by bhauman** [comment]
Thanks for that!!
