### ISSUE TITLE
Using outputParameters to decode "string[]" return type failed

### ISSUE THREAD

**Issue by CoreyLin** [web3j/web3j#1236]
# _Issue_title_
Using outputParameters to decode "string[]" return type failed

## _Issue_description_
My smart contract has one function `balanceOf`, and its ABI is as following:

```
    {
        "constant": true,
        "inputs": [
            {
                "name": "_ss",
                "type": "string[]"
            }
        ],
        "name": "balanceOf",
        "outputs": [
            {
                "name": "result",
                "type": "string[]"
            }
        ],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
    },
```

According to the input and output parameters type, I use web3j to call this function, the code snippet is as following:

``` java
    @Test
    public void testCallBalanceOfHTLC() throws IOException {
        Web3j web3j = Web3j.build(new HttpService(
                "http://10.100.128.231:8545/"));
        Function function =
                new Function(
                        "balanceOf",
                        Arrays.asList(
                                new DynamicArray<>(
                                        new Utf8String("0xD3Ac266C12B0f198B1F103Ef87EadAb1162E39ed"))),
                        Collections.singletonList(new TypeReference<DynamicArray<Utf8String>>() {
                        }));
        String data = FunctionEncoder.encode(function);
        Transaction transaction = Transaction.createEthCallTransaction("0xD3Ac266C12B0f198B1F103Ef87EadAb1162E39ed", "0x3e6e547bC917001Cef35a3dDd6376BAd2e4Ab7Db", data);
        EthCall ethCall = web3j.ethCall(transaction, DefaultBlockParameterName.LATEST).send();

        List<Type> results = FunctionReturnDecoder.decode(ethCall.getValue(), function.getOutputParameters());

        System.out.println(((DynamicArray)results.get(0)).getValue().get(0));
    }
```

The calling is successful but the output's ABI decoding result `((DynamicArray)results.get(0)).getValue().get(0)` is **empty string** "", so I doubt there is something wrong with the `new Function` especially the third argument `outputParameters` , but I have already gone through all the [web3j unit tests](https://github.com/web3j/web3j/tree/master/abi/src/test/java/org/web3j/abi) for abi very carefully and haven't not found any clue, so I can't figure out it is a web3j bug or I use it incorrectly.

In contrast, `balanceOf` function can be called from remix and it worked well and returned corrent value.

<img width="321" alt="微信图片_20200713194936" src="https://user-images.githubusercontent.com/12689769/87369022-08c1f180-c5b2-11ea-8140-8e48c0f0f4b9.png">

So is there any web3j expert to tell me what is wrong with my code? How to solve the outputparameter decoding problem? Thanks very much.

## _Issue_context_
web3j version is 4.5.0

**Comment by CoreyLin** [comment]
Supplemented information:

The value of `ethCall.getValue()` is:

0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000203939373737380000000000000000000000000000000000000000000000000000

**Comment by SweeXordious** [comment]
There is a [PR](https://github.com/web3j/web3j/pull/1321) solving the arrays of strings encoding/decoding and adding support for arrays of structs and also multiple structs/arrays of structs multiple returns. Please take a look on it and let us know your feedback.
Also, instead of creating the transaction yourself, we have a [Web3j-Gradle-Plugin](https://github.com/web3j/web3j-gradle-plugin) that will create Java wrappers for the solidity contract you are targeting and will do all the work for you.
Thank you and have a great day.

**Comment by SweeXordious** [comment]
Fixed and merged 🎉
