### ISSUE TITLE
java.util.concurrent.ExecutionException: com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class com.fasterxml.jackson.databind.util.LRUMap and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.web3j.protocol.core.Request["web3jService"]->org.web3j.protocol.http.HttpService["objectMapper"]->com.fasterxml.jackson.databind.ObjectMapper["_deserializationConfig"]->com.fasterxml.jackson.databind.DeserializationConfig["_base"]->com.fasterxml.jackson.databind.cfg.BaseSettings["_classIntrospector"]->com.fasterxml.jackson.databind.introspect.BasicClassIntrospector["_cachedFCA"])

### ISSUE THREAD

**Issue by mimosaha** [web3j/web3j#1242]
# java.util.concurrent.ExecutionException: com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class com.fasterxml.jackson.databind.util.LRUMap and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.web3j.protocol.core.Request["web3jService"]->org.web3j.protocol.http.HttpService["objectMapper"]->com.fasterxml.jackson.databind.ObjectMapper["_deserializationConfig"]->com.fasterxml.jackson.databind.DeserializationConfig["_base"]->com.fasterxml.jackson.databind.cfg.BaseSettings["_classIntrospector"]->com.fasterxml.jackson.databind.introspect.BasicClassIntrospector["_cachedFCA"])

## _Issue_description_
I am trying to fetch Etherium balance using my wallet address
I am using the following line for reading ether
`web3j.ethGetBalance(address, DefaultBlockParameterName.LATEST).sendAsync().get()` 

This line working fine in debug mode but when I am preparing release build with `minifyEnabled` is true then I am facing this exception.

My Proguard rule is 

```
-dontwarn java8.util.**
-dontwarn jnr.posix.**
-dontwarn com.kenai.**

#-keep class org.bouncycastle.**
-dontwarn org.bouncycastle.jce.provider.X509LDAPCertStoreSpi
-dontwarn org.bouncycastle.x509.util.LDAPStoreHelper

-keep public class com.go.releasewalletcreate.CurrencyUtil { *; }

-dontwarn com.fasterxml.jackson.databind.**
-keep class org.** {*;}
-keep class com.fasterxml.jackson.core.** {*;}
-keep interface com.fasterxml.jackson.core { *; }
-keep public class * extends com.fasterxml.jackson.core.*
-keep class com.fasterxml.jackson.databind.introspect.VisibilityChecker$Std.
-keep class com.fasterxml.jackson.databind.ObjectMapper.
-keep class com.fasterxml.jackson.databind.** {*;}
-keep class com.fasterxml.jackson.databind.introspect.VisibilityChecker${*;}
-keep interface com.fasterxml.jackson.databind { *; }
-keep public class * extends com.fasterxml.jackson.databind.*
-keep class com.fasterxml.jackson.annotation.** {*;}
-keep interface com.fasterxml.jackson.annotation.** {*;}
```

And my grade version list

```
implementation 'org.web3j:core:4.6.0-android'
implementation 'io.socket:socket.io-client:1.0.0'

```
Please provide me the guideline for how can I resolve this and working in release mode.

Thanks.
Mimo

**Comment by haoyh** [comment]
same exception, Have you fix it?

**Comment by GrapeBaBa** [comment]
com.fasterxml.jackson.databind.util.LRUMap should be added in reflect-config.json.
