### ISSUE TITLE
How to write a smart contract in Java and deploy it

### ISSUE THREAD

**Issue by liming1010** [web3j/web3j#1243]
How to write a smart contract in Java and deploy it？

**Comment by AlexandrouR** [comment]
Hey, in regards to writing smart contracts  there are a ton of great tutorials out there. To deploy smart contracts you can use [Epirus CLI](https://github.com/epirus-io/epirus-cli). Have a look at the docs we make it very easy.

**Comment by liming1010** [comment]
emmmmmm....... ok
