### ISSUE TITLE
can't call parity method personalAccountsInfo

### ISSUE THREAD

**Issue by Brucecarl** [web3j/web3j#125]
It seems that parity api has changed! the parity api of personalAccountsInfo is [parity_allAccountsInfo](https://github.com/paritytech/parity/wiki/JSONRPC-parity_accounts-module#parity_allaccountsinfo)  ,but the method send a request :{"jsonrpc":"2.0","method":"personal_accountsInfo","params":[],"id":1}

so this cause to the error "Method not found".(my parity server version is v1.5.12)
has this issue handled???

**Comment by conor10** [comment]
There have been some changes to the Parity API, work is being done to bring them up to date. Hopefully this release will go out in the next week or two.

**Comment by conor10** [comment]
Fixed by https://github.com/web3j/web3j/pull/147.
