### ISSUE TITLE
RLPDecoder fails to throw an exception for invalid input

### ISSUE THREAD

**Issue by jrhea** [web3j/web3j#1252]
### Expected behavior
The following test cases should raise an exception in RLPDecoder:

This string is missing a valid length prefix:
```Java
        assertThrows(
                RuntimeException.class,
                (() ->
                        RlpDecoder.decode(
                                new byte[] {
                                    (byte) 0x58, (byte) 0x58, (byte) 0x58, (byte) 0x58, (byte) 0x58
                                })));

```
This RLP list has the wrong length prefix: 
```Java
        assertThrows(
                RuntimeException.class,
                (() ->
                        RlpDecoder.decode(
                                new byte[] {
                                    (byte) 0xc0, (byte) 0x58, (byte) 0x58, (byte) 0x58, (byte) 0x58
                                })));
```
### Actual behavior
The decoder does not raise an exception

**Comment by Nashatyrev** [comment]
@jrhea I believe both cases are legit RLP lists. 
The first case is `[0x58, 0x58, 0x58, 0x58, 0x58]`, i.e. the list of 5 byte strings (each of size 1)
The second case is `[[], 0x58, 0x58, 0x58, 0x58]`, i.e. the list with empty list and 4 bytes strings (each of size 1)

**Comment by jrhea** [comment]
> @jrhea I believe both cases are legit RLP lists.

I checked these inputs with the code at: 

   https://eth.wiki/fundamentals/rlp

and it doesn't seem equivalent

> The first case is `[0x58, 0x58, 0x58, 0x58, 0x58]`, i.e. the list of 5 byte strings (each of size 1)

According to code in the RLP wiki, it needs to be prefixed with `0x85`.  web3J classifies it as 5 single byte strings, but that is not how the specification describes this type:

`the data is a string if the range of the first byte(i.e. prefix) is [0x00, 0x7f], and the string is the first byte itself exactly;`

The only way to classify a single byte string is to only pass in a single byte string.  We can verify it with the code in the wiki, the first thing `rlp_decode()` does is call `decode_length()` which has it's own specific condition for a single byte string:

```python
    if prefix <= 0x7f:
        return (0, 1, str)
```

Otherwise, it has to have a length prefix.  So we can either call the decode method 5 times each with a 1 byte string, or pass it in at once as a multibyte string (see output below):

![image](https://user-images.githubusercontent.com/5555162/92030966-6a3e4b00-ed2d-11ea-98c7-fc93d2853c2c.png)


As you can see, it prefixes the string with `0x85`.  The only way to classify a single byte string is provide an input with only a single byte: 


![image](https://user-images.githubusercontent.com/5555162/92030903-5397f400-ed2d-11ea-8dac-4238ca5693e9.png)


> The second case is `[[], 0x58, 0x58, 0x58, 0x58]`, i.e. the list with empty list and 4 bytes strings (each of size 1)

Again, using the code from the RLP wiki I can verify that `[0xc0, 0x58, 0x58, 0x58, 0x58]` does not translate to an  empty list and 4 bytes strings (each of size 1):

![image](https://user-images.githubusercontent.com/5555162/92031521-5a733680-ed2e-11ea-87fb-97de45657d34.png)

The only way to encode an empty list and 4 individual byte strings of size 1, is to put it in an outer list that has a length prefix of `0xc5`, or call decode 5 times. Once with `0xc0` and four times with `0x58`.

**Comment by mohamedelshami** [comment]
I've closed this due to inactivity, please feel free to reopen if still valid
