### ISSUE TITLE
ABI v2 decoder cannot decode struct containing bytes32.

### ISSUE THREAD

**Issue by usd-yamazaki** [web3j/web3j#1257]
## Steps To Reproduce
Execute a function that returns the following structure
```
struct Test {
    bytes32 a;
    string b;
}
```

### Expected behavior
Parameters are decoded and structure is returned

### Actual behavior
java.lang.StringIndexOutOfBoundsException

## Environment
-Web3j version
4.6.0-android
-Epirus version
1.2.4
-Java or Android version
Android 9
-Operating System
Android

## Additional context
Maybe something is wrong here.
Reading the data in Bytes32 advances the offset by 32 * 32.
https://github.com/web3j/web3j/blob/7ab0f6a05d318cb1b434647dd33a17b442ab06ac/abi/src/main/java/org/web3j/abi/TypeDecoder.java#L513
https://github.com/web3j/web3j/blob/7ab0f6a05d318cb1b434647dd33a17b442ab06ac/abi/src/main/java/org/web3j/abi/datatypes/BytesType.java#L30

**Comment by usd-yamazaki** [comment]
I made a mistake, the offset added is 32 * 32 * 2.

**Comment by SweeXordious** [comment]
There is a [PR](https://github.com/web3j/web3j/pull/1321) solving this and adding support for arrays of structs and also multiple structs/arrays of structs multiple returns. Please take a look on it and let us know your feedback.
Thank you and have a great day.

**Comment by SweeXordious** [comment]
Fixed and merged 🎉
