### ISSUE TITLE
java.lang.IllegalArgumentException: Cost parameter N must be > 1 and < 65536

### ISSUE THREAD

**Issue by siddhpuraamitr** [web3j/web3j#1262]
From server side we are using below library

https://nethereum.com/

From Android Side we are using Web3j library

Now if wallet file is generated on Android side then it is working fine on Server side

Below is file which is generated by Android

`{"version":3,"id":"7ba21600-3b17-40f0-b95b-6e3e3da40fd8","crypto":{"ciphertext":"978a49bf02fc0f340894eadfc2ad9ba66c3893ef21ca481b1746d40160dfe4c9","cipherparams":{"iv":"cce1f2d2f7a21607ad6215a17a421f41"},"kdf":"scrypt","kdfparams":{"r":6,"p":1,"n":4096,"dklen":32,"salt":"a579622a0e9bc14d1dc7b73707abbabdb1810ec870c755ca9dc665ca4aa44d05"},"mac":"5078490e9d60a1d022bf0294a11a977bb45d243df5b6ee6fb46cae29e726c072","cipher":"aes-128-cbc"},"address":"0x70843049e9e3a282b984046b47540a4fc949458d"}`

Now if wallet file is generated by Server side then that file is not working on Android side, below is wallet file

`{"crypto":{"cipher":"aes-128-ctr","ciphertext":"5009596033bbe20218f4df102a5284b5f15a8c62b742a610e5f62f468a9ee074","cipherparams":{"iv":"41a1bbd9c1e2bd16619bafa3e586817d"},"kdf":"scrypt","mac":"441367c0375bc2028ba1162e98e3b280838e3f9b0da5d236dfefd149b58a097c","kdfparams":{"n":262144,"r":1,"p":8,"dklen":32,"salt":"58510022b0399a8c5b7ce63ff27967ec38ee08b388c56f3b32857abcb6a2c381"}},"id":"fbf22e42-7b84-41ff-8d44-405ec951c04b","address":"0xdD3482f1545dF52b85B85A8F65C461D1b696Bd83","version":3}`

Now in both file difference you can see here is that 

(Server side: {**"n":262144,"r":1,"**. vs  Client Side (Android) **"r":6,"p":1,"n":4096,"**

If I try to get credential on Android side by executing following function

 WalletUtils.loadCredentials(walletPassword, walletFile)

I will get below error 

```
Caused by: java.lang.IllegalArgumentException: Cost parameter N must be > 1 and < 65536.
        at org.bouncycastle.crypto.generators.SCrypt.generate(Unknown Source:24)
        at org.web3j.crypto.Wallet.generateDerivedScryptKey(Wallet.java:145)
        at org.web3j.crypto.Wallet.decrypt(Wallet.java:213)
        at org.web3j.crypto.WalletUtils.loadCredentials(WalletUtils.java:151)
```

This is just because 

in SCrypt.java (line no. 51) following code throwing an error

       if (r == 1 && N >= 65536) // it become true because from Server side: {**"n":262144,"r":1,"**. 
        {
            throw new IllegalArgumentException("Cost parameter N must be > 1 and < 65536.");
        }

How can I resolve this, can anyone help me, thanks in advance

**Comment by JasonYH** [comment]
I also encountered this problem.

**Comment by TSRL** [comment]
I encounter the same problem when feeding the key generated by python web3 to a web3j
