### ISSUE TITLE
okhttp3

### ISSUE THREAD

**Issue by woshiyezhuxi** [web3j/web3j#1269]
springboot 
java.lang.ClassNotFoundException: okhttp3.CipherSuite

POM.xml
        <dependency>
            <groupId>org.web3j</groupId>
            <artifactId>core</artifactId>
            <version>4.6.3</version>
            <exclusions>
                <exclusion>
                    <artifactId>okhttp</artifactId>
                    <groupId>com.squareup.okhttp3</groupId>
                </exclusion>
            </exclusions>
        </dependency>

<dependency>
     <groupId>com.squareup.okhttp3</groupId>
     <artifactId>okhttp</artifactId>
     <version>4.9.0</version>
</dependency>

**Comment by mmaryo** [comment]
Hello @woshiyezhuxi 

You should give us an repository with minimal example 

I had this error for another project and the reason was 2 versions of okhttp was provided by dependencies
I have to exclud okhttp from each dependency and import it
