### ISSUE TITLE
NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'

### ISSUE THREAD

**Issue by mmaryo** [web3j/web3j#1271]
Hello 

When I run Web3j.build(HttpService("https://ropsten.infura.io/$id")).web3ClientVersion().send()

Therer is an error

java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'

Inside **HttpService** and **performIO** I see  
> RequestBody.create(request, JSON_MEDIA_TYPE);    

Is wrong 

It should be 
> RequestBody.create(JSON_MEDIA_TYPE, request);   

![Screenshot 2020-09-30 02:42:51](https://user-images.githubusercontent.com/1669985/94630801-0cb70300-02c7-11eb-9b78-994803983c95.png)

## Environment
Kotlin 1.4.0
Quarkus 1.8.1.Final
Web3j 5.0.0

**Comment by thor-ragnarok** [comment]
please use 4.6.3 which is the actual current latest lol - web3j 5.0.0 is on the way...

**Comment by Komari-Koshigaya** [comment]
I encountered  the same problem *java.lang.NoSuchMethodError: okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;*; 
when I use web3j-4.6.3 and run `Web3ClientVersion clientVersion = web3.web3ClientVersion().send();`

Is there any solution?

**Comment by claritize** [comment]
Still running into this issue, I am using Ganache. Will test with Geth when it's sync'd.

**Comment by claritize** [comment]
> I encountered the same problem _java.lang.NoSuchMethodError: okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;_;
> when I use web3j-4.6.3 and run `Web3ClientVersion clientVersion = web3.web3ClientVersion().send();`
> 
> Is there any solution?

Did you manage to fix it?

**Comment by claritize** [comment]
Fixed: Manually adding the okhttp3 dependency will fix it!

**Comment by hadv** [comment]
> Fixed: Manually adding the okhttp3 dependency will fix it!

thanks!

**Comment by pipepi** [comment]
web3j-4.8.4 has the same problem

**Comment by BarBozz** [comment]
Still issue with `web3j-5.0.0`!

Only helping is 

```xml
	<dependencyManagement>
		<dependencies>
			<!--  Needed to avoid conflict with OkHttp being used in auth0-java and okhttp3 being used by spring -->
			<dependency>
				<groupId>com.squareup.okhttp3</groupId>
				<artifactId>okhttp</artifactId>
				<version>4.9.0</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

found here: https://github.com/auth0/auth0-java/pull/342/files and here https://github.com/auth0/auth0-java/issues/324

**Comment by jacktpy** [comment]
> Fixed: Manually adding the okhttp3 dependency will fix it!

I have the same problem, how do I need to add dependencies manually?

**Comment by ronni7** [comment]
> 
> 
> > Fixed: Manually adding the okhttp3 dependency will fix it!
> 
> I have the same problem, how do I need to add dependencies manually?

Hey. I had the same issue, solved it by copypasting @BarBozz code, so my pom.xml structure looks like this:
<project>
<modelVersion></modelVersion>
<dependencies></dependencies>

</project>

**Comment by icemagno** [comment]
Same issue with 4.8.4.

@BarBozz solutions gives me this
```

Exception in thread "main" java.lang.NoSuchMethodError: kotlin.collections.ArraysKt.copyInto([B[BIII)[B
	at okio.Segment.writeTo(Segment.kt:169)
	at okio.Segment.compact(Segment.kt:152)
	at okio.Buffer.write(Buffer.kt:1842)
	at okio.Buffer.read(Buffer.kt:1854)
	at okio.Buffer.writeAll(Buffer.kt:1642)
	at okio.Options$Companion.buildTrieRecursive(Options.kt:187)
	at okio.Options$Companion.buildTrieRecursive(Options.kt:174)
	at okio.Options$Companion.buildTrieRecursive$default(Options.kt:113)
	at okio.Options$Companion.of(Options.kt:72)
	at okhttp3.internal.Util.<clinit>(Util.kt:71)
	at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
	at org.web3j.protocol.http.HttpService.createOkHttpClient(HttpService.java:138)
	at org.web3j.protocol.http.HttpService.<init>(HttpService.java:118)


```
I'm using Spring Boot

**Comment by piotrzietek** [comment]
<dependency>
			<groupId>org.web3j</groupId>
			<artifactId>core</artifactId>
			<version>4.8.9</version>
		</dependency>
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp</artifactId>
			<version>4.9.3</version>
		</dependency>

Solve it.

**Comment by bpawan** [comment]
For anyone using gradle:

`
	implementation 'org.web3j:core:5.0.0'
	implementation 'com.squareup.okhttp3:okhttp:4.9.3'
`

Will fix the problem.

**Comment by MarkusKramer** [comment]
I'm still seeing this bug. Setting the versions as suggested in the last two comments didn't help. Tested with:
- java 17
- quarkus 2.13.3.Final
- kotlin 1.7.20
- web3j 4.8.9 and 4.9.4

Going back to older versions (Java 11, Quarkus 2.1.2, Kotlin 1.4.32) solves the issue for me - without having to include a dependency to okhttp.

**Comment by Kydarenft** [comment]
Is there anyone out there to fix this bug?

**Comment by FaribaGhaffari91** [comment]
Hello Everyone :) 
I had the same problem, and then I added the dependency manually, the problem solved. Now I face with a new issue.  Okhttp prints all DEBUG logs. I appreciate your help to see if anyone solved this issue? [I may need add sth in properties file, but I don't know what to add].

**Comment by FaribaGhaffari91** [comment]
> Is there anyone out there to fix this bug?
If you are using maven, add this dependency in your pom file.

	<dependency>
		<groupId>com.squareup.okhttp3</groupId>
		<artifactId>okhttp</artifactId>
		<version>4.10.0</version>
	</dependency>

**Comment by MarkusKramer** [comment]
For me the solution is now to not using the quarkus-bom.
So remove the line (when using Gradle)
```
implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))
```
and instead append ":${quarkusPlatformVersion}" to all quarkus dependencies. This way the okhttp version is not getting fixed to 3.x.x by the quarkus bom.

Works with
 * Quarkus 3.0.3
 * web3j:core:4.9.8

**Comment by bofomike** [comment]
It's still na issue for me even if I have already added suggested dependency. 

Java 17

```
        <dependency>
            <groupId>org.web3j</groupId>
            <artifactId>core</artifactId>
            <version>4.9.7</version>
        </dependency>

        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.9.3</version>
        </dependency>
```

```
java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'
	at org.web3j.protocol.http.HttpService.performIO(HttpService.java:159) ~[core-4.9.7.jar:na]
	at org.web3j.protocol.Service.send(Service.java:48) ~[core-4.9.7.jar:na]
	at org.web3j.protocol.core.Request.send(Request.java:87) ~[core-4.9.7.jar:na]
```

Can anyone help me please?

**Comment by ixiaoku** [comment]
这样就解决报错了 不知道是是不是版本做了兼容

**Comment by ixiaoku** [comment]
这样就解决报错了不知道是不是版本兼容 这两个版本放一起就没问题了

 <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.9.0</version>
        </dependency>

 
        <dependency>
            <groupId>org.web3j</groupId>
            <artifactId>core</artifactId>
            <version>4.9.7</version>
        </dependency>

**Comment by ixiaoku** [comment]
这个困扰了我好久 升级了okhttp的版本 原先是4.12.0 怎么搞都不行 不要okhttp都不行
` 
        <dependency>
            <groupId>org.web3j</groupId>
            <artifactId>core</artifactId>
            <version>4.9.7</version>
        </dependency>

<dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.9.0</version>
        </dependency>
`

**Comment by ixiaoku** [comment]
web3j用4.0.7 okhttp用这个版本 问题解决
<dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.9.0</version>
        </dependency>
