### ISSUE TITLE
Utf8String DynamicArray is decoded incorrectly

### ISSUE THREAD

**Issue by usd-yamazaki** [web3j/web3j#1278]
It is currently being tested with the following data:
https://github.com/web3j/web3j/blob/bc3f03ddf98b5c0b9c678ecb9e600d1b4f6bf30c/abi/src/test/java/org/web3j/abi/TypeDecoderTest.java#L1121

```
0000000000000000000000000000000000000000000000000000000000000002	array length
000000000000000000000000000000000000000000000000000000000000000d	string1 length
48656c6c6f2c20776f726c642100000000000000000000000000000000000000	string1 data
000000000000000000000000000000000000000000000000000000000000000d	string2 length
776f726c64212048656c6c6f2c00000000000000000000000000000000000000	string2 data
```

But, the actual DynamicArray of Utf8String has such a structure.

```
0000000000000000000000000000000000000000000000000000000000000002	array length
0000000000000000000000000000000000000000000000000000000000000040	string1 offset
0000000000000000000000000000000000000000000000000000000000000080	string2 offset
000000000000000000000000000000000000000000000000000000000000000d	string1 length
48656c6c6f2c20776f726c642100000000000000000000000000000000000000	string1 data
000000000000000000000000000000000000000000000000000000000000000d	string2 length
776f726c64212048656c6c6f2c00000000000000000000000000000000000000	string2 data
```

## Environment
-Web3j version
4.6.0-android
-Epirus version
1.2.4
-Java or Android version
Android 9
-Operating System
Android

**Comment by esaulpaugh** [comment]
can confirm. just tested it on my library. array has to have offsets for each dynamic element

**Comment by jeremyjams** [comment]
I also confirm the issue, I'm having the same problem when a contract method returns such struct:
```
struct Kind {
    address owner;
    bytes32 type;
    string  params;
    uint256 ratio;
    Resource linkedResource;
}
```

**Comment by SweeXordious** [comment]
There is a [PR](https://github.com/web3j/web3j/pull/1321) solving this and adding support for arrays of structs and also multiple structs/arrays of structs multiple returns. Please take a look on it and let us know your feedback.
Thank you and have a great day.

**Comment by SweeXordious** [comment]
Fixed and merged 🎉
