### ISSUE TITLE
Do generated contracts need binary file ?

### ISSUE THREAD

**Issue by mmaryo** [web3j/web3j#1280]
I simply generate contract with command line 

`epirus solidity generate --abiFile=contracts/UniswapV2RouterContract.abi --outputDir=src/main/java --package=com.app.contracts`

The result is in UniswapV2RouterContract.java in constructer I see BINARY constante
```
protected UniswapV2RouterContract(String contractAddress, Web3j web3j,...) {
        super(BINARY, contractAddress, web3j, ...);
    }
```

And the value is 
`    public static final String BINARY = "Bin file was not provided";`

When I load the contract and call isValid() method, that throw an exception 

```
        val contract = UniswapV2RouterContract.load(
            contractAddress,
            web3j,
            web3j.getCredentials(),
            garsProvider)
        log.info("Load UniswapV2RouterContract, isValid: ${contract.isValid}")
```
`
UnsupportedOperationException: Contract binary not present in contract wrapper, please generate your wrapper using -abiFile=<file>`

**Comment by thor-ragnarok** [comment]
you need to pass the `--binFile` flag for `epirus solidity generate`
