### ISSUE TITLE
ethGetBalance in release mode

### ISSUE THREAD

**Issue by bajritoAbc** [web3j/web3j#1282]
App works fine in debug mode but in release mode ethGetBalance isn't returning Balance.

Here's exception printStackTrace :

Can not create TypeBindings for class java.lang.Object with 1 type parameter: class expects 0 (through reference chain: org.web3j.protocol.core.Request["web3jService"]

**Comment by thor-ragnarok** [comment]
Thanks for submitting the bug report. To help out the maintainers it would be useful to provide as much information as possible so they can attempt to replicate your issue. Please tell us what version of Web3j you are using. Also a minimum code example to help replicate would be super useful.

**Comment by bajritoAbc** [comment]
@thor-ragnarok 
I'm using 'org.web3j:core:5.0.0' ,
Here's the whole method. Works fine in debug mode but not in release mode.

public Double getWalletBalance(String walletAddress) throws ExecutionException, InterruptedException {
        Web3j web3j = WalletLib.getServerInstance();
        boolean serverInstance = web3j != null;
        EthGetBalance ethGetBalance = null;
        if (serverInstance) {
            try {
                ethGetBalance = web3j.ethGetBalance(walletAddress, DefaultBlockParameterName.LATEST).sendAsync().get();
            } catch (Exception e) {
                e.printStackTrace(); 
            }
        }
        BigInteger wei = ethGetBalance.getBalance();
        return Convert.fromWei(wei.toString(), Convert.Unit.ETHER).doubleValue();
    }

when trying  to get balance exception is thrown : Can not create TypeBindings for class java.lang.Object with 1 type parameter: class expects 0 (through reference chain: org.web3j.protocol.core.Request["web3jService"]

Thank you !

**Comment by bajritoAbc** [comment]
@thor-ragnarok  here's my release buildType 

 release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.sign
        }

**Comment by thor-ragnarok** [comment]
please can you edit your messages and surround code with triple backticks (usually top left key below `esc`) -> ```
```
so much easier to read
```

**Comment by bajritoAbc** [comment]
@thor-ragnarok  I've edited my message. Thank you for your help !

**Comment by thor-ragnarok** [comment]
please try with web3j v4.7.0 - this is current latest version. Version 5.0.0 was a release done by mistake which cannot be removed from maven...

your code looks correct on the face of it you shouldn't have any problem. LMK how it goes I will try to reproduce if issue persists

**Comment by bajritoAbc** [comment]
Same problem again : 

W/System.err: java.util.concurrent.ExecutionException: com.shakebugs.shake.internal.Nk: Can not create TypeBindings for class java.lang.Object with 1 type parameter: class expects 0 (through reference chain: org.web3j.protocol.core.Request["web3jService"]->testdev.com.mwalletlib.networking.HttpServiceLib["objectMapper"])

**Comment by thor-ragnarok** [comment]
hmm, best thing to do is set the logging level of `org.web3j.protocol` to debug - this will show us the http that are being made

**Comment by JasonLee-crypto** [comment]
@bajritoAbc If you use android proguard, try use this:
`proguardFiles getDefaultProguardFile('proguard-android.txt')` instead of the optimize one, this will work
