### ISSUE TITLE
Exception when try to getTransactionCount

### ISSUE THREAD

**Issue by AlexShniperson-INO** [web3j/web3j#1286]
# Exception throws when call getTransactionCount
Exception throws when call `getTransactionCount`

## Steps To Reproduce
call `getTransactionCount` with block number `1101705`

### Expected behavior
Valid number of transactions

### Actual behavior
```
>>> Error 'Value must be in format 0x[1-9]+[0-9]* or 0x0' block=1101705
org.web3j.exceptions.MessageDecodingException: Value must be in format 0x[1-9]+[0-9]* or 0x0
	at org.web3j.utils.Numeric.decodeQuantity(Numeric.java:47)
	at org.web3j.protocol.core.methods.response.EthGetBlockTransactionCountByNumber.getTransactionCount(EthGetBlockTransactionCountByNumber.java:23)
```

## Environment
_Describe the environment in which the issue occurs_
- Web3j 5.0.0
- Java: 1.8
- Operating System: osx 10.15.7

**Comment by AlexandrouR** [comment]
@AlexShniperson-INO Hi, the latest web3j version is 4.8.4 is that the version you are using?

**Comment by AlexShniperson-INO** [comment]
hi, no i used `5.0.0` version
