### ISSUE TITLE
Filtering never returns if no matching topic is found in a range of blocks

### ISSUE THREAD

**Issue by zguesmi** [web3j/web3j#1288]
# Filtering does not stop when no item is found in a range of blocks.
I am using `web3j.ethLogFlowable(filter).blockingFirst()` to filter for a specific topic in a range of blocks. If that topic is not matched in that range I expect it to throw a NoSuchElementException as mentioned [here](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#blockingFirst--).

## Description
My goal is to check for a smart contract's event in a range of blocks. I create an `EthFilter` with a start/end blocks
```
private EthFilter createEthFilter(long fromBlock, long toBlock, Event event) {
    DefaultBlockParameter startBlock = DefaultBlockParameter.valueOf(BigInteger.valueOf(fromBlock));
    DefaultBlockParameter endBlock = DefaultBlockParameter.valueOf(BigInteger.valueOf(toBlock));
    EthFilter ethFilter = new EthFilter(
            startBlock,
            endBlock,
            getContractAddress()
    );
    ethFilter.addSingleTopic(EventEncoder.encode(event));
    return ethFilter;
}
```

and I use it in `web3j.ethLogFlowable()` to filter for my event.
```
EthFilter filter = createEthFilter(from, to, event);
web3j.ethLogFlowable(filter)
        .map(log -> {
            // convert to event
        })
        .filter(event -> {
            // specify criteria
        })
        .map(event -> {
            // do transformation
        })
        .blockingFirst();
```
Everything works perfectly if the event is found in that range of blocks, but if the event is not found, the call never returns or throws NoSuchElementException error as it should be doing according to the official documentation (of reactivex.io). The thread waiting for `.blockingFirst()` is simply blocked for ever. From a first glance, I did not manage to find where are you considering the start/end blocknumbers in the code. I might be missing something. 

## Context
Java version: 11
Web3j version: `org.web3j:core:4.6.0`

**Comment by zguesmi** [comment]
@conor10 any thoughts about this, please?

**Comment by mohamedelshami** [comment]
@zguesmi does this issue still persist?

**Comment by zguesmi** [comment]
@mohamedelshami thank you for your comment.
I don't know if the problem is still present, I haven't tested it for a long time.
I think we could close this issue for now.
