### ISSUE TITLE
Different Credentials with the same nemonic

### ISSUE THREAD

**Issue by eggham0518** [web3j/web3j#1291]
Which credential should I use?

When I restored my wallet with the same nemonic from another service //metaMask
Credentials generated by getCredentialsFromNemonic() had the same as the wallet generated by other services.

And This method did not WalletUtils.loadCredentials()

How can I make the same wallet as other services?

    private void testBip39Wallet(String password) {
        try {
            Bip39Wallet bip39Wallet = WalletUtils.generateBip39Wallet(password, getCacheDir());
            String mnemonic = bip39Wallet.getMnemonic();

            getCredentialsFromNemonic(mnemonic);
            Credentials credentialsFromLocalWallet = WalletUtils.loadCredentials(password, getCacheDir() + "/" + bip39Wallet.getFilename());
          
            String hexPrvKey = getHexPrvKey(credentialsFromLocalWallet.getEcKeyPair().getPrivateKey());
           
         
        } catch (Exception e) {
            e.printStackTrace();
            Log.e("Log e ", e.getMessage());
        }
    }

    int[] path = {44 | HARDENED_BIT, 60 | HARDENED_BIT, HARDENED_BIT, 0, 0,};

    private Credentials getCredentialsFromNemonic(String mnemonic) {
        Bip32ECKeyPair masterKeypair = Bip32ECKeyPair.generateKeyPair(MnemonicUtils.generateSeed(mnemonic, null));
        Bip32ECKeyPair derivedKeyPair = Bip32ECKeyPair.deriveKeyPair(masterKeypair, path);

        Credentials credentials =  Credentials.create(derivedKeyPair);
        return credentials;
    }

    private String getHexPrvKey(BigInteger bigInteger) {
        return Numeric.toHexStringWithPrefix(bigInteger);
    }

**Comment by Odiljon1994** [comment]
`      

        Random random = new Random();
        byte[] initialEntropy = new byte[16];
        random.nextBytes(initialEntropy);

        String mnemonic = MnemonicUtils.generateMnemonic(initialEntropy);
        System.out.println(mnemonic);
        Bip32ECKeyPair masterKeypair = Bip32ECKeyPair.generateKeyPair(MnemonicUtils.generateSeed(mnemonic, null));
      
        int[] path = {44 | Bip32ECKeyPair.HARDENED_BIT, 60 | Bip32ECKeyPair.HARDENED_BIT, 0 | Bip32ECKeyPair.HARDENED_BIT, 0,0};
        Bip32ECKeyPair  x = Bip32ECKeyPair.deriveKeyPair(masterKeypair, path);

        Credentials credentials = Credentials.create(x);

        System.out.println(credentials.getAddress());
        System.out.println(credentials.getEcKeyPair().getPrivateKey());
        System.out.println(Numeric.toHexStringWithPrefix(credentials.getEcKeyPair().getPrivateKey()));


`
