### ISSUE TITLE
Migrate to OkHttp for handling HTTP communication

### ISSUE THREAD

**Issue by conor10** [web3j/web3j#130]
web3j has historically used Apache HTTP client for HTTP connectivity with Ethereum nodes.

This has been problematic for Android clients, as HTTP client is not Java 1.6 compatible. A forked HTTP client is used to address this issue. However, users are still reporting [issues](https://github.com/web3j/web3j/issues/66) with this 

Migrating to [OkHttp](http://square.github.io/okhttp/) should address these issues, and given its robustness and size is a sound choice for web3j.

**Comment by fooock** [comment]
I agree that migrate to `OkHttp` is good idea, I can help with this. @conor10 have you started working on it? If not, I can prepare one PR to discuss the changes

**Comment by conor10** [comment]
Yes I have - I've got it working, see https://github.com/web3j/web3j/tree/okhttp.

However, I still haven't resolved how best to support the logging of HTTP requests. 

web3j has historically used Apache Commons' default logger for enabling request/response logging for HTTP/IPC clients as per https://docs.web3j.io/trouble.html#i-want-to-see-details-of-the-json-rpc-requests-and-responses. For working with okhttp, I've put slf4j in there for now, but not sure I want to stick with this, as I'm not convinced that slf4j is as popular with Android developers.

I'd be interested to get your thoughts, as I want to ensure web3j works for older versions of Andriod too.

**Comment by fooock** [comment]
Ok I see

I don't see much apps that use slf4j but is possible. 

Another possible solution can be create a listener to notify the http/ipc updates, so the developer is in charge of implementing their own logs logic.  Since the slf4j is only used in two classes, `HttpService` and `IpcService`, with this approach, this dependency can be removed. I explain.

Interface to receive the messages (http or ipc)
```java
public interface LogListener {
    void onReceive(Message message);
}
```

New class to notify messages
```java
public class Message {
    private final String message;

    public Message(String message) {
        this.message = message;
    }

    public String getMessage() {
        return message;
    }
}
```

When the `HttpLoggingInterceptor` is created, a new `Logger`is created:
```java
HttpLoggingInterceptor logging = new HttpLoggingInterceptor(message -> {
    logListener.onReceive(new Message(message));
});
okhttpclient.addInterceptor(logging);
```

If you want to receive new log updates a new constructor is required, for example

```java
public HttpService(LogListener logListener) {
    ....        
}
```

What do you think?

**Comment by conor10** [comment]
I've merged the okhttp migration branch.

From a non-Android perspective, I think the slf4j dependency is fine. However, I want to ensure web3j has just as much appeal for Android devs. 

@ligi - do you have an opinion on this?

**Comment by ligi** [comment]
Love the fact that you migrate to okhttp! I use this in nearly all of my apps and am really happy with it - also have a look into the underlying okio that you get with this - can also help in other aspects - this is a really good talk about this: https://www.youtube.com/watch?v=WvyScM_S88c
With slf4j - it is not a blocker - but I am personally not a big fan of it - and don't use it in my apps - though I have worked with it in some other apps I am involved with. I like timber way more: https://github.com/JakeWharton/timber

**Comment by conor10** [comment]
Appreciate your input @ligi - will watch that video shortly.

@fooock - your suggestion is valid, however, I'm going to leave the slf4j dependency in for now.

If it's enough to put Android dev's off the library I'd certainly reconsider. However, it's good to have for the Java community, and I want to ensure it remains as simple as possible for the majority of developers to log JSON-RPC requests in the library.

**Comment by ligi** [comment]
Was talking to @schildbach (he is actually using slf4j in his android apps) @cketti about it - the slf4j dependency is ok - just important that you just pull in the API and not a concrete implementation. Under android you would then use something like https://github.com/tony19/logback-android - or you could even use it with timber as I just found out (but never tested) https://github.com/arcao/slf4j-timber

**Comment by conor10** [comment]
Cool - yeah web3j is only using the [API dependency](https://github.com/web3j/web3j/blob/master/build.gradle#L97).
