### ISSUE TITLE
EIP712 Structured Data Reads BigInteger as Integer Causing RuntimeException

### ISSUE THREAD

**Issue by matthewdowney** [web3j/web3j#1301]
# EIP712 Structured Data Reads `BigInteger` as `Integer` Causing `RuntimeException`
- I am attempting to hash JSON formatted EIP712 structured data using `org.web3j.crypto.StructuredDataEncoder`. 
- One of my fields has the type `unt256`, and when my JSON is read via `new StructuredDataEncoder(myJson)` the field is read as an `Integer`, rather than a `BigInteger` or a `long`. 
- Subsequently, when I call `sde.hashStructuredData()`, I get a `RuntimeException` saying "Received an invalid argument for which no constructor exists for the ABI Class Uint256", because there's no constructor for `Uint256` that can handle an `Integer`.

## Steps To Reproduce
1. Take the JSON (below) and read it into a string.
2. Pass the json string to the constructor of `org.web3j.crypto.StructuredDataEncoder` and call `.hashStructuredData()` on it.

```json
{
  "types": {
    "EIP712Domain": [
      {
        "name": "name",
        "type": "string"
      },
      {
        "name": "version",
        "type": "string"
      },
      {
        "name": "chainId",
        "type": "uint256"
      },
      {
        "name": "verifyingContract",
        "type": "address"
      }
    ],
    "Order": [
      {
        "name": "flags",
        "type": "bytes32"
      },
      {
        "name": "amount",
        "type": "uint256"
      },
      {
        "name": "limitPrice",
        "type": "uint256"
      },
      {
        "name": "triggerPrice",
        "type": "uint256"
      },
      {
        "name": "limitFee",
        "type": "uint256"
      },
      {
        "name": "maker",
        "type": "address"
      },
      {
        "name": "taker",
        "type": "address"
      },
      {
        "name": "expiration",
        "type": "uint256"
      }
    ]
  },
  "primaryType": "Order",
  "domain": {
    "name": "P1Orders",
    "version": "1",
    "chainId": 1,
    "verifyingContract": "0x3ea6F88eC8F7b24Bb3Ad206fa80124210e8e28F3"
  },
  "message": {
    "flags": "0x0000000000000000000000000000000000000000000000000000000000000005",
    "amount": 10000,
    "limitPrice": 72010000000000000000,
    "triggerPrice": 0,
    "limitFee": 250000000000000,
    "maker": "0x00000000000000000000000090f8bf6a479f320ead074411a4b0e7944ea8c9c1",
    "taker": "0x000000000000000000000000ffcf8fdee72ac11b5c542428b35eef5769c409f0",
    "expiration": 1234
  }
}
```

### Expected behavior
The call to `.hashStructuredData()` should return hashed data, not throw an exception. (I'm expecting that hashed data to match [this dYdX python test case](https://github.com/dydxprotocol/dydx-python/blob/master/tests/test_perp_orders.py#L22).)

### Actual behavior
I get a `RuntimeException` saying "Received an invalid argument for which no constructor exists for the ABI Class Uint256", because there's no constructor for `Uint256` that can handle an `Integer`

## Environment
- Web3j version `4.8.1`
- Java or Android version: `javac 11.0.9.1`
- Operating System `Ubuntu 18.04.5 LTS`

## Additional context

I attached a debugger to figure out why it wasn't able to find the correct constructor. The other fields which have larger numbers (e.g. limitPrice) don't exhibit the same problem — they're read into instances of `BigInteger` — so it seems like a type inference problem for small numbers (in this case the expiry field).

**Comment by mohamedelshami** [comment]
This maybe handled in recent version, please report again if not.
