### ISSUE TITLE
Tether USDT token Approve method support

### ISSUE THREAD

**Issue by qdriven** [web3j/web3j#1302]
## Tether USDT token Approve method support

Follow the smart contract interaction of web3j,  approve call is failed for Tether USDT token. The reason I guess why it is failed is that the approve of Tether USDT token is not a standard ERC20 implementation.  

What I did was that:
1. download Tether USDT ABI file
2. Generate the contract code by the USDT ABI file
3. Create Contract instance by load function, then call the approve method
4. It is always failed, while other tokens like DAI/USDC could be successful.

But I didn't find a way to make the approve method call successfully via web3j. Is there any possible to do so?

**Comment by AlexandrouR** [comment]
@qdriven can you post the logs or stacktrace of the result ?
