### ISSUE TITLE
Duplicate class org.bouncycastle with Gradle "org.web3j:core:4.6.0-android" on Android Studio

### ISSUE THREAD

**Issue by Pren7z** [web3j/web3j#1305]
I just tried to implement org.web3j:core:4.6.0-android in my build.gradle in Android Studio but I get the duplicate class error for bouncy castle:

Duplicate class org.bouncycastle.LICENSE found in modules jetified-bcprov-jdk15on-1.60 (org.bouncycastle:bcprov-jdk15on:1.60) and jetified-bcprov-jdk15to18-1.63 (org.bouncycastle:bcprov-jdk15to18:1.63)

**Comment by Pren7z** [comment]
I have added the following to build.gradle and was able to run the application.

configurations {
        compile {
            exclude module: 'bcprov-jdk15on'
        }
    }

**Comment by AlexandrouR** [comment]
Do both of these dependencies come from web3j? @Pren7z
