### ISSUE TITLE
abi does not support DynamicArray of tuple 

### ISSUE THREAD

**Issue by Pana** [web3j/web3j#1317]
## Feature description_tupleDynamicArray
_A clear and concise description of what the feature would be._
For example i have defined a Struct  
```js
struct Entry {
        bytes key;
        bytes value;
}
```

And there is also a function, who's parameter is a Entry[].
It seems currently this is not support.
Seems DynamicArray only support string and bytes ?

**Comment by SweeXordious** [comment]
There is a [PR](https://github.com/web3j/web3j/pull/1321) solving this. Please take a look on it and let us know your feedback.
Thank you and have a great day.

**Comment by Pana** [comment]
@SweeXordious Good job, waiting for this PR merged 👍

**Comment by SweeXordious** [comment]
Fixed and merged 🎉
