### ISSUE TITLE
The Gradle Solidity plugin does not overwrite the generated Java files only if the Smart Contract interface does not change

### ISSUE THREAD

**Issue by saltiniroberto** [web3j/web3j#1319]
The Gradle Solidity plugin does not overwrite the generated Java files only if the Smart Contract interface does not change

## Steps To Reproduce
1. Create a new project via `epirus new`
2. Execute `./gradlew test`
3. Modify the `greeting` function of `HelloWorld.sol` to
```
    function greeting() public view returns (string memory)  {
        return "ERROR";
    }
```
4. Execute `./gradlew test`

### Expected behavior

1. The field `BINARY` of the file `/build/generated/sources/web3j/main/java/io/epirus/generated/contracts/HelloWorld.java` should be modified by the execution of step 4 above.
2. As a consequence of this,  the execution of `./gradlew test` at step 4 should fail

### Actual behavior
1. The field `BINARY` of the file `/build/generated/sources/web3j/main/java/io/epirus/generated/contracts/HelloWorld.java` is not modified by the execution of step 4 above.
2. The execution of `./gradlew test` at step 4 does not fail

## Environment
- Web3j: 4.8.1
- Java: 11
- Operating System: Ubuntu 18.04

## Additional context
if the Smart Contract interface is changed, like by adding a function, then the plugin behaves as expected.

**Comment by AlexandrouR** [comment]
Fix is on the way.

**Comment by AlexandrouR** [comment]
[Fix](https://github.com/web3j/web3j-gradle-plugin/pull/52)
