### ISSUE TITLE
`epirus solidity generate` results in unrecognised input parameters

### ISSUE THREAD

**Issue by saltiniroberto** [web3j/web3j#1320]
# `epirus solidity generate` does not work as expected
`epirus solidity generate` results in unrecognised input parameters

## Steps To Reproduce
1. Use `solc` to generate the Smart Contract abi file `Greet.abi`
2. Execute `epirus solidity generate -a Greet.abi -o . -p com`

### Expected behavior
A Java wrapper for the Greet Smart Contract should be generated.

### Actual behavior
The following is outputted:
```
  ______       _                
 |  ____|     (_)               
 | |__   _ __  _ _ __ _   _ ___ 
 |  __| | '_ \| | '__| | | / __|
 | |____| |_) | | |  | |_| \__ \
 |______| .__/|_|_|   \__,_|___/
        | |                     
        |_|                     
Unknown options: '-a', 'Greet.abi', '-o', '.', '-p', 'com'

epirus [OPTIONS] [COMMAND]

Description:

Run Epirus CLI commands

Options:
  -h, --help        Show this help message and exit.
      --telemetry   Whether to perform analytics.
  -v, --version     Print version information and exit.
Commands:
  account   Manage your epirus account
  audit     Audit Solidity contract
  docker    Run generated projects in Docker
  generate  Generate Wrappers or Tests
  help      Displays help information about the specified command
  import    Import existing Solidity contracts into a new Web3j Project
  login     Login to an Epirus account
  logout    Logout from an Epirus account
  new       Create a new Web3j Project
  openapi   Generate a Web3j-OpenAPI project
  run       Run your project using a live Ethereum network
  test      Run the tests of a gradle project
  wallet    Manage wallets for Ethereum

Epirus CLI is licensed under the Apache License 2.0
```

## Environment
- Epirus: 1.4.0
- Java: 11
- Operating System: Ubuntu 18.04

## Additional context
The following command exhibits the same behaviour  
`epirus generate solidity -a Greet.abi -o . -p com`

**Comment by xellDart** [comment]
same error with web3j

**Comment by mart1435** [comment]
I have the same issue ! :/

**Comment by xrpdevs** [comment]
Me too. It's rather annoying. I can use web3j-4.0.1 to generate bindings, but it only seems to work with abi/bins from older versions of solc.

Doubly frustrating since I'm unable to test compilation and generation of bindings with the latest tools which will hopefully resolve the errors Im getting in my (Android) app when trying to deal with String objects being returned from the contract giving "StringIndexOutOfRange" errors and data being corrupted....

Only been writing EVM stuff for a few days though so Im sure Ill get it all worked out...

**Comment by AlexandrouR** [comment]
the command is has been updated you can use [web3j-cli](https://github.com/web3j/web3j-cli). Use the latest version and try the command `web3j generate solidity`
