### ISSUE TITLE
Support more levels of nested structs

### ISSUE THREAD

**Issue by SweeXordious** [web3j/web3j#1329]
## Feature description_
Currently, the library supports only three levels of nested structs. This means that the following:

```
    struct Foo {
        string id;
        string name;
    }

    struct Nuu {
        Foo foo;
    }

    struct Nar {
        Nuu nuu;
    }

    Nar nar;
```
Works fine with the encoder/decoder for all possibilities like multiple returns and arrays of structs.

However, the following: 
```
    struct Naz {
        Nar nar;
        uint data;
    }
```
Will fail to encode/decode.

This limitation can seem reasonable because nesting structs is pretty gas expensive. Also, there are gas limitations on the majority of public networks available. So, three levels is almost enough.
However, for private networks, where the user can define the `gasLimit`. Then, we should be able to create arbitrary number of nested structs and the library will need to fix this limitation.

**Comment by mohamedelshami** [comment]
Assume this is complete with partial issues remaining
