### ISSUE TITLE
Updated Javadoc for Web3j?

### ISSUE THREAD

**Issue by kinson603** [web3j/web3j#1333]
[https://docs.web3j.io/javadoc-api/](url)

This link clearly does not work anymore. Is there an updated one available? Thanks.

**Comment by arunkapur** [comment]
The link should be updated to: https://docs.web3j.io/latest/javadoc-api/

**Comment by kinson603** [comment]
Thanks! 
But when I go through the document, I find there are still some places being left empty (e.g.: descriptions, method details, etc.).
Is there any plan to update it as well?

**Comment by AlexandrouR** [comment]
the link has been updated to work properly. We aim to update it much as we can and community contributions are of course welcomed
