### ISSUE TITLE
How can i get all my ERC20 tokens?

### ISSUE THREAD

**Issue by Alas-Wallet** [web3j/web3j#1335]
Hello, help me pls!

I want get all balance ERC20 tokens in my wallet. How can I do it?

If all is impossible, then how to receive one at a time?

Thanks :*

**Comment by EAOE154** [comment]
did you figure out how to do it? if yes please share the solution

**Comment by AlexandrouR** [comment]
Hi, this is not really a web3j issue in order to get the balance of your erc20 tokens you would need to know the address of said erc tokens and then call the get balance function this is the way I assume wallets do it.
