### ISSUE TITLE
Interacting with deployed smart contracts

### ISSUE THREAD

**Issue by EAOE154** [web3j/web3j#1363]
How can i interact with deployed smart contracts using web3j ?

**Comment by AlexandrouR** [comment]
you need to generate the contract wrappers and call the load method for example if you have already deployed a contract you would generate the wrappers for the contract and call is as such `MyContract.load()` passing in all the required variables. For more information please check [here](http://docs.web3j.io/latest/smart_contracts/construction_and_deployment/#construction-and-deployment)
