### ISSUE TITLE
Tag release 5.0.0

### ISSUE THREAD

**Issue by fulldecent** [web3j/web3j#1368]
Please tag release 5.0.0.

Version 5.0.0 is already available at https://search.maven.org/artifact/org.web3j/crypto/5.0.0/jar

And having it tagged here will help to find which code relates to that.

Also it may possibly trigger an update to documentation at http://docs.web3j.io/latest/

**Comment by AlexandrouR** [comment]
@fulldecent The release of 5 was a mistake the latest version is 4.8.4

**Comment by fulldecent** [comment]
Got it, thanks for explaining.

In this case I would recommend to delete that version.

If not possible, you can release version 5.0.0.1-warning that will supersede 5.0.0, does not contain any code, and has a just a warning in a README file.
