### ISSUE TITLE
Invalid RLP 

### ISSUE THREAD

**Issue by jaimemorales52** [web3j/web3j#137]
Hi,

I have a problem using the API with a test chain in parity.

When I try to do a transfer I obtain this code error.

org.web3j.protocol.core.Response$Error@2d2eff11
-32602
FromBytesError(DataIsTooShort)
Invalid RLP.

The code that I have implemented is too easy so I dont understand where the mistake is.
Credentials credentials;

web3j = Web3j.build(new HttpService()); // defaults to http://localhost:8545/
credentials = WalletUtils.loadCredentials("passwd",
					"/key/path");

EthGetTransactionCount ethGetTransactionCount = web3j
					.ethGetTransactionCount(ADDRESS, DefaultBlockParameterName.LATEST).sendAsync().get();

BigInteger nonce = ethGetTransactionCount.getTransactionCount();

RawTransaction rawTransaction = RawTransaction.createEtherTransaction(BigInteger.TEN, GAS_PRICE, GAS_LIMIT,
					"0x002070d48be146127C7F3BfCBF3958DBCBCC0685", GAS_PRICE);

byte[] signedMessage = TransactionEncoder.signMessage(rawTransaction, credentials);
String hexValue = Numeric.toHexString(signedMessage);

EthSendTransaction ethSendTransaction = web3j.ethSendRawTransaction(hexValue).sendAsync().get();
			transactionHash = ethSendTransaction.getTransactionHash();

**Comment by conor10** [comment]
Hi @jaimemorales52 - it's the zeroes in the destination address. Release to address this will be out shortly, see https://github.com/web3j/web3j/commit/86804b808d61f1730cb644e38b7eb3b949fb828a.
