### ISSUE TITLE
Include a sponsor button

### ISSUE THREAD

**Issue by fulldecent** [web3j/web3j#1370]
## Feature description_

Please include a sponsor button here.

GitHub natively integrates with sponsorship to make the experience easy.

P.S. the main monetization part of https://www.web3labs.com is the "Schedule a Consultation" page and that is currently a broken link.

**Comment by conor10** [comment]
Thanks for highlighting this! We've requested a sponsor page, which hopefully will be public [here](https://github.com/sponsors/web3j) in the coming days!

**Comment by fulldecent** [comment]
Perfect. It's live, thank you
