### ISSUE TITLE
`web3j new` command fails

### ISSUE THREAD

**Issue by rampatra** [web3j/web3j#1384]
# web3j new command fails with an error
`web3j new` command fails with erros in the logs

## Description
Upon looking at the logs, I see that https://jcenter.bintray.com/org/web3j/core/4.8.4/core-4.8.4.pom gives a 403 Forbidden error. Anything I need to do to get access to this? In the [Quickstart doc](http://docs.web3j.io/latest/quickstart/), nothing is mentioned though.

**Comment by SweeXordious** [comment]
@rampatra you're still facing the issue ? Because I have access to that `pom` file, and I am also able to build a new project with no issue.
Please check if you have connectivity issues or firewall blocking that. 
Will close for now. Reopen please if the issue still persists.

**Comment by rampatra** [comment]
It works for me now. Not sure what was the issue.
