### ISSUE TITLE
Web3j maven plugin not found

### ISSUE THREAD

**Issue by rampatra** [web3j/web3j#1385]
# Web3j 4.8.1 not found in maven central
Can't find this plugin.

## Description
I use the below code in `pom.xml` file but it doesn't work.
```
<plugin>
    <groupId>org.web3j</groupId>
    <artifactId>web3j-maven-plugin</artifactId>
    <version>4.8.1</version>
    <configuration>
        <soliditySourceFiles/>
    </configuration>
</plugin>
```

**Comment by SweeXordious** [comment]
@rampatra Can you please try again and let us know if the issue still persists ?

**Comment by rampatra** [comment]
Yes, it still fails but when I use `4.6.5`, it works.

**Comment by SweeXordious** [comment]
I just let the team know about the issue. Will get back to you later.
Thanks for reporting this.

**Comment by rampatra** [comment]
Also, if you see the tags here: https://github.com/web3j/web3j-maven-plugin the latest available tag is `4.6.5`.

**Comment by BarBozz** [comment]
Publishing pipeline to maven repository fails as far as my research. Needed to compile everything from scratch. Working with 5.0.0 rn

**Comment by SweeXordious** [comment]
@BarBozz We have issues publishing the maven plugin... If it is convenient for you, please use the `4.8.4` release of the `we3bj-gradle-plugin` as it has the latest changes you need.
PS: `5.0.0` release was a mistake relase.

**Comment by paulvi** [comment]
The latest version in https://github.com/web3j/web3j-maven-plugin/blob/master/pom.xml is 4.8.1

But https://mvnrepository.com/artifact/org.web3j/web3j-maven-plugin shows no 4.8.x on Central

**Comment by herbig** [comment]
Is there any solution to this? I'm also experiencing this, and can't switch from maven.

**Comment by mohamedelshami** [comment]
@rampatra @herbig does working v4.8.4 or this is still an issue?
