### ISSUE TITLE
web3j won't reconnect after the net breaked

### ISSUE THREAD

**Issue by yockii** [web3j/web3j#139]
im using web3j to subscribe the transaction, but if I restart parity, web3j won't reconnect, and even no error throws!  how to make sure it will keep connection?

**Comment by conor10** [comment]
I've checked in changes to web3j to use okhttp instead of Apache HTTP client, which hopefully will provide more robust connectivity.

This won't be released until the 3.0 milestone, but you're welcome to test this scenario if you check out the okhttp web3j branch.

**Comment by conor10** [comment]
Is this still an issue with the 3.0 release?

**Comment by yockii** [comment]
I haven't checked it, but okhttp has the ability to  auto recover, so it should be resolved.
