### ISSUE TITLE
Error: only replay-protected (EIP-155) transactions allowed over RPC

### ISSUE THREAD

**Issue by W3-MajorArif** [web3j/web3j#1397]
Hello Sir,

I'm using web3j library in my android application. in my gradle file I'm using org.web3j:core:4.6.0-android.
When I try to submit any transaction it shows the following error
Error: Returned error: only replay-protected (EIP-155) transactions allowed over RPC

After googling sometimes I found including chainid will solve the issue. 
But I can't add chainid in the transaction as it is calling smart contract method directly.
My code is like this
        Future<String> future =  executor.submit(new Callable() {
            @Override
            public String call() {
                TransactionReceipt rcpt = null;
                try {
                    rcpt = token.approve(address, amount).send();
                    Log.i(TAG, "RECEIPT  " + rcpt.getTransactionHash());
                } catch (Exception e) {
                    Log.e(TAG, e.toString());
                }
                return rcpt.getTransactionHash();
            }
        });

Could you please help me to solve this issue?
Many many thanks in advance
with regards

**Comment by tommq** [comment]
Hi, we faced this after upgrade to the latest Geth (v1.10.1)

The replay-protection can be disabled if you start your wallet with _--rpc.allow-unprotected-txs_ 

See _ChainID enforcement section_ of https://blog.ethereum.org/2021/03/03/geth-v1-10-0/

**Comment by W3-MajorArif** [comment]
Thank you @tommq. You just saved my life :).  It's working fine with your solution in the web3j library. 
Otherwise, in the web3.js library, I've provided chainid in the transaction and it also worked. 
So is there any probability that you guys will improve the web3j library to work with chainid?

Many many thanks again.

**Comment by tommq** [comment]
I'm glad I could help. We send regular transactions and specify the chainId using [TransactionEncoder](https://github.com/web3j/web3j/blob/bf44b8f3fae9f76bea4b5f5377294eaa9225d923/crypto/src/main/java/org/web3j/crypto/TransactionEncoder.java#L31) :

`TransactionEncoder.signMessage(rawTransaction, chainId, credentials)
`

**Comment by otcyan** [comment]
> chainId

ChainID is a byte type and chain is 137, which is out of scope

**Comment by lmxdawn** [comment]
Geth version is 1.10.5, web3j version is 4.8.5, also encountered this problem

The code is:
`Web3j web3 = Web3j.build(new HttpService());  // defaults to http://localhost:8545/
Credentials credentials = WalletUtils.loadCredentials("password", "/path/to/walletfile");
TransactionReceipt transactionReceipt = Transfer.sendFunds(
        web3, credentials, "0x<address>|<ensName>",
        BigDecimal.valueOf(1.0), Convert.Unit.ETHER).send();`

**Comment by mohamedelshami** [comment]
Based on the response @tommq I believe this is no longer an issue.
