### ISSUE TITLE
Besu class not found in web3j-core.jar

### ISSUE THREAD

**Issue by rampatra** [web3j/web3j#1398]
<img width="972" alt="Screenshot 2021-04-07 at 20 44 06" src="https://user-images.githubusercontent.com/2862724/113924675-0196df80-97e2-11eb-926b-eca5ec61cd68.png">

I am using web3j (v4.8.4) in my maven project and these classes (marked in red) aren't found in the jar. Any ideas?

**Comment by mohamedelshami** [comment]
It looks like web3j-besu module is not included in maven depedency.

<dependency>
  <groupId>org.web3j</groupId>
  <artifactId>besu</artifactId>
  <version>4.8.4</version>
</dependency>

**Comment by rampatra** [comment]
Yes, I have included all three now and it's working:
```
<dependencies>
        <dependency>
            <groupId>org.web3j</groupId>
            <artifactId>core</artifactId>
            <version>4.8.4</version>
        </dependency>
        <dependency>
            <groupId>org.web3j</groupId>
            <artifactId>besu</artifactId>
            <version>4.8.4</version>
        </dependency>
        <dependency>
            <groupId>org.web3j</groupId>
            <artifactId>eea</artifactId>
            <version>4.8.4</version>
        </dependency>
    </dependencies>
```

I thought just adding the core dependency would include everything.
