### ISSUE TITLE
Suggestion for Address.java: Getter for address as Hex-String

### ISSUE THREAD

**Issue by MaxBinnewies** [web3j/web3j#14]
Hi Conor,

I was trying to compare the Address-object that I got from my smart contract with the Credentials-object of the current user to find out if that object was created by the current user. Address returns the address as a decimal, Credentials as a Hex String. 

Eventually I figured it out and its working now, but it would be nice if Address would also have a getter for the Hex-String, so these two can be easily compared.

with best regards,
Max

**Comment by conor10** [comment]
So that toString calls Numeric.toHexStringWithPrefix(<BigInteger> address)?

**Comment by MaxBinnewies** [comment]
Oh, I didn't know that method. I parsed it with BigInteger and added "0x" manually.^^
But yes, that sounds good. :-)

**Comment by MaxBinnewies** [comment]
omg, I am in a leading-zero-nightmare right now!^^
Not only does my new account have too few TAs as described in the other issue, it also has a leading zero in its address.

This is my new address:
0x01c52b08330e05d731e38c856c1043288f7d9744
Numeric.toHexStringWithPrefix(req.getCreator().getValue()); returns this:
0x1c52b08330e05d731e38c856c1043288f7d9744

req.getCreator() returns the datatype Address.

I am gonna quit working now and do something without zeros.
Good Night, Max

**Comment by conor10** [comment]
I've fixed this in my latest commit. However, please could you send me your public key? I'd like to add it to the unit tests.

**Comment by MaxBinnewies** [comment]
Thats the public key: 0xa1b31be4d58a7ddd24b135db0da56a90fb5382077ae26b250e1dc9cd6232ce2270f4c995428bc76aa78e522316e95d7834d725efc9ca754d043233af6ca90113

If you need the private key, write me your email and I send it to you. There is only like three dollars worth of ether in the account anyway, i dont think you gonna steal that. ^^

**Comment by conor10** [comment]
Thanks Max - public key is used in the address derivation, so shouldn't need the private key, but appreciate the offer ;)
