### ISSUE TITLE
Publish 4.8.5 to Maven Central

### ISSUE THREAD

**Issue by hbs** [web3j/web3j#1407]
# _Issue_title_
Maven Central publishing of recent release.

## _Issue_description_
the last release of web3j-crypto on Maven Central is 4.8.4 dated january 2021. There is a bug in that release which affects StructuredDataEncoder and prevents the hashing of structures which contain arrays. This bug has been corrected in march 2021, are there any plans to publish a new release to Maven Central?

**Comment by paulvi** [comment]
I second motion for ASAP v4.8.5 release

@hbs can you reference exact bug that was fixed?
Could you please rename issue as it is not about publishing to Maven Central that is already was done, e.g. see
https://mvnrepository.com/artifact/org.web3j/core
but about releasing new version (that includes publishing to Central and other repositories)

**Comment by hbs** [comment]
Not sure it was a referenced issue, but the handling of multidimensional arrays in crypto/src/main/java/org/web3j/crypto/StructuredDataEncoder.java was fixed in march 2021 with the following commit:

commit 202dcc24f5f5800cd267cbefec9802444d9c0d10
Author: James Brown <soylentblue@hotmail.co.uk>
Date:   Wed Mar 17 00:41:18 2021 +1100

    Fix EIP712 StructuredDataEncoding (#1382)
    
    * - fix for StructuredDataEncoding (EIP712 v3) with int values.
    - enable EIP712 v4, StructuredData with Arrays
    - add tests for EIP712v3, EIP712v4 and EIP712v3 Gnosis Multisig commit sample.
    
    * fix issue with decoding array data

**Comment by paulvi** [comment]
ref #1382

**Comment by hbs** [comment]
Any ETA for the publication of a more recent version on Maven Central?

**Comment by paulvi** [comment]
This is DONE

4.8.5 is released

https://mvnrepository.com/artifact/org.web3j/core
