### ISSUE TITLE
EventEncoder is using package name to generate the Event Signature when with struct in the event

### ISSUE THREAD

**Issue by iansim** [web3j/web3j#1408]
# EventEncoder is using package name to generate the Event Signature

## Steps To Reproduce
1. create a contract
pragma abicoder v2;

contract EventTest {
    struct Structure {
      uint value;
    }
    event Created(uint indexed unum,Structure indexed structure);
 /**....**/
    function sendEvent() public {
	    Structure memory myStruct;
        myStruct.value = 2;		
        emit Created(40,myStruct);
    }
}
}
2. generate a warpper 
3. generate Signature 

### Expected behavior
EventEncoder.buildMethodSignature(EventTest.CREATED_EVENT.getName(),
        		EventTest.CREATED_EVENT.getParameters()); will generate the string same with other enviroment 
The sigatrue can be used for subscribe eth log

### Actual behavior

EventEncoder.buildMethodSignature(EventTest.CREATED_EVENT.getName(),
        		EventTest.CREATED_EVENT.getParameters());  is generate below string
Created(uint256,com.mypackagename.contract.EventTest$Structure)

The final sigatrue is different with the topics[0] inside the logs

## Environment
_Describe the environment in which the issue occurs_
- Web3j version. 4.8.4
- Java or Android Java 11
- Operating System Mac

**Comment by gtebrean** [comment]
@iansim does this happens also in current web3j-4.9.7?

**Comment by gtebrean** [comment]
Since that moment multiples PRs related to events encoding were merged so this should be fixed. If no feel free to reopen it.
