### ISSUE TITLE
Is there any changes on current web3j version?

### ISSUE THREAD

**Issue by unnamedw** [web3j/web3j#1409]
**When I send a request using sendToken, I get the following error.**

```
Non-fatal Exception: java.lang.UnsupportedOperationException: Empty transaction receipt, only transaction hash is available
       at org.web3j.tx.response.EmptyTransactionReceipt.unsupportedOperation(EmptyTransactionReceipt.java:43)
       at org.web3j.tx.response.EmptyTransactionReceipt.getStatus(EmptyTransactionReceipt.java:139)
       at org.web3j.protocol.core.methods.response.TransactionReceipt.isStatusOK(TransactionReceipt.java:161)
       at org.web3j.tx.Contract.executeTransaction(Contract.java:375)
       at org.web3j.tx.Contract.executeTransaction(Contract.java:350)
       at org.web3j.tx.Contract.executeTransaction(Contract.java:344)
       at org.web3j.tx.Contract.executeTransaction(Contract.java:339)
       at org.web3j.tx.Contract.m(Contract.java:410)
       at org.web3j.tx.Contract.n()
       at org.web3j.tx.g.call(:4)
       at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42)
```

**When I wrote this version, I wasn't caught by onError.**

version.web3j_core_version = '4.2.0-android'
version.web3j_crypto_version = '3.2.0'

**When the corresponding version is used, it is caught by onError and the above error occurs.**

version.web3j_core_version = '4.6.0-android'
version.web3j_crypto_version = '4.6.0-android'

**Are there any changes due to version migration? It's hard to find somewhere. 
Please ask any advice for me, thank you very much!**

  ```
@Throws(Exception::class)
 private fun getERC20Contract(tokenAddress: String, password: String, gasPrice: BigInteger = 0.toBigInteger(), gasLimit: BigInteger = TOKEN_TRNASFER_GAS_LIMIT): ERC20Contract {
        val fileName = settingInfo.keystoreFileName
        val credentials = getCredentials(fileName, password)
        val web3j = web3()
        val transactionReceiptProcessor = NoOpProcessor(web3j) // this works fine in previous version, but not now!
        val transactionManager = RawTransactionManager(
                web3j, credentials!!, ChainId.ROPSTEN, transactionReceiptProcessor)
        val staticGasProvider = StaticGasProvider(gasPrice, gasLimit)
        return ERC20Contract.load(tokenAddress, web3j, transactionManager, staticGasProvider)
    }
```

```
@Throws(Exception::class)
  fun sendToken(tokenAddress: String, toAddress: String, amount: String, tokenDecimals: Int, transactionFee: BigDecimal, password: String, timestamp: String, gasLimit: BigInteger): Observable<Array<String>> {
        /*val amountBuilder = StringBuilder(amount)
        for (i in 0 until tokenDecimals) {
            amountBuilder.append("0")
        }*/
        val amountBuilder = BigDecimal(amount).multiply(BigDecimal(Math.pow(10.0, tokenDecimals.toDouble())))
//        val actualAmount = BigInteger(amountBuilder.toString())
        val actualAmount = amountBuilder.toBigInteger()
        val gasPrice = gasPricefromTransactionFee(true, transactionFee, gasLimit)
        val contract = getERC20Contract(tokenAddress, password, gasPrice, gasLimit)
        val transactionHashObservable = contract.transfer(toAddress, actualAmount).flowable().map {
            arrayOf<String>(it.transactionHash, timestamp)
        }
        return transactionHashObservable.toObservable()
    }
```

>> in my withdrawService class

```
disposables.add(wallet.sendToken(TOKEN.getSmart_contract(), ADDRESS, PRICE, TOKEN.getDecimal(), new BigDecimal(FEE), wallet_password, TIMESTAMP, new BigDecimal(GAS_LIMIT).toBigInteger())
                        .subscribeOn(Schedulers.io())
                        .observeOn(AndroidSchedulers.mainThread())
                        .subscribe(this::handleSuceess, this::handleErrors));
```

**Comment by paulvi** [comment]
Latest version is 4.8.4

see at https://mvnrepository.com/artifact/org.web3j/core

**Comment by unnamedw** [comment]
> Latest version is 4.8.4
> 
> see at https://mvnrepository.com/artifact/org.web3j/core

But, in android, shouldn't I have use '-android' versions?

**Comment by paulvi** [comment]
Indeed, version for android are released separately.
But they are visible together with usual version

See 
https://mvnrepository.com/artifact/org.web3j/core
https://mvnrepository.com/artifact/org.web3j/crypto

I'd say that usual versioning would suggest to use the same `4.2.0-android'` for both dependencies

```
version.web3j_core_version = '4.2.0-android'
version.web3j_crypto_version = '4.2.0-android'
```

When you have been using 4.2.0-android + older crypto 3.2.0 that is not `-android`
Usually one would say, that there is no guarantees at all for such case.
You should use the same version for all web3j dependencies

And to answer your question about changes:

There is no CHANGELOG in this repo.

https://github.com/web3j/web3j/releases/tag/v4.2.0-android has some release notes,
https://github.com/web3j/web3j/releases/tag/v4.6.0-android but not this 

Good luck. Maybe outhers will take look into this
But usually https://stackoverflow.com/questions/ or such places are better

**Comment by unnamedw** [comment]
> Indeed, version for android are released separately.
> But they are visible together with usual version
> 
> See
> https://mvnrepository.com/artifact/org.web3j/core
> https://mvnrepository.com/artifact/org.web3j/crypto
> 
> I'd say that usual versioning would suggest to use the same `4.2.0-android'` for both dependencies
> 
> ```
> version.web3j_core_version = '4.2.0-android'
> version.web3j_crypto_version = '4.2.0-android'
> ```
> 
> When you have been using 4.2.0-android + older crypto 3.2.0 that is not `-android`
> Usually one would say, that there is no guarantees at all for such case.
> You should use the same version for all web3j dependencies
> 
> And to answer your question about changes:
> 
> There is no CHANGELOG in this repo.
> 
> https://github.com/web3j/web3j/releases/tag/v4.2.0-android has some release notes,
> https://github.com/web3j/web3j/releases/tag/v4.6.0-android but not this
> 
> Good luck. Maybe outhers will take look into this
> But usually https://stackoverflow.com/questions/ or such places are better

Thanks bro.

**Comment by andrii-kl** [comment]
@unnamedw Can I close this issue?

**Comment by andrii-kl** [comment]
If you still have a problem with a new web3j version, just create a new issue.
