### ISSUE TITLE
EIP1559 transaction encoding

### ISSUE THREAD

**Issue by ligi** [web3j/web3j#1416]
basically this is a reopening of #1404 - unfortunately I cannot reopen this issue

I am a bit surprised by this implementation: https://github.com/web3j/web3j/commit/37e9710a1e6671db4ea1f80f684fd8f2ecb7c775

as it does not use EIP-2718 and so the tx will not be recognized as a EIP-1559 transaction as far as I see

maybe @abdelhamidbakhta can shed some light on this

**Comment by abdelhamidbakhta** [comment]
> basically this is a reopening of #1404 - unfortunately I cannot reopen this issue
> 
> I am a bit surprised by this implementation: [37e9710](https://github.com/web3j/web3j/commit/37e9710a1e6671db4ea1f80f684fd8f2ecb7c775)
> 
> as it does not use EIP-2718 and so the tx will not be recognized as a EIP-1559 transaction as far as I see
> 
> maybe @abdelhamidbakhta can shed some light on this

This implementation was done way before 2718 was introduced as a requirement for 1559

**Comment by ligi** [comment]
ah interesting - thanks for the insight. But yea - then this needs to be changed. Maybe even do an intermittent step to throw an exception when encoding 1559 transactions for now to not lead more people on that wrong path I was on for a bit ;-)

**Comment by vae520283995** [comment]
@ligi hi,When is this expected to be completed, the mainnet upgrade will be on July 15

**Comment by ligi** [comment]
@vae520283995 not sure - you might want to follow #1417

**Comment by vae520283995** [comment]
> @vae520283995 not sure - you might want to follow #1417

thank you

**Comment by yasseralaa** [comment]
@ligi hi, is this okay to close?

**Comment by ligi** [comment]
yea - I think with  #1417 merged this can be closed
