### ISSUE TITLE
Make available via jitpack again

### ISSUE THREAD

**Issue by ligi** [web3j/web3j#1421]
adding web3j via  jitpack was possible in old versions - e.g. see: https://jitpack.io/com/github/web3j/web3j/v3.6.0/build.log

but with current versions I see: https://jitpack.io/com/github/web3j/web3j/v4.8.3/build.log

and cannot use web3j via jitpack. The root problem seems to be: ` Cannot perform signing task ':abi:signMavenPublication' because it has no configured signatory`

Would be great to be able to use web3j via jitpack again. E.g. nice when one just wants to try out a PR - I just wanted to try out the 1559 fixing PR via `com.github.web3j:web3j:PR1417-SNAPSHOT`

**Comment by gtebrean** [comment]
in file gradle/publish/build.gradle there is line 

> sign publishing.publications.maven

Comment it out in order avoid it.
