### ISSUE TITLE
-32000 : invalid sender

### ISSUE THREAD

**Issue by otcyan** [web3j/web3j#1434]
I use TransactionEncoder signMessage (rawTransaction, 137. ToByte (), credentials)  , signMessage chainId is byte,However, my chainId is 137, which exceeds the maximum byte capacity of 127. Could you please tell me how to pass parameters?

**Comment by vae520283995** [comment]
ChainIdLong

**Comment by mahima-manik** [comment]
Use long data type instead for chainID: https://github.com/web3j/web3j/blob/master/crypto/src/main/java/org/web3j/crypto/TransactionEncoder.java#L43

Feel free to open if issue still persists
