### ISSUE TITLE
Blocks arriving with long delays in bursts

### ISSUE THREAD

**Issue by luziusmeisser** [web3j/web3j#1436]
# blockFlowable does not create smooth flow

When creating a blockFlowable and subscribing to it, the blocks flow in with a considerable delay and in bursts.

## Description

When subsribing to a block flowable, I expect to be notified about new blocks as they happen. But web3j does not do that. Instead, the notifications arrive with a considerable delay and in bursts of typically two or three.

## How to Reproduce

Run the following program with Web3J 4.8.4, connecting to a local geth node or to infura:

	public static void main(String[] args) throws InterruptedException {
		Web3j ethereum = Web3j.build(new HttpService("http://127.0.0.1:8545"));
		ethereum.blockFlowable(false).subscribe(block -> {
			System.out.println(System.currentTimeMillis() / 1000 % 1000 + ": " + block.getBlock().getNumber());
		});
		Thread.sleep(10000000);
	}

A typical output looks like this:

709: 12747124
724: 12747125
754: 12747126
754: 12747127
769: 12747128
784: 12747129
814: 12747130
814: 12747130
814: 12747131

As you can see, many blocks arrive in bursts, like two or three at a time, even though they actually happened over the course of a minute or so. There is a delay of up to a minute between the time the my node picks up a new block and the time I get notified by web3j about the new block. I don't think the problem is with my local geth node as it also occurs when connecting to infura.

**Comment by mohamedelshami** [comment]
Push based block subscription can be achieved via WebSocketService; here is an [example](https://github.com/web3j/web3j/blob/49fe2c4e2d9d325ec465879736d6c384f41a4115/core/src/test/java/org/web3j/protocol/websocket/WebSocketServiceTest.java#L385)

**Comment by luziusmeisser** [comment]
Thanks for the hint. I now did an implement with very simple polling. This of course causes somewhat more overhead, but I distrust websockets in general. :) Websockets seem much more prone to subtle connection errors than polling.

**Comment by mohamedelshami** [comment]
Yes, if missing blocks is not an issue then polling should be fine.
