### ISSUE TITLE
EIP1559 Transactions sent to blockchain with gas price 0, won't be mined

### ISSUE THREAD

**Issue by cristianberbecaru** [web3j/web3j#1455]
Hi,

I am unable to send transactions. They are successfully sent to blockchain, but with gas price 0, so the transactions won't be mined. I am using Geth 1.10.4.

I tried the following code:

RawTransaction transaction1559 = RawTransaction.createEtherTransaction(
ChainId.ROPSTEN,
BigInteger.valueOf(4L),
Transfer.GAS_LIMIT,
transfer.getRecipientAddress(),
amountInWei,
DefaultGasProvider.GAS_LIMIT,
DefaultGasProvider.GAS_PRICE
);
EthSendTransaction ethSendTransaction = manager.signAndSend(transaction1559);

**Comment by AlexandrouR** [comment]
what version of web3j are you using ?

**Comment by cristianberbecaru** [comment]
> what version of web3j are you using ?

I am using 4.8.5. I manually compiled it.

**Comment by AlexandrouR** [comment]
do you have the same result if you do it through the `Transfer` `sendFundsEIP1559` ?

**Comment by AlexandrouR** [comment]
thank you i will investigate this issue

**Comment by yasseralaa** [comment]
Hi @cristianberbecaru, can you post parameter used for sendFundsEIP1559?

**Comment by cristianberbecaru** [comment]
Here

 RemoteCall<TransactionReceipt> eip1559receipt = Transfer.sendFundsEIP1559(
                rpc.connect(),
                credentials,
                transfer.getRecipientAddress(),
                BigDecimal.valueOf(0.003),
                Convert.Unit.ETHER,
                Transfer.GAS_LIMIT,
                Convert.toWei("1", Convert.Unit.GWEI).toBigInteger(),
                Convert.toWei("150", Convert.Unit.GWEI).toBigInteger());
        TransactionReceipt t = eip1559receipt.send();

**Comment by cristianberbecaru** [comment]
Hi,

@AlexandrouR any updates on this?

**Comment by mohamedelshami** [comment]
@cristianberbecaru not sure if 0 price transaction is valid unless Geth itself configured or running with the miner.gasPrice=0? is this how is it currently configured?

**Comment by cristianberbecaru** [comment]
@mohamedelshami  Geth version is 1.10.5 and I'm using the Ropsten Network. What do you mean by 0 price transaction? I'm not sending any fee with 0.

**Comment by yasseralaa** [comment]
I have recreated this issue using geth:-
$geth --rpcapi personal,db,eth,net,web3 --rpc --ropsten --syncmode "light"
https://ropsten.etherscan.io/tx/0xcd48e1dea9c9a17b66e938120348eeb8fa53e18100543a49fa7553ed20bd55b2

also tried using infura's network and it worked fine: https://ropsten.etherscan.io/tx/0x5d674d189a7427effd77008bdcdf967077a7b3ac2f80bf43ab538833754312b7

**Comment by cristianberbecaru** [comment]
@yasseralaa  can you show me the code that you have used, please?

**Comment by yasseralaa** [comment]
@cristianberbecaru used the same code you posted:-
        RemoteCall<TransactionReceipt> eip1559receipt = Transfer.sendFundsEIP1559(
                  web3j,
                  credentials,
                  "toAddress",
                  BigDecimal.valueOf(0.003),
                  Convert.Unit.ETHER,
                  Transfer.GAS_LIMIT,
                  Convert.toWei("1", Convert.Unit.GWEI).toBigInteger(),
                  Convert.toWei("150", Convert.Unit.GWEI).toBigInteger());
    TransactionReceipt t = eip1559receipt.send();

**Comment by yasseralaa** [comment]
@cristianberbecaru 
can you make another transaction with this code again, It worked with me even that transaction was pending yesterday worked well:-
```
$geth --rpcapi personal,db,eth,net,web3 --rpc --ropsten --syncmode "light"
```
https://ropsten.etherscan.io/tx/0xcd48e1dea9c9a17b66e938120348eeb8fa53e18100543a49fa7553ed20bd55b2

can you give it a try?

**Comment by cristianberbecaru** [comment]
@yasseralaa it worked. I can see all my past transactions are mined one by one. I think the problem is with Ropsten. 
I tried now another one on Ropsten and it is still pending, with 0 gas price, but on Rinkeby it worked instantly. 

Thank you for the help.
With geth v1.10.5 it's all good.

**Comment by yasseralaa** [comment]
@cristianberbecaru great to know that.

closing issue.
