### ISSUE TITLE
Random & Android

### ISSUE THREAD

**Issue by ligi** [web3j/web3j#146]
As Web3j is also intended to be used on Android - a secure random implementation should be used like:
https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/crypto/LinuxSecureRandom.java

also see:
https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/core/ECKey.java#L136

and:

https://android-developers.googleblog.com/2013/08/some-securerandom-thoughts.html

**Comment by conor10** [comment]
Thanks for highlighting this @ligi, much appreciated.

**Comment by conor10** [comment]
Done.

**Comment by ligi** [comment]
thanks!
