### ISSUE TITLE
Empty Array's type as string throwing IndexOutOfBoundException

### ISSUE THREAD

**Issue by b3kan** [web3j/web3j#1474]
FunctionEncoder calls Type::TypeAsString method before encoding function with provided arguments.

If someone wants to pass empty array, than IndexOutOfBoundException is thrown.

I think you've to modify code like this:

DynamicArray.java

@Override
    public String getTypeAsString() {
        String type;
        if (!value.isEmpty() && StructType.class.isAssignableFrom(value.get(0).getClass())) {
            type = value.get(0).getTypeAsString();
        } else {
            type = AbiTypes.getTypeAString(getComponentType());
        }
        return type + "[]";
    }
    
    
StaticArray.java
    @Override
    public String getTypeAsString() {
        String type;
        if (!value.isEmpty() && StructType.class.isAssignableFrom(value.get(0).getClass())) {
            type = value.get(0).getTypeAsString();
        } else {
            type = AbiTypes.getTypeAString(getComponentType());
        }
        return type + "[" + value.size() + "]";
    }
   
   
 Also as I see it's code duplication, maybe you have to change this method with default implementation?

**Comment by fenghaoming** [comment]
I have the same problem. Is it settled now? Thank you!

```
    public static void main(String... args) {
        List<Type> inputParameters = new ArrayList<>();
        DynamicArray<Address> some = new DynamicArray<>(Address.class, Collections.singletonList(new Address("000000000000000000000000000000000000000000000000000000000000000")));
        inputParameters.add(some);
        Function function = new org.web3j.abi.datatypes.Function(
                "funcName",
                inputParameters,
                Collections.emptyList());
        FunctionEncoder.encode(function); // it is ok

        inputParameters = new ArrayList<>();
        DynamicArray<Address> empty = new DynamicArray<>(Address.class, Collections.emptyList());
        inputParameters.add(empty);
        function = new org.web3j.abi.datatypes.Function(
                "funcName",
                inputParameters,
                Collections.emptyList());
        FunctionEncoder.encode(function); // java.lang.IndexOutOfBoundsException: Index: 0
    }
```

**Comment by mmotiy** [comment]
I ran into the same problem

**Comment by mmotiy** [comment]
> I ran into the same problem

extends DynamicArray and overwrite the method,like this.
`public class MyDynamicArray<T extends Type> extends DynamicArray<T> {

    public MyDynamicArray(T... values) {
        super(values);
    }

    public MyDynamicArray(List<T> values) {
        super(values);
    }

    public MyDynamicArray(Class<T> type, List<T> values) {
        super(type, values);
    }

    @Override
    public int bytes32PaddedLength() {
        return super.bytes32PaddedLength();
    }

    public MyDynamicArray(Class<T> type, T... values) {
        super(type, values);
    }

    @Override
    public String getTypeAsString() {
        String type;
        if (!value.isEmpty()&&StructType.class.isAssignableFrom(value.get(0).getClass())) {
            type = value.get(0).getTypeAsString();
        } else {
            type = AbiTypes.getTypeAString(getComponentType());
        }
        return type + "[]";
    }
}`

**Comment by andrii-kl** [comment]
@b3kan @fenghaoming @mmotiy is this issue good to close?

**Comment by andrii-kl** [comment]
@b3kan @fenghaoming @mmotiy  If you still have a problem with a new web3j version, just create a new issue and let me know.
