### ISSUE TITLE
Transaction getter must convert maxPriorityFeePerGas and maxFeePerGas too

### ISSUE THREAD

**Issue by b3kan** [web3j/web3j#1476]
Class:

org.web3j.protocol.core.methods.request.Transaction

Getters for provided fields should look like this:

public BigInteger getMaxPriorityFeePerGas() {
        return convert(maxPriorityFeePerGas);
    }

 public BigInteger getMaxFeePerGas() {
        return convert(maxFeePerGas);
  }

**Comment by yasseralaa** [comment]
@b3kan maxPriorityFeePerGas and maxFeePerGas can have fractions, I think BigInteger wouldn't be suitable.

**Comment by yasseralaa** [comment]
@b3kan That's right, I will update it.

**Comment by yasseralaa** [comment]
maxPriorityFeePerGas and maxFeePerGas are returned in response in Wei.

**Comment by avexphp** [comment]
Is this issue going to be fixed?

If these getters do not return a converted hex string, the JSON string that it forms would be wrong. For example, supposed a transaction is created with the following code:

```
Transaction trnx = new Transaction("[from address]", null, null, BigInteger.valueOf(69145), "[contract address]", BigInteger.ZERO,
                  "[contract data]", null, BigInteger.ZERO, BigInteger.valueOf(50000000000))

```
And if we send trnx using the personalSendTransaction method, the JSON that it is sent to the GETH would be something like the following:

```
{
	"jsonrpc": "2.0",
	"method": "personal_sendTransaction",
	"params": [
		{
			"from": "[from address]",
			"to": "[contract address]",
			"gas": "0x10e19",
			"value": "0x0",
			"data": "[contract data]",
			"maxPriorityFeePerGas": 0,
			"maxFeePerGas": 50000000000
		},
		"secretkey"
	]
}

```
The "maxPriorityFeePerGas" and "maxFeePerGas" nodes are supposed to be hex strings (like the "gas" node in the example above), but they are sent as numbers instead.

The call would then trigger an error with the message: "invalid argument 0: json: cannot unmarshal non-string into Go struct field TransactionArgs.maxPriorityFeePerGas of type *hexutil.Big".

**Comment by kobayashimaru871** [comment]
I'm having the same problem. Also, chainId has the same issue.

**Comment by andrii-kl** [comment]
@avexphp @kobayashimaru871 @b3kan  is this issue good to close?

**Comment by avexphp** [comment]
> @avexphp @kobayashimaru871 @b3kan is this issue good to close?

The changes in the code seem good to me. But I haven't used the updated version it in my environment and might not be updating it any time soon. I am with closing this issue.
