### ISSUE TITLE
What is the approach to swap tokens programmatically?

### ISSUE THREAD

**Issue by pellyadolfo** [web3j/web3j#1479]
Hello, I have looked for this question extensively on the web, also in this Issues list and I cannot find a proper answer, or even the same question somewhere else. 

I know from the documentation that we can create a 'send' transaction from one address to another address http://docs.web3j.io/4.8.7/transactions/transactions_and_smart_contracts/

I am looking for the way to do a atomic swap, but this does not seem to be included in web3j's scope.

Is there any chunk of demo code about how to create a swap between 2 tokens?

(I am quite new to crypto programming and I can be missing things so apologizes in advance if this is a basic question)

**Comment by mohamedelshami** [comment]
hi @pellyadolfo 

Web3j supports any Solidity smart contract operation as long as you're able to generate the wrapper from the contract interface. Please see how wrappers can be generated using web3j [here](http://docs.web3j.io/4.8.7/smart_contracts/construction_and_deployment/#solidity-smart-contract-wrappers) 

Atomic swap can only be performed on-chain via a smart contract that supports the atomic swap operation. It would be nice to try and generate a wrapper for a 1inch exchange [split contract](https://github.com/1inch/1inchProtocol/blob/master/contracts/IOneSplit.sol)

Here is a simple app I wrote before which uses web3j to execute an existing solidity contract https://github.com/mohamedelshami/url-shortener-web3j
