### ISSUE TITLE
web3j maven dependency gives error in Eclipse maven project

### ISSUE THREAD

**Issue by pkul3003** [web3j/web3j#148]
Hi,
After adding a dependency in the pom.xml for my sample web3j project, I am getting below error while building and deploying on the local tomcat server

> An internal error occurred during: "Updating status for Tomcat v8.0 Server at localhost...".
> java.lang.IndexOutOfBoundsException

The dependency I am adding is as below
```
<dependency>
	  <groupId>org.web3j</groupId>
	  <artifactId>core</artifactId>
	  <version>2.3.0</version>
</dependency>
```
Can you please help as I have tried various combination and versions but all in vain.

**Comment by conor10** [comment]
Without a full stack trace it's hard to know if this has anything to do with web3j.

**Comment by pkul3003** [comment]
Hello Conor,

Thanks for the prompt response. The issue is that whenever I am adding that
dependency, the tomcat8 server log is showing a missing jar file
jaxb-api-2.1.jar. But the thing is that this and other jars are present. If
I remove the dependency, the maven install works just fine and I can see
the output of my SampleWebService as a RESTful service.

Hope this gives you a better clue. Let me know if it does not, so I can
give more information.

[image: Inline image 2]




Aug 09, 2017 3:15:47 AM org.apache.catalina.core.StandardContext
backgroundProcess
WARNING: Exception processing loader WebappLoader[/SampleWebService]
background process
java.lang.IllegalStateException: java.io.FileNotFoundException:
/home/parag/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SampleWebService/WEB-INF/lib/jaxb-api-2.1.jar
(No such file or directory)
    at
org.apache.catalina.webresources.JarResourceSet.getArchiveEntry(JarResourceSet.java:123)
    at
org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:260)
    at
org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:281)
    at org.apache.catalina.webresources.Cache.getResource(Cache.java:63)
    at
org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:216)
    at
org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:225)
    at
org.apache.catalina.loader.WebappClassLoaderBase.modified(WebappClassLoaderBase.java:733)
    at
org.apache.catalina.loader.WebappLoader.modified(WebappLoader.java:342)
    at
org.apache.catalina.loader.WebappLoader.backgroundProcess(WebappLoader.java:286)
    at
org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5660)
    at
org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1376)
    at
org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1380)
    at
org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1380)
    at
org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1348)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException:
/home/parag/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SampleWebService/WEB-INF/lib/jaxb-api-2.1.jar
(No such file or directory)
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:219)
    at java.util.zip.ZipFile.<init>(ZipFile.java:149)
    at java.util.jar.JarFile.<init>(JarFile.java:166)
    at java.util.jar.JarFile.<init>(JarFile.java:103)
    at
org.apache.catalina.webresources.AbstractArchiveResourceSet.openJarFile(AbstractArchiveResourceSet.java:308)
    at
org.apache.catalina.webresources.JarResourceSet.getArchiveEntry(JarResourceSet.java:119)
    ... 14 more

Aug 09, 2017 3:15:57 AM org.apache.catalina.core.StandardContext
backgroundProcess
WARNING: Exception processing loader WebappLoader[/PayblockService]
background process
java.lang.IllegalStateException: java.io.FileNotFoundException:
/home/parag/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PayblockService/WEB-INF/lib/asm-all-3.3.1.jar
(No such file or directory)
    at
org.apache.catalina.webresources.JarResourceSet.getArchiveEntry(JarResourceSet.java:123)
    at
org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:260)
    at
org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:281)
    at org.apache.catalina.webresources.Cache.getResource(Cache.java:63)
    at
org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:216)
    at
org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:225)
    at
org.apache.catalina.loader.WebappClassLoaderBase.modified(WebappClassLoaderBase.java:733)
    at
org.apache.catalina.loader.WebappLoader.modified(WebappLoader.java:342)
    at
org.apache.catalina.loader.WebappLoader.backgroundProcess(WebappLoader.java:286)
    at
org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5660)
    at
org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1376)
    at
org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1380)
    at
org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1380)
    at
org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1348)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException:
/home/parag/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PayblockService/WEB-INF/lib/asm-all-3.3.1.jar
(No such file or directory)
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:219)
    at java.util.zip.ZipFile.<init>(ZipFile.java:149)
    at java.util.jar.JarFile.<init>(JarFile.java:166)
    at java.util.jar.JarFile.<init>(JarFile.java:103)
    at
org.apache.catalina.webresources.AbstractArchiveResourceSet.openJarFile(AbstractArchiveResourceSet.java:308)
    at
org.apache.catalina.webresources.JarResourceSet.getArchiveEntry(JarResourceSet.java:119)
    ... 14 more

Aug 09, 2017 3:15:57 AM org.apache.catalina.core.StandardContext
backgroundProcess
WARNING: Exception processing loader WebappLoader[/SampleWebService]
background process
java.lang.IllegalStateException: java.io.FileNotFoundException:
/home/parag/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SampleWebService/WEB-INF/lib/jaxb-api-2.1.jar
(No such file or directory)
    at
org.apache.catalina.webresources.JarResourceSet.getArchiveEntry(JarResourceSet.java:123)
    at
org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:260)
    at
org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:281)
    at org.apache.catalina.webresources.Cache.getResource(Cache.java:63)
    at
org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:216)
    at
org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:225)
    at
org.apache.catalina.loader.WebappClassLoaderBase.modified(WebappClassLoaderBase.java:733)
    at
org.apache.catalina.loader.WebappLoader.modified(WebappLoader.java:342)
    at
org.apache.catalina.loader.WebappLoader.backgroundProcess(WebappLoader.java:286)
    at
org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5660)
    at
org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1376)
    at
org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1380)
    at
org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1380)
    at
org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1348)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException:
/home/parag/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SampleWebService/WEB-INF/lib/jaxb-api-2.1.jar
(No such file or directory)
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:219)
    at java.util.zip.ZipFile.<init>(ZipFile.java:149)
    at java.util.jar.JarFile.<init>(JarFile.java:166)
    at java.util.jar.JarFile.<init>(JarFile.java:103)
    at
org.apache.catalina.webresources.AbstractArchiveResourceSet.openJarFile(AbstractArchiveResourceSet.java:308)
    at
org.apache.catalina.webresources.JarResourceSet.getArchiveEntry(JarResourceSet.java:119)
    ... 14 more


Aug 09, 2017 3:16:07 AM org.apache.catalina.core.StandardContext
backgroundProcess
WARNING: Exception processing loader WebappLoader[/SampleWebService]
background process
java.lang.IllegalStateException: java.io.FileNotFoundException:
/home/parag/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SampleWebService/WEB-INF/lib/jaxb-api-2.1.jar
(No such file or directory)
    at
org.apache.catalina.webresources.JarResourceSet.getArchiveEntry(JarResourceSet.java:123)
    at
org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:260)
    at
org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:281)
    at org.apache.catalina.webresources.Cache.getResource(Cache.java:63)
    at
org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:216)
    at
org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:225)
    at
org.apache.catalina.loader.WebappClassLoaderBase.modified(WebappClassLoaderBase.java:733)
    at
org.apache.catalina.loader.WebappLoader.modified(WebappLoader.java:342)
    at
org.apache.catalina.loader.WebappLoader.backgroundProcess(WebappLoader.java:286)
    at
org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5660)
    at
org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1376)
    at
org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1380)
    at
org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1380)
    at
org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1348)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException:
/home/parag/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SampleWebService/WEB-INF/lib/jaxb-api-2.1.jar
(No such file or directory)
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:219)
    at java.util.zip.ZipFile.<init>(ZipFile.java:149)
    at java.util.jar.JarFile.<init>(JarFile.java:166)
    at java.util.jar.JarFile.<init>(JarFile.java:103)
    at
org.apache.catalina.webresources.AbstractArchiveResourceSet.openJarFile(AbstractArchiveResourceSet.java:308)
    at
org.apache.catalina.webresources.JarResourceSet.getArchiveEntry(JarResourceSet.java:119)
    ... 14 more



[image: Inline image 1]

*Thanks & Regards*

*Parag Kulkarni*
pkul3003@gmail.com
+91 9922962322
+91 9975998206
http://www.pkscienceacademy. com <http://www.pkscienceacademy.com/>

**Comment by pkul3003** [comment]
![indexoutofbound](https://user-images.githubusercontent.com/17665385/29149044-137e3d40-7d8f-11e7-9030-97aa4e3a3c07.png)

Here is the image.

**Comment by conor10** [comment]
This issue looks like its Tomcat specific and issues with dependency resolution, not web3j per say.

**Comment by MihirMehta5695** [comment]
If you are using maven and trying to use Jersey 2.26 and this error occured.
Just try to update pom.xml and change version of Jersey to 2.16.

This error may get vanished.
