### ISSUE TITLE
Request for eth_feeHistory API

### ISSUE THREAD

**Issue by sahashuvo** [web3j/web3j#1483]
## Request for eth_feeHistory API

EIP-1559 transactions require three values to be considered when picking a network fee:
* Base fee. A fee that floats based on the network congestion and the most recent value can be fetched via a **new JSON RPC call eth_feeHistory.**
* Priority fee (tip). A fee to entice a block producer to include the transaction.
* Max fee. The highest network fee the user is willing to pay.

Reference: https://blog.infura.io/london-fork/#whatiseip1559

Is there any support for fetching the "Base fee" via the "eth_feeHistory" JSON RPC call?
If not, I would like to request you to implement this feature in the upcoming version.
Thanks!

**Comment by chris-stallings-pol** [comment]
Looks like there currently isn't a way to do this @sahashuvo, I combed over most of the codebase today. I am looking for the same thing; debating extending Web3j, waiting, or contributing.

**Comment by mohamedelshami** [comment]
@sahashuvo @chris-stallings-pol closing this, support for eth_feeHistory was [added](https://github.com/web3j/web3j/commit/3e7250b78250c02c565356bc8ab65065dd6e46c7) a while back.
