### ISSUE TITLE
Contract that returns a string array gives an array with a weird first element.

### ISSUE THREAD

**Issue by IgnacioGarcia198** [web3j/web3j#1485]
# Contract that returns a string array gives an array with a weird first element.

## Steps To Reproduce
1. Create a simple smart contract that has:
    - an empty string array
    - a method to add string to the array
    - a method to retrieve current string array
2. Deploy contract
3. Call method to add string 3 times, add strings "message 0", "message 1", "message 2"
4. Call method to get whole array, print it on console.

### Expected behavior
"[message 0, message 1, message 2]" is logged to console

### Actual behavior
"[�����������������������������������������������������������������������������������������������	, message 1, message 2]" is logged to console

## Environment
_Describe the environment in which the issue occurs_
- Web3j version: 5.0.0
- Java or Android version: 1.8.0_232
- Operating System MacOs Catalina 10.15.7 (19H1323)
- JVM application in Kotlin.

## Additional context
_Add any other context about the problem here._
- Logs
- Sample code and/or code snippets
```
private fun deploySmartContract(): SimpleMessageContract {
        val contract = SimpleMessageContract.deploy(
            web3,
            Credentials.create(ACCOUNT1_PRIVATE_KEY),
            DefaultGasProvider()
        ).send()
        return contract
    }

suspend fun getMessages(): List<String> = withContext(Dispatchers.IO) {
        messageContract.messages.send() as List<String>
    }


pragma solidity ^0.8.4;

contract SimpleMessageContract {
    /*
    * Storage
    */
    string[] messages;

    /**
    * @dev Constructor
    */
    constructor() {

    }

    function addMessage(string memory message) public {
        messages.push(message);
        emit NewMessage(message);
    }

    function getMessages() public view returns (string[] memory) {
        return messages;
    }

    // events
    event NewMessage(string message);
}

```
- Unit/integration tests to highlight the issue
- [etherscan](https://etherscan.io/) references

**Comment by paulvi** [comment]
Do not use Web3j version: 5.0.0
It is abandoned, see #1461 (I got confused to)
Try on latest 4.8.7

**Comment by IgnacioGarcia198** [comment]
> Do not use Web3j version: 5.0.0
> It is abandoned, see #1461 (I got confused too)
> Try on latest 4.8.7

Thanks, understood. It works alright on 4.8.7.
