### ISSUE TITLE
EIP1559 Smart contract wrapper 

### ISSUE THREAD

**Issue by cristianberbecaru** [web3j/web3j#1487]
Hi,

I'm using v4.8.7 which should support EIP -1559. However, I am unable to find how can I send a smart contract transaction using EIP1559. For example. I want to call the transfer function from the ERC-20 Wrapper Contract, but there is no option to specify the type o tx, or to add base maxPriorityFeePerGas or maxFeePerGas. 

Can someone help me with this please?

**Comment by mahima-manik** [comment]
@cristianberbecaru Please refer to: https://blog.web3labs.com/announcing-web3j-support-for-eip-1559

**Comment by mahima-manik** [comment]
Adding docs link: http://docs.web3j.io/4.8.7/transactions/transfer_eth/. Feel free to reopen if still help is required.

**Comment by igorsimjanoski** [comment]
Hi, i think the main problem is not how to transfer funds using eip-1599 (which is supported as explained in referenced links above) but how to use 'Solidity smart contract wrappers' and send eip-1599 transaction type.

For example, this snippet:

ERC20 contract = ERC20.load(tokenAddress, web3j, txManager, gasPriceProvider);
BigInteger balance = contract.balanceOf(account).send();

will send legacy type of transaction.
