### ISSUE TITLE
No virtual method longValueExact()J in class Ljava/math/BigInteger

### ISSUE THREAD

**Issue by maxyou** [web3j/web3j#1498]
My code:
Log.d("wallet-web3j", "ens 3: ${EnsResolver(web3Client).resolve("cfb.eth")}")

My gradle:
implementation ('org.web3j:core:4.8.7-android')

My API level:
    compileSdkVersion 30
    buildToolsVersion '30.0.3'
    minSdkVersion 23
    targetSdkVersion 30

My device:
    Android 11

I get error:
java.lang.NoSuchMethodError: No virtual method longValueExact()J in class Ljava/math/BigInteger; or its super classes (declaration of 'java.math.BigInteger' appears in /apex/com.android.art/javalib/core-libart.jar)
        at org.web3j.ens.EnsResolver.isSynced(EnsResolver.java:159)
        at org.web3j.ens.EnsResolver.obtainPublicResolver(EnsResolver.java:72)
        at org.web3j.ens.EnsResolver.resolve(EnsResolver.java:88)

I read the code in EnsResolver.java:
    boolean isSynced() throws Exception {
            ......other code........
            long timestamp = ethBlock.getBlock().getTimestamp().longValueExact() * 1000;
    }

So, what's the resolution for this error? Thankx

**Comment by spacelinkers** [comment]
Is there any update regarding this bug?? I have the same issue.

**Comment by maxyou** [comment]
> Is there any update regarding this bug?? I have the same issue.

Finally, I copy EnsResolver.java to my project as my file, and change longValueExact() to longValue(). Currently, it works.

**Comment by sahashuvo** [comment]
I am facing the same issue with Web3J 4.8.7-android when I try to use

**Comment by sahashuvo** [comment]
I am facing the same issue when using 
```java
web3j.ethGetTransactionByHash(txHash);
```
Version of web3j-android used: 4.8.7. Android Version: 11 (API: 30)
Previous versions of web3j-android does not have the same issue.
Some breaking change in the new 4.8.7 is causing this bug related to BigInteger.longValueExact().

Here is my [sample project](https://github.com/sahashuvo/Web3JTransactionTest).

**Comment by andrii-kl** [comment]
Hi @maxyou, you can use web3j without your fix. This bug was fixed. 
#1516
