### ISSUE TITLE
Polkadot support

### ISSUE THREAD

**Issue by paulvi** [web3j/web3j#1499]
## Feature description_
Polkadot https://polkadot.network/ is other blockchain 
(see 2019 comparison https://www.purestake.com/blog/ethereum-vs-polkadot/)

However, I bet some developer would like to see polkadot client library to be exactly or like web3j, maybe by we3 labs.
There is https://github.com/polkadot-java/api implementation that is abandoned  https://github.com/polkadot-java/api/issues/34 and have different idea and tech than web3j.

This issues is raised to ask, if you ever considered 
Or it is definitely  out of scope, so will not work on it.

**Comment by mohamedelshami** [comment]
Hi @paulvi, this is certainly something we can consider support for in Web3j but it's not something in the scope in the short term.
