### ISSUE TITLE
Can't send transactions from accounts with less than 17 transactions

### ISSUE THREAD

**Issue by MaxBinnewies** [web3j/web3j#15]
Hi Conor,

I am trying to send a Transaction with Credentials. That goes through ManagedTransaction.getNonce(). However, the method fails to get the nonce for a new account that I created. This seems to be because that account doesn't have enough transactions. With 16 TAs RPC returns "0x0f". When I have 17 it works.

I believe the problem is in org.web3j.utils.Numeric line 54:
```    
private static boolean isValidHexQuantity(String value) {
        if (value == null) {
            return false;
        }

        if (value.length() < 3) {
            return false;
        }

        if (!value.startsWith(HEX_PREFIX)) {
            return false;
        }

        if (value.length() > 3 && value.charAt(2) == '0') {
            return false;
        }

        return true;
    }
```

**Comment by conor10** [comment]
That's a bug in the client you're using. Which one are you working with?

Quantity values over JSON-RPC should never be zero padded - see https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding for more info.
