### ISSUE TITLE
Get correct balance from wallet

### ISSUE THREAD

**Issue by vlad-alekseev** [web3j/web3j#150]
Guys, I hope to your help! I am try to develop wallet for ethereum using web3j library. At this point I try to get the ballance of wallet. As example I am use the wallets numbers from this resourse https://etherscan.io/accounts. When I made a request to get the balance I get the BigInteger variable where contains correct numbers of balance but without comma.

How should I understand what is the whole part in the number, and what is fractional?
Thanks for your help!

**Comment by conor10** [comment]
The balance is always returned in Wei, the smallest unit of currency in Ethereum.

web3j contains conversion functions [here](https://github.com/web3j/web3j/blob/master/src/main/java/org/web3j/utils/Convert.java#L27)

**Comment by vlad-alekseev** [comment]
Great thanks man! That's what I need.
