### ISSUE TITLE
I cannot generate solidity wrapper class on android

### ISSUE THREAD

**Issue by juckrit** [web3j/web3j#1501]
# I cannot generate solidity wrapper class on android

I have try the following code from doc

> web3j solidity generate -b /path/to/<smart-contract>.bin -a /path/to/<smart-contract>.abi -o /path/to/src/main/java -pcom.your.organisation.name`

But I got this error

> by Web3Labs 
Unknown option: '-b'

**Comment by saullfeng** [comment]
you an try 
web3j generate solidity  -b /path/to/.bin -a /path/to/.abi -o /path/to/src/main/java -pcom.your.organisation.name
