### ISSUE TITLE
Which method is the same as Web3.solidityKeccak (['uint256', [signature_int]) in web3.py?

### ISSUE THREAD

**Issue by fastener** [web3j/web3j#1509]
Which method is the same as Web3.solidityKeccak (['uint256', [signature_int]) in web3.py?

**Comment by mohamedelshami** [comment]
Not sure about Web.py APIs, in Python in general it can be:

```
from Crypto.Hash import keccak
k = keccak.new(digest_bits=256)
k.update(b'\x1a').hexdigest()

```

Sha3 for Web3j https://github.com/web3j/web3j/blob/49fe2c4e2d9d325ec465879736d6c384f41a4115/utils/src/main/java/org/web3j/crypto/Hash.java#L69

**Comment by fastener** [comment]
how to use EIP-712 Ethereum signature?

**Comment by mohamedelshami** [comment]
hey @fastener just to understand, you're trying to Web3j to sign tx, but Hash.sha3 (Keccak-256) doesn't match solidityKeccak?

Do you have a snippet code please where you comparing the two hash functions?

**Comment by fastener** [comment]
I'm looking at the python SDK code for DYDX and trying to turn it into Java code. I'm trying to generate the Ethereum Key Authentication. The code in the python SDK uses solidityKeccak and sends a communication to the ether node to get the signature.

**Comment by mohamedelshami** [comment]
Hi @fastener as far as I know the solidityKeccak should be equivalent to sha3 in Web3j library, would help more but the question on DYDX example can't be identified as an issue with Web3j, so I will move this to discussion for follow up
