### ISSUE TITLE
How to use web3j to generate account private key through eip-712?

### ISSUE THREAD

**Issue by fastener** [web3j/web3j#1510]
How to use web3j to generate account private key through eip-712?

**Comment by mahima-manik** [comment]
To generate key pair, use the Credentials class: https://github.com/web3j/web3j/blob/release/4.8.7/crypto/src/main/java/org/web3j/crypto/Credentials.java
http://docs.web3j.io/4.8.7/transactions/credentials/

There is no separate way to generate keys for EIP-712.
