### ISSUE TITLE
Exception Value must be in format 0x[1-9]+[0-9]* or 0x0 when using EthEstimateGas.amountUsed

### ISSUE THREAD

**Issue by zahir-hl** [web3j/web3j#1512]
I am getting exception Value must be in format 0x[1-9]+[0-9]* or 0x0 while trying to get gas estimation from EthEstimateGas.amountUsed, can anyone please give actual solution, because there are alot of same issues opened but no one gave proper answer, should we consider this as web3j is not maintained anymore?

**Comment by mahima-manik** [comment]
Hi @zahir-hl, I was able to reproduce this issue by setting the transaction gasLimit below base fees. Basically, it can happen when the transaction itself has failed and therefore the return value is null. There can be two approaches for this:
1. Check the response if transaction was successful, in case of error, return the corresponding exception to the user
2. Before the transaction is made, check if the gasLimit is set above the base fees and give warning to the user.

**Comment by zahir-hl** [comment]
Hello @mahima-manik, 

If that so, why it is not giving error like gasLimit should be above specific fees, because how would a non experienced person know what exactly that error(Value must be in format 0x[1-9]+[0-9]* or 0x0) means.
For the two approaches:

1. If the gasLimit is not estimated yet, how can a transaction be successful in the first place? because I'm making the transaction only after I get the estimated gasLimit.
2. What is the base fees for gasLimit? because that's what I'm calling web3j.ethEstimateGas(transaction).send().amountUsed for, just to know the gasLimit needed for a transaction.

**Comment by zahir-hl** [comment]
And even If I call web3j.ethSendTransaction(customTransaction).send() without estimating gas limit, then the transaction is being called successfully, but whenever I call web3j.ethEstimateGas, I get error,

here is my code snippet,

            val price = BigInteger.valueOf(1000000000)
            val limit = BigInteger.valueOf(3000000)
            val gasProvider = StaticGasProvider(price, limit)
            val txnManager = MagicTxnManager(web3j,account);

            val contract = FPost.load(contractAddress, web3j, txnManager, gasProvider)

            val getData = contract.purchase(BigInteger.valueOf(2)).encodeFunctionCall()
            val getNonce = web3j.ethGetTransactionCount(account, DefaultBlockParameterName.PENDING)
                .send().transactionCount

            val customTransaction  = Transaction.createFunctionCallTransaction(
                account,
                getNonce ,
                price,
                limit,
                contractAddress,
                BigInteger.valueOf(1000000000),
                getData
            )

            val getGasLimit = web3j.ethEstimateGas(customTransaction).send().amountUsed

**Comment by mahima-manik** [comment]
@zahir-hl I tried with createContractTransaction and gasLimit can be one of the possible reasons for this error. For createFunctionCallTransaction there can be other issue. Root cause is that Response is not being checked for success/failure before calling the decode function. 

Code pointer: https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/protocol/core/methods/response/EthEstimateGas.java#L23

To answer your above questions:
We pass gasLimit proposed for the transaction as the [parameter](https://eth.wiki/json-rpc/API#eth_call) to create Transaction function. If the gasLimit is lesser, then this exception was thrown. 

I suggest you to try with higher value of gas limit. We will put the fix on our side to show right exception to the clients.

**Comment by zahir-hl** [comment]
@mahima-manik I tried as you suggested, and still I face the same issue, below are the gas price and gas limit I used for a transaction.

val gasPrice = BigInteger.valueOf(3000000000)
val gasLlimit = BigInteger.valueOf(20000000)

I get this error from EthEstimateGas
code = -32603
message = Internal error: JSON-RPC error.

**Comment by mahima-manik** [comment]
Can you try with gasLimit as null: https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/protocol/core/methods/request/Transaction.java#L95

If no gas limit is specified geth uses the block gas limit from the pending block as an upper bound.

Similar issue: https://github.com/MetaMask/metamask-extension/issues/7286

**Comment by zahir-hl** [comment]
@mahima-manik 
I tried with the function createContractTransaction which takes no gasLimit, 
Now it gives below error:

code = -32602
message = Error forwarded from node: invalid argument 0: json: cannot unmarshal non-string into Go struct field TransactionArgs.nonce of type hexutil.Uint64

**Comment by zahir-hl** [comment]
@mahima-manik ,

Is there any solution for this or not? or Should I consider the silence as a negative response?
