### ISSUE TITLE
very slow pending transactions?

### ISSUE THREAD

**Issue by gillbates** [web3j/web3j#1513]
# very slow pending transactions when compared to web3js ?

## description
I've run both web3js and web3j to subscribe pending transactions and print to console on the same machine.
It seemed web3js version would print out far more pending transactions and much more faster?

my java code is

`
public static void main(String[] args) throws URISyntaxException, ConnectException {
        log.debug("hallo world ...");

        final WebSocketClient webSocketClient = new WebSocketClient(new URI("wss://bsc-ws-node.nariox.org:443"));
        final boolean includeRawResponses = false;

        final WebSocketService webSocketService = new WebSocketService(webSocketClient, includeRawResponses);
        webSocketService.connect();
        Web3j web3j = Web3j.build(webSocketService);

        Web3ClientVersion web3ClientVersion = null;
        try {
            web3ClientVersion = web3j.web3ClientVersion().send();
            String clientVersion = web3ClientVersion.getWeb3ClientVersion();
            log.debug("{}", clientVersion);

            Subscription subscription = (Subscription) web3j.blockFlowable(false).subscribe(block -> {
                EthBlock ethBlock = block;
                log.debug("latest block number: {}", block.getResult().getNumber());
            });

            Subscription pendingTransactionsSubscription = (Subscription) web3j.pendingTransactionFlowable().subscribe(tx -> {
                Transaction transaction = (Transaction) tx;
                log.debug("pending transaction:{}", transaction.getHash());
            });
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
`

and my node js code is:

`    
var subscription = web3.eth.subscribe('pendingTransactions', function (error, result) {
        if (error) console.error(error);
        console.log('pending: ${result}');
    }).on("data", function (transaction) {});`

and java result

![iShot2021-09-22 18 59 20](https://user-images.githubusercontent.com/783547/134332017-8a15425a-7c8e-4f21-bc06-ffec8030f51b.jpg)

node result:

![iShot2021-09-22 19 02 21](https://user-images.githubusercontent.com/783547/134332424-c3cadc6f-c9c4-4298-8fee-12a3ed25720c.jpg)

It seemed, node will print more pending transactions of the same block than web3j.

Any ideas why?

**Comment by mohamedelshami** [comment]
Hi @gillbates thank you for providing this helpful comparison

It looks like the underlying RPC `[pendingTransactionFlowable](https://github.com/web3j/web3j/blob/49fe2c4e2d9d325ec465879736d6c384f41a4115/core/src/main/java/org/web3j/protocol/rx/JsonRpc2_0Rx.java#L97)` is still polling on fixed interval
