### ISSUE TITLE
 EIP-1559 Smart contract wrapper

### ISSUE THREAD

**Issue by igorsimjanoski** [web3j/web3j#1517]
Hi, i think the main problem is not how to transfer funds using eip-1599 (which is supported as explained in referenced links above) but how to use 'Solidity smart contract wrappers' and send eip-1599 transaction type.

For example, this snippet:

ERC20 contract = ERC20.load(tokenAddress, web3j, txManager, gasPriceProvider);
contract.transfer(....)

will send legacy type of transaction.

_Originally posted by @igorsimjanoski in https://github.com/web3j/web3j/issues/1487#issuecomment-930801301_

**Comment by muratogat** [comment]
Just want to add that this is the ContractGasProvider (4.8.8-android) and it doesn't support EIP-1559 at all.

```
public interface ContractGasProvider {
    BigInteger getGasPrice(String contractFunc);

    @Deprecated
    BigInteger getGasPrice();

    BigInteger getGasLimit(String contractFunc);

    @Deprecated
    BigInteger getGasLimit();
}
```

Sorry but web3j can't claim that it supports EIP-1559 while not supporting >90% of use cases.

**Comment by fergarrui** [comment]
Hi, any news on this issue?

Thanks

**Comment by Vorh** [comment]
Hi, any news on this issue?

Thanks

**Comment by fergarrui** [comment]
@conor10 , @snazha-blkio @AlexandrouR 

Is this library still maintained? :)

**Comment by AlexandrouR** [comment]
@fergarrui Hi, yes the repo is still maintained but we are two people so it may take a bit of time to respond sorry for that. Sending contract transactions as EIP 1559  is not directly supported at the moment, it is possible to do but not in the best way we are looking to change this and make it easier.

**Comment by fergarrui** [comment]
@AlexandrouR  No problem, thanks.
Could you explain the workaround so we can use it in the meantime? We want to use NoOpProcessor, I mean we do not want to wait for the transaction to be mined, we just want the tx hash and then we listen to events in our side.  Thanks!

**Comment by andrii-kl** [comment]
@igorsimjanoski @fergarrui @muratogat  To use EIP-1559 with Contracts you should use another constructor
ERC20(String contractAddress, Web3j web3j, TransactionManager transactionManager, ContractGasProvider contractGasProvider)

Initialize TransactionManager with chainId parameter (RawTransactionManager implementation) 
for example RawTransactionManager(Web3j web3j, Credentials credentials, long chainId)

**Comment by igorsimjanoski** [comment]
Hi, i'm using latest web3j release at time of writing this comment (v.4.9.2) to check EIP-1559 support and it looks OK, switching to new StaticEIP1559GasProvider fix the problem, i'm able to deploy smart contract and send EIP-1559 transaction type during deployment.

However, afterwards i'm trying to invoke some of the smart contract methods. In our application layer, we're using TransactionManager with 'QueuingTransactionReceiptProcessor' (which returns 'EmptyTransactionReceipt' that contains only transaction hash).

In Contract.executeTransaction after transactions is sent there is check:
```
if (receipt != null && !receipt.isStatusOK()) {
........
```

where isStatusOK() is implemented in TransactionReceipt as:
```
        if (null == getStatus()) {
            return true;
        }
         ......
```
But getStatus() for EmptyTransactionReceipt is throwing UnsupportedOperationException

Prior v4.5.17 this code was used to be:
```
        if (null == status) {
            return true;
        }
```

So, not necessarily related to EIP-1559 but it looks like starting from v4.5.17 there is no way to use QueuingTransactionReceiptProcessor 
@alexdupre can you please share your opinion on this, is this real problem or i'm missing something :)

Thanks.

**Comment by alexdupre** [comment]
That code is 5 years old, it has nothing to do with EIP-1559. That's the "expected" behavior, look at https://github.com/web3j/web3j/issues/480#issuecomment-769912912

**Comment by igorsimjanoski** [comment]
Closing the issue, EIP-1559 is supported from auto-generated smart contract wrappers.
