### ISSUE TITLE
Public Release required for the Fix to Transaction response error / No virtual method longValueExact()J in class Ljava/math/BigInteger

### ISSUE THREAD

**Issue by Armaan-Ul-Islam** [web3j/web3j#1518]
### Requriment: A new Android **release** for Web3J (say 4.8.8 or 4.8.8-android)

@AlexandrouR Thanks. We really appreciate your quick fix.

Required one more support from your end,

### Reasons: 
* **For the Sake of Developers using Web3J**: This issue can be considered a major issue as all the devices running on Android 11 or below (~almost all android devices) will not be able to retrieve transactions properly without this fix. We expect most developers to import a publicly released version, rather than snapshots. So this fix should be released as soon as possible.

* **For the Sake of My project**: The model/Architecture used in my project (an android library) is that we do not package/export the Web3J library ourselves. Thus, developers have to import the publicly released version of Web3J in their 'build.gradle' files to use our SDK/services. (which also showcases Web3J library to all :+1: ). So in our case, we urgently require this fix to go public. (We've tried jitpack Snapshots, but facing challenges in many cases)

@conor10 @mohamedelshami Please support triggering a release as an urgent need. Thanks in advance.

**Comment by gtebrean** [comment]
As there is no new message we consider it solved.
