### ISSUE TITLE
NullPointerException after transactionObservable(). subscribe (web3j=v.2.3.0, related with fix #100 "Ancient event logs not listed")

### ISSUE THREAD

**Issue by VadymKryshyna** [web3j/web3j#152]
Hi!
After commit Fix #100. "Ancient event logs not listed" I have a NullPointerException when I want subscribe on event
"
Web3j web3j = Web3j.build(new HttpService());
 web3j.transactionObservable().subscribe(tx -> { /** do something **/ },...);
"
I think reason is in:
1) class: "org.web3j.protocol.core.filters.Filter<T>"
method: "public void run(ScheduledExecutorService scheduledExecutorService, long blockTime)"
"
EthLog ethLogInit = web3j.ethGetFilterLogs(filterId).send();
process(ethLogInit.getLogs());
"
2) and in extends class: "org.web3j.protocol.core.filters.LogFilter"
methods: "void process(List<EthLog.LogResult> logResults)"
"List<EthLog.LogResult> logResults" can be null (I receive logResults as null), and I get NullPointerException in foreach.

Maybe need add check that logResults is not null, or I do something wrong?
p.s. in version web3j 2.2.2 (before fix #100) - all is ok.
Thanks

**Comment by zzq-ly** [comment]
Hi,i already meet this problem?Can you  tell how did you resolve it,

**Comment by PhineasClick** [comment]
I'm having the same Problem. Does anyone have a solution?

**Comment by VadymKryshyna** [comment]
Hi. @zzq-ly and @PhineasClick as solution - (in current time) I used version 2.2.2 (I write it in my issue - "p.s. in version web3j 2.2.2 (before fix #100) - all is ok."), but I think that it is not good solution.

**Comment by the-wastl** [comment]
I created a pull request that should resolve the issue
Basically the problem is that not all filters can get data from block 0 but only new events

**Comment by VadymKryshyna** [comment]
Thanks @the-wastl.
