### ISSUE TITLE
Get ABI encoding of function calls

### ISSUE THREAD

**Issue by drinkcoffee** [web3j/web3j#1536]
## Feature description_
I have created a fork for Web3J that allows the code generator to take an additional command line parameter. If the parameter is set, extra functions are generated for each Solidity function that returns the ABI encoding of the function selector and data. 

Having the ability to get the ABI encoded function selector and parameter data is useful for crosschain systems that need to submit this information at times other than as part of a transaction call. For example, the GPACT protocol creates a call execution tree to be executed. The call execution tree is consists of blockchain ids, contract addresses, and the function call information generated by the fork of web3j using the feature described in this issue.

The command line parameter can be either -r or --abiFuncs

The additional functions look like:
`public String getABI_allowanceMax(String owner, String spender)`
where the standard function generated by web3j is:
`public RemoteFunctionCall<BigInteger> allowanceMax(String owner, String spender) {`

For example, have a look at:
https://github.com/ConsenSys/gpact/blob/main/application/atomic-appcontracts/erc20/src/main/java/net/consensys/gpact/appcontracts/atomic/erc20/soliditywrappers/LockableERC20PresetFixedSupply.java

The repo is here: https://github.com/drinkcoffee/web3j-abi

I plan to pull changes from the main web3j repo, integrated any feedback raised in comments on this issue, and then submit a pull request. As such, your comments and feedback would be greatly appreciated.

**Comment by sambacha** [comment]
this can be closed per #1537
