### ISSUE TITLE
Signing transactions with metamask using web3j

### ISSUE THREAD

**Issue by KorniienkoYehor** [web3j/web3j#1551]
I want to call smart contract methods (write methods) and they must be signed by the owner of the wallet (using metamask or trust wallet). How can I do it? I want to use methods of an existing contract (I know smart contract address), do I need to deploy the contract? Or I can use transactions(or rawTransaction)  from the web3j? help me please

**Comment by AlexandrouR** [comment]
Web3j is meant to be used on the backend. Metamask injects its own client into the browser. one possible way so you could try to get the signed data of the function call encoded and send that as a web3j transaction. 
```
Transaction transaction = Transaction.createContractTransaction(
        <fromAddress>,
        <nonce>,
        <gasPrice>,
        <gasLimit>,
        <value>,
        "your function call here");


```
