### ISSUE TITLE
credentials.getAddress, With uppercase

### ISSUE THREAD

**Issue by DorenBoust** [web3j/web3j#1554]
Hello,
the credentials.getAddress() automatic change the address to lowercase, I need to get the Exact address with uppercase.

For address:
0x8bB45E8fd80fC1792abB0e6819eCE27a8E332A48

I get:
0x8bb45e8fd80fc1792abb0e6819ece27a8e332a48

How can i get the '0x8bB45E8fd80fC1792abB0e6819eCE27a8E332A48' version?

Thanks

**Comment by andrii-kl** [comment]
@DorenBoust You can use String function 'toUpperCase()' to return in uppercase
