### ISSUE TITLE
Binary string constant too long in generated java wrapper

### ISSUE THREAD

**Issue by tena4881** [web3j/web3j#1562]
Hello all,
I have been using Web3j to generate java wrappers of smart contracts and I encountered an issue with more a complex smart contracts having a binary that has a length beyond what Java string constants support. As a result when attempting to compile the java wrapper code it throws an error 

The smart contract I am using is quite complex. It deploys a number of other smart contracts and has many constructor arguments. The java wrapper is created just fine however I have to manually extract the binary constant, save it in a text file, put the file in the resources of my project and load it using java resource stream. However when decoupling  and automating the wrapper generation process it becomes an issues when and java compile stage due to the large string constant that stores the  smart contract binary found in the wrapper.

I know I was not supposed to modify the generated java wrapper but I gave it a shot and it works like a charm. However again, I don't think it can scale.

Java output 
`[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.058 s
[INFO] Finished at: 2020-03-14T17:56:34+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile (default-testCompile) on project core-java-strings: Compilation failure
[ERROR] <path to the java wrapper class>:[10,32] constant string too long`

Any input would be great!

**Comment by andrii-kl** [comment]
@tena4881 It's not totally clear the steps to reproduce. 
It would be great if you localize your problem and create a small contract to reproduce this case.
