### ISSUE TITLE
web3j new throws build error

### ISSUE THREAD

**Issue by phazejeff** [web3j/web3j#1566]
I am on Windows 10, and I installed the CLI successfully using `Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/web3j/web3j-installer/master/installer.ps1'))`

Yet running `web3j new` throws this: 
```

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 709ms
```

**Comment by mohamedelshami** [comment]
@phazejeff please confirm whether this is still an issue with recent web3j v4.9.4, and feel free to reopen if you still facing above issue.
