### ISSUE TITLE
Android. Play Store. Supported devices limitation.

### ISSUE THREAD

**Issue by ramanbranavitski** [web3j/web3j#157]
Hi, there. When I add your library to my project, I found really strange thing. It started to be supported only on 10 devices (according to play store statistic). When I remove this dependency, app become to be supported on 2300+ devices. I tried to analyze AndroidManifest files with and without this library but didn't found any changes. Can you help me with my problem? What from you library can add such serious limitation? Thank you.

**Comment by ramanbranavitski** [comment]
As I found the reason is in 'com.lambdaworks:scrypt:1.4.0' dependency

**Comment by conor10** [comment]
Ok, thanks for highlighting. Easiest thing to do would be to remove this dependency and stick to the Scrypt implementation in Bouncy/Spongy Castle. Doing so may cause issues with one of the tests in https://github.com/web3j/web3j/blob/master/src/test/java/org/web3j/crypto/WalletUtilsTest.java, but it's important that web3j works nicely with as many Android devices as possible.

**Comment by ramanbranavitski** [comment]
> A precompiled native library for Android 2.3 running on ARM is located in
  src/android/resources/lib/arm5/libscrypt.so. If placed in an .apk file's
  lib/armeabi directory it will be automatically loaded.

The easiest thing is to put this `libscrypt.so` file to `main/src/jniLibs/armeabi` folder in your repo. I've already tested this approach and everything works fine.

**Comment by dmi3coder** [comment]
This would possibly be a compatibility issue if we'll remove SCrypt and replace it with Bouncy Castle. For example, the test fails because 'N' value is greater than 65536 while 'r' value is 1. Is there any way to workaround this limitation?

**Comment by conor10** [comment]
Going with the change to the test data makes sense.
