### ISSUE TITLE
"Cannot resolve symbol 'RequestTester'"

### ISSUE THREAD

**Issue by gabirezzo** [web3j/web3j#1573]
The cloned code from the tool's repository has several dependency errors, and doesn't recognize some types that are used to run the tests. For example, the module that contains a RequestTester class, used as the base class of several test classes, is not being recognized as a dependency on higher-level modules.

### Expected behavior
Tests should run without error and the RequestTester class needs to be recognized.

## Environment
- Web3j version: 4.8.7
- CLI: 1.4.1
- Java version : 8 e 11
- Operating System : Windows

## Additional context
![WhatsApp Image 2021-12-13 at 22 15 14](https://user-images.githubusercontent.com/33133399/145916221-b4601e9b-cae8-42da-affa-7f394be849da.jpeg)

**Comment by mohamedelshami** [comment]
The class `org.web3j.protocol.RequestTester` is in test scope under org.web3j.core.test, please make sure web3k-core dependency is added testImplementation scope.
