### ISSUE TITLE
WalletUtils.isValidPrivateKey() 

### ISSUE THREAD

**Issue by guangxingmao** [web3j/web3j#1574]
Can I use this method to verify the privateKey？

![截屏2021-12-14 16 46 07](https://user-images.githubusercontent.com/19208420/145964547-529b990f-604a-4580-8f87-52b2c33f8fa0.png)

**Comment by andrii-kl** [comment]
@guangxingmao  Yes, you can use this method to validate a private key. 
But keep in the mind that this method validate only a key length.
