### ISSUE TITLE
HexData Transaction including Ether Value

### ISSUE THREAD

**Issue by ArmanYeghiazaryan** [web3j/web3j#1575]
hello, 

I would like to send a transaction like this:

`RawTransaction.createTransaction(
        <nonce>, GAS_PRICE, GAS_LIMIT, "0x<address>", <amount>, "0x<hex encoded text>");

byte[] signedMessage = TransactionEncoder.signMessage(rawTransaction, ALICE);
String hexValue = Numeric.toHexString(signedMessage);

EthSendTransaction ethSendTransaction =
        web3j.ethSendRawTransaction(hexValue).send();
String transactionHash = ethSendTransaction.getTransactionHash();
...`
Source: https://docs.web3j.io/4.8.7/references/troubleshooting/#is-it-possible-to-send-arbitrary-text-with-transactions

However, how can I add an Ether Value to this transaction? for example: 0.03ETH. 
The amount parameter in the example is a BigInteger.

Thank you

**Comment by ArmanYeghiazaryan** [comment]
@

**Comment by ArmanYeghiazaryan** [comment]
Somebody here who could help?

**Comment by meligame** [comment]
new BigInteger(Convert.toWei("0.03", Unit.ETHER).toString());
