### ISSUE TITLE
Cannot install Web3j (website "internal.services.web3labs.com" down?)

### ISSUE THREAD

**Issue by CJ42** [web3j/web3j#1579]
# Cannot install Web3j

⚠️ Impossible to install Web3j, using this command below from the docs:
http://docs.web3j.io/4.8.7/command_line_tools/

## _Issue_description_
_Please describe what are you trying to do and why it doesn't work_

trying to install Web3j, using the command below from the docs:

```shell
curl -L get.web3j.io | sh && source ~/.web3j/source.sh
```

It always fail with the following error:

```shell
curl: (28) Failed to connect to internal.services.web3labs.com port 443: Connection timed out
The Web3j CLI requires a Java version between 1.8 and 12. Please ensure you have a compatible Java version before installing Web3j for full functionality.
sh: 166: cannot open /dev/tty: No such device or address
Downloading Web3j ...
Looks like there was an error while trying to download web3j
/home/runner/work/_temp/1102ef17-1ea9-45d7-bb56-23c021ecfa67.sh: line 1: /home/runner/.web3j/source.sh: No such file or directory
```

It looks like the website is either down, or has some firewalls.
https://internal.services.web3labs.com/

## _Context_

It fails **both locally + in github actions.**

See our github action + failing CI here: https://github.com/lukso-network/lsp-universalprofile-smart-contracts/runs/4532862361?check_suite_focus=true

**Comment by ahamdi** [comment]
Hi, I have the same issue, in fact it causes failure on our CI/CD pipeline. We use the Web3j maven plugin which uses Sokt to manage the Solidity compiler, and fails to download the needed verion of solidity.
Could someone help ?

**Comment by kljaja95** [comment]
Hi ahamdi, 
I have the same problem. Did you find the solution to this problem? 
Also, for 'curl -L get.web3j.io | sh' I have connection timeout error.
Kind regards

**Comment by ahamdi** [comment]
> Hi ahamdi, I have the same problem. Did you find the solution to this problem? Also, for 'curl -L get.web3j.io | sh' I have connection timeout error. Kind regards

@kljaja95 I had to include the folder **.web3j** that I had before in my laptop in the Docker image to avoid that Web3J looks for the solidity compiler online and just use the one already available inside that folder. that folder is located under the User Home folder.

**Comment by KyunghoSong** [comment]
same problem here, `curl -L get.web3j.io | sh` command times out with `curl: (7) Failed to connect to internal.services.web3labs.com port 443: Operation timed out`

**Comment by iBroProJeff** [comment]
After I try to change the different network, it work.

**Comment by ahamdi** [comment]
It seems the service came back again. I am able to download the solidity compiler again. Thanks for who fixed this.
