### ISSUE TITLE
 Web3J how to call Geth's Personal client APIs

### ISSUE THREAD

**Issue by codingEcho** [web3j/web3j#158]
web3J how to call **Geth's Personal** client APIs,such as `personal_newAccount`,I'm not find method

**Comment by hatzhang** [comment]
use parity:
`parity.personalNewAccount(PASSWORD).send()`

**Comment by VadymKryshyna** [comment]
@codingEcho, I used next code:
`String someYourPrivateKey = "someYourPrivateKey";`
`Parity parity = Parity.build(new HttpService());`
`NewAccountIdentifier newAccountIdentifier = parity.personalNewAccount(someYourPrivateKey)
.sendAsync().get();`
`String publicAccountAddress = newAccountIdentifier.getAccountId();`

**Comment by codingEcho** [comment]
@hatzhang  it working.but [web3j Features](https://github.com/web3j/web3j) show us  `Support for Parity's Personal, and Geth's Personal client APIs`.It's not very understanding

**Comment by ajit-soman** [comment]
You can try this code to create a new account using Geth's personal. I know this issue is already closed but it will be useful for other

```
HttpService httpService = new HttpService("http://localhost:8000");
Admin web3j = Admin.build(httpService);
NewAccountIdentifier  newAccountIdentifier = web3j.personalNewAccount("password@123").sendAsync().get();
System.out.println(newAccountIdentifier.getAccountId());
```
