### ISSUE TITLE
Failed to get solidity version from server

### ISSUE THREAD

**Issue by kljaja95** [web3j/web3j#1584]
# _Bug_title_
web3j-maven-plugin error **Failed to get solidity version from server**

## Steps To Reproduce
I am following [tutorial](https://kauri.io/#communities/Java%20Ethereum/generate-a-java-wrapper-from-your-smart-contract/) to generate a Java Wrapper from Smart Contract. I am following 3rd way for web3j-maven-plugin. 

### Expected behavior
On mvn:generate-sources phase I should get Java Wrapper classes inside my package

### Actual behavior
Build failed with message - Failed to get solidity version from server

## Environment
- Web3j version : 4.8.7
- Java or Android version - Java 11
- Operating System: Windows 10

## Additional context
![image](https://user-images.githubusercontent.com/94906963/146781882-db98937f-4cd6-4d5a-ad3c-50cb1e0e5583.png)

my pom.xml
`<plugin>
        <groupId>org.web3j</groupId>
        <artifactId>web3j-maven-plugin</artifactId>
	<version>4.8.7</version>
		<executions>
			<execution>
				<id>generate-sources-web3j</id>
				<phase>generate-sources</phase>
				<goals>
					<goal>generate-sources</goal>
				</goals>
				<configuration>
				<packageName>com.blockchain.api.smart-contracts</packageName>
				<sourceDestination>${basedir}/target/generated-sources/contracts</sourceDestination>
				<soliditySourceFiles>
					<directory>${basedir}/src/main/resources</directory>
					<includes>
						<include>**/*.sol</include>
					</includes>
				</soliditySourceFiles>
			</configuration>
		</execution>
	</executions>
</plugin>`

**Comment by Vivek-Thakare** [comment]
Maybe this will help.

https://stackoverflow.com/questions/68032384/problem-with-web3j-maven-plugin-it-cant-find-the-solidity-compiler

**Comment by kljaja95** [comment]
Is https://internal.services.web3labs.com/api/solidity/versions/ down? It doesn't work for me

**Comment by iBroProJeff** [comment]
has anyone solve it?? I also met this problem....

**Comment by kljaja95** [comment]
Try to avoid the maven plugin. For some reason, it doesn't work. 
My solution:

+ Download web3j from [releases](https://github.com/web3j/web3j-cli/releases/tag/v1.4.1)
+ Extract folder in users ~./.web3j/ 
+ Do the same thing for web3j-cli-shadow.
+ Open envairement variables and add web3j. Path should be ~./.web3j/web3j-cli-shadow-1.4.1/bin
+ Instal solc with 'npm install -q solc'
+ Restart your PC if needed
+ Compile solidity with: 'solcjs YourSolidity.sol --bin --abi --optimize -o ./'
+ Create Java Wraper Classes with: 'web3j generate solidity -a YourSolidity_sol_YourSolidity.abi  -b YourSolidity_sol_YourSolidity.bin -o . -p your.package'

I hope it will work for you.

**Comment by gtebrean** [comment]
@kljaja95, I tried to replicate it with your specifications but it worked for me, even if the solc is not installed the plugin will download it...
Can you add please the full pom file and the contract?
Here is mine also:

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>TestProject</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <pluginRepositories>
        <pluginRepository>
            <id>central</id>
            <name>Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
            <layout>default</layout>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <releases>
                <updatePolicy>never</updatePolicy>
            </releases>
        </pluginRepository>
    </pluginRepositories>
    <repositories>
        <repository>
            <id>central</id>
            <name>Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
            <layout>default</layout>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.web3j</groupId>
            <artifactId>abi</artifactId>
            <version>4.8.7</version>
        </dependency>
        <dependency>
            <groupId>org.web3j</groupId>
            <artifactId>core</artifactId>
            <version>4.8.7</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.web3j</groupId>
                <artifactId>web3j-maven-plugin</artifactId>
                <version>4.8.7</version>
                <executions>
                    <execution>
                        <id>generate-sources-web3j</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate-sources</goal>
                        </goals>
                        <configuration>
                            <packageName>com.blockchain.api.smart.contracts</packageName>
                            <sourceDestination>${basedir}/target/generated-sources/contracts</sourceDestination>
                            <soliditySourceFiles>
                                <directory>${basedir}/src/main/resources</directory>
                                <includes>
                                    <include>**/*.sol</include>
                                </includes>
                            </soliditySourceFiles>
                            <abiSourceFiles>
                                <directory>${basedir}/src/main/resources</directory>
                                <includes>
                                    <include>**/*.json</include>
                                </includes>
                            </abiSourceFiles>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${basedir}/target/generated-sources/contracts</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>`

and a test contract:
`pragma solidity >=0.4.19 < 0.7.0;

contract Issue17import1 {
    address creator;

    constructor() public{
        creator = msg.sender;
    }

}`

**Comment by gtebrean** [comment]
Due no updates I will close this.
