### ISSUE TITLE
okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;

### ISSUE THREAD

**Issue by zxjwgw** [web3j/web3j#1589]
# _Bug_title_
okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;

## Steps To Reproduce
Web3j web3 = Web3j.build(new HttpService());
        Web3ClientVersion web3ClientVersion = web3.web3ClientVersion().send();
        String clientVersion = web3ClientVersion.getWeb3ClientVersion();

### Actual behavior
![image](https://user-images.githubusercontent.com/16741719/147449371-356fe232-fa2d-4243-ba4a-1b98bee95a22.png)

## Environment
_Describe the environment in which the issue occurs_
- Web3j version 5.0.0
- Java
- mac 11.6.1

**Comment by zhupan1** [comment]
please，How is this problem solved?
