### ISSUE TITLE
ENS L2/offchain data integration

### ISSUE THREAD

**Issue by makoto** [web3j/web3j#1603]
Hi.

At ENS we're planning a couple of significant changes to how ENS resolves names, and it'd be great to see web3j support them from day 1.

The support consists of integrating the following 2 specifications.

- [ENSIP-10: Wildcard Resolution ](https://docs.ens.domains/ens-improvement-proposals/ensip-10-wildcard-resolution) 
- [EIP-3668: CCIP Read: Secure offchain data retrieval](https://eips.ethereum.org/EIPS/eip-3668)  and [the sample implementation for ethers.js](https://github.com/smartcontractkit/ccip-read/tree/rewrite/packages/ethers-ccip-read-provider)

**Comment by andrii-kl** [comment]
@makoto  I have a problem to run "offchain-resolver", I left an issue with description. Could you take a look it or give me an alternative way how to test implementation?
https://github.com/ensdomains/offchain-resolver/issues/3

**Comment by andrii-kl** [comment]
@makoto Base integration is finished. It would be great if you take a look this PR and give me your feedback.

**Comment by andrii-kl** [comment]
@makoto https://github.com/web3j/web3j/pull/1617#issuecomment-1113122572
