### ISSUE TITLE
org.web3j.protocol.exceptions.MessageDecodingException: Value must be in format 0x[1-9]+[0-9]* or 0x0

### ISSUE THREAD

**Issue by traycho** [web3j/web3j#163]
Hi problem occurs when subscribed for pending transactions. The blockNumber of pending transaction is null and it is not possible to be decoded. I would suspect for such case null has to be returned for method getBlockNumber

Code:
```java
Web3j web3 = Web3j.build(new HttpService()); 
		Subscription subscription = web3.pendingTransactionObservable().subscribe(tx -> {
		   System.out.println(tx.getHash() + " " + tx.getBlockNumber());
		}, Throwable::printStackTrace, () -> System.out.println("ptx done"));
```
Stacktrace:
```java
org.web3j.protocol.exceptions.MessageDecodingException: Value must be in format 0x[1-9]+[0-9]* or 0x0
	at org.web3j.utils.Numeric.decodeQuantity(Numeric.java:32)
	at org.web3j.protocol.core.methods.response.Transaction.getBlockNumber(Transaction.java:84)
```

**Comment by conor10** [comment]
You can call `getBlockNumberRaw` instead.

**Comment by amyodov** [comment]
If this method fails with a regular usage scenario, can it at least be marked as “obsolete” or unusable in the documentation? I’ve noticed some other methods fail to handle the input data properly, so basically only `*Raw` methods are something that can work stable – in such case, maybe it is worthy to update the documentation that non-*Raw methods are not ready to production use yet, isn’t it?
