### ISSUE TITLE
Shouldn't prefix quantities according to JSON-RPC spec

### ISSUE THREAD

**Issue by davidyang** [web3j/web3j#1631]
https://github.com/web3j/web3j/blob/49fe2c4e2d9d325ec465879736d6c384f41a4115/core/src/main/java/org/web3j/protocol/core/JsonRpc2_0Web3j.java#L525

I'm using web3j to communicate with a Hardhat Node and getting an error with 'eth_getFilterLogs' because Web3j is formatting hex numbers with a leading 0.

According to the spec, numbers coming over JSON-RPC shouldn't have leading 0s.

https://eth.wiki/json-rpc/API

**Comment by davidyang** [comment]
You can work around this by just create 16 filter logs so you get pass the initial 0x0 padding problem.

**Comment by mahileeb** [comment]
This is a duplicate of https://github.com/web3j/web3j/issues/1392
