### ISSUE TITLE
bad nonce: account does not exist

### ISSUE THREAD

**Issue by Abuzik** [web3j/web3j#1653]
ERC20 class file has a function called transfer which is doesn't work right in smartBCH chain. 
_Error processing transaction request: code:104 info:"bad nonce: account does not exist"_

**Comment by gtebrean** [comment]
SmartBCH has some libraries that make it compatible with evm, also web3j is compatible and created to work with Ethereum network, but this doesn't guarantee web3j  compatibility with smartBCH. Transfer functionality works and is fine in the Ethereum network, due this I will close the ticket.
