### ISSUE TITLE
only replay-protected (EIP-155) transactions allowed over RPC

### ISSUE THREAD

**Issue by tanqiyou1990** [web3j/web3j#1658]
# _only replay-protected (EIP-155) transactions allowed over RPC

Web3j 4.8.7 

Call contract method error

**Comment by paologazzola** [comment]
It happens also to me. Any idea?

**Comment by dinhnv** [comment]
Please use a specific `chainId` and create TransactionManager by yourself like this:

```
// BSC mainnet
long chainId = 56;
TransactionManager txManager = new RawTransactionManager(web3j, credentials, chainId);
ERC20 contract = ERC20.load(tokenAddress, web3j, txManager, gasProvider);
```

**Comment by sench93** [comment]
For ERC20 i understand. How send Etherium if i got same error ? 

Transfer.sendFunds(web3,
                    credentials,
                    "0xEF0D524cE3C7dE6ca2237eC94A6e2f9777AB64bF",
                    Convert.toWei("1", Convert.Unit.WEI),
                    Convert.Unit.WEI
            ).send().getTransactionHash();

**Comment by punk8** [comment]
> For ERC20 i understand. How send Etherium if i got same error ?
> 
> Transfer.sendFunds(web3, credentials, "0xEF0D524cE3C7dE6ca2237eC94A6e2f9777AB64bF", Convert.toWei("1", Convert.Unit.WEI), Convert.Unit.WEI ).send().getTransactionHash();

same question

**Comment by ngoctoan99** [comment]
> For ERC20 i understand. How send Etherium if i got same error ?
> 
> Transfer.sendFunds(web3, credentials, "0xEF0D524cE3C7dE6ca2237eC94A6e2f9777AB64bF", Convert.toWei("1", Convert.Unit.WEI), Convert.Unit.WEI ).send().getTransactionHash();

fun sendWalletEth(
        chainId: String,
        toAddress: String,
        amount: BigInteger,
        none: BigInteger,
        gasPrice: BigInteger,
        gasLimit: BigInteger,
        privateKey: String,
    ): Single<EthSendTransaction>{
        val rawTransaction: RawTransaction = RawTransaction.createEtherTransaction(
           none,gasPrice,gasLimit,toAddress,amount
        )
        val decode = Integer.decode(chainId)
        val credentials = Credentials.create(privateKey)
        val signedTransaction = TransactionEncoder.signMessage(rawTransaction,decode.toLong(),credentials)
        return Single.fromCallable {
            GasService.getService(chainId)!!.ethSendRawTransaction(Numeric.toHexString(signedTransaction)).send()
        }
    } it work for me
