### ISSUE TITLE
TransactionReceipt result returns null

### ISSUE THREAD

**Issue by gspasov** [web3j/web3j#166]
So here is the problem. I'm currently successfully sending a RawTransaction where I specify the wallet credentials, gas price, gas limit, toAddress and amountToSend. But when i try to get the transaction receipt for the transaction hash i get result = null;

Here is the Task I execute for the rawTransaction: 

    public class RawTransactionTask extends AsyncTask<Void, Boolean, Boolean> {
    private static final String TAG = "RawTransactionTask";
    public static final String HEX_PREFIX = "0x";

    private Web3j mWeb3j;
    private Credentials mCredentials;
    private String mToAddress;
    private BigInteger mAmountToSend;
    private Convert.Unit mUnit;
    private BigInteger mGasPrice;
    private BigInteger mGasLimit;
    private SendTransactionCallback mTransactionCallback;
    private EthGetTransactionReceipt receipt;
    private String transactionHash = "";

    public RawTransactionTask(Web3j web3j, Credentials credentials, String address,
                              BigInteger amountToSend, Convert.Unit unit,
                              BigInteger gasPrice, BigInteger gasLimit,
                               SendTransactionCallback transactionCallback) {
        this.mWeb3j = web3j;
        this.mCredentials = credentials;
        this.mToAddress = address;
        this.mAmountToSend = amountToSend;
        this.mUnit = unit;
        this.mGasPrice = gasPrice;
        this.mGasLimit = gasLimit;
        this.mTransactionCallback = transactionCallback;
    }

    @Override
    protected Boolean doInBackground(Void... voids) {
        try {

            String address = mCredentials.getAddress();

            // get the next available nonce
            EthGetTransactionCount ethGetTransactionCount = mWeb3j.ethGetTransactionCount(
                    address, DefaultBlockParameterName.LATEST).send();
            BigInteger nonce = ethGetTransactionCount.getTransactionCount();
            Log.d(TAG, "createCustomTransaction: nonce: " + nonce);

            // create our transaction
            RawTransaction rawTransaction  = RawTransaction.createEtherTransaction(
                    nonce, mGasPrice, mGasLimit, mToAddress, mAmountToSend);
            Log.d(TAG, "createCustomTransaction: Value: " + rawTransaction.getValue());
            Log.d(TAG, "createCustomTransaction: ToAddress: " + rawTransaction.getTo());
            Log.d(TAG, "createCustomTransaction: GasPrice: " + rawTransaction.getGasPrice());
            Log.d(TAG, "createCustomTransaction: GasLimit: " + rawTransaction.getGasLimit());

            // sign & send our transaction
            byte[] signedMessage = TransactionEncoder.signMessage(rawTransaction, mCredentials);
            String hexValue = Hex.toHexString(signedMessage);
            Log.d(TAG, "createCustomTransaction: hexValue: " + hexValue);

            // Send the transaction
            EthSendTransaction raw = mWeb3j.ethSendRawTransaction(HEX_PREFIX + hexValue).send();
            transactionHash = raw.getTransactionHash();

            // Log the Error message if there was an error
            if (raw.hasError()) {
                Log.d(TAG, "createCustomTransaction: Transaction error message: " + raw.getError().getMessage());
                Log.d(TAG, "createCustomTransaction: Transaction error data: " + raw.getError().getData());
            }
            Log.d(TAG, "createCustomTransaction: Transaction JSON-RPC"+ raw.getJsonrpc());
            Log.d(TAG, "createCustomTransaction: Transaction result: " + raw.getResult());
            Log.d(TAG, "createCustomTransaction: Transaction hash: " + raw.getTransactionHash());

            return true;
        } catch (IOException e) {
            e.printStackTrace();
            return false;
        }
    }

    @Override
    protected void onPostExecute(Boolean isFinished) {
        super.onPostExecute(isFinished);
        mTransactionCallback.onFinished(isFinished);

        // Get the receipt
        try {
            receipt = mWeb3j.ethGetTransactionReceipt(transactionHash).sendAsync().get();

            Log.d(TAG, "transactionReceipt: Receipt result:"+ receipt.getResult());
            // Log the Error message if there was an error
            if (receipt.hasError()) {
                Log.d(TAG, "transactionReceipt: Error: " + receipt.getError().getMessage());
            } else if (receipt.getResult() != null || receipt.getTransactionReceipt() != null) {
                Log.d(TAG, "transactionReceipt: Block hash: " + receipt.getTransactionReceipt().getBlockHash());
                Log.d(TAG, "transactionReceipt: Root: " + receipt.getResult().getRoot());
                Log.d(TAG, "transactionReceipt: Contract address: " + receipt.getResult().getContractAddress());
                Log.d(TAG, "transactionReceipt: From: " + receipt.getResult().getFrom());
                Log.d(TAG, "transactionReceipt: To: " + receipt.getResult().getTo());
                Log.d(TAG, "transactionReceipt: Block hash: " + receipt.getResult().getBlockHash());
                Log.d(TAG, "transactionReceipt: Block number: " + receipt.getResult().getBlockNumber());
                Log.d(TAG, "transactionReceipt: Block number raw: " + receipt.getResult().getBlockNumberRaw());
                Log.d(TAG, "transactionReceipt: Gas used: " + receipt.getResult().getGasUsed());
                Log.d(TAG, "transactionReceipt: Gas used raw: " + receipt.getResult().getGasUsedRaw());
                Log.d(TAG, "transactionReceipt: Cumulative gas used: " + receipt.getResult().getCumulativeGasUsed());
                Log.d(TAG, "transactionReceipt: Cumulative gas used raw: " + receipt.getResult().getCumulativeGasUsedRaw());
                Log.d(TAG, "transactionReceipt: Transaction hash: " + receipt.getResult().getTransactionHash());
                Log.d(TAG, "transactionReceipt: Transaction index: " + receipt.getResult().getTransactionIndex());
                Log.d(TAG, "transactionReceipt: Transaction index raw: " + receipt.getResult().getTransactionIndexRaw());
                Log.d(TAG, "transactionReceipt: JSON-RPC response: " + receipt.getJsonrpc());
            }

        } catch (InterruptedException | ExecutionException e) {
            e.printStackTrace();
        }
    }
}

I saw the send Ether scenario and inside it i saw this called : 
TransactionReceipt transactionReceipt =
waitForTransactionReceipt(transactionHash); 

, but i didn't find what does waitForTransactionReceipt(hash);
I guessed that i should wait that the transaction is finished to ask for a transaction hence why I try to get the receipt in the onPostExecute() method of the AsyncTask, but still getting null.

On a side note i have another AsyncTask that does a simple Transaction like this: 

    public class SendTransactionTask extends AsyncTask<Void, Boolean, Boolean> {
    private static final String TAG = "SendTransactionTask";
    private Web3j mWeb3j;
    private Credentials mCredentials;
    private String mToAddress;
    private Double mCoins;
    private Convert.Unit mUnit;
    private SendTransactionCallback mTransactionCallback;

    public SendTransactionTask(Web3j web3j, Credentials credentials, String address,
                               Double coins, Convert.Unit unit,
                               SendTransactionCallback transactionCallback) {
        this.mWeb3j = web3j;
        this.mCredentials = credentials;
        this.mToAddress = address;
        this.mCoins = coins;
        this.mUnit = unit;
        this.mTransactionCallback = transactionCallback;
    }

    @Override
    protected Boolean doInBackground(Void... voids) {
        try {
            TransactionReceipt transactionReceipt = Transfer.sendFunds(
                    mWeb3j,
                    mCredentials,
                    mToAddress,
                    BigDecimal.valueOf(mCoins),
                    mUnit);

            Log.d(TAG, "makeTransaction: From: " + transactionReceipt.getFrom());
            Log.d(TAG, "makeTransaction: To: " + transactionReceipt.getTo());
            Log.d(TAG, "makeTransaction: Root: " + transactionReceipt.getRoot());
            Log.d(TAG, "makeTransaction: Contract Address: " + transactionReceipt.getContractAddress());
            Log.d(TAG, "makeTransaction: Used Gas: " + transactionReceipt.getGasUsed());
            Log.d(TAG, "makeTransaction: Cumulative Gas: " + transactionReceipt.getCumulativeGasUsed());
            Log.d(TAG, "makeTransaction: getTransaction Hash: " + transactionReceipt.getTransactionHash());
            Log.d(TAG, "makeTransaction: Transaction index: " + transactionReceipt.getTransactionIndex());
            Log.d(TAG, "makeTransaction: Block Number: " + transactionReceipt.getBlockNumber());
            Log.d(TAG, "makeTransaction: Block Hash: " + transactionReceipt.getBlockHash());
            Log.d(TAG, "makeTransaction: Block Number Raw: " + transactionReceipt.getBlockNumberRaw());
            return true;
        } catch (InterruptedException |
                TransactionTimeoutException |
                IOException e) {
            e.printStackTrace();
            return false;
        }
    }

    @Override
    protected void onPostExecute(Boolean result) {
        super.onPostExecute(result);
        mTransactionCallback.onFinished(result);
    }
}

Where I do get the TransactionReceipt, but i still get some null values:

09-04 12:04:57.840 16093-16333/ D/SendTransactionTask: makeTransaction: From: null
09-04 12:04:57.840 16093-16333/ D/SendTransactionTask: makeTransaction: To: null
09-04 12:04:57.840 16093-16333/ D/SendTransactionTask: makeTransaction: Root: null
09-04 12:04:57.840 16093-16333/ D/SendTransactionTask: makeTransaction: Contract Address: null
09-04 12:04:57.841 16093-16333/ D/SendTransactionTask: makeTransaction: Used Gas: 21000
09-04 12:04:57.841 16093-16333/ D/SendTransactionTask: makeTransaction: Cumulative Gas: 21000
09-04 12:04:57.841 16093-16333/ D/SendTransactionTask: makeTransaction: getTransaction Hash: 0x452c3b1f26982ffb9fddb0c5cc574cf2bddeb052eaec4d61c30e9211e923432d
09-04 12:04:57.841 16093-16333/ D/SendTransactionTask: makeTransaction: Transaction index: 0
09-04 12:04:57.841 16093-16333/ D/SendTransactionTask: makeTransaction: Block Number: 3585599
09-04 12:04:57.841 16093-16333/ D/SendTransactionTask: makeTransaction: Block Hash: 0x4964af91ce51d87865aa5f744a5f127625e705b989f5940070219bbe3772d80a
09-04 12:04:57.841 16093-16333/ D/SendTransactionTask: makeTransaction: Block Number Raw: 0x36b63f

PS. Using the Kovan test network if this has any input into this.

Thanks!

**Comment by conor10** [comment]
What values are you using for the gas price & gas limit?

**Comment by gspasov** [comment]
Oh, it was a while back but as far as I remmember the gas price was around 0.0001 Ether and the limit was 20000. But you may close it actually. Eather way I appriciate your response :)

**Comment by conor10** [comment]
Typically this behaviour is seen when a bad gas price or limit is used, or there are issues in the Ropsten testnet, as there has been of late.
