### ISSUE TITLE
Can I write a function with dynamic output ?

### ISSUE THREAD

**Issue by tuannm2** [web3j/web3j#1668]
I try to writing a function with parameter (nameMethod, input, output) to call contract.

Is there any ways to write the function without defined Class extend StaticStruct.

**Comment by SweeXordious** [comment]
It is certainly possible to do via encoding the function call yourself etc.
However, you will be repeating the boilerplate abstracted under the java wrappers. Thus, the best way to interact is to generate the Java wrappers and use them to make your calls.
Let us know if you found any issues with the wrappers that made you consider not using them.
Please reopen if needed.

**Comment by tuannm2** [comment]
@SweeXordious Thank you for your quick reply.
Sorry that I can't understand your answer :))

I have a abi like this: 

```
{
    "inputs": [
      {
        "internalType": "address",
        "name": "nft",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "getByNFT",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bool",
            "name": "isEnded",
            "type": "bool"
          },
          {
            "internalType": "address",
            "name": "nft",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "winner",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "owner",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "currency",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "tokenId",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "fee",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "bid",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "bidDuration",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "end",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "id",
            "type": "uint256"
          }
        ],
        "internalType": "struct MarketServiceV1.Auction",
        "name": "auction",
        "type": "tuple"
      },
      {
        "components": [
          {
            "internalType": "bool",
            "name": "isEnded",
            "type": "bool"
          },
          {
            "internalType": "address",
            "name": "nft",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "currency",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "owner",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "tokenId",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "fee",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "price",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "id",
            "type": "uint256"
          }
        ],
        "internalType": "struct MarketServiceV1.Listing",
        "name": "listing",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
```

And how I write a function that can return the full information like output parameter without defined Class.

**Comment by SweeXordious** [comment]
Ah, got you now :+1: 
Instead of doing that, follow this tutorial:
http://docs.web3j.io/4.8.7/getting_started/deploy_interact_smart_contracts/

You already have the `abi` of your smart contract, so you can move directly to installing the [web3j-cli](https://github.com/web3j/web3j-cli). 
Then, running the following:
```shell
$ web3j generate solidity -a /path/to/<smart-contract>.abi -o /output/path -p com.your.organisation.name
```
Which should generate for you a Java class abstracting all the calls.
Then, you can interact with it directly as follows:

```java
Web3j web3 = Web3j.build(new HttpService());  // defaults to http://localhost:8545/
Credentials credentials = WalletUtils.loadCredentials("password", "/path/to/walletfile");

YourSmartContract contract = YourSmartContract.deploy(
        <web3j>, <credentials>,
        GAS_PRICE, GAS_LIMIT,
        <param1>, ..., <paramN>).send();  // constructor params
```

Thus, no need to encode the function name, parameters and everything yourself. It will be done automatically for you.

PS: If you only specify the `abi` and not the `bin` in the above command, you won't be able to deploy your smart contract. So, either specify also the `bin`, or instead of `YourSmartContract.deploy(...)`, use `YourSmartContract.load(...)` which will load the contract using its address (if it's already deployed).

Also, make sure to check the [web3j-gradle-plugin](https://github.com/web3j/web3j-gradle-plugin) (or it's maven version, if you're using maven). This latter can be added to your Gradle project and will generate code for you automatically on every build, and put the files in the right place.

Let me know if you have more questions.

**Comment by tuannm2** [comment]
@SweeXordious I mean that I'm client and interact with contract. However, I don't know exactly what abi I'll interact with 😄 . So I want to write a dynamic function that passing parameter like: name method of abi, input of the method and output of the method. That why  I don't want to generate class  abstract 😄 . 

Sorry if I confusing explanation 😃

**Comment by SweeXordious** [comment]
Then check the following: http://docs.web3j.io/4.8.7/transactions/transactions_and_smart_contracts/

**Comment by tuannm2** [comment]
> Then check the following: http://docs.web3j.io/4.8.7/transactions/transactions_and_smart_contracts/

Thank you for your supporting 👍
