### ISSUE TITLE
web3j.ethGetTransactionReceipt(transactionHash) invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go value of type common.Hash

### ISSUE THREAD

**Issue by wujinzhiye** [web3j/web3j#1677]
# _Issue_title_
I had invoked this method, the blockchain response an error. The error message is "invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go value of type common.Hash". 

## _Issue_description_
I'm making an app that interacts with blockchain. The server uses web3j to obtain the transaction result based on the transaction hash. 
During the method call, the blockchain returned an error message. 
The hash value is obtained by listening to the transaction events of the blockchain. Shoud I need to convert the hash value when making a method call? But I didn't find a way to convert.

## _Issue_context_
_Please provide additional information that might be helpful_
```
EthGetTransactionReceipt ethGetTransactionReceipt = null;
        try {
            ethGetTransactionReceipt = web3j.ethGetTransactionReceipt(transactionHash).send();
        } catch (Exception e) {
           e.printStackTrace();
}
```

**Comment by abheektripathy** [comment]
i get this error using beefy finance, while exiting a retired pool, any solutions?
