### ISSUE TITLE
Improvement: Update rxjava to V2 on Android lib

### ISSUE THREAD

**Issue by deisold** [web3j/web3j#168]
Hello,

would it be possible to update rxjava to Version 2 in the Android lib?

Thanks & Best regards, 

Dirk

**Comment by conor10** [comment]
It would be. However, unfortunately, the upgrade is non-trivial as web3j would need to start using Flowables instead of Observables. If you're keen to have it, you're welcome to submit a PR which I will gladly accept.

**Comment by theres-still-more** [comment]
Keen to take a more thorough look and talk about this.

From the brief look I did it seems like you could utilise some of the RxJava2 types if you were to upgrade version, however it would also likely break a lot of existing code for anyone using the reactive stuff in the current release without much ability to maintain compatibility or have them side by side based on how the Web3jRx interface is implemented in the rest of the core code

**Comment by yervantk** [comment]
I started making the transition on a branch. Any tips I should know about/watch out for?

**Comment by franz-see** [comment]
@yervantk i've created a PR for #441 to fix the integration tests. You can check them out to help with this.

**Comment by Vogel612** [comment]
Of note: RxJava 1 is marked EOL as of March 31 according to the [official readme](https://github.com/ReactiveX/RxJava). As such any improvements to RxJava beyond 1.3.8 will only benefit users when the transition can be done.

It might be beneficial to broaden this issue to include a transition of the exposed APIs into separate plugin-like satellite projects. This would also allow users to minimize the size of the package they include.

**Comment by iikirilov** [comment]
Implemented in https://github.com/web3j/web3j/pull/753 however still needs to ported for android https://github.com/web3j/web3j/issues/769

**Comment by AlexandrouR** [comment]
This issue is no longer relevant as the latest we3j android version is 4.6.0 and is using rxjava v2
