### ISSUE TITLE
Question: recovery-ids (recId) in recoverFromSignature?

### ISSUE THREAD

**Issue by agigao** [web3j/web3j#1685]
Hey guys, thanks for the phenomenal job you've done!

I have a question regarding `recovery-id`:
- In the typescript implementation we plainly see that `value` of `recovery-id` must be either `0` or `1` - [noble-secp256k1:L458](https://github.com/paulmillr/noble-secp256k1/blob/97aa518b9c12563544ea87eba471b32ecf179916/index.ts#L458)
- In case of web3j it's allowed to have any `recId` that is >= 0 - [Sign.java#L139](https://github.com/web3j/web3j/blob/5dd98c29e242e7ea9673062a225e66fafbd13524/crypto/src/main/java/org/web3j/crypto/Sign.java#L139)

I wonder what difference it might have or what `threat` it might pose for my implementation of recovering signature from the token that was generated in the `Javascript` side?

**Comment by andrii-kl** [comment]
According to the Ethereum yellowpaper: 
_The recovery identifier is a 1 byte value specifying the parity and finiteness of the coordinates of the curve point for which r is the x-value; this value is in the range of [0, 3], however we declare the upper two possibilities, representing infinite values, invalid._

https://ethereum.github.io/yellowpaper/paper.pdf
