### ISSUE TITLE
TransactionReceipt with Geth 1.5.2 parsing errror

### ISSUE THREAD

**Issue by fraspadafora** [web3j/web3j#17]
With geth 1.5.2 the getTransactionReceipt is returning:

> {
>   "blockHash": "0xa7b997ddc84692ba0536d4de90a1abf9d4feaba83baf9058c1f1005cd42e8a4c",
>   "blockNumber": "0x1b",
>   "contractAddress": "0xaa1395f6afd14c755b11435474f830de2cb41237",
>   "cumulativeGasUsed": "0x28344a",
>   "from": "0x810840d715da2af2e2e7f9376ef799cc7ba1cb9e",
>   "gasUsed": "0x28344a",
>   "logs": [],
>   **"logsBloom":** "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
>   "root": "0x7b830ae9bbf34b85d3722e510ff1fa397330347975f4928f8d9c496f22257586",
>   "to": null,
>   "transactionHash": "0x1a4898dc450ba5a157d3607a42e1368c87c5d73b5067c52f9ceacc0c2784ef4f",
>   "transactionIndex": "0x0"
> }

But the class TransactionReceipt is not matching the logsBloom parameter, so gives Parsing error.

**Comment by conor10** [comment]
I've checked in a fix for this issue. However, due to the testnet issues going on right now I haven't been able to test.

**Comment by fraspadafora** [comment]
I created a private network with geth 1.5.2 and tested the getTransactionReceipt

**Comment by conor10** [comment]
Great - have tested myself too. Will push out a new release with the updates.
