### ISSUE TITLE
Support release v4.9.2 for Android

### ISSUE THREAD

**Issue by toidv** [web3j/web3j#1705]
version `4.8.8-android` has a lot of problems related to `getTypeName` please help to release v4.9.2 for Android

```
public Class<T> getClassType() throws ClassNotFoundException {
        Type clsType = getType();

        if (getType() instanceof ParameterizedType) {
            return (Class<T>) ((ParameterizedType) clsType).getRawType();
        } else {
            return (Class<T>) Class.forName(clsType.getTypeName());
        }
    }
```

**Comment by hoanganhtuan95ptit** [comment]
I got the same error as you, I already have a PR to solve this error, you can track it https://github.com/web3j/web3j/pull/1706

**Comment by mohamedelshami** [comment]
@toidv @hoanganhtuan95ptit the PR was merged, please feel free to reopen if required.
