### ISSUE TITLE
Deploy Contract not work 

### ISSUE THREAD

**Issue by tretonis** [web3j/web3j#1710]
# _Bug_title_
_A clear and concise description of what the issue is._

## Steps To Reproduce
_Describe the exact steps or scenario to reproduce the issue._

### Expected behavior
_A clear and concise description of what you expected to happen._

### Actual behavior
_A description of the actual behavior occurring._

## Environment
_Describe the environment in which the issue occurs_
- Web3j version
- Java or Android version
- Operating System

## Additional context
_Add any other context about the problem here._
- Logs
- Sample code and/or code snippets
- Unit/integration tests to highlight the issue
- [etherscan](https://etherscan.io/) references

**Comment by tretonis** [comment]
Truffle v5.5.13 (core: 5.5.13)
Ganache v^7.1.0
Solidity - 0.8.13 (solc-js)
Node v16.15.0
Web3.js v1.5.3
------
solc, the solidity compiler commandline interface
Version: 0.8.13+commit.abaa5c0e.Linux.g++
------
web3j  = core-4.8.7.jar
 <dependencies>
        <dependency>
            <groupId>org.web3j</groupId>
            <artifactId>core</artifactId>
            <version>4.8.7</version>            
        </dependency>
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-nop</artifactId>
            <version>1.7.5</version>
            <scope>compile</scope>
        </dependency>
        
    </dependencies>
--------------
Program Wrapper Solidity

```
package com.web3j

/**
 *
 * @author jorge
 */

import java.math.BigInteger;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import org.web3j.abi.TypeReference;
import org.web3j.abi.datatypes.Function;
import org.web3j.abi.datatypes.Type;
import org.web3j.crypto.Credentials;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.RemoteCall;
import org.web3j.protocol.core.methods.response.TransactionReceipt;
import org.web3j.tx.Contract;
import org.web3j.tx.TransactionManager;

/**
 * <p>Auto generated code.
 * <p><strong>Do not modify!</strong>
 * <p>Please use the <a href="https://docs.web3j.io/command_line.html">web3j command line tools</a>,
 * or the org.web3j.codegen.SolidityFunctionWrapperGenerator in the 
 * <a href="https://github.com/web3j/web3j/tree/master/codegen">codegen module</a> to update.
 *
 * <p>Generated with web3j version 3.3.1.
 */
public class Example extends Contract {
    private static final String BINARY = "0x60606040523415600e57600080fd5b60848061001c6000396000f300606060405260043610603f576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063b818dacd146044575b600080fd5b3415604e57600080fd5b60546056565b005b5600a165627a7a72305820bebcbbdf06550591bc772dfcb0eadc842f95953869feb7a9528bac91487d95240029";

    protected static final HashMap<String, String> _addresses;

    static {
        _addresses = new HashMap<>();
    }

    protected Example(String contractAddress, Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit) {
        super(BINARY, contractAddress, web3j, credentials, gasPrice, gasLimit);
    }

    protected Example(String contractAddress, Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit) {
        super(BINARY, contractAddress, web3j, transactionManager, gasPrice, gasLimit);
    }

    public static RemoteCall<Example> deploy(Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit) {
        return deployRemoteCall(Example.class, web3j, credentials, gasPrice, gasLimit, BINARY, "");
    }

    public static RemoteCall<Example> deploy(Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit) {
        return deployRemoteCall(Example.class, web3j, transactionManager, gasPrice, gasLimit, BINARY, "");
    }

    public RemoteCall<TransactionReceipt> ExampleFunction() {
        final Function function = new Function(
                "ExampleFunction", 
                Arrays.<Type>asList(), 
                Collections.<TypeReference<?>>emptyList());
        return executeRemoteCallTransaction(function);
    }

    public static Example load(String contractAddress, Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit) {
        return new Example(contractAddress, web3j, credentials, gasPrice, gasLimit);
    }

    public static Example load(String contractAddress, Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit) {
        return new Example(contractAddress, web3j, transactionManager, gasPrice, gasLimit);
    }

    protected String getStaticDeployedAddress(String networkId) {
        return _addresses.get(networkId);
    }

    public static String getPreviouslyDeployedAddress(String networkId) {
        return _addresses.get(networkId);
    }
}
```

--------
Program Java deploy contract 
```
package com.web3j

import java.io.IOException;
import java.math.BigInteger;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.web3j.crypto.CipherException;
import org.web3j.crypto.Credentials;
import org.web3j.crypto.WalletUtils;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.http.HttpService;
import org.web3j.tx.ChainId;
import org.web3j.tx.Contract;
import org.web3j.tx.ManagedTransaction;
import org.web3j.tx.RawTransactionManager;
import org.web3j.tx.TransactionManager;
import org.web3j.tx.gas.ContractGasProvider;


public class ChainLink_local {

	// Ganache for test	    
    Web3j web3 = Web3j.build(new HttpService("http://127.0.0.1:8545"));
    
    public ChainLink_local()  {
        try {  
            
            process();
            
        } catch (IOException ex) {            
             ex.printStackTrace();
             
        } catch (CipherException ex) {
             ex.printStackTrace();
             
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
   
    
    public void process() throws IOException, CipherException, Exception {
 				        
        String  privetKey= "46041fcef1694847e3acaf7b90adad13b8b2441b5562046c71ee1b5ff3dadcd6"; 
 
        Credentials credentials = Credentials.create(privetKey);
        
         Example contract = Example.deploy(
                    this.web3,
                    credentials,
                    BigInteger.valueOf(3000000),
                    BigInteger.valueOf(5201314)
                    ).send();
        
    }
    
    
    public static void main(String[] args) {
        ChainLink_local cl = new ChainLink_local();        
        
    }
    
}

```
Error Display
--- exec-maven-plugin:3.0.0:exec (default-cli) @ web3j_test ---
java.lang.RuntimeException: java.lang.NoSuchMethodException: com.web3j..Example.<init>(java.lang.String, org.web3j.protocol.Web3j, org.web3j.crypto.Credentials, org.web3j.tx.gas.ContractGasProvider)
	at org.web3j.tx.Contract.deploy(Contract.java:460)
	at org.web3j.tx.Contract.deploy(Contract.java:506)
	at org.web3j.tx.Contract.lambda$deployRemoteCall$5(Contract.java:549)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42)
	at com.menezes.web3j.web3j_test.ChainLink_local.process(ChainLink_local.java:75)
	at com.menezes.web3j.web3j_test.ChainLink_local.<init>(ChainLink_local.java:30)
	at com.menezes.web3j.web3j_test.ChainLink_local.main(ChainLink_local.java:103)

Caused by: java.lang.NoSuchMethodException: com.web3j..Example.<init>(java.lang.String, org.web3j.protocol.Web3j, org.web3j.crypto.Credentials, org.web3j.tx.gas.ContractGasProvider)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.web3j.tx.Contract.deploy(Contract.java:446)



Thank's

**Comment by tretonis** [comment]
solved

**Comment by danielelrond** [comment]
what are you done, to solve this error?

**Comment by Giuseppe-Pascale-Altanet** [comment]
@tretonis please can you post here how you solved this issue ? I'm in the same truble and it's very difficult to find some good documentation.

**Comment by Giuseppe-Pascale-Altanet** [comment]
@danielelrond i solved it too. I just need to study i little bit more. 
Here the solution:
1) open console/cmd/powershell in same folder of YourContract.sol
2) execture this cmd: solcjs YourContract.sol --bin --abi --optimize -o pathWhereSaveFile/
3) execute this cmd: web3j generate solidity -b 'YourContract.bin' -a 'YourContract.abi' -o 'co.yourPackage.path' -p 'c:\absolute\path\where\save\your\file\inside\project\folder'

NB. you have to install solc and web3j for console
1) execute to instal solidity: npm install -g solc
2) execute to instal web3j: npm install -g web3j  
or 
2) download the release from here https://github.com/web3j/web3j/releases/tag/v4.9.8 and add system path to bin folder contained into this package. 
3) you can install Ganache for test deploy

Restart and start to deploy your contracts ;)
