### ISSUE TITLE
Error processing transaction request: transaction underpriced

### ISSUE THREAD

**Issue by atulmundaware** [web3j/web3j#172]
Hello ,

I have created two wallets and using https://ropsten.infura.io testnet,
When I try to transfer ether from one wallet to other i am getting this error:-
 "Error processing transaction request: transaction underpriced
	at org.web3j.tx.ManagedTransaction.processResponse(ManagedTransaction.java:74)".

 assume wallet A & B
I tried to transfer 0.01 from B to A it had worked but it didn't reflacted in A's wallet 
A balance: 5000000000000000000
B balance: 4999916000000000000
Transaction Hash : 0x76008e09cf2afd810b7f21e0eb56c4adfeece31ecc10a8b4d3be4389b1377bb0

A balance : 5000000000000000000
B balance : 4999496000000000000

then I tried again since then it's giving me that error it then it again worked with 0.05 
but again it didn't work later

This code i used to transfer ether from one wallet to other

TransactionReceipt transactionReceipt = Transfer.sendFunds(
		        web3j, credentials, receiversAddress, BigDecimal.valueOf(ethers), Convert.Unit.ETHER);

**Comment by conor10** [comment]
There have been issues with the Ropsten network of late - please can you use Kovan or Rinkeby to verify?
