### ISSUE TITLE
Increment id field on requests

### ISSUE THREAD

**Issue by conor10** [web3j/web3j#173]
The id field on JSON-RPC messages currently uses a constant value of 1.

It should be updated to use a UUID which should be globally unique.
http://docs.oracle.com/javase/8/docs/api/java/util/UUID.html#randomUUID()

web3j.js uses an incrementing long value, however, this could result in shared id values if multiple versions of the library are invoked at the same time.

https://github.com/ethereum/web3.js/blob/develop/lib/web3/jsonrpc.js

**Comment by IgorPerikov** [comment]
Hi, Conor! I'll help with this one
