### ISSUE TITLE
Add support for determining network version automatically 

### ISSUE THREAD

**Issue by conor10** [web3j/web3j#174]
The [net_version](https://github.com/ethereum/wiki/wiki/JSON-RPC#net_version) JSON-RPC call provides information on the network the Ethereum client is connected to.

This information could be cached in web3j's [RawTransactionManager](https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/tx/RawTransactionManager.java#L27), following the first transaction call, enabling web3j to automatically support EIP155 in full.

**Comment by mushketyk** [comment]
Do I understand it correctly that after this change this code in the `RawTransactionManager`:

```java
    if (chainId > ChainId.NONE) {
        ...
    }
```

will be replaced with something like:

```java
    if (getChainId() > ChainId.NONE) {
        ...
    }
```

where `getChainId()` is:

```java
    private byte getChainId() {
        // Return cached chainId or return a call "net_version"
    }
```

**Comment by fcorneli** [comment]
Chain id != net version ...

**Comment by fcorneli** [comment]
The only way to get the correct chain id, is to get the latest block and analyze the signature on the (first) transaction. If EIP-155 is not enabled on your private network, then chain id can be null, and thus different from the network version.

**Comment by magooster** [comment]
There is a JSON RPC endpoint eth_chainId, https://github.com/ethereum/EIPs/blob/master/EIPS/eip-695.md

It's implemented by the major clients Geth, Classic, Parity, Besu, Quorum and in Ganache...

Happy to submit a PR

**Comment by soumyajitsamanta** [comment]
Hi All, is this issue closed and changes made?
