### ISSUE TITLE
Contract method always timeout, never return the TransactionReceipt

### ISSUE THREAD

**Issue by y0unghe** [web3j/web3j#1753]
## After the contract method is sent, just return the transaction hash 
It seems the contract method never works. No matter how high the gas was set, it never works. The TransactionReceipt never return.  How about learning from other web3 libraries, just return the transaction hash, no need to return the TransactionReceipt.

**Comment by AlexandrouR** [comment]
Please open an issue following the issue template in order for us to resolve this.
