### ISSUE TITLE
Web3j in Java 9 and newer

### ISSUE THREAD

**Issue by dman-sol** [web3j/web3j#1755]
I am trying to use the web3j library in java 17. I need core, utils and crypto modules. I added dependencies to my pom.xml .
Next I need to add these three modules to module-info.java

```
    module com.dman.test {
        requires javafx.controls;
        requires javafx.fxml;
        requires core;
        requires utils;
        requires crypto;
    
        opens com.dman.test to javafx.fxml;
        exports com.dman.test ;
    }
```

, but then I get an error (module com.dman.test reads package org.web3j.crypto from both core and crypto).

Is it possible to use web3j after Java 8, and if so, how to configure module-info.java for working with multiple modules?

**Comment by AlexandrouR** [comment]
HI as far as i know web3j can be used with java 8 and 11

**Comment by dman-sol** [comment]
> HI as far as i know web3j can be used with java 8 and 11

You have an example of module-info.java to use multiple modules (such as core, utils and crypto)?

**Comment by mohamedelshami** [comment]
hi @dman-sol there is no short-term plan to support later versions of Java, this is primarily to dependencies on core Crypto and protocol libarires. But it's something we will look to address at some point.
