### ISSUE TITLE
Critical Security Severity on 4.9.4

### ISSUE THREAD

**Issue by Boldbayar** [web3j/web3j#1767]
Hello, I have found the following security issue by scanning with snyk

Provides transitive vulnerable dependency **org.bouncycastle:bcprov-jdk15on:1.68**

1. https://advisory.checkmarx.net/advisory/vulnerability/Cxa9261daf-3755/ on dependency

**Comment by mohamedelshami** [comment]
@Boldbayar thank you for this finding, we will look into possibly adding a dependency override.
