### ISSUE TITLE
How can I load my wallet like web3.js? 

### ISSUE THREAD

**Issue by abc906093117** [web3j/web3j#1768]
I want to load the wallet flexibly like the front-end page(web3.js), instead of loading the wallet only through keystore and privatekey.

For example, after I connect the wallet through web3.js on the front-end page, how can I make Java load the wallet through web3j dependency?

**Comment by mohamedelshami** [comment]
webj3 which is a different library from web3.js works on the server side, in order to integrate with the front-end / Web you would need to communicate with generated APIs, please take a look at the web3j [OpenAPI guide ](https://docs.web3j.io/4.8.7/web3j_openapi/).
