### ISSUE TITLE
Contract metadata

### ISSUE THREAD

**Issue by ivanursul** [web3j/web3j#177]
Is it possible to get a contract metadata with web3j?
In particular, I need contract name, contract details.
Example: https://ropsten.etherscan.io/address/0x159f9fc4525a1804ccdfec69e146d934cad078cb#code

**Comment by conor10** [comment]
Not currently - web3j does not parse the compiled contract information. You're welcome to submit an issue or PR with this functionality if you need it.

**Comment by iikirilov** [comment]
@ivanursul Let's define a scope for the metadata. What do you mean by contract details?

So far I can see you will benefit from:

`contract.getContractName()`

What other methods are useful?

**Comment by AlexandrouR** [comment]
Closed due to inactivity. Seems like this is not a highly requested feature.
