### ISSUE TITLE
Error generating java wrapper

### ISSUE THREAD

**Issue by jjanczur** [web3j/web3j#1773]
# Error generating java wrapper
When I try to generate a wrapper for this simple contract I get an error: `not a valid name: class`

## Steps To Reproduce
Compile the following contract and try to create a java wrapper

```
//SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

contract MeasurementTypeLookup {
    
    struct MeasurementType {
        string name;
        string category;
        string unit;
    }

    MeasurementType[] public lookup;
    event TypeDefined(uint256 index, string name, string class, string unit);
  
    function defineType(
        string memory name,
        string memory class,
        string memory unit
    ) public returns (uint256) {
        lookup.push(MeasurementType(name, class, unit));
        emit TypeDefined(lookup.length - 1, name, class, unit);
        return lookup.length -1;
    }
}
```

To get the wrapper
`web3j generate solidity -a MeasurementTypeLookup.abi -b MeasurementTypeLookup.bin -o . -p com.project.evm.wrapper`

### Expected behavior

I expect to get the java wrapper like I did with the other contracts

### Actual behavior

I get the following error:
```
by Web3Labs
Generating com.project.evm.wrapper.MeasurementTypeLookup ... not a valid name: class
```

## Environment

_Describe the environment in which the issue occurs_
- Web3j version - Version: 1.4.1
- Java
- macOS Monterey v 12.4

**Comment by Fouad-maker** [comment]
I tried to initialize in memory measurementType before pushing it into but it doesn't work:

//SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "@openzeppelin/contracts/access/Ownable.sol";

contract MeasurementTypeLookup is Ownable {
    
    struct MeasurementType {
        string name;
        string category;
        string unit;
    }

    MeasurementType[] public lookup;
    event TypeDefined(uint256 index, string name, string class, string unit);
  
    function defineType(
        string memory name,
        string memory class,
        string memory unit
    ) public onlyOwner returns (uint256) {
        MeasurementType memory measurmentType = MeasurementType(name, class, unit);
        lookup.push(measurmentType);
        emit TypeDefined(lookup.length - 1, name, class, unit);
        return lookup.length -1;
    }
}

**Comment by jjanczur** [comment]
I can share as well my ABI and bin:

bin:
https://pastebin.com/7e3US4eH

ABI:
```
[
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "index",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "string",
				"name": "name",
				"type": "string"
			},
			{
				"indexed": false,
				"internalType": "string",
				"name": "class",
				"type": "string"
			},
			{
				"indexed": false,
				"internalType": "string",
				"name": "unit",
				"type": "string"
			}
		],
		"name": "TypeDefined",
		"type": "event"
	},
	{
		"inputs": [
			{
				"internalType": "string",
				"name": "name",
				"type": "string"
			},
			{
				"internalType": "string",
				"name": "class",
				"type": "string"
			},
			{
				"internalType": "string",
				"name": "unit",
				"type": "string"
			}
		],
		"name": "defineType",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"name": "lookup",
		"outputs": [
			{
				"internalType": "string",
				"name": "name",
				"type": "string"
			},
			{
				"internalType": "string",
				"name": "category",
				"type": "string"
			},
			{
				"internalType": "string",
				"name": "unit",
				"type": "string"
			}
		],
		"stateMutability": "view",
		"type": "function"
	}
]
```

**Comment by Fouad-maker** [comment]
Change all the propriety "class" occurrences in the contract with another property Name solves the problem

**Comment by jjanczur** [comment]
Thanks! It works! I'm wondering if it's a feature or a bug 😁

**Comment by Gelassen** [comment]
I guess it is constrains by design -- as we know class is reserved word in Java, it looks like there is a clash under the hood of the web3j sol-to-java converter.

**Comment by NickSneo** [comment]
Yes, @Gelassen is correct it was due to the reserved word - "class" in java, it was not able to create the java wrappers.
I tested with latest web3j, if class is Function's name or variable's name outside of a struct it works fine by converting into "_class" but if it is inside struct it gives error.

Will work on this to fix.
