### ISSUE TITLE
Unable to get result of SmartContract

### ISSUE THREAD

**Issue by gspasov** [web3j/web3j#179]
So following the instruction I built the auto-generated Java code of the solidity .bin and .abi file. So this is the result:

/**
 * Auto generated code.<br>
 * <strong>Do not modify!</strong><br>
 * Please use the <a href="https://docs.web3j.io/command_line.html">web3j command line tools</a>, or {@link org.web3j.codegen.SolidityFunctionWrapperGenerator} to update.
 *
 * <p>Generated with web3j version 2.3.1.
 */
public final class Greeter extends Contract {
    private static final String BINARY = "6060604052341561000f57600080fd5b60405161050338038061050383398101604052808051820191905050336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055508060019080519060200190610081929190610088565b505061012d565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106100c957805160ff19168380011785556100f7565b828001600101855582156100f7579182015b828111156100f65782518255916020019190600101906100db565b5b5090506101049190610108565b5090565b61012a91905b8082111561012657600081600090555060010161010e565b5090565b90565b6103c78061013c6000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806341c0e1b51461005e57806342cbb15c14610073578063a41368621461009c578063cfae3217146100f957600080fd5b341561006957600080fd5b610071610187565b005b341561007e57600080fd5b610086610218565b6040518082815260200191505060405180910390f35b34156100a757600080fd5b6100f7600480803590602001908201803590602001908080601f01602080910402602001604051908101604052809392919081815260200183838082843782019150505050505091905050610220565b005b341561010457600080fd5b61010c61023a565b6040518080602001828103825283818151815260200191508051906020019080838360005b8381101561014c578082015181840152602081019050610131565b50505050905090810190601f1680156101795780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161415610216576000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16ff5b565b600043905090565b80600190805190602001906102369291906102e2565b5050565b610242610362565b60018054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156102d85780601f106102ad576101008083540402835291602001916102d8565b820191906000526020600020905b8154815290600101906020018083116102bb57829003601f168201915b5050505050905090565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061032357805160ff1916838001178555610351565b82800160010185558215610351579182015b82811115610350578251825591602001919060010190610335565b5b50905061035e9190610376565b5090565b602060405190810160405280600081525090565b61039891905b8082111561039457600081600090555060010161037c565b5090565b905600a165627a7a72305820b811dc67f5d24a16167883d14964d6f2e7d65cb5a0fbb6a0e4d6a6f4b1be706f0029";

    private Greeter(String contractAddress, Web3j web3j, Credentials credentials, 
                    BigInteger gasPrice, BigInteger gasLimit) {
        super(BINARY, contractAddress, web3j, credentials, gasPrice, gasLimit);
    }

    private Greeter(String contractAddress, Web3j web3j, TransactionManager transactionManager, 
                    BigInteger gasPrice, BigInteger gasLimit) {
        super(BINARY, contractAddress, web3j, transactionManager, gasPrice, gasLimit);
    }

    public Future<TransactionReceipt> kill() {
        Function function = new Function(
                "kill",
                Arrays.<Type>asList(),
                Collections.<TypeReference<?>>emptyList());
        return executeTransactionAsync(function);
    }

    public Future<Uint256> getBlockNumber() {
        Function function = new Function(
                "getBlockNumber",
                Arrays.<Type>asList(), 
                Arrays.<TypeReference<?>>asList(new TypeReference<Uint256>() {}));
        return executeCallSingleValueReturnAsync(function);
    }

    public Future<TransactionReceipt> setGreeting(Utf8String _newgreeting) {
        Function function = new Function(
                "setGreeting",
                Arrays.<Type>asList(_newgreeting),
                Collections.<TypeReference<?>>emptyList());
        return executeTransactionAsync(function);
    }

    public Future<Utf8String> greet() {
        Function function = new Function(
                "greet",
                Arrays.<Type>asList(), 
                Arrays.<TypeReference<?>>asList(new TypeReference<Utf8String>() {}));
        return executeCallSingleValueReturnAsync(function);
    }

    public static Future<Greeter> deploy(Web3j web3j, Credentials credentials, BigInteger gasPrice, 
                                         BigInteger gasLimit, BigInteger initialWeiValue, Utf8String _greeting) {
        String encodedConstructor = FunctionEncoder.encodeConstructor(Arrays.<Type>asList(_greeting));
        return deployAsync(Greeter.class, web3j, credentials,
                gasPrice, gasLimit, BINARY, encodedConstructor, initialWeiValue);
    }

    public static Greeter load(String contractAddress, Web3j web3j, Credentials credentials, 
                               BigInteger gasPrice, BigInteger gasLimit) {
        return new Greeter(contractAddress, web3j, credentials, gasPrice, gasLimit);
    }
}

Inside the MainActivity I deploy this Contract with the following method:

public void btnCreateContract_OnClick(View view) {
        BigInteger gasPrice = new BigInteger("5000000000"); // in Wei
        BigInteger gasLimit = new BigInteger("200000");
        BigInteger initialValueInWei = new BigInteger("1000000000000000");

        try {
            Log.i(TAG, "btnCreateContract_OnClick: Contract Started!");
            Greeter contract = Greeter.deploy(
                    mWeb3j, mWalletCredentials,
                    gasPrice, gasLimit, initialValueInWei,
                    new Utf8String("Hello, blockchain world")).get();

            contract.setGreeting(new Utf8String("Hello, blockchain!!!")).get();

            String contractAddress = contract.getContractAddress();
            Log.i(TAG, "btnCreateContract_OnClick: Address: " + contractAddress);

            Utf8String greet = contract.greet().get();
            Log.i(TAG, "btnCreateContract_OnClick: Contract: " + greet.getTypeAsString());

        } catch (InterruptedException | ExecutionException e) {
            e.printStackTrace();
        } finally {
            Log.i(TAG, "btnCreateContract_OnClick: Contract Finished!");
        }
    }

But when I try to call contract.greet().get() I get an IndexOutOfBoundsExeception
The interesting part is that i do deploy the contract and receive an address of the contract as shown in the log.

So what am I doing wrong?
BTW: Currently using the Kovan testnet client.

This is the Log:

09-28 10:54:04.607 16040-16040/com.quanterall.ethereumwalletweb3j I/MainActivity: btnCreateContract_OnClick: Contract Started!
09-28 10:54:36.281 16040-16040/com.quanterall.ethereumwalletweb3j I/MainActivity: btnCreateContract_OnClick: Address: 0x1b58c3ceee501abfe02afdc59c27951ecc81b78a
09-28 10:54:36.452 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err: java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 0
09-28 10:54:36.452 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at java.util.concurrent.FutureTask.report(FutureTask.java:94)
09-28 10:54:36.452 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at java.util.concurrent.FutureTask.get(FutureTask.java:164)
09-28 10:54:36.452 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at com.quanterall.ethereumwalletweb3j.MainActivity.btnCreateContract_OnClick(MainActivity.java:694)
09-28 10:54:36.452 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-28 10:54:36.452 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at android.view.View.performClick(View.java:5637)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at android.view.View$PerformClick.run(View.java:22429)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at android.os.Looper.loop(Looper.java:154)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err: Caused by: java.lang.IndexOutOfBoundsException: Index: 0
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at java.util.Collections$EmptyList.get(Collections.java:3690)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:182)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at org.web3j.tx.Contract$1.call(Contract.java:164)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at org.web3j.tx.Contract$1.call(Contract.java:161)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j W/System.err:     at java.lang.Thread.run(Thread.java:761)
09-28 10:54:36.453 16040-16040/com.quanterall.ethereumwalletweb3j I/MainActivity: btnCreateContract_OnClick: Contract Finished!

**Comment by conor10** [comment]
The initial value in Wei should be 0, as you're not using the payable modifier on any of the Solidity methods. See http://solidity.readthedocs.io/en/develop/contracts.html for background.

**Comment by witwiki** [comment]
I get the same error but I use `.load() ` to deploy my contract. I am trying to do the same as @gspasov where I try to call `contract.greet().get()` and as such get an **IndexOutOfBoundsExeception**. 

- I wrap the `contract.greet()` in a `Future<Utf8String>` and then call `.get()` as a `Utf8String` type. 
- After this I called the `Utf8String` method `.getValue()` which is set into a `TextView ` in Android.

An` e.getCause()` gives me (first couple of lines):

> java.lang.IndexOutOfBoundsException: Index: 0 
> at java.util.Collections$EmptyList.get

An `e.fillInStackTrace()` gives me (first couple of lines):

> java.util.concurrent.ExecutionException:
> java.lang.IndexOutOfBoundsException: Index: 0

There is no way I can set an `initialValueInWei` to 0, in the case of load().

Any help would be appreciated.
Thanks in advance.

**Comment by conor10** [comment]
Please can you provide the code you are using.
