### ISSUE TITLE
Web3J installation fail on Github Action (CI) with error "Bad Substitution"

### ISSUE THREAD

**Issue by CJ42** [web3j/web3j#1802]
We are currently experiencing an issue in our CI when trying to install Web3j.

Here is a screenshot of the error message.

![image](https://user-images.githubusercontent.com/31145285/197496411-a2f6569d-2442-4842-add5-992f1b52126f.png)

This just happened today and did not happen before. Does anyone know why this is happening?

**Comment by mohamedelshami** [comment]
@CJ42 we've made a change recently to the install script that might cause this issue, which OS is this CI running on, please?

**Comment by CJ42** [comment]
@mohamedelshami it's running on Ubuntu 20.04.5.

Here is the link to the failing CI. 
https://github.com/lukso-network/lsp-smart-contracts/actions/runs/3311493240/jobs/5469708206

You can click on the toggle "Setup Job" to see more details about the OS of the machine the CI is running on.

![image](https://user-images.githubusercontent.com/31145285/197536317-a183cef9-b00e-4bf8-9298-48e0549d635b.png)

**Comment by mohamedelshami** [comment]
@CJ42 thank you!

Please try again now.

**Comment by CJ42** [comment]
Still not working @mohamedelshami . There is a syntax error.
![image](https://user-images.githubusercontent.com/31145285/197550635-337ffa4b-9146-419f-ab56-d6382999c452.png)

**Comment by mohamedelshami** [comment]
@CJ42 this error was due to Dash being the default shell on Ubuntu. 

The installer has been updated now to fix this, please confirm if this works for you now.

**Comment by mohamedelshami** [comment]
@CJ42 I assume this is resolved now. I'm going to close this issue, feel free to reopen it if needed.
