### ISSUE TITLE
Transfer.sendFundsEIP1559 is missing and/or unclear docs

### ISSUE THREAD

**Issue by MarkusKramer** [web3j/web3j#1808]
Online resources talk at several locations about using Transfer.sendFundsEIP1559
* https://docs.web3j.io/4.8.7/transactions/transfer_eth
* https://medium.com/web3labs/announcing-web3j-support-for-eip-1559-3c75c023a599

But in latest Web3j 4.9.4 the method sendFundsEIP1559 is missing.

What is the new way to specify maxFeePerGas / maxPriorityFeePerGas for a raw transaction? Does web3j support it?
It would be great to update the docs.

**Comment by mattiamonari** [comment]
@MarkusKramer I think it is still possiblle to replicate the behaviour of sendFundsEIP1559 using the Transaction1559 class, e.g. :
```
BigInteger maxFeePerGas = BigInteger.valueOf(2000000000L); 
BigInteger maxPriorityFeePerGas = BigInteger.valueOf(1000000000L); 

Transaction1559 transaction = Transaction1559.createTransaction(
    chainId, //ChainId
    nonce, // Nonce
    BigInteger.valueOf(gasLimit), // Gas limit
    recipientAddress, // Recipient address
    value, // Value to send (in wei)
    data, // Transaction data (optional)
    maxPriorityFeePerGas, // Maximum priority fee per gas
    maxFeePerGas // Maximum fee per gas
);
```
