### ISSUE TITLE
 issue for meta-transactions

### ISSUE THREAD

**Issue by lyonnee** [web3j/web3j#1811]
I'm building an application that uses meta-transactions. 

this is solidity function signature
```js
// test contract address on polygonmumbai, and you can see the contract code
// https://mumbai.polygonscan.com/address/0x6447a3582e971a9a46b798fdaab5fc321f238425#code

 struct Asset {
      address token;
      uint256 tokenId;
      uint256 tokenAmount;
      uint8 assetType;
  }

  struct BuyRequest{
      address seller;
      Asset asset;
  }

  struct ForwardRequest {
      address from;
      address to;
      uint256 nonce;
      bytes data;
  }

function buyMatchSell(ForwardRequest calldata forwardReq, bytes calldata signature, BuyRequest calldata buyReq)
{
(execOk, ) = ForwarderUpgradeable(_trustedForwarder).execute(forwardReq, signature);
....
}
```

When I call the function like this, it gets an error
```java
Exchange exchange = Exchange.load(exchangeAddr, web3j, credentials, new DefaultGasProvider());
TransactionReceipt transactionReceipt = exchange.buyMatchSell(forwardRequest, forwardSign.getBytes(), buyRequest).send();
```
the error message
```shell
org.web3j.protocol.exceptions.TransactionException: JsonRpcError thrown with code -32000. Message: only replay-protected (EIP-155) transactions allowed over RPC
```

And I see other solutions to the problem, use RawTransaction.
So I modify Java code like this
```java
RemoteFunctionCall<TransactionReceipt> transactionReceiptRemoteFunctionCall = exchange.buyMatchSell(forwardRequest, forwardSign.getBytes(), buyRequest);
RawTransaction rawTransaction = RawTransaction.createTransaction(
        nonce,
        new BigInteger("10000000000"),
        new BigInteger("1000000"),
        exchangeAddr,
        new BigInteger("100000000000000000"),
        transactionReceiptRemoteFunctionCall.encodeFunctionCall()
);

byte[] signedTx = TransactionEncoder.signMessage(rawTransaction, 80001L, credentials);
Request<?, EthSendTransaction> ethSendTransactionRequest = web3j.ethSendRawTransaction(Numeric.toHexString(signedTx));
EthSendTransaction ethSendTransaction = ethSendTransactionRequest.sendAsync().get();
```
The transaction was successfully sent to the blockchain node, but failed
[https://mumbai.polygonscan.com/tx/0x276bbb43d43904ab0862c36e3a10b9a597a3b58f4dc2a31e75070e7a2ac01425](https://mumbai.polygonscan.com/tx/0x276bbb43d43904ab0862c36e3a10b9a597a3b58f4dc2a31e75070e7a2ac01425)

The methodid is matched, but the coded data was wrong
![image](https://user-images.githubusercontent.com/30852031/199477803-d134e4cb-0851-4d2c-a703-e22ea8623b69.png)

"0303030303030303003030303" It's not the data I put in
![image](https://user-images.githubusercontent.com/30852031/199478404-a8b98e95-c922-4e54-b594-cb72192cdd8d.png)

Please tell me what to do?

**Comment by saulgiordani** [comment]
Did you solve it? If not, could you share the full java code before the the .execute method? Have you tried to use the minimalforward contract by openzeppelin?
