### ISSUE TITLE
Compute Pair Address (e.g. UniSwap or PancakeSwap)

### ISSUE THREAD

**Issue by anscash** [web3j/web3j#1815]
Hi guys,

i am trying to compute a pair of two addresses like in this [example](https://docs.uniswap.org/protocol/V2/guides/smart-contract-integration/getting-pair-addresses)

You can find implementations in other languages with other web3 frameworks like [here](https://stackoverflow.com/questions/69940402/compute-the-lp-address-of-a-token-pair-using-web3-py)

My issue: I am not able to get this work with web3j.

I want to get the (pancakeswap liquidity-)pair address of two tokens on the Binance Smart Chain; WBNB and GREEN TRUST (0xf750a26eb0acf95556e8529e72ed530f3b60f348)

My code:
// PancakeSwap InitCode
`String initCode = "0x00fb7f630766e6a796048ea87d01acd3068e8ff67d078148a3fa3f4a84f69bd5";`

// PancakeSwap Factory
`String factoryAddress = "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73";`
        
// The tokens are ordered alphabetically
`String encoded = new DefaultFunctionEncoder().encodeParameters(Arrays.asList(new Address(tokenA), new Address(tokenB))); 
`
`String salt = Hash.sha3(encoded);
`       
```
String pair = ContractUtils.generateCreate2ContractAddress(
                factoryAddress,
                Numeric.hexStringToByteArray(salt),
                Numeric.hexStringToByteArray(initCode));
```

The result should be **0x3747e3e107223539FD09bb730b055A1f11F78Adf**
But in my case it's **0xd55574ade50bf2339515e0eb12a18132da4c0dfe**

What am i doing wrong?

Thanks a lot for helping me

**Comment by anscash** [comment]
Okay guys, i did it. Can be closed.
Some of you might be interested in the solution:
`private static String computePair(String tokenA, String tokenB) {
        String initCode = "0x00fb7f630766e6a796048ea87d01acd3068e8ff67d078148a3fa3f4a84f69bd5"; // PancakeSwap InitCode
        String factoryAddress = "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73"; // PancakeSwap Factory
        List<Type> addresses;
        if (tokenA.compareTo(tokenB) < 0) {
            addresses = Arrays.asList(new Address(tokenA), new Address(tokenB));
        } else {
            addresses = Arrays.asList(new Address(tokenB), new Address(tokenA));
        }
        String encoded = FunctionEncoder.encodeConstructorPacked(addresses); // The tokens are ordered alphabetically
        String salt = Hash.sha3(encoded);
        final String val = Hash.sha3(FunctionEncoder.encodeConstructorPacked(
                Arrays.asList(new Bytes1(Numeric.hexStringToByteArray("0xff")),
                        new Address(factoryAddress),
                        new Bytes32(Numeric.hexStringToByteArray(salt)),
                        new Bytes32(Numeric.hexStringToByteArray(initCode)))));
        return "0x" + val.substring(val.length() - 40);
    }`

**Comment by aucry** [comment]
Thank you for sharing this @anscash  - it's exactly what I was looking for (and you solved it only 10 days ago too!)
