### ISSUE TITLE
missing json-rpc method

### ISSUE THREAD

**Issue by SuperEdison** [web3j/web3j#1838]
The trace_replayTransaction method is missing

**Comment by mattiamonari** [comment]
If you have a parity client, it should be possible to call the JSON-RPC method 'trace_replayTransaction' like this : 
```
String txHash = "0x...";
//Type of trace, one or more of: "vmTrace", "trace", "stateDiff".
List<String> traceType = Arrays.asList("trace");
FullTraceInfo fullTrace = web3j.parity().traceReplayTransaction(txHash, traceType).send().getFullTraceInfo();
```

Depending on the traceType chosen, the fullTrace will contain different values.  According to [docs](https://openethereum.github.io/JSONRPC-trace-module#trace_replaytransaction) the response should look like this: 

```
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "output": "0x",
    "stateDiff": null,
    "trace": [{
      "action": { ... },
      "result": {
        "gasUsed": "0x0",
        "output": "0x"
      },
      "subtraces": 0,
      "traceAddress": [],
      "type": "call"
    }],
    "vmTrace": null
  }
}
```

From the FullTraceInfo object, you will be able to get output, stateDiff, trace, and vmtrace. Check documentation for further details.
