### ISSUE TITLE
Web3J not compatible with new geth 1.7.1?

### ISSUE THREAD

**Issue by axcrest** [web3j/web3j#185]
This always returns an empty Optional.  

`web3j.ethGetTransactionReceipt("0x6a640d534e1fb06755d22b8af8d3efb368bfe5639c80eb3b10940204d2ecb1eb").send()`

But on rinkeby etherscan the tx hash is valid.  See here:   
[https://rinkeby.etherscan.io/tx/0x6a640d534e1fb06755d22b8af8d3efb368bfe5639c80eb3b10940204d2ecb1eb](url)

This was working fine before [1.7.1.](https://github.com/ethereum/go-ethereum/releases)  Also no new `EthFilter` subscription events are coming through anymore.  I do still get old events that were generated with geth 1.7.0.

**Comment by conor10** [comment]
I've just run the following [ERC20 integration test](https://github.com/web3j/web3j/blob/master/integration-tests/src/test/java/org/web3j/protocol/scenarios/HumanStandardTokenGeneratedIT.java) against Geth/v1.7.1-stable-05101641/darwin-amd64/go1.9.1 without any issues.

Please can you provide some code that you're trying to run? Or the JSON-RPC output?

**Comment by axcrest** [comment]
Thanks for checking.  I figured out the problem.  It had nothing to do with web3j (I'm using version 2.3.0) or geth 1.7.1.  It was due to the Byzantium fork on Oct 9 for Rinkeby and I happened to upgrade to 1.7.1 at about the exact time of the fork!  The solution to the problem was posted here:   [https://www.reddit.com/r/ethereum/comments/758ouw/rinkeby_guide_to_nodes_left_behind_on_how_to/](https://www.reddit.com/r/ethereum/comments/758ouw/rinkeby_guide_to_nodes_left_behind_on_how_to/)

**Comment by conor10** [comment]
Cool.
