### ISSUE TITLE
Polygon Main and Test nets not receiving events with subscribe

### ISSUE THREAD

**Issue by matthew-cameron1** [web3j/web3j#1886]
# Polygon and Mumbai not receiving and block headers.

## Issue description
It seems to be relatively inconsistent however when subscribing to blockFlowable as follows:
`
logger.info("Subscribing to new block headers");

        WebSocketService webSocketService = new WebSocketService(new WebSocketClient(URI.create(System.getenv("NETWORK_WS_URL"))), true);
        Web3j web3j = Web3j.build(webSocketService);

        new Thread(() -> {
            try {
                webSocketService.connect();

                Disposable blockSubscriptionDisposable = web3j.blockFlowable(false).subscribe(blockHeader -> {

                    if (blockHeader.getBlock() == null) {
                        return;
                    }

                    WrappedBlockHeader wrappedBlockHeader = new WrappedBlockHeader(blockHeader.getBlock());
                    this.sqsService.sendObjectToQueue(System.getenv("BLOCK_QUEUE_URL"), wrappedBlockHeader);

                    }, Throwable::printStackTrace);

            } catch (ConnectException e) {
                throw new RuntimeException(e);
            }
        }).start();`
        
No headers are received on the polygon mainnet or testnet. This wasn't always the issue, has worked on and off over the last week.

## Issue context
Goerli and Ethereum seem to work without issue. No matter what provider I use (Infura or QuickNode) subscriptions just don't come in.

**Comment by gtebrean** [comment]
Did few tests and it seems that on Infura and QuickNode the method eth_newBlockFilter is not supported, method which is mandatory in order to be able to do the Flowable subscription.
In our test we manage to find that the method is supported by polygon quickstart https://wiki.polygon.technology/docs/supernets/operate/supernets-quick-start/
