### ISSUE TITLE
MetaTransaction signature fails

### ISSUE THREAD

**Issue by saulgiordani** [web3j/web3j#1889]
# Sign a function with an Account and send it to the Blockchain with another - support ERC-2771

I'm trying the use the Openzeppelin's MetaTransaction contract "MinimalForwarder" with Web3j. You can find the full tutorial here: https://github.com/OpenZeppelin/workshops/tree/master/25-defender-metatx-api
I was able to make it work with web3js, but I'd like to do the same with Web3j and Java.

The main issue is when I execute the MinimalForwarder's function "execute", the signature is not valid according to the contract.

Here is the java code:

```
public TransactionReceipt emitRegistry(Web3j web3j, String signerPrivateKey, String senderPrivateKey, String registryContractAddress, String forwardContractAddress, String addressToSendGreetingsTo) throws Exception {
        final Credentials signerCredentials = Credentials.create(signerPrivateKey);
        final Credentials senderCredentials = Credentials.create(senderPrivateKey);

        BigInteger gasPrice = web3j.ethGasPrice().send().getGasPrice();
        BigInteger gasLimit = DefaultGasProvider.GAS_LIMIT;

        final Function createRegistryfunction = new Function(
                FUNC_CREATEREGISTRY,
                List.of(new Address(160, addressToSendGreetingsTo)),
                Collections.emptyList());
        byte[] encodedFunction = FunctionEncoder.encode(createRegistryfunction).getBytes(StandardCharsets.UTF_8);

        // Send the signed transaction to the network
        Sign.SignatureData signature = Sign.signMessage(encodedFunction, signerCredentials.getEcKeyPair());
        byte[] signatureInBytes = new byte[65];
        System.arraycopy(signature.getR(), 0, signatureInBytes, 0, 32);
        System.arraycopy(signature.getS(), 0, signatureInBytes, 32, 32);
        System.arraycopy(signature.getV(), 0, signatureInBytes, 64, 1);

        MinimalForwarder minimalForwarder = MinimalForwarder.load(forwardContractAddress, web3j, senderCredentials, new DefaultGasProvider());
        BigInteger nonce = minimalForwarder.getNonce(signerCredentials.getAddress()).send();

        // create forward request
        MinimalForwarder.ForwardRequest forwardRequest = new MinimalForwarder.ForwardRequest(
                signerCredentials.getAddress(),
                registryContractAddress,
                BigInteger.ZERO,
                gasLimit,
                nonce,
                encodedFunction
        );

        return minimalForwarder.execute(forwardRequest, signatureInBytes, gasLimit.add(gasPrice)).send();
}
```

I basically send greetings to another contract.

The first issue I've noticed is the encoding function: in web3js the execution of the function
`registry.interface.encodeFunctionData('createRegistry', [addressToSendGreetingsTo])`
returns a different hash than `FunctionEncoder.encode`.

The second is the signature, I'm not able to execute the `minimalForwarder.execute method`, I always receive the message **Revert reason: MinimalForwarder: signature does not match request**. 
Just for info, you can find the MinimalForwarder contract here: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/metatx/MinimalForwarder.sol

**Comment by saulgiordani** [comment]
I've did more tests and tried other ways. One has been to repeat step by step the signer.js class used by OpenZeppelin, you can find it here: https://github.com/OpenZeppelin/workshops/blob/master/25-defender-metatx-api/src/signer.js

This is my java class:

`@UtilityClass
public class Signer {

    public static TransactionReceipt signMetaTxRequest(Credentials signer, MinimalForwarder forwarder, ForwardRequest input, Web3j web3j, ObjectMapper objectMapper) throws Exception {
        String chainId = web3j.netVersion().send().getNetVersion();
        input = buildRequest(forwarder, input);
        EIP712Message toSign = getMetaTxTypedData(chainId, forwarder.getContractAddress());
        Sign.SignatureData signature = Sign.signMessage(objectMapper.writeValueAsBytes(toSign), signer.getEcKeyPair());

        byte[] signatureInBytes = new byte[65];
        System.arraycopy(signature.getR(), 0, signatureInBytes, 0, 32);
        System.arraycopy(signature.getS(), 0, signatureInBytes, 32, 32);
        System.arraycopy(signature.getV(), 0, signatureInBytes, 64, 1);
        return forwarder.execute(input, signatureInBytes, BigInteger.ZERO).send();
    }

    public ForwardRequest buildRequest(MinimalForwarder forwarder, ForwardRequest input) throws Exception {
        input.nonce = forwarder.getNonce(input.from).send();
        return input;
    }

    public EIP712Message getMetaTxTypedData(String chainId, String verifyingContract) {
        List<Entry> forwardRequest = List.of(
                new Entry("from", "address"),
                new Entry("to", "address"),
                new Entry("value", "uint256"),
                new Entry("gas", "uint256"),
                new Entry("nonce", "uint256"),
                new Entry("data", "bytes")
        );
        List<Entry> eip712Domain = List.of(
                new Entry("from", "string"),
                new Entry("version", "string"),
                new Entry("chainId", "uint256"),
                new Entry("verifyingContract", "address")
        );
         EIP712Domain domain = new EIP712Domain(
            "MinimalForwarder",
                 "0.0.1",
                 chainId,
                 new Address(verifyingContract),
                 null
         );
        HashMap<String, List<Entry>> types = new HashMap<>();
        types.put("EIP712Domain", eip712Domain);
        types.put("ForwardRequest", forwardRequest);
        return new EIP712Message(types, "ForwardRequest", null, domain);
    }

    @Getter
    static class Entry {
        private final String name;
        private final String type;

        @JsonCreator
        public Entry(
                @JsonProperty(value = "name") String name,
                @JsonProperty(value = "type") String type) {
            this.name = name;
            this.type = type;
        }
    }

    @Getter
    static class EIP712Domain {
        private final String name;
        private final String version;
        private final Uint256 chainId;
        private final Address verifyingContract;
        private final String salt;

        @JsonCreator
        public EIP712Domain(
                @JsonProperty(value = "name") String name,
                @JsonProperty(value = "version") String version,
                @JsonProperty(value = "chainId") String chainId,
                @JsonProperty(value = "verifyingContract") Address verifyingContract,
                @JsonProperty(value = "salt") String salt) {
            this.name = name;
            this.version = version;
            this.chainId = chainId != null ? new Uint256(new BigInteger(chainId)) : null;
            this.verifyingContract = verifyingContract;
            this.salt = salt;
        }
    }

    @Getter
    static class EIP712Message {
        private final HashMap<String, List<Signer.Entry>> types;
        private final String primaryType;
        private final Object message;
        private final Signer.EIP712Domain domain;

        @JsonCreator
        public EIP712Message(
                @JsonProperty(value = "types") HashMap<String, List<Signer.Entry>> types,
                @JsonProperty(value = "primaryType") String primaryType,
                @JsonProperty(value = "message") Object message,
                @JsonProperty(value = "domain") Signer.EIP712Domain domain) {
            this.types = types;
            this.primaryType = primaryType;
            this.message = message;
            this.domain = domain;
        }

        @Override
        public String toString() {
            return "EIP712Message{"
                    + "primaryType='"
                    + this.primaryType
                    + '\''
                    + ", message='"
                    + this.message
                    + '\''
                    + '}';
        }
    }
}`

The error still persists.

**Comment by saulgiordani** [comment]
It's definitely the recoverSignature solidity function, it returns a different address: not the signer, not the sender, not the forwarderContract, not the deployed registry contract. I've debugged deeply and the address returned by
```
 address signer = _hashTypedDataV4(
            keccak256(abi.encode(_TYPEHASH, req.from, req.to, req.value, req.gas, req.nonce, keccak256(req.data)))
        ).recover(signature);
```
is never initialised during the test

**Comment by saulgiordani** [comment]
Update: I tried to use the method Sign.signedTypedData that was introduced not long ago. Same result, the recovered signer address is different than the signer

**Comment by saulgiordani** [comment]
I finally solved it, thanks @NickSneo for the valuable help!

Apart of using the EIP712Message, the trick has been to pass to the MinimalForwarder.ForwardRequest's data the encodedFunction in bytes, using the Numeric static class instead of the .getBytes() method:

`String encodedFunction = FunctionEncoder.encode(new Function(FUNC_FUNCTOCALL, List.of(param1, ...), Collections.emptyList()));
byte[] encodedFunctionBytes = Numeric.hexStringToByteArray(encodedFunction);`

encodedFunction must be passed as data in EIP712Message -> message -> data
while encodedFunctionBytes to ForwardRequest -> data

Previously, I was creating encodedFunctionBytes in this way
`byte[] encodedFunctionBytes = encodedFunction.getBytes(UTF_8);`

which is wrong!

**Comment by NickSneo** [comment]
> I finally solved it, thanks @NickSneo for the valuable help!
> 
> Apart of using the EIP712Message, the trick has been to pass to the MinimalForwarder.ForwardRequest's data the encodedFunction in bytes, using the Numeric static class instead of the .getBytes() method:
> 
> `String encodedFunction = FunctionEncoder.encode(new Function(FUNC_FUNCTOCALL, List.of(param1, ...), Collections.emptyList())); byte[] encodedFunctionBytes = Numeric.hexStringToByteArray(encodedFunction);`
> 
> encodedFunction must be passed as data in EIP712Message -> message -> data while encodedFunctionBytes to ForwardRequest -> data
> 
> Previously, I was creating encodedFunctionBytes in this way `byte[] encodedFunctionBytes = encodedFunction.getBytes(UTF_8);`
> 
> which is wrong!
> 
> Another advice: make sure the Blockchain network you are using is compatible with eth_signTypedData rpc call. The one I was using at the beginning (ganache) was not compatible. I'm now using BESU from web3j-junit 4.9.7 dependency.

Yeah We got to the point that something is wrong when we are creating forwardRequest with data in bytes and in EIP7112 json giving data as hexadecimal string thats why the signature is failing, we tried different things like sending hexadecimal string only in forwardRequest by changing its signature.
Glad you were able to spot the problem, and found the fix.

Thanks!
