### ISSUE TITLE
Anyone know how to Send ERC20 Coin (OMG) using ethSendRawTransaction please help me

### ISSUE THREAD

**Issue by witchupan** [web3j/web3j#189]
RawTransaction rawTransaction = RawTransaction.createTransaction(nonce, gasPrice, gasLimit, "?", value, "?");
        byte[] signedMessage = TransactionEncoder.signMessage(rawTransaction, credentials);
        String hexValue = Numeric.toHexString(signedMessage);
        System.out.println("hexValue=" + hexValue);

Please help. I don't know how to input param "to" and "data".

**Comment by conor10** [comment]
I'd recommend you use a smart contract wrapper. See the following [ERC20 integration test](https://github.com/web3j/web3j/blob/master/integration-tests/src/test/java/org/web3j/protocol/scenarios/HumanStandardTokenGeneratedIT.java) which uses the [ConsenSys ERC20](https://github.com/ConsenSys/Tokens/tree/master/contracts) implementation.

**Comment by witchupan** [comment]
Thank you for your answer conor10.

**Comment by huahuadashen** [comment]
how to Send ERC20 Coin I do not know how to use the ConsenSys ERC20 implementation

**Comment by huahuadashen** [comment]
The Version  is 3.3.1-android
