### ISSUE TITLE
Improving account import

### ISSUE THREAD

**Issue by fraspadafora** [web3j/web3j#19]
I saw that you are using the Java Scrypt library to calculate the derived key.
I noticed that is not that fast and I found that the Bouncy Castle implementation is better.
Here is the class and method that you can call.

org.bouncycastle.crypto.generators.SCrypt.generate(...)

Hope this can improve the Web3j library.

**Comment by conor10** [comment]
I started off using the Bouncy Castle Scrypt implementation, however migrated to the Java Scrypt library as per the following comments in the [Wallet implementation](https://github.com/web3j/web3j/blob/master/src/main/java/org/web3j/crypto/Wallet.java#L19).

**Note**: we don't use the Bouncy Castle Scrypt implementation org.bouncycastle.crypto.generators.SCrypt, as the following parameter assertion results in failure of the Ethereum reference [Scrypt test vector](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition#scrypt):

```
  // Only value of r that cost (as an int) could be exceeded for is 1
  if (r == 1 && N > 65536)
  {
      throw new IllegalArgumentException("Cost parameter N must be > 1 and < 65536.");
  }
```

**Comment by fraspadafora** [comment]
Oh I didn't know that, I used Bouncy Castle and I have never received that error because my test accounts have r = 8 and N = 262144.

**Comment by conor10** [comment]
Closing, as for the time being I want to ensure that web3j remains compliant with the Scrypt test vector.
