### ISSUE TITLE
Build issue INSTALL_FAILED_NO_MATCHING_ABIS with Google Pixel phone

### ISSUE THREAD

**Issue by JamesSmartCell** [web3j/web3j#190]
We're seeing a new problem when we try to install our Android build on Google Pixel.

The APK installs and works correctly on several other pre 8.0 Android phones, but when we attempt to install on Google Pixel the app fails. 

We traced the problem to NDK code included in Web3j dependencies, namely libscrypt. Do you do a NDK build of the libscrypt library? It appears to be incompatible with Pixel.

**Comment by colourful-land** [comment]
The error message is:
```
Failed to install app-debug.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```
To find out what "native library" exists in the build, I examined the apk file (which uses web3j android) and found this in it:

lib/x86_64/darwin/libscrypt.dylib

What I am going to do next, is to build an almost empty Android project with nothing special except that it uses web3j and see if this problem can be reproduced.

**Comment by colourful-land** [comment]
Okay, this problem definitely lies with some libraries web3j uses.

I created an empty project with nothing in the main activity (literately:
```
import android.app.Activity;

public class MainActivity extends Activity {
}
```
It does nothing but including this line in build.gradle:

    compile 'org.web3j:core-android:2.2.1'

The resulting apk can't be installed with the same INSTALL_FAILED_NO_MATCHING_ABIS

**Comment by conor10** [comment]
Hey gents, good to hear from you. The issue is the Scrypt dependency which I've removed for the upcoming 3.0 release.

See this issue for background https://github.com/web3j/web3j/issues/157

Hoping to get 3.0 out in the next week or so.

Conor

**Comment by colourful-land** [comment]
Would be great to see this released - is the android branch up to date?

**Comment by conor10** [comment]
I’m upgrading the android branch at the moment. Will push out an alpha release once this is done, in preparation for the main 3.0 release.

Conor

**Comment by conor10** [comment]
I've just put 'org.web3j:core:3.0.0-alpha4-android' on Bintray  - please can you take a look at it? The 3.0 release should be almost, if not completely identical.

**Comment by JamesSmartCell** [comment]
Hi Conor, thanks for the update.

We dropped the new library and although there have been some minor changes since the last Android release we were able to shoehorn the new code in and now we have API26 Android 'O' phones working, so yay! Thankyou for the update.

The difference is that the Async calls have been removed from Contract and also RawTransaction is no longer available (although I haven't looked into it much). Is there an alternative? The RawTransaction code was awesome.

You may want to update the command line tools to generate the wrapper code without the Async calls. It'll break existing code that handles those calls but the updates to get it working again are minor.

Cheers,

James

**Comment by conor10** [comment]
RawTransaction has been moved to the crypto package https://github.com/web3j/web3j/blob/master/crypto/src/main/java/org/web3j/crypto/RawTransaction.java.

I'll get the code generator built imminently - just updating documentation first.

**Comment by conor10** [comment]
Hey guys - is this still an issue for you with the 3.0 release?

**Comment by JamesSmartCell** [comment]
Hi Conor, this is working correctly now.

**Comment by conor10** [comment]
👍
