### ISSUE TITLE
4.10.0 seems to require Java 17

### ISSUE THREAD

**Issue by michaelnetter** [web3j/web3j#1907]
# _Issue_title_
4.10.0 seems to require Java 17

## _Issue_description_
It seems that with the latest release 4.10.0, Java 17 is required.

I could not find minimum Java requirements for Web3j.
Can anyone confirm that Java 17 is now required for Web3j versions >= 4.10.0 ?

## _Issue_context_
Calling javap on Web3j.class seems to confirm this.

**4.10.0** 
`javap -verbose Web3j`
```
...
public interface org.web3j.protocol.Web3j extends org.web3j.protocol.core.Ethereum,org.web3j.protocol.rx.Web3jRx,org.web3j.protocol.core.Batcher
  minor version: 0
  major version: 61
...
  ```
  **4.9.8** 
`javap -verbose Web3j`
```
...
public interface org.web3j.protocol.Web3j extends org.web3j.protocol.core.Ethereum,org.web3j.protocol.rx.Web3jRx,org.web3j.protocol.core.Batcher
  minor version: 0
  major version: 52
...
  ```
According to [this](https://www.baeldung.com/java-find-class-version) mapping, class version 61 -> Java 17 while 52 -> Java 8

**Comment by mattiascaricato** [comment]
+1 to downgrade to JDK 11 for backward compatibility

**Comment by franMtProto** [comment]
Created duplicate by mistake. This issue is impacting us, we use JDK 11 and can't migrate at the moment. We are using 4.9.0 as a workaround while this issue is pending.

**Comment by gtebrean** [comment]
We had to upgrade to java 17 in order to can support Besu latest version. We will see we will create a separated version with java 11.

**Comment by gtebrean** [comment]
Because we are using Besu as a valid Java implementation of an EVM client, against which we are validating new EIP features with integration tests, we won't downgrade the java version as will make these 2 incompatible. You can continue to use the old versions but those started to be outdated in terms of EVM compatibility.
