### ISSUE TITLE
only replay-protected (EIP-155) transactions allowed over RPC

### ISSUE THREAD

**Issue by punk8** [web3j/web3j#1908]
when i use the function "Transfer.sendFunds", i got the error like "only replay-protected (EIP-155) transactions allowed over RPC", how can i fixed it? if i can only build the rawTransaction with "chainid" to solve this problem? or may be there is some other ways to do this?

web3j version: 4.8.7

**Comment by sench93** [comment]
`    String hash = Transfer.sendFundsEIP1559(web3j,
                credentials,
                toAddress,
                Convert.toWei(amount, Convert.Unit.WEI),
                Convert.Unit.WEI,
                new BigInteger("70000"),
                Convert.toWei("1", Convert.Unit.GWEI).toBigIntegerExact(),
                Convert.toWei("70", Convert.Unit.GWEI).toBigIntegerExact()
        ).send().getTransactionHash();`
        
        
        If you are using Ethereum  , then this will work.

**Comment by NickSneo** [comment]
@punk8 Did Sench93's suggestion worked for you?

**Comment by NickSneo** [comment]
Closing as it is not an issue, @sench93 provided the correct way for transaction.
