### ISSUE TITLE
Too many methods - 46820 of them

### ISSUE THREAD

**Issue by colourful-land** [web3j/web3j#191]
46820 is the number of methods introduced by putting core-android:2.2.1 in compilation dependency. Given the 65536 methods requirement without multi-dex, that is 71% of available methods are used by webj along. How is the situation with web3j version 3?

**Comment by conor10** [comment]
It should be less, I've removed the unused Solidity types (Ufixed/Fixed) and the modular approach allows you to pick what you want to include in the library.

**Comment by conor10** [comment]
I've just put 'org.web3j:core:3.0.0-alpha4-android' on Bintray  - please can you take a look at it? The 3.0 release should be almost, if not completely idendital.

**Comment by colourful-land** [comment]
> It should be less, I've removed the unused Solidity types (Ufixed/Fixed) and the modular approach allows you to pick what you want to include in the library.

Actually it went up.

An empty android app which has core-andreoid:2.2.1

```
Total methods in app-release-unsigned.apk: 47624 (72.67% used)
Total fields in app-release-unsigned.apk:  19168 (29.25% used)
Total classes in app-release-unsigned.apk:  7220 (11.02% used)
```

An empty Android app with core:3.0.0-alpha4-android

```
Total methods in app-release-unsigned.apk: 55366 (84.48% used)
Total fields in app-release-unsigned.apk:  27583 (42.09% used)
Total classes in app-release-unsigned.apk:  7210 (11.00% used)
```

**Comment by conor10** [comment]
I'm really confused by this. I've deleted [hundres of classes](https://github.com/web3j/web3j/commit/f78a4c583fbd25107787bc2f3ce7084b6db23ae0) for the 3.0 release. Additionally, a lot of classes from core have been moved into dedicated modules that core doesn't depend on, so I cannot see how this number could possibly go up.

How are these numbers calculated?

**Comment by conor10** [comment]
@colourful-land please reopen if this is still an issue.
