### ISSUE TITLE
Unable to send BNB on BSC with Transfer class. 

### ISSUE THREAD

**Issue by sench93** [web3j/web3j#1911]
Trying to send BNB with web3j (4.9.7 version).  I have tried 2 below mentioned methods. 

```
        Credentials credentials = WalletUtils.loadCredentials(wallet.getPassword(), new File(wallet.getPath()));
        Web3j web3j = Web3j.build(new HttpService(URL), 60000, Async.defaultExecutorService());
        return Transfer.sendFundsEIP1559(web3j,
                credentials,
                toAddress,
                Convert.toWei(amount, Convert.Unit.WEI),
                Convert.Unit.WEI,
                new BigInteger("70000"),
                Convert.toWei("1", Convert.Unit.GWEI).toBigIntegerExact(),
                Convert.toWei("5", Convert.Unit.GWEI).toBigIntegerExact()
        ).send().getTransactionHash();
```

```
        Credentials credentials = WalletUtils.loadCredentials(wallet.getPassword(), new File(wallet.getPath()));
        Web3j web3j = Web3j.build(new HttpService(quickNodeURL), 60000, Async.defaultExecutorService());
        return Transfer.sendFunds(web3j,
                credentials,
                toAddress,
                Convert.toWei(amount, Convert.Unit.WEI),
                Convert.Unit.WEI
        ).send().getTransactionHash();
```

First method returns   

> invalid sender

Second method returns following error 

> only replay-protected (EIP-155) transactions allowed over RPC

Now my question is how we can send BNB in BSC chain with web3j.

**Comment by NickSneo** [comment]
Hey @sench93 , as mentioned by @dh1314al 
You will need to give chainId too - https://github.com/web3j/web3j/blob/ac0618c4d38ca780a7781d58255ff8b38626d7fc/crypto/src/main/java/org/web3j/crypto/transaction/type/Transaction1559.java#L39

Another example - https://github.com/web3j/web3j/blob/ac0618c4d38ca780a7781d58255ff8b38626d7fc/crypto/src/test/java/org/web3j/crypto/TransactionEncoderTest.java#L141

Let us know if it works

**Comment by NickSneo** [comment]
Closing ticket as resolved.
