### ISSUE TITLE
New Actions workflow breaks JDK11 compatibility

### ISSUE THREAD

**Issue by franMtProto** [web3j/web3j#1913]
# New Actions workflow breaks JDK11 compatibility
A recent change in the Github Actions build workflow has upgraded the build JDK from 8 to 17. This makes the compiled classes incompatible with older JDK versions.

## Description
JDK17 is fairly new and older versions, specially JDK 11, are still widely used and supported.

For example we started using version `4.10.0` with JDK 11 and on build we get the following error:
```
Error:    bad class file: /home/runner/.m2/repository/org/web3j/crypto/4.10.0/crypto-4.10.0.jar(/org/web3j/crypto/Credentials.class)
Error:      class file has wrong version 61.0, should be 55.0
Error:      Please remove or make sure it appears in the correct subdirectory of the classpath.
```

## Context
The upgrade from JDK 8 to 17 was done here https://github.com/web3j/web3j/commit/5186c3d67fc325597f2cd263813973670ece5b6c and doesn't seem to add anything other than changing the JDK version used for build. Meaning no new feature of JDK 17 (or 11 for that matter) is actually being used. 

## Proposed Solution
Downgrade to JDK 11, still higher than 8, still widely supported and takes advantages from the most performance improvements when comparing JDK8 -> 11 vs JDK 8 -> 17.

**Comment by mattiascaricato** [comment]
+1 to downgrade to JDK 11 for backward compatibility

**Comment by franMtProto** [comment]
Closing the issue as duplicate of https://github.com/web3j/web3j/issues/1907
