### ISSUE TITLE
DuplicateFileException issue on Android Studio 2.3.3 

### ISSUE THREAD

**Issue by fbschon** [web3j/web3j#192]
If I include  <<compile 'org.web3j:core-android:2.2.1'>> in a clean project with an empty MainActivity I get these conflicts:

Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/LICENSE
  	File1: /home/user/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.8.5/b3035f37e674c04dafe36a660c3815cc59f764e2/jackson-databind-2.8.5.jar
  	File2: /home/user/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.8.0/45b426f7796b741035581a176744d91090e2e6fb/jackson-annotations-2.8.0.jar
  	File3: /home/user/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.8.5/60d059f5d2930ccd1ef03535b713fd9f933d1ba7/jackson-core-2.8.5.jar

If I use <<exclude 'META-INF/LICENSE'>> I get "INSTALL_FAILED_NO_MATCHING_ABIS"!

Here is my build.gradle file:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'
    defaultConfig {
        applicationId "com.example.user.bbs4"
        minSdkVersion 23
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
    packagingOptions {
        exclude 'META-INF/LICENSE'
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'org.web3j:core-android:2.2.1'
    testCompile 'junit:junit:4.12'
}

**Comment by ameen192** [comment]
i'm facing it too, did u get any solution??

**Comment by fbschon** [comment]
As I wrote in my initial post:
> If I use <<exclude 'META-INF/LICENSE'>> I get "INSTALL_FAILED_NO_MATCHING_ABIS"!`

**Comment by ameen192** [comment]
well, this might be redundant or unhelpful but , error is for 3 files so put all those 3 lines and, you have put packagingOption tag outside android tag, put in inside android tag..

**Comment by conor10** [comment]
I've just put 'org.web3j:core:3.0.0-alpha4-android' on Bintray  - please can you take a look at it? The 3.0 release should be almost, if not completely identical.

**Comment by 6epreu** [comment]
getting the same error on Android studio 3.0

```
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/LICENSE
  	File1: /Users/sergeybrazhnik/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.8.0/45b426f7796b741035581a176744d91090e2e6fb/jackson-annotations-2.8.0.jar
  	File2: /Users/sergeybrazhnik/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.8.5/b3035f37e674c04dafe36a660c3815cc59f764e2/jackson-databind-2.8.5.jar
  	File3: /Users/sergeybrazhnik/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.8.5/60d059f5d2930ccd1ef03535b713fd9f933d1ba7/jackson-core-2.8.5.jar

```

Using compile ('org.web3j:core:3.1.1-android')

**Comment by 6epreu** [comment]
After I have added this 
```
packagingOptions {
exclude 'META-INF/DEPENDENCIES'
exclude 'META-INF/NOTICE'
exclude 'META-INF/LICENSE'
}
```

I've started to get this error
```
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex '/Users/sergeybrazhnik/.gradle/caches/modules-2/files-2.1/org.web3j/utils/3.1.1-android/f25b5c6ea2e40e163509787662dd9f3f415056e1/utils-3.1.1-android.jar' to '/Users/sergeybrazhnik/REPOS/android/test/MyApplication/app/build/intermediates/transforms/dex/debug/folders/1000/10/utils-3.1.1-android_185103386714345c9f4060fa89eb2cd1de1bf9f5'
```

using compile ('org.web3j:core:3.1.1-android')

**Comment by iikirilov** [comment]
@fbschon @6epreu is this still an issue with web3j android 3.3.1?

**Comment by AlexandrouR** [comment]
issue closed due to inactivity
