### ISSUE TITLE
Android. Play Store. Supported devices limitation (duplicated)

### ISSUE THREAD

**Issue by maxutolen** [web3j/web3j#193]
Hi, everyone. When I add 'compile 'org.web3j:core-android:2.2.1'' in my build.gradle file. I found really strange thing. It started to be supported only on 1 device (according to play store statistic). When I remove this dependency, app become to be supported on 9987 devices. As mentioned here https://github.com/web3j/web3j/issues/157 limitation problem with "wg/scrypt" library. I tried to copy "libscrypt.so" file from "wg/scrypt" library to my 'src/main/java/jniLibs/armeabi' folder, but it didn't work. Help me please with this problem.

**Comment by conor10** [comment]
I've just put 'org.web3j:core:3.0.0-alpha4-android' on Bintray  - please can you take a look at it? The 3.0 release should be almost, if not completely identical.

**Comment by iikirilov** [comment]
@maxutolen is this still an issue with 3.3.1?
