### ISSUE TITLE
web3.logsNotifications cannot listen to multiple contract events at the same time

### ISSUE THREAD

**Issue by shadowseverywhere** [web3j/web3j#1931]
Example 1，This is possible：
    Flowable<LogNotification> logNotifications = web3.logsNotifications(Collections.singletonList("0xdac17f958d2ee523a2206206994597c13d831ec7"),
              Collections.singletonList(transferSignature));

  Example 2，This can not get the monitoring result：
    Flowable<LogNotification> logNotifications = web3.logsNotifications(Collections.singletonList("0xdac17f958d2ee523a2206206994597c13d831ec7"),
               Arrays.asList(transferSignature, approvalSignature));

**Comment by NickSneo** [comment]
Hey @shadowseverywhere , 
Can you plz try this - 

```
Flowable logNotifications = web3.logsNotifications(Arrays.asList("0xdac...", "0xdac..."), Arrays.asList(transferSignature, approvalSignature));
```

**Comment by NickSneo** [comment]
Closing the ticket as resolved, you can reopen it if anyone face any issue.
