### ISSUE TITLE
Issues in web3j repos

### ISSUE THREAD

**Issue by hendrikebbers** [web3j/web3j#1942]
Hi,
I created some issues in smaller web3j repos that received zero reaction so far. Is it better to create such issues directly in the web3j main repo (this one)? I'm not creating this issue since I assume to have you doing free support or something. As I mentioned in the issue I would be happy to work on them but would like to agree on the solution first :)

The issues I'm talking about:

- https://github.com/web3j/web3j-maven-plugin/issues/113
- https://github.com/web3j/web3j-maven-plugin/issues/112
- https://github.com/web3j/web3j-sokt/issues/21

**Comment by gtebrean** [comment]
Sorry for the late answer, first 2 are good. So please go for it. Also once you raise the PRs please ping me on discord (@gdev)

**Comment by EAG-es** [comment]
What is the way to force to the plugin to use a compiler version...

>           <plugin>
>                 <groupId>org.web3j</groupId>
>                 <artifactId>web3j-maven-plugin</artifactId>
>                 <version>4.11.1</version>
>                 <configuration>
>                     <packageName>innui.web3j.generated.contracts</packageName>
>                     <sourceDestination>src/main/java</sourceDestination>
>                     <nativeJavaType>true</nativeJavaType>
>                     <outputFormat>java,abi</outputFormat>
>                     <soliditySourceFiles>
>                         <directory>src/main/solidity</directory>
>                         <includes>
>                             <include>**/*.sol</include>
>                         </includes>
>                     </soliditySourceFiles>
>                     <outputDirectory>
>                         <java>src/main/java</java>
>                         <bin>src/main/bin</bin>
>                         <abi>src/main/abi</abi>
>                     </outputDirectory>
>                     <contract>
>                         <includes>
>                             <include>greeter</include>
>                         </includes>
>                         <excludes>
>                             <exclude>mortal</exclude>
>                         </excludes>
>                     </contract>
>                     <pathPrefixes>
>                         <pathPrefix>dep=../dependencies</pathPrefix>
>                     </pathPrefixes>
>                 </configuration>
>                 <dependencies>
>                     <dependency>
>                         <groupId>org.web3j</groupId>
>                         <artifactId>web3j-sokt</artifactId>
>                         <version>0.3.0</version>
>                     </dependency>
>                 </dependencies>
>             </plugin>            
> 
Because:

>     <properties>
>         <solidity.version>0.8.18</solidity.version>
>     </properties>
> 
Does not work...
And authomatically does not download the compiler (in linux mint) and when I do manually does not use it...

So the pragma: 

> // solidity 0.8.20 introduces the PUSH0(0x5f) opcode which is only supported on ETH mainnet 
> // and not on any other chains. 
> // That's why other chains can't find the PUSH0(0x5f) opcode and throw this error.
> pragma solidity >0.4.13 <0.8.19;
> 

Is not having effect...

Any help is welcome.
