### ISSUE TITLE
Using  sendAsync causes delayed end of Java process

### ISSUE THREAD

**Issue by Fhaohaizi** [web3j/web3j#1943]
# Using org.web3j.protocol.core.Request#sendAsync causes delayed end of Java process

## Steps To Reproduce
    static Web3j web3 = Web3j.build(new HttpService("http://127.0.0.1:7545"));
    public static void main(String[] args) throws IOException, InterruptedException, ExecutionException, TimeoutException {

        CompletableFuture<EthAccounts> ethAccountsCompletableFuture = web3.ethAccounts().sendAsync();
        System.out.println(ethAccountsCompletableFuture.get().getAccounts().size());
        web3.shutdown();
    }
### Actual behavior
When the main method ends, org.web3j.utils.Async#executor is not shutdown. because java.util.concurrent.BlockingQueue#poll（workQueue.poll(keepAliveTime, TimeUnit.NANOSECONDS)） will take more time （max keepAliveTime = 60 s）。
Only then will it be executed shutdownhook in /Users/oker/.m2/repository/org/web3j/core/4.3.0/core-4.3.0.jar!/org/web3j/utils/Async.class:63：
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            shutdown(executor);
        }));

## Environment
_Describe the environment in which the issue occurs_
- Web3j version 4.3.0
- Java or Android version 1.8
- Operating System Mac OS 13.5

## Additional context
"pool-4-thread-1" #16 prio=5 os_prio=31 tid=0x00007fdedf121000 nid=0x5803 waiting on condition [0x000070000ade4000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000076ebe82f0> (a java.util.concurrent.SynchronousQueue$TransferStack)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

**Comment by NickSneo** [comment]
Hey @Fhaohaizi , Can you plz try with latest web3j version 4.10.2 if it still happens?

**Comment by Fhaohaizi** [comment]
ok，I will try this week. tks

**Comment by Fhaohaizi** [comment]
No, this version does not solve it.

**Comment by NickSneo** [comment]
Hey @Fhaohaizi ,

The current await termination time is set to 60 secs before the executorService shutdown - https://github.com/web3j/web3j/blob/ac0618c4d38ca780a7781d58255ff8b38626d7fc/core/src/main/java/org/web3j/utils/Async.java#L75

```
/**
     * Shutdown as per {@link ExecutorService} Javadoc recommendation.
     *
     * @param executorService executor service we wish to shut down.
     */
    private static void shutdown(ExecutorService executorService) {
        executorService.shutdown();
        try {
            if (!executorService.awaitTermination(60, TimeUnit.SECONDS)) {
                executorService.shutdownNow();
                if (!executorService.awaitTermination(60, TimeUnit.SECONDS)) {
                    System.err.println("Thread pool did not terminate");
                }
            }
        } catch (InterruptedException ie) {
            executorService.shutdownNow();
            Thread.currentThread().interrupt();
        }
    }
 ```
    
    
We will let it be default value and wont be changing it, if you wish you can modify and use as per your use case.
Thanks!

**Comment by Fhaohaizi** [comment]
OK，tks。
