### ISSUE TITLE
EIP-191 hash witch web3j

### ISSUE THREAD

**Issue by anscash** [web3j/web3j#1944]
"The signature is calculated by taking the [EIP-191](https://eips.ethereum.org/EIPS/eip-191) hash of the json body encoded as UTF-8 bytes. Here's an example using ethers.js:"
from: [Flashbots Documentation](https://docs.flashbots.net/flashbots-auction/searchers/advanced/rpc-endpoint#authentication)

How do i do this with web3j?

Thanks a lot!

**Comment by gtebrean** [comment]
@anscash sorry for late answer but you can do it the following way:
1. Calculate the body hash by using the Hash.sha3() method corresponding to the input parameter. 
2. Sign the value resulted at 1. by using this approach https://blog.web3labs.com/web3development/how-to-sign-messages-with-web3j.
3. Append the account address with resulted signature.

Hope it will help, also you can find many approaches by looking in to web3j code in terms of hashing and signature. Feel free to reopen it if unclear.
