### ISSUE TITLE
deprecated function

### ISSUE THREAD

**Issue by liukai1055** [web3j/web3j#1948]
Hi:
protected Contract(
            String contractBinary,
            String contractAddress,
            Web3j web3j,
            Credentials credentials,
            BigInteger gasPrice,
            BigInteger gasLimit)
This function is deprecated, Is it no longer usable？I need help.  Thank you

**Comment by liukai1055** [comment]
I used the version 3.20

**Comment by gtebrean** [comment]
@liukai1055 Are you asking because now you migrated to last Web3J version?

**Comment by gtebrean** [comment]
I took a look and yes, that one is deprecated because ContractGasProvider was introduced in 2018, and we recommend to use that one. I will close this, feel free to reopen it if you have any doubts.
