### ISSUE TITLE
how to encode struct[][]

### ISSUE THREAD

**Issue by daxuanxiaoyou** [web3j/web3j#1949]
# _Issue_title_
how to encode struct[][]

## _Issue_description_
i.e:
{
            "components":[
                {
                    "internalType":"uint256",
                    "name":"orderIndex",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"itemIndex",
                    "type":"uint256"
                }
            ],
            "internalType":"struct FulfillmentComponent[][]",
            "name":"",
            "type":"tuple[][]"
        }

## _Issue_context_
how to encode this tuple[][]

**Comment by daxuanxiaoyou** [comment]
i try to this with web3j：

/*
* offerFulfillments = [[{"orderIndex":0,"itemIndex":0}],[{"orderIndex":1,"itemIndex":0}]]
*/
List<Type> encodedParameters = new ArrayList<>();
encodedParameters.add(
                new DynamicArray<DynamicArray>(
                        DynamicArray.class,
                        offerFulfillments.stream().map(ov ->
                                new DynamicArray<>(
                                        DynamicStruct.class,
                                        ov.stream().map(iv ->
                                                new DynamicStruct(
                                                        new Uint256(iv.getOrderIndex()),
                                                        new Uint256(iv.getItemIndex()))
                                        ).collect(Collectors.toList())
                                )
                        ).collect(Collectors.toList())
                )
        );
return FunctionEncoder.encodeConstructor(encodedParameters);

the encode data is :
0000000000000000000000000000000000000000000000000000000000000020
0000000000000000000000000000000000000000000000000000000000000002
0000000000000000000000000000000000000000000000000000000000000001 -- the 1 
0000000000000000000000000000000000000000000000000000000000000020 -- ？？
0000000000000000000000000000000000000000000000000000000000000000 -- 0
0000000000000000000000000000000000000000000000000000000000000000 -- 0
0000000000000000000000000000000000000000000000000000000000000001 -- the 2
0000000000000000000000000000000000000000000000000000000000000020 -- ？？
0000000000000000000000000000000000000000000000000000000000000001 -- 1
0000000000000000000000000000000000000000000000000000000000000000 -- 0

============================================================================================but i try it with web3js:

abi = {
            "components":[
                {
                    "internalType":"uint256",
                    "name":"orderIndex",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"itemIndex",
                    "type":"uint256"
                }
            ],
            "internalType":"struct FulfillmentComponent[][]",
            "name":"",
            "type":"tuple[][]"
        };

const functionSignature = web3.eth.abi.encodeFunctionCall(abi, [offerFulfillments]);

the i get the encode data is 

0000000000000000000000000000000000000000000000000000000000000020
0000000000000000000000000000000000000000000000000000000000000002  -- total 2
0000000000000000000000000000000000000000000000000000000000000040 -- offset of 1
00000000000000000000000000000000000000000000000000000000000000a0 -- offset of 2
0000000000000000000000000000000000000000000000000000000000000001 -- the 1
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000001  -- the 2
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000000

and web3js is right;

so ,how to get the right data with web3j

**Comment by gtebrean** [comment]
@daxuanxiaoyou I tried to reproduce your web3js result and I couldn't. I encodeFunctionCall used from web3-eth-abi 4.1.1 but it seems is not compiling with your input, json is not according to AbiFunctionFragment format. I assume you used an older version of web3. Please could you share the web3 version and your test?

**Comment by daxuanxiaoyou** [comment]
Thanks,man. Which version resolve this BUG?

**Comment by gtebrean** [comment]
> Thanks,man. Which version resolve this BUG?

not released yet, will be part of 4.10.4
