### ISSUE TITLE
Would like to override the Sign.sign(byte[] transactionHash, BigInteger privateKey) method

### ISSUE THREAD

**Issue by eztierney** [web3j/web3j#195]
I would like to override the behavior of the `sign` method in `org.web3k.crypto.Sign`(I'd like to have the signing done out of process), but there is no easy way to override the static method without copying most of the `Sign` and `TransactionEncoder` classes.

One possible solution would be to move the `sign` method to the `ECKeyPair` class, which could then be extended and overridden to change the behavior. Happy to put up a PR if this seems like an ok idea.

**Comment by conor10** [comment]
Hey @eztierney, out of process signing would definitely be useful. Go for it!

**Comment by ZhiyuHelloWorld** [comment]
👍
