### ISSUE TITLE
https certificate is invalid

### ISSUE THREAD

**Issue by Azleal** [web3j/web3j#1965]
# https certificate is invalid
https://internal.services.web3labs.com/ cert invalid

## error when installing web3j-cli 
![image](https://github.com/web3j/web3j/assets/7901126/d0c6998e-3cc0-438e-95e7-1b10d1ec0ce3)

if you visit https://internal.services.web3labs.com/ directlt from chrome, you'll see that the cert is invalid

**Comment by NickSneo** [comment]
After pressing enter or continuing you are able to install web3j-cli right?

**Comment by NickSneo** [comment]
Will fix this issue, it is related to web3j installer script

**Comment by Azleal** [comment]
> Will fix this issue, it is related to web3j installer script

yeah, it occurred during executing the installer script. using `--insecure` flag is a workaround, it's not secure though.

**Comment by Azleal** [comment]
> After pressing enter or continuing you are able to install web3j-cli right?
> 
> ![image](https://user-images.githubusercontent.com/32759145/269283559-116fe945-fd12-4232-8e48-70f491c8749a.png)

no, after pressing enter, it just quit.

**Comment by NickSneo** [comment]
We have merged the fix -  https://github.com/web3j/web3j-installer/pull/6
Plz try again now, it should work. Also plz make sure you have java 17 or higher installed

Closing this ticket.
