### ISSUE TITLE
Structures without members are not encoded properly

### ISSUE THREAD

**Issue by Supertuba12** [web3j/web3j#1967]
# Structures without members are not encoded properly
The JSON RPC API specification for 'eth_signTypedData_v4' does not
explicitly state that the required struct 'EIP712Domain' has to define
any members [1]. The current implementation cannot correctly encode
such a structure, as it assumes that at least one member has been
parsed and added to the struct's string representation.

[1] https://eips.ethereum.org/EIPS/eip-712#specification-of-the-eth_signtypeddata-json-rpc

## Steps To Reproduce
Pass a valid structured data object where a type structure lacks a member:

```{json}
{
  "types": {
    "EIP712Domain": []
  },
  "primaryType": "EIP712Domain",
  "domain": {},
  "message": {}
}
```

### Expected behavior
The internal function `encodeStruct` should return `"EIP712Domain()"` when encoding `EIP712Domain`.
### Actual behavior
The internal function returns `"EIP712Domain)"`

## Environment
- Web3j version: First found using the latest android release `4.8.8-android`. Reproduced on master `ac0618c4d38ca780a7781d58255ff8b38626d7fc`

**Comment by NickSneo** [comment]
Thanks for reporting and contributing.

**Comment by NickSneo** [comment]
PR merged
