### ISSUE TITLE
Is there a way to send a sequence of transactions to a contract?

### ISSUE THREAD

**Issue by joh-mue** [web3j/web3j#204]
I would like to send a sequence of transactions to a Smart Contract with the web3j compiled java class of my contract. Unfortunately there is no way to increase the nonce and thus all subsequent transactions are competing to be mined.

Is this even possible and if it is already how can I achieve this?

thx

**Comment by conor10** [comment]
Yes, see https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/tx/FastRawTransactionManager.java & for usage of it https://github.com/web3j/web3j/blob/master/integration-tests/src/test/java/org/web3j/protocol/scenarios/FastRawTransactionManagerIT.java
