### ISSUE TITLE
Expose additional behaviors from auto-generated contract classes for use with ethGetLogs

### ISSUE THREAD

**Issue by brianlenz** [web3j/web3j#205]
We are building a token sale dapp. The smart contract has internal event logging that we will be using to log ether contribution transactions.

We have a separate web app that needs to pull the logs from the blockchain (via `eth_getLogs`) to do some data processing on them. The web3j command line tool to auto-generate a Java `Contract` class implementation from a compiled smart contract is brilliant. The default auto-generated class provides handy ways to create Filters for Events, but there is no good way (that I can find, anyway) to extract the events from `ethGetLogs`.

Some ideas for improvement include:

1) The `ethLogObservable` mapping function that translates the `Log` data into the struct-like data types would be super handy for externally processing `Log` objects.

2) `Contract.extractEventParameters()` is protected and thus can not be used externally. It may not be needed if item 1 is implemented above, but without 1, we'd need this in order to be able to extract the data.

3) The `Event` type definition would be useful to expose for each event defined in the contract so that it doesn't need to be duplicated externally for use with `ethGetLogs`.

As it stands right now, in order to use `ethGetLogs` we have to manually copy/paste a lot of the scaffolding code from the contract in order to be able to process the data.

**Comment by brianlenz** [comment]
I don't know if this is going to be helpful at all, but here's an example of a custom method that we are using to use `ethGetLogs`. I'm not sure of the best abstraction for this, but some of the ideas above would definitely help a lot. 90% of the code here is duplicated from the auto-generated contract and the `Contract` class. The only custom code really is for invoking `ethGetLogs` and for our case of adding an extra topic filter.

```
// method is largely based on auto-generated code for:
// public Observable<ReceivedETHEventResponse> receivedETHEventObservable(DefaultBlockParameter startBlock, DefaultBlockParameter endBlock) {
public static List<Crowdsale.ReceivedETHEventResponse> getContributionTransactions(Web3j web3j, DefaultBlockParameter startBlock, DefaultBlockParameter endBlock, String contractAddress, String filterByAddress) throws IOException, CipherException, ExecutionException, InterruptedException {
    //////////////////////////////////
    // START from receivedETHEventObservable
    //////////////////////////////////
    final Event event = new Event("ReceivedETH",
            Arrays.<TypeReference<?>>asList(),
            Arrays.<TypeReference<?>>asList(new TypeReference<Address>() {}, new TypeReference<Uint256>() {}, new TypeReference<Uint8>() {}));
    EthFilter filter = new EthFilter(startBlock, endBlock, contractAddress);
    filter.addSingleTopic(EventEncoder.encode(event));
    //////////////////////////////////
    // END from receivedETHEventObservable
    //////////////////////////////////
	
    //////////////////////////////////
    // START custom topic filter
    //////////////////////////////////
    filter.addSingleTopic("0x000000000000000000000000" + Numeric.cleanHexPrefix(filterByAddress));
    //////////////////////////////////
    // END custom topic filter
    //////////////////////////////////

    //////////////////////////////////
	// ethGetLogs replacement for web3j.ethLogObservable(filter).map()
    //////////////////////////////////
    EthLog ethLog = web3j.ethGetLogs(filter).sendAsync().get();
    if(ethLog.getError()!=null) {
        return Collections.emptyList();
    }
	
    List<Crowdsale.ReceivedETHEventResponse> results = new LinkedList<>();
    for(EthLog.LogResult logResult : ethLog.getLogs()) {
        Log log = (Log)logResult.get();

        //////////////////////////////////
        // START extractEventParameters(Event event, Log log)
		//////////////////////////////////
        List<String> topics = log.getTopics();
        if (!topics.get(0).equals(encodedEventSignature)) {
            continue;
        }

        List<Type> indexedValues = new ArrayList<>();
        List<Type> nonIndexedValues = FunctionReturnDecoder.decode(
                log.getData(), event.getNonIndexedParameters());

        List<TypeReference<Type>> indexedParameters = event.getIndexedParameters();
        for (int i = 0; i < indexedParameters.size(); i++) {
            Type value = FunctionReturnDecoder.decodeIndexedValue(
                    topics.get(i + 1), indexedParameters.get(i));
            indexedValues.add(value);
        }
        EventValues eventValues = new EventValues(indexedValues, nonIndexedValues);
        //////////////////////////////////
        // END extractEventParameters(Event event, Log log)
		//////////////////////////////////
		
	    //////////////////////////////////
		// START web3j.ethLogObservable(filter).map() -> call()
	    //////////////////////////////////
        Crowdsale.ReceivedETHEventResponse typedResponse = new Crowdsale.ReceivedETHEventResponse();
        typedResponse.backer = (Address) eventValues.getIndexedValues().get(0);
        typedResponse.amount = (Uint256) eventValues.getNonIndexedValues().get(0);
        typedResponse.step = (Uint8) eventValues.getNonIndexedValues().get(1);
	    //////////////////////////////////
		// END web3j.ethLogObservable(filter).map() -> call()
	    //////////////////////////////////

        results.add(typedResponse);
    }
    return results;
}
```

**Comment by conor10** [comment]
I agree this is definitely useful functionality.

There was a piece of functionality that got removed in 2.3.1 accidentally which may have contributed to this, which has since been fixed for 3.0 - see the following [commit](https://github.com/web3j/web3j/commit/8ab165cbd3efe3c78139c228f07f0c2ed708e672#diff-4a12c2f44bc352957031613fd7e82c7aR49). 

All being well with this update, if you provide a DefaultBlockParameter of block 0/earliest to the contract event observable, *ethGetFilterLogs* in the LogFilter should provide the log history when it's first called.

Please can you update this issue once the 3.0 release is out in the next few days?

**Comment by brianlenz** [comment]
Hi @conor10 , thanks for the follow-up! For us, we are using Infura, so we are not able to use filters. We just want to create a one-time "filter" to use with `ethGetLogs`. As such, I'm not sure the commit you referenced would necessarily address the issues (since we won't be referencing an existing filter by ID).

Does that make sense?

**Comment by conor10** [comment]
Yes it does.

**Comment by xaviarias** [comment]
Hi @brianlenz! I made a PR for this enhancement so you can specify a filter to observe events. For instance the event: 

    event Modified(string indexed oldGreetingIdx, string indexed newGreetingIdx,
                   string oldGreeting, string newGreeting);

would generate the constant 

    public static final Event MODIFIED_EVENT = new Event("Modified", 
            Arrays.<TypeReference<?>>asList(new TypeReference<Utf8String>() {}, new TypeReference<Utf8String>() {}),
            Arrays.<TypeReference<?>>asList(new TypeReference<Utf8String>() {}, new TypeReference<Utf8String>() {}));

and the methods:

    public Observable<ModifiedEventResponse> modifiedEventObservable(EthFilter filter) { ... }

    public Observable<ModifiedEventResponse> modifiedEventObservable(DefaultBlockParameter startBlock, DefaultBlockParameter endBlock) { ... }

Would this help for what you need to implement? How could this be improved?

**Comment by brianlenz** [comment]
Hi @xaviarias! Thanks for the follow-up and for your contribution to FOSS. It's possible that could help with the scenario I originally presented. We've since moved on beyond that issue onto other projects, so we no longer have this specific need, but perhaps others actively involved in the project can provide some insight as to the usefulness.

**Comment by yuriymyronovych** [comment]
@brianlenz I might have misunderstood you, but there is a fairly easy workaround to get the specific logs you want with existing implementation.
For example here is how we get ONLY 'Transfer' logs for our contract.

```
Observable<EthLog> logsObs = web3j.ethGetLogs(new EthFilter(fromBlock, DefaultBlockParameterName.LATEST, walletAddress)).observable();
        return logsObs.map(logs -> {
            WalletLibrary remoteContract = WalletLibrary.load(walletAddress, web3j, (Credentials) null, BigInteger.ZERO, BigInteger.ZERO);
            TransactionReceipt receipt = new TransactionReceipt();
            receipt.setLogs(logs);
            return remoteContract.getTransferEvents(receipt);
        });
```
