### ISSUE TITLE
sha3 Event hash consistency issue

### ISSUE THREAD

**Issue by brianlenz** [web3j/web3j#209]
Say you have an event:

```
event ReceivedETH(address indexed backer, uint amount, uint8 indexed step);
```

`EventEncoder.encode` won't create the proper sha3 hash for this Event due to the fact that there is an indexed property after an unindexed property. `EventEncoder.encode`orders the parameters by `indexed` first, which results in the hash being:

```
ReceivedETH(address,uint8,uint)
```

but the proper hash used in the Event's tokens will be based on:

```
ReceivedETH(address,uint,uint8)
```

I am admittedly new to Ethereum, but based on how I've seen everything working on the blockchain, it seems like this is a bug in Web3j?

To workaround the issue, we just rearranged the parameters on the event definition so that it is compatible with the forced ordering of Web3j:

```
event ReceivedETH(address indexed backer, uint8 indexed step, uint amount);
```

**Comment by conor10** [comment]
Hi @brianlenz, that sounds correct.

**Comment by 4ntoine** [comment]
Any fixes?

**Comment by mushketyk** [comment]
@conor10 I've implemented a fix by changing the `Event` class constructor to:
```
    public Event(String name, List<TypeReference<?>> parameters) {
        this.name = name;
        this.parameters = convert(parameters);
    }
```

But now I need to re-generate `ENS` and `PublicResolver` contracts, but I can't find how to do this. What commands do you use for this?

**Comment by 4ntoine** [comment]
Still open bug?
