### ISSUE TITLE
Configure the way hex numbers are encoded

### ISSUE THREAD

**Issue by 4ntoine** [web3j/web3j#217]
I'm testing with TestRpc and having similar issue as here:
https://ethereum.stackexchange.com/questions/15824/a-problem-with-filters-and-events-web3j-testrpc-sos:

    FilterSubprovider - no filter with that id: 0x2

It's not an issue in web3j but it would be great to have any settings to encode 0x3 as 0x03. Thanks

**Comment by 4ntoine** [comment]
https://github.com/web3j/web3j/pull/220

**Comment by conor10** [comment]
This should be fixed by https://github.com/web3j/web3j/pull/284.
