### ISSUE TITLE
No smart contract events received

### ISSUE THREAD

**Issue by 4ntoine** [web3j/web3j#218]
Smart contract:

```
pragma solidity ^0.4.0;
contract EventsContract {
    address owner;
    uint256 payload_;

    event PayloadEvent(uint256 payload);
    
    function EventsContract(uint256 payload) public {
        owner = msg.sender;
        payload_ = payload;
    }
    
    function check() public {
        PayloadEvent(payload_);
    }
}
```

Smart contract wrappers are generated with web3j maven plugin 0.1.3 and installed solidity compiler 0.4.18:

> [INFO] ------------------------------------------------------------------------
> [INFO] Building integration-tests 1.0
> [INFO] ------------------------------------------------------------------------
> [INFO] 
> [INFO] --- web3j-maven-plugin:0.1.3:generate-sources (default-cli) @ integration-tests ---
> [INFO] process 'EventsContract.sol'
> [INFO] Solidity Compiler found
> [INFO] 	Built Class for contract 'EventsContract'
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 1.633 s
> [INFO] Finished at: 2017-11-05T01:06:27+05:00
> [INFO] Final Memory: 16M/306M
> [INFO] ------------------------------------------------------------------------

Here is test method:

    private BigInteger eventPayload;

    @Test
    public void testEvent() throws Exception {
        Web3j web3 = Web3j.build(new HttpService());
        Credentials credentials = Credentials.create(DEVELOPER_PRIVATE_KEY);

        final BigInteger payload = BigInteger.valueOf(7L);

        EventsContract contract = EventsContract.deploy(
            web3,
            credentials,
            BigInteger.valueOf(3000000L),
            BigInteger.valueOf(3000000L),
            payload)
            .send();

        assertNotNull(contract);

        CountDownLatch countDownLatch = new CountDownLatch(1);

        Subscription subscription = contract.payloadEventEventObservable(
            DefaultBlockParameterName.EARLIEST,
            DefaultBlockParameterName.LATEST)
            .subscribe(response -> {
                eventPayload = response.payload;
                countDownLatch.countDown();
            });

        contract.check().send();

        if (!countDownLatch.await(10, TimeUnit.SECONDS))
            fail("No event is fired");

        subscription.unsubscribe();
        assertEquals(payload, eventPayload);
    }

The test fails:

    > junit.framework.AssertionFailedError: No event is fired

I'm testing with TestRPC, here is the log:

> eth_getTransactionCount
> eth_sendRawTransaction
> 
>   Transaction: 0xb5e6023afaf01587840e03f1455ccdb58cc41c65e23b8852dc0871fe39a32952
>   Contract created: 0x2e9c5a28a1946d66d0a558c1f9750d7e851bda03
>   Gas usage: 145959
>   Block Number: 33
>   Block Time: Sun Nov 05 2017 00:57:26 GMT+0500 (+05)
> 
> eth_getTransactionReceipt
> eth_newFilter
> eth_getFilterChanges
> eth_getFilterLogs
> eth_getTransactionCount
> eth_sendRawTransaction
> 
>   Transaction: 0xd546e8e5b79b33ad201b85eb20fa0eb2563b79c7ca7ff53ad2373adb10410e40
>   Gas usage: 22651
>   Block Number: 34
>   Block Time: Sun Nov 05 2017 00:57:26 GMT+0500 (+05)
> 
> eth_getTransactionReceipt

**Comment by 4ntoine** [comment]
The contract obviously works in Remix:
<img width="1286" alt="2017-11-05 1 04 30" src="https://user-images.githubusercontent.com/846671/32409030-6d4bb012-c1c5-11e7-95e8-494eee212af2.png">

**Comment by 4ntoine** [comment]
However, if i using method (not listener) with TransactionReceipt as argument i can get the event:

    List<EventsContract.PayloadEventEventResponse> response = contract.getPayloadEventEvents(receipt);
    assertEquals(1, response.size());

**Comment by 4ntoine** [comment]
BTW it does not work with TestRpc but works with Geth! So probably it's not web3j issue but TestRpc or RestRpc+web3j

**Comment by conor10** [comment]
Unfortunately test-rpc does not support filters.

**Comment by vingorius** [comment]
Even in testrpc, i made event and test it with web3.js. 
there's no problem. 
So i don't understand testrpc does not support filters.
