### ISSUE TITLE
cannot find org.web3j.crypto

### ISSUE THREAD

**Issue by tianleios** [web3j/web3j#219]
`<dependency>
      <groupId>org.web3j</groupId>
      <artifactId>core</artifactId>
      <version>3.0.1</version>
    </dependency>
` 
i cannot find   org.web3j.crypto package
in org.web3j:utils:3.0.1    org.web3j.crypto only find Hash.java.   have not other file.

**Comment by 4ntoine** [comment]
Did you try to add dependency to crypto?

        <dependency>
            <groupId>org.web3j</groupId>
            <artifactId>crypto</artifactId>
            <version>3.0.1</version>
        </dependency>

**Comment by conor10** [comment]
Following the modular releases, it appears that you need to explicitly add all of the dependencies as per @4ntoine's comment. I'm looking to get this fixed up, as it wasn't the intention to be quite this granular. I.e. core should pull in crypto.

**Comment by conor10** [comment]
@tianleios please can you tell me if you get the same problem with web3j 3.0.2?

**Comment by conor10** [comment]
It appears to be caused by the following Gradle [issue](https://github.com/gradle/gradle/issues/1118). I'm in the process of upgrading to version 4.3. You shouldn't have this issue if you pull the artefacts down from Nexus, only Bintray.

**Comment by tianleios** [comment]
i cannot find web3j 3.0.2 in maven,    have not release.

**Comment by conor10** [comment]
It's definitely available - see http://search.maven.org/#artifactdetails%7Corg.web3j%7Ccore%7C3.0.2%7Cjar

**Comment by conor10** [comment]
Upgrading to Gradle 4.3 has fixed this issue. web3j 3.1.0 shouldn't suffer from this problem.
