### ISSUE TITLE
Use chainId when signing a transaction

### ISSUE THREAD

**Issue by adridadou** [web3j/web3j#22]
Have a look at the issue I've created on web3js
https://github.com/ethereum/web3.js/issues/526

Basically the issue is that the way tx are signed has changed

**Comment by conor10** [comment]
Thanks for the heads up. Will update the transaction object to support this.

Is it causing you any issues currently? From what Vitalik has said & the previous transaction signing mechanism should still be fine in the meantime - I didn't have any issues using it myself during last week post HF.

**Comment by yaoyu26** [comment]
great! this project help me, i will use it.

**Comment by conor10** [comment]
This has been implemented. However, it's not enabled in the web3j smart contract wrappers. I'd rather wait until we have a JSON-RPC call or similar for obtaining the chainId, so users don't have to provide the chainId web3j.

**Comment by conor10** [comment]
The RawTransactionManagers used by smart contract wrappers as of upcoming version 1.2 allows you to specify the chain id on all transactions.
