### ISSUE TITLE
Support direct import of contracts compiled with Truffle

### ISSUE THREAD

**Issue by eepstein** [web3j/web3j#226]
Better support for a hybrid dev env in which Truffle is used for the Solidity code including testing and deployment.

This would allow, for example, access to the deployed addresses without manual intervention.

It would also mean that the .abi and .bin inputs would be precisely those generated and used by Truffle.

As a side-effect, keeping track of addresses would allow support for looking up contract addresses on the generated instance - though integration with web3j's deploy mechanism means those values would not survive restart but would revert to the values in the generated code.

**Comment by eepstein** [comment]
I'm implemented this in a fork, along with tests.
My build is failing in :codegen:checkstyleMain
I've got the google style xml installed and ran a full reformat for the changed and new files.
bubkis.
Is there a formal .xml file for us?

**Comment by eepstein** [comment]
Hmm.  Seems there's a requirement that AbiDefinition's equal and hashCode methods include all the ivars.  But, given that Solidity functions have flags that don't factor into the uniqueness requirements of the function (e.g., you can add "pure" to a function but that doesn't change the function's uniqueness, which is determined solely by name + argument types, except for constructors where the uniqueness is by name).  so, enforcing this in Java seems not to line up with the thing being modeled.

**Comment by conor10** [comment]
Implemented in https://github.com/web3j/web3j/pull/228.
