### ISSUE TITLE
web3j.personalUnlockAccount is undefined

### ISSUE THREAD

**Issue by mslinn** [web3j/web3j#227]
From the [docs](https://docs.web3j.io/getting_started.html#transactions):
```
Admin web3j = Admin.build(new HttpService());
PersonalUnlockAccount personalUnlockAccount = web3j.personalUnlockAccount("0x000...", "a password").sendAsync().get();
```

The Scala compiler says:
```
val personalUnlockAccount: PersonalUnlockAccount = web3j.personalUnlockAccount("0x000...", "a password").sendAsync.get
Error:(38, 60) value personalUnlockAccount is not a member of org.web3j.protocol.Web3j
  val personalUnlockAccount: PersonalUnlockAccount = web3j.personalUnlockAccount("0x000...", "a password").sendAsync().get()
```

**Comment by eepstein** [comment]
I think you are correct.
Is this meant as a feature request ?

**Comment by mslinn** [comment]
Thank you, I missed that. The docs are clear, I just did not read them properly. This is not a feature request. 

I have tried to work through all the docs, and I have a few more questions:
1. With regards to [the wallet directory](https://github.com/mslinn/web3j-scala/blob/master/demo/DemoSmartContracts.scala#L38). Would you mind suggesting to me how to compute the wallet directory?
1. Once the wallet directory is known, [how can the presence of a wallet be determined](https://github.com/mslinn/web3j-scala/blob/b7e9dfa320beb3f0c3ebe2e4c3fb0e26210c5975/demo/DemoTransaction.scala#L37)?
1. Seems the Ethereum directory [depends on the network used](https://github.com/mslinn/web3j-scala/blob/2f59fb1713a6f96953f9f5b044e268c8fa0e46cc/demo/Demo.scala#L43). Is there a good way of computing or discovering the Ethereum directory?

Thank you!

**Comment by eepstein** [comment]
Maybe those belong on gitter?
And this issue can be closed ?

**Comment by eepstein** [comment]
yes,
the name is based on the network name. 
i’ve added an enum for that which maps to the network id.  will see if conor approves the pull request.
