### ISSUE TITLE
Internal exception when in function that is returning Tuple require() fails

### ISSUE THREAD

**Issue by 4ntoine** [web3j/web3j#229]
I'm having the Solidity function that assert some requirement and return tuple:

```
    function getVariablePledge(uint featureKey) public
        forFeature(featureKey)
        constant returns (uint256, uint256)
    {
        Feature memory feature = features[featureKey];
        require(feature.pledgeType == PledgeType.Variable);
        return (feature.variablePledge.minPledge, feature.variablePledge.maxPledge);
    }
```

If requirement assertion fails i expect `send()` to throw an Exception.
However invocations fails with internal exception (`java.lang.IndexOutOfBoundsException: Index: 0`) as  return type values list is empty (see `results` is empty so `results.get(0)` fails):

<img width="760" alt="2017-11-09 11 55 15" src="https://user-images.githubusercontent.com/846671/32592451-8bf34dda-c545-11e7-944c-7bcb4dc446e7.png">

If you see RPC call for some reason there is no `error` (see `null`) but `result` looks strange (`0x`):

<img width="777" alt="2017-11-09 11 54 17" src="https://user-images.githubusercontent.com/846671/32592498-d3001ab4-c545-11e7-9bac-317a24f42bb6.png">

If it's RPC error i believe '0x' value can be used as wrong result or one should add checking while filling out tuple from result array list to get some expected exception (not `IndexOutOfBoundsException`) to make it catchable in some expected way.

**Comment by 4ntoine** [comment]
Just wanted to note that in Remix it shows error:

<img width="710" alt="2017-11-09 12 06 16" src="https://user-images.githubusercontent.com/846671/32592620-706add66-c546-11e7-921f-82a73a2277d9.png">
So i believe there is proper way to handle such case.

**Comment by 4ntoine** [comment]
Same for SingleValueReturn functions. The only difference is that it throws `NPE`, see `result` is `null`:

<img width="620" alt="2017-11-09 12 17 07" src="https://user-images.githubusercontent.com/846671/32593019-11ce6d98-c548-11e7-82c7-f951e4ad5031.png">

**Comment by 4ntoine** [comment]
BTW value `0x` seems to be invalid (see https://github.com/ethereum/wiki/wiki/JSON-RPC):

    > WRONG: 0x (should always have at least one digit - zero is "0x0")

**Comment by conor10** [comment]
A fix was checked in a few days ago for this issue - see https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/tx/Contract.java#L174.

**Comment by Schefferk** [comment]
I get the same error when I try to get value from my contract , have you find the solution?
