### ISSUE TITLE
web3j is too slow

### ISSUE THREAD

**Issue by 4ntoine** [web3j/web3j#231]
My smart contract wrapper invocations lasts for ~15 seconds:

> 19666 [main] INFO FeatureTest - Adding feature ...
> 35199 [main] INFO FeatureTest - added

java code:

```
private TransactionReceipt addFeature_() throws Exception {
        logger.info("Adding feature ...");
        TransactionReceipt receipt = contract.addFeature(
            featureKey,
            goal,
            finishOnGoal,
            campaignStart,
            campaignFinish,
            maxDevelopmentDelay,
            developmentDuration)
            .send();

        logger.info("added");
        return receipt;
    }
```

It's connected using HTTP RPC:

    web3 = Web3j.build(new HttpService());  // defaults to http://localhost:8545/

If i connect to my private blockchain with Remix (and Web 3 provider) transactions are invoked within 1-2 seconds! In geth log i can see average block is mined very fast:
```
INFO [11-09|16:19:42] Successfully sealed new block            number=441 hash=dc0c14…327780
INFO [11-09|16:19:42] 🔗 block reached canonical chain          number=436 hash=dba8e8…8e2e54
INFO [11-09|16:19:42] 🔨 mined potential block                  number=441 hash=dc0c14…327780
INFO [11-09|16:19:42] Commit new mining work                   number=442 txs=0 uncles=0 elapsed=209.517µs
INFO [11-09|16:19:42] Successfully sealed new block            number=442 hash=b08130…4bb1d9
INFO [11-09|16:19:42] 🔗 block reached canonical chain          number=437 hash=97a773…7e08d5
INFO [11-09|16:19:42] 🔨 mined potential block                  number=442 hash=b08130…4bb1d9
INFO [11-09|16:19:42] Mining too far in the future             wait=2s
INFO [11-09|16:19:44] Commit new mining work                   number=443 txs=0 uncles=0 elapsed=2.003s
INFO [11-09|16:19:44] Successfully sealed new block            number=443 hash=967319…e8cb04
INFO [11-09|16:19:44] 🔗 block reached canonical chain          number=438 hash=ac932a…a25fd8
INFO [11-09|16:19:44] 🔨 mined potential block                  number=443 hash=967319…e8cb04
INFO [11-09|16:19:44] Commit new mining work                   number=444 txs=0 uncles=0 elapsed=126.637µs
INFO [11-09|16:19:46] Successfully sealed new block            number=444 hash=59afb9…be0e60
INFO [11-09|16:19:46] 🔗 block reached canonical chain          number=439 hash=e2914c…e14337
INFO [11-09|16:19:46] 🔨 mined potential block                  number=444 hash=59afb9…be0e60
INFO [11-09|16:19:46] Commit new mining work                   number=445 txs=0 uncles=0 elapsed=135.23µs
INFO [11-09|16:19:46] Successfully sealed new block            number=445 hash=766624…7bc22a
INFO [11-09|16:19:46] 🔗 block reached canonical chain          number=440 hash=282e4b…6639d3

```

Geth is started with the following arguments:

    geth --datadir $DATADIR \
    --dev \
    --rpc \
    --mine \
    --minerthreads 4 \
	--networkid 1999 \
	--rpcapi="db,eth,net,web3,personal,web3" \
	--rpcport 8545 \
	--rpcaddr 0.0.0.0 \
	--rpccorsdomain "*" \
	--fast \
	--cache=1024

```
$geth version
Geth
Version: 1.7.2-stable
Git Commit: 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.2
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.9.2/libexec

```
Can anyone confirm it's web3j issue?

**Comment by 4ntoine** [comment]
Tried to solve with other ppl's help:
https://stackoverflow.com/questions/47188266/how-to-speed-up-geth-transactions-in-private-blockchain
https://ethereum.stackexchange.com/questions/30221/how-to-speed-up-geth-transactions-in-private-blockchain
but it seems to be not geth issue

**Comment by conor10** [comment]
By default web3j waits 15 seconds between polling for transactions. You can modify this parameter by constructing your own TransactionManager - see https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/tx/RawTransactionManager.java#L50

**Comment by 4ntoine** [comment]
Thanks for the explanation!

9 Ноя 2017 г. 16:43 пользователь "Conor Svensson" <notifications@github.com>
написал:

**Comment by 4ntoine** [comment]
Just curious, why is there such 15 seconds `sleep time`?

**Comment by conor10** [comment]
Ethereum block time is around 15 seconds.
