### ISSUE TITLE
Events are coming too late

### ISSUE THREAD

**Issue by 4ntoine** [web3j/web3j#233]
It's seems to be related to issue #231.

I've set up new Transaction Manager with 1 second sleep delay and using it for `web3j` instance creation:
   
    public static final int TRANSACTION_DELAY = 1 * 1000;
    public static final int TRANSACTION_ATTEMPTS = 15;

    // much faster transaction manager
    private static class TestTransactionManager extends RawTransactionManager {

        public TestTransactionManager(Web3j web3j, Credentials credentials) {
            super(web3j, credentials, TRANSACTION_ATTEMPTS, TRANSACTION_DELAY);
        }
    }

However, events are coming too late (~ 10 seconds):

```
16911 [main] INFO FeatureTest - Subscribing to onDeployed() event ...
17156 [main] INFO FeatureTest - Deploying feature ...
20681 [main] INFO FeatureTest - Feature deployed
31980 [pool-2-thread-1] INFO FeatureTest - Received onDeployed(8417892656758172225) event
31981 [main] INFO FeatureTest - Unsubscribing ...
```

Event is sent in `deployFeature()` method so it's expected to come much faster (Solidity code):

    event onDeployed(uint featureKey);

    // deploy (end building of feature struct)
    function deployFeature(uint featureKey) public
        ownerOnly
        withState(featureKey, State.Deployment)
    {
        // some code
        
        // fire event
        onDeployed(featureKey);
    }

This is how i subscribe to event:

```
//  we have to filter out event from previous deployments (other tests)
BigInteger firstBlock = addFeature_().getBlockNumber();
setFeatureStructs_();

logger.info("Subscribing to onDeployed() event ...");
eventFeatureKey = null;
subscription = contract.onDeployedEventObservable(
    DefaultBlockParameter.valueOf(firstBlock),
    DefaultBlockParameterName.LATEST).subscribe(response -> {
    logger.info("Received onDeployed({}) event", response.featureKey);
    eventFeatureKey = response.featureKey;
    latch.countDown();
});

TransactionReceipt deployReceipt = deployFeature_();
logger.info("Feature deployed");

// event
List<SomeContract.OnDeployedEventResponse> onDeployedEvents =
    contract.getOnDeployedEvents(deployReceipt);
assertEquals(1, onDeployedEvents.size());
assertEquals(featureKey, onDeployedEvents.get(0).featureKey);

if (!latch.await(20, TimeUnit.SECONDS))
    fail("No onDeployed() event received");

assertNotNull(eventFeatureKey);
assertEquals(featureKey, eventFeatureKey);
```

    private TransactionReceipt deployFeature_() throws Exception {
        logger.info("Deploying feature ...");
        return contract.deployFeature(featureKey).send();
    }

Note deploy receipt is checked for the events right after deploy so the log is received actually.
That's why i believe it's some intentional delay introduced like the way it's done with default Transaction Manager.

**Comment by conor10** [comment]
Build your web3j instance with the following [method](https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/protocol/Web3j.java#L17) and you should be good.
