### ISSUE TITLE
Add support for non-byte chain id values

### ISSUE THREAD

**Issue by conor10** [web3j/web3j#234]
In the current web3j implementation, the [ChainId](https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/tx/ChainId.java) is of type byte.

The reason for this is historical,to support [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md), where you place a byte value in the raw transaction object - see [here](https://github.com/web3j/web3j/blob/master/crypto/src/main/java/org/web3j/crypto/TransactionEncoder.java#L39).

However, further down the original [EIP](https://github.com/ethereum/EIPs/issues/155) discussion it is mentioned that the v value when the transaction is RLP encoded shouldn't be limited to a single byte. So web3j could be enhanced to accommodate this.

This would mean enhancing the Transaction encoder so that a long value can be provided:

https://github.com/web3j/web3j/blob/master/crypto/src/main/java/org/web3j/crypto/TransactionEncoder.java#L34

The SignatureData object should not however be modified as this requires a byte value for *v* in transaction signing. This means that in the initial encode of the RawTransaction the chain id field should be RLP encoded, which would require modification of the current encode [method](https://github.com/web3j/web3j/blob/master/crypto/src/main/java/org/web3j/crypto/TransactionEncoder.java#L61).

The ChainId itself should probably become an enum wrapping the underlying long value.

**Comment by fcorneli** [comment]
I've been looking into this one a bit. See PR https://github.com/web3j/web3j/pull/478
ChainId of type byte is really all over the place.
Easiest to move forward here I guess is to first have a `TransactionDecoder` and proper signature validation within `RawTransaction` and work your way up from there.

**Comment by fcorneli** [comment]
Started working on that `TransactionDecoder`:
https://github.com/e-Contract/web3j/tree/transaction-decoder

**Comment by fcorneli** [comment]
Seems like `Sign.signedMessageToKey` has a problem when the message has been signed with an explicit chain id.

**Comment by fcorneli** [comment]
TransactionDecoder ready: https://github.com/web3j/web3j/pull/491
Funny thing: change `chainId` within `TransactionDecoderTest.testDecodingSignedChainId` to something else than 1, and the test explodes. But anyway, it's already a starting point I guess...

**Comment by fcorneli** [comment]
You can change `chainId` within `TransactionDecoderTest.testDecodingSignedChainId` up to `46` without any problem. Above `46`, the `v` requires more than one byte I guess, so it fails from there on.

**Comment by fcorneli** [comment]
Next step I guess is to allow for byte array `v` within `Sign.SignatureData`:
https://github.com/e-Contract/web3j/tree/signaturedata-v-array

**Comment by adridadou** [comment]
any news on that? it's limiting if we want to use it for non public chains ...

**Comment by bartwell** [comment]
Any news?

**Comment by d10r** [comment]
Looks like this was fixed in https://github.com/web3j/web3j/pull/913, included in release 4.3.  
Unfortunately the last android build is 4.2 though.
