### ISSUE TITLE
Estimate gas for transaction

### ISSUE THREAD

**Issue by CosimoSguanci** [web3j/web3j#248]
Is there a way to have the estimate gas cost of an ETH transaction, or even a contract's method call? Thanks!

**Comment by iikirilov** [comment]
`web3j.ethEstimateGas(Transaction transaction)`

Please use the [gitter](https://gitter.im/web3j/web3j) channel for future usage questions.

**Comment by Himanshu-Pandey** [comment]
But how can I get the gas estimate from contract wrapper object.

**Comment by rad-p** [comment]
Yea, we want gas estimate before sending transaction? 

You have to provide interface `ContractGasProvider` while loading contract; How can we know the gas price and limit before sending transactions? And gas price and limit  is dynamic. Limit is corelated with transactions, and price is with time one want to send. 

Is there an example how to sent tx, which has estimated gas limit before sending, and set to be precise?

**Comment by fcorneli** [comment]
Viable gas price as calculated by your client node (for example):
```
web3j.ethGasPrice()
```
