### ISSUE TITLE
Decode Transaction.input data from Contract

### ISSUE THREAD

**Issue by sirhill** [web3j/web3j#254]
My use case is the following:
I would like to have a daemon monitoring what is happening to my smart contract and how users are interacting with it.
I would like to set my

Similarly to what ConsenSys [https://github.com/ConsenSys/abi-decoder](abi-decoder) does in Javascript, it would be very practical to have a way to decode an input.

If there is interest in the feature and it makes sense (project-wise), I am available for the pull request.

Best,
Cyril

**Comment by conor10** [comment]
web3j's smart contract wrappers enable you to do this already - are you familiar with how they work? See https://docs.web3j.io/smart_contracts.html#invoking-transactions-and-events.

**Comment by sirhill** [comment]
Thanks a lot @conor10 for your reply.
If I understand your proposal, you are suggesting that I process the smart contract's events instead ?

Events cost a bit of gas and in my case all the information should already be available in the input data.
So there is no advantage to pay for some events.
I've dig a little bit on web3j's api but I was unable to find a method to decode it.
Hence my proposal to extends web3j for it.
What do you think ?

**Comment by flefevre** [comment]
Hey, I do agree, it will make sense to have a function to decode directly the String of 

`TransactionResult<org.web3j.protocol.core.methods.response.Transaction> tr = block.getTransactions().get(0);
	tr.get().getInput();`

If we could retrieve it, as ascii or as json or eventually directly as the event.
But perhaps it is a miss understanding from me on how to go from block>transaction to TransactionReceipt ?

Thanks for your input

**Comment by fcorneli** [comment]
I'm also looking for a way to decode the Input of a transaction.

**Comment by iikirilov** [comment]
This is not an issue with Web3j. Web3j also support a number of decoding and encoding methods. If you have specific feature requests or issues please open a new thread with detail. Closing thread.

Please ask usage question on [gitter](https://gitter.im/web3j/web3j?utm_source=share-link&utm_medium=link&utm_campaign=share-link).

**Comment by codebazz** [comment]
transaction.input=>input parameters
Any update ?

**Comment by shanbub** [comment]
> transaction.input=>input parameters
> Any update ?

Just encountered this:
https://github.com/prettymuchbryce/abidecoder
But having trouble using it from my java project at the moment.

**Comment by iikirilov** [comment]
Hey, after some thinking this may be possible but is non-trivial. It is possible to extend the contract wrapper generation to include the primitives you need to decode input of transactions to known contracts.

1. For deployment transaction - it is only possible to decode what input parameters were used (rlp encoded)
2. For contract calls - it is possible to decode what function was called (using the first 8 bytes of the keccak256 hash of the function signature) and what parameters were used (rlp encoded)

You can use the already existed abi and rlp modules in web3j to do this.

I m re-opening this issue because it is something that is useful - but I do not have time to implement.

**Comment by shanbub** [comment]
If I get you right you assume the contract is known in advanced, what about cases where the abi + function input are given at runtime and I need to decode some transaction?

Class `FunctionReturnDecoder` does provide the function
   
```
 public static List<Type> decode(
            String rawInput, List<TypeReference<Type>> parameters)
```

but it is almost impossible to create TypeReference for all types in runtime (not all types are supported by org.web3j.abi.datatypes.generated.ABITypes). To overcome that I had to generate a class, compile it and extract TypeReferences using reflection all in runtime, super overkill.

I would expect to have a simple method:

```
 public static List<Type> decode(
            String rawInput, string functionSig)
```

Or something like that..

**Comment by iikirilov** [comment]
Yes, to generate those methods we need to know the contract in advance.

It is possible to do without generating anything. You can parse each function in the abi to `AbiDefinition`. From there you can transform the parameters to the correct type to call the `decode` function.

However, you do need to know the contract in advance because the only thing you have in the raw input is the first 4 bytes of `keccak(functionSig)` to tie it to a particular function in the abi so you know the types of the parameters. Those 4 signature bytes can easily clash between functions in different contracts which have different parameters.

**Comment by shanbub** [comment]
AbiDefinition does not provide you with `TypeReference` which is required by the decode function:

```
 public static List<Type> decode(
            String rawInput, List<TypeReference<Type>> parameters)
```

To create `TypeReference` for each parameter (assuming you have the ABI of course) you can use:

```
List<TypeReference<Type>> typeReferences = new ArrayList();
for(AbiDefinition abiDefinition :abiDefinitions) {
    String type = abiDefinition.getType();
    Class<Type> typeClazz = AbiTypes.getType(type);
    TypeReference<Type> typeReference = TypeReference.create(typeClazz);
    typeReferences.add(typeReference);
}
```

This should work just fine for all types that are supported by class `org.web3j.abi.datatypes.generated.AbiTypes`.
What about those that aren't (all arrays for example)?
How do you create `TypeReference` object for those types?

**Comment by iikirilov** [comment]
Yes, that is the correct code snippet. I just dug out some old code it looks exactly the same.

You are correct that decoding static and dynamic arrays is an issue. This are my notes

        // FIXME: java.lang.UnsupportedOperationException: Unsupported type encountered: bytes3[2]
        // assertEquals(decode(functionCall2), "")
        // FIXME: java.lang.UnsupportedOperationException: Unsupported type encountered: uint256[]
        // assertEquals(decode(functionCall3), "")

So a `typeClazz` in `funcationCall2` parameter is `bytes3[2]`. I think you need to manually chop off the `[2]` and create a `bytes3` reference and then wrap that in a `StaticArray`. Similar this for dynamic arrays.

I will have a play around and report back.

**Comment by iikirilov** [comment]
Which is non-trivial because you can't make a class reference of a typed `Type` to constructed a typed `Type` `TypeReference`. Not sure if this makes sense but I need to consult an expert in reflection to continue.

i.e. `AbiTypes.getType(StaticArray2<Bytes3>.class)`;

**Comment by shanbub** [comment]
You are right, this is the problem I'm talking about.
At the moment I've solved it by doing the following (in runtime):

1. Generating a java class that holds static members of the the required `TypeReference<Type>`.
2. Compiling that class
3. Using reflection to get the required `TypeReference<Type>`.

It works but it is clearly overkill for a simple task of decoding input data.

**Comment by iikirilov** [comment]
I believe #972 fixes this

Please try with web3j 4.4.1
