### ISSUE TITLE
The class org.web3j.generated.HumanStandardToken in which jar

### ISSUE THREAD

**Issue by codingEcho** [web3j/web3j#255]
the class [HumanStandardTokenGeneratedIT](https://github.com/web3j/web3j/blob/master/integration-tests/src/test/java/org/web3j/protocol/scenarios/HumanStandardTokenGeneratedIT.java) in which jar,or web3j modules. how to send ERC20 transaction use web3j.

**Comment by conor10** [comment]
That class is in the integration-tests project, so not a bundled artifact.

What you need to do is create your own smart contract wrapper from your ERC20 smart contract solidity code. Then interact with it much like the HumanStandardTokenGeneratedIT does.
