### ISSUE TITLE
avoid method names declared on Object (and Contract base class) in wrappers

### ISSUE THREAD

**Issue by eepstein** [web3j/web3j#259]
I wrapped a "finalizable" contract and noticed that this led to an implementation to a finalize method in the wrapper class.  Probably not a good thing.

https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html

There are a handful of standard method names for which it's probably best to preserve their Java-based meaning:  hashCode, equals, toString, finalize, etc.  For these I think it makes more sense to add some standard prefix or suffix to the generated method names - for example "contract".  So, "contractFinalize" or "finalizeContract".  Basically, we don't want the code calling out to an ethereum node when performing internal Java life-cycle methods.

**Comment by sowmyakannan** [comment]
I am facing the same issue when having to use the RefundablePostDeliveryCrowdsale that extends from Finalizable contract from OZ. After generating the wrapper classes using web3j , it does not compile giving an error such as:

Error:(204, 43) java: finalize() in com.reit.resreitsmartcontractwrapper.TokenSale cannot override finalize() in java.lang.Object
  return type org.web3j.protocol.core.RemoteCall<org.web3j.protocol.core.methods.response.TransactionReceipt> is not compatible with void.


Is there a workaround for this issue?

**Comment by AlexandrouR** [comment]
This issue was fixed in #776
