### ISSUE TITLE
Creation of a web3j Gradle plugin

### ISSUE THREAD

**Issue by conor10** [web3j/web3j#260]
This should be pretty straightforward. A Gradle plugin should be created based on the existing [web3j Maven plugin](https://github.com/web3j/web3j-maven-plugin), which looks for a Solidity compiler in the user's classpath to perform the initial compilation. 

The smart contract wrappers should be generated by calling the SolidityFunctionWrapperGenerator.

The [Protobuf Gradle plugin](https://github.com/google/protobuf-gradle-plugin) will serve as a good reference point. You could also potentially refer to the  [Antlr4 Gradle plugin](https://github.com/melix/antlr4-gradle-plugin).

The project will need a README file with relevant unit tests. Additionally it will need to be deployed to Bintray and Maven central repositories. I can assist with this setup.

**Comment by IgorPerikov** [comment]
Hi, Conor! I have some experience creating gradle plugins, as well as making some integration testing for them (with netflix-made library `nebula-test`) and I would like to help with this one. Few suggestions:
1. Please create a repository so I can create fork-pr against it
2. Speaking about the plugin you referenced - I would like to write it in Java? I know netflix might have another level of scale, but they tend to have some performance issues with groovy-written plugins. Also from my point of view, since java8 release there is not so much extra-profit of using groovy above j8. Any concerns about it?

**Comment by Ugo** [comment]
I've started to implement this in a project in my github, could you create a repo web3j-gradle-plugin so I could push there directly? Thank you.

**Comment by conor10** [comment]
Hey @Ugo, great! You should have access to the repo now.

**Comment by mushketyk** [comment]
@conor10 @Ugo Would it also make sense to extract classes related to using solidity compiler from the Maven project to a new project? Then both Maven/Gradle plugins would be able to use the same code.

**Comment by Ugo** [comment]
Thanks @conor10 I'll start committing there.
@mushketyk The maven plugin copied some files from the  [ethereumj project](https://github.com/ethereum/ethereumj) for the solidity compiler while I'm using this project directly in the dependencies. I first try to have a working version for that plugin but for sure we might refactor one or both plugins to use the same code.

**Comment by Ugo** [comment]
I'm not authorized to push code to the web3j-gradle-plugin repo directly, is there anything to change?

**Comment by mushketyk** [comment]
@conor10 It looks like you need to add an initial commit to the repo so that @Ugo could fork it.

**Comment by Ugo** [comment]
Hello @conor10, sorry to bother but I'm still unable to commit to the repo. Could you help on this please?

**Comment by conor10** [comment]
Sorry guys - completely missed this. You can always get me via hi@web3j.io.

@Ugo you should be sorted now.

**Comment by Ugo** [comment]
No problem, thank you I can commit now.

**Comment by conor10** [comment]
Plugin has been available for a while now at https://github.com/web3j/web3j-gradle-plugin.
