### ISSUE TITLE
Support for Actual Fee for processed Transactions

### ISSUE THREAD

**Issue by bcholmes** [web3j/web3j#266]
Hi,

I'm trying to write an app that'll track ETH transfers and I'm getting a touch stuck on after-the-fact fees. 

I wrote up a question about this problem on Stack*: https://ethereum.stackexchange.com/questions/31455/after-the-fact-fee-calculation-for-eth-transfers .

Can the Transaction API include a method to easily allow access to actual Gas used to process a transaction?

**Comment by iikirilov** [comment]
```
Transaction transaction = web3j.ethGetTransactionByHash(transactionHash);
BigInteger gasPrice = transaction.getGasPrice();
TransactionReceipt transactionReceipt =
             web3j.ethGetTransactionReceipt(transactionHash).send().getTransactionReceipt();
BigInteger gasUsed = transactionReceipt.getGasUsed()
BigInteger fee = gastPrice.multiply(gasUsed)
```
