### ISSUE TITLE
Error in documentation page about Transactions

### ISSUE THREAD

**Issue by javahippie** [web3j/web3j#269]
In the documentation page about transactions, there seems to be an issue with the part ["Transacting with a smart contract"](https://docs.web3j.io/transactions.html#transacting-with-a-smart-contract). It shows a call of the function Transaction#createEthCallTransaction only with the contract address and data like this:

    Transaction.createEthCallTransaction(contractAddress, encodedFunction)

The [method itself](https://github.com/web3j/web3j/blob/958ad9819e29a08cf0ef2b7263b64618df740dc2/core/src/main/java/org/web3j/protocol/core/methods/request/Transaction.java) on the other hand also requires the `from` address to be passed into:

    public static Transaction createEthCallTransaction(String from, String to, String data) {

        return new Transaction(from, null, null, null, to, null, data);
    }

**Comment by conor10** [comment]
Are you able to provide a PR with this update? Makes my life easier :)

**Comment by javahippie** [comment]
No problem, I hope it is okay this way?
