### ISSUE TITLE
Add web3j shutdown method

### ISSUE THREAD

**Issue by conor10** [web3j/web3j#273]
As per the following [issue](https://github.com/web3j/web3j/issues/206#issuecomment-344610752), there are a number of shutdown hooks in web3j for closing the ScheduledExecutor instances. 

web3j should provide a `web3j.shutdown()` method, that calls `scheduledExecutorService.shutdown()`, so that users can control when the internal ScheduledExectorService is shutdown.

**Comment by LionbI4** [comment]
Just pass your own executor to Web3j.build and shutdown it when you need
