### ISSUE TITLE
PrivateKey generating wrong address on MyEtherWallet

### ISSUE THREAD

**Issue by ahmedrizwan** [web3j/web3j#278]
Hi!
I generated a wallet on Android, the address for which is : **d2f785b8974e847439240d8695c433c9eb48d2e9**
And then I generated a private key using
`String(Hex.encode(Wallet.decrypt(password, walletFile).toByteArray()))`
If I use the generated key in MyEtherWallet.com or MetaMask, it gives me a different address with some of the letters being uppercased: **D2f785B8974E847439240D8695C433C9EB48D2E9**

Do you have any ideas as to why it's generating a different address? 

Thanks!

**Comment by conor10** [comment]
Yes - they use checksum encoding. You can read more at https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md.

There is an enhancement proposed for web3j to support checksum addresses - see https://github.com/web3j/web3j/issues/79. I'm hoping a member of the community will pick this up.
