### ISSUE TITLE
new block Observable stops and does not recover when node connection fails

### ISSUE THREAD

**Issue by iikirilov** [web3j/web3j#279]
Creating a Observable via `web3j.blockObservable(true)` creates a 'ScheduledFuture' object to poll for filter changes. If an IOException is thrown due to the connection to the node going down, the exception is suppressed by the `ScheduledFuture`. Polling for future blocks also stops.

Expected behavior is either of:
1. Have a thread to check if an exception is thrown and propagate it accordingly. [This](https://www.cosmocode.de/en/blog/schoenborn/2009-12/17-uncaught-exceptions-in-scheduled-tasks?) resource provides a starting point to implement this.
2. Continue polling even if the connection to the node goes down and log exceptions rather than throwing them.

N.B. this behavior also occurs with all other observables that poll for filter changes

**Comment by conor10** [comment]
Related issues - https://github.com/web3j/web3j/issues/197 & https://github.com/web3j/web3j/issues/144

**Comment by conor10** [comment]
Fixed by https://github.com/web3j/web3j/releases/tag/v3.2.0.
