### ISSUE TITLE
send transaction to geth 1.4.17 get rlp decodeError

### ISSUE THREAD

**Issue by bigstar119** [web3j/web3j#29]
client:goClient geth-1.4.17
web3j:web3j-1.0.9
when I send transaction to geth rpc, I got follow Error:
java.lang.RuntimeException: Error processing transaction request: rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).S
	at org.web3j.abi.ManagedTransaction.signAndSend(ManagedTransaction.java:87)
	at org.web3j.abi.Transfer.send(Transfer.java:75)
	at org.web3j.abi.Transfer.sendFunds(Transfer.java:106)
	at com.neusoft.ethereum.client.testcase.TransferThread.transfer(TransferTestCase.java:106)
	at com.neusoft.ethereum.client.testcase.TransferThread.call(TransferTestCase.java:128)
	at com.neusoft.ethereum.client.testcase.TransferThread.call(TransferTestCase.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
this error has a certain probability of occurrence，i find the problem is web3j`s signatureData encoding format is dfferent from the geth txdata struct
geth-1.4.17 txdata struct is 
type txdata sturct {
...
V        type
R,  S   *big.Int
}
but we3j`s code is:
 if (signatureData != null) {
            result.add(RlpString.create(signatureData.getV()));
            result.add(RlpString.create(signatureData.getR()));//FIX ME here shoud be bigInteger not byte[]
            result.add(RlpString.create(signatureData.getS()));//FIX ME here shoud be bigInteger not byte[]
        }

**Comment by conor10** [comment]
Please could you provide the full test that you're running to produce this issue?

**Comment by bigstar119** [comment]
[testcase.zip](https://github.com/web3j/web3j/files/647822/testcase.zip)

**Comment by conor10** [comment]
So this issue doesn't happen with every transaction, only some?

Please can you verify that the following integration test works for you:

https://github.com/web3j/web3j/blob/master/src/integration-test/java/org/web3j/protocol/scenarios/SendEtherIT.java#L66

**Comment by bigstar119** [comment]
yes only R or S has leading zero, in other words when R or S is small and lower 16 bit is zero.. because of follow code:
 byte[] r = Numeric.toBytesPadded(sig.r, 32);//lower 16 bit maybe zero
        byte[] s = Numeric.toBytesPadded(sig.s, 32);//lower 16 bit maybe zero
        SignatureData ret=new SignatureData(v, r, s);

and SendEtherIT.java use Parity.ethSendTransaction ,it is call jsonRPC "ethSendTransaction" directly do not need to  signTransaction like Transfer.sendFunds( use RawTransaction) ,so it is ok.
but can not explain my problem

**Comment by RichardAckerman** [comment]
hello,I have the same error
