### ISSUE TITLE
OOM exception occurs due to native scrypt code incopamtibility for Android lib

### ISSUE THREAD

**Issue by vikulin** [web3j/web3j#299]
Possible regression issue for all 3.x.x versions, Reproduced for v android 3.0.1:

Following wallet generation throws an OOM exception.
fileName = WalletUtils.generateNewWalletFile(pass, destination, true);

    "java.lang.RuntimeException: An error occurred while executing doInBackground()",
    "\tat android.os.AsyncTask$3.done(AsyncTask.java:318)",
    "\tat java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)",
    "\tat java.util.concurrent.FutureTask.setException(FutureTask.java:223)",
    "\tat java.util.concurrent.FutureTask.run(FutureTask.java:242)",
    "\tat android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)",
    "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)",
    "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)",
    "\tat java.lang.Thread.run(Thread.java:760)",
    "Caused by: java.lang.OutOfMemoryError: Failed to allocate a 1036 byte allocation with 16777216 free bytes and 48MB until OOM; failed due to fragmentation (required continguous free 16384 bytes for a new buffer where largest contiguous free 8192 bytes)",
    "\tat org.spongycastle.util.Arrays.clone(Arrays.java:602)",
    "\tat org.spongycastle.crypto.generators.SCrypt.SMix(SCrypt.java:126)",
    "\tat org.spongycastle.crypto.generators.SCrypt.MFcrypt(SCrypt.java:87)",
    "\tat org.spongycastle.crypto.generators.SCrypt.generate(SCrypt.java:66)",
    "\tat org.web3j.crypto.Wallet.generateDerivedScryptKey(Wallet.java:136)",
    "\tat org.web3j.crypto.Wallet.create(Wallet.java:74)",
    "\tat org.web3j.crypto.Wallet.createStandard(Wallet.java:93)",
    "\tat org.web3j.crypto.WalletUtils.generateWalletFile(WalletUtils.java:61)",
    "\tat org.web3j.crypto.WalletUtils.generateNewWalletFile(WalletUtils.java:52)",
    "\tat org.vikulin.etherwallet.AccountListActivity$5.doInBackground(AccountListActivity.java:434)",
    "\tat org.vikulin.etherwallet.AccountListActivity$5.doInBackground(AccountListActivity.java:427)",
    "\tat android.os.AsyncTask$2.call(AsyncTask.java:304)",
    "\tat java.util.concurrent.FutureTask.run(FutureTask.java:237)"

Possible cause:
Removed dependency:
https://github.com/web3j/web3j/blob/01bdfa33087fd36cb6ffc951eabbbca7cf49e80d/build.gradle#L95
https://github.com/web3j/web3j/commit/df8db2061054ec50a9e925d4440d38946174a4f6
As result old version (2.2.1 and prior 3.0) used to be compatible with native scrypt code:
jbyteArray JNICALL scryptN(JNIEnv *env, jclass cls, jbyteArray passwd, jbyteArray salt,
    jint N, jint r, jint p, jint dkLen)

**Comment by conor10** [comment]
The issue with the original Scrypt dependency is overall Android compatibility, as per https://github.com/web3j/web3j/issues/193.

**Comment by nzkozar** [comment]
Getting the same issue when trying to do: `Credentials credentials = WalletUtils.loadCredentials(walletPass, walletFile);`

Strange enough, if I run the app in an emulator running Android 8.0, it all works fine. If I run it in anything less than 8.0 (Emulator or real device), i get the OutOfMemoryError

Any solutions to this problem?

**Comment by vikulin** [comment]
@nzkozar , yes:
back to com.lambdaworks:scrypt:1.4.0 lib and undo this commit:
https://github.com/web3j/web3j/blob/01bdfa33087fd36cb6ffc951eabbbca7cf49e80d/build.gradle#L95
https://github.com/web3j/web3j/commit/df8db2061054ec50a9e925d4440d38946174a4f6

**Comment by comodoro** [comment]
It seems to me that the OOM happens because of allocating a large array at `at org.spongycastle.crypto.generators.SCrypt.SMix(SCrypt.java:126)`. Wouldn't it be possible to change or add slower implementation that goes through disk?

**Comment by vikulin** [comment]
Not good approach. This could cause running time impact.

27 янв. 2018 г. 10:41 ПП пользователь "comodoro" <notifications@github.com>
написал:

**Comment by comodoro** [comment]
I agree, but still better than OOM and easy as temporary solution. I think
I saw somewhere mentioned issues with the other library.

2018-01-27 21:43 GMT+01:00 vikulin <notifications@github.com>:

**Comment by vikulin** [comment]
You might not completely understand scrypt algo. It implemented to be
effective only if encryption/decryption goes through RAM. Disk can bring
huge time impact.

27 янв. 2018 г. 10:52 ПП пользователь "comodoro" <notifications@github.com>
написал:

**Comment by sathish76** [comment]
@vikulin thanks for your answer and from that I came with a simple solution.
removed jniLibs and passing **_useFullScrypt -> false_** makes very faster in android.
`public class CustomWallet extends WalletUtils {

    private static final ObjectMapper objectMapper = new ObjectMapper();

    static {
        objectMapper.configure(JsonParser.Feature.ALLOW_UNQUOTED_FIELD_NAMES, true);
        objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
    }

    public static String generateLightNewWalletFile(String password, File destinationDirectory)
            throws NoSuchAlgorithmException, NoSuchProviderException,
            InvalidAlgorithmParameterException, CipherException, IOException {

        return generateNewWalletFile(password, destinationDirectory, false);
    }

    public static String importWalletFromKey(
            String password, ECKeyPair ecKeyPair, File destinationDirectory, boolean useFullScrypt)
            throws CipherException, IOException {

        WalletFile walletFile;
        if (useFullScrypt) {
            walletFile = Wallet.createStandard(password, ecKeyPair);
        } else {
            walletFile = Wallet.createLight(password, ecKeyPair);
        }

        String fileName = getWalletFileName(walletFile);
        File destination = new File(destinationDirectory, fileName);

        objectMapper.writeValue(destination, walletFile);

        return fileName;
    }

    private static String getWalletFileName(WalletFile walletFile) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("'UTC--'yyyy-MM-dd'T'HH-mm-ss.SSS'--'");
        return dateFormat.format(new Date()) + walletFile.getAddress() + ".json";
    }

}
`
To import lightwallet from privatekey.

```
ECKeyPair keys = ECKeyPair.create(Hex.decode("privateKey"));
String filename = CustomWallet.importWalletFromKey("password", keys, getFilesDir(), false);
```

**Comment by uncleleonfan** [comment]
This still happen when I call Wallet.decrypt:
    Caused by: java.lang.OutOfMemoryError: Failed to allocate a 1036 byte allocation with 8239648 free bytes and 7MB until OOM; failed due to fragmentation (required continguous free 16384 bytes for a new buffer where largest contiguous free 12288 bytes)
        at org.spongycastle.util.Arrays.clone(Arrays.java:671)
        at org.spongycastle.crypto.generators.SCrypt.SMix(SCrypt.java:126)
        at org.spongycastle.crypto.generators.SCrypt.MFcrypt(SCrypt.java:87)
        at org.spongycastle.crypto.generators.SCrypt.generate(SCrypt.java:66)
        at org.web3j.crypto.Wallet.generateDerivedScryptKey(Wallet.java:136)
        at org.web3j.crypto.Wallet.decrypt(Wallet.java:214)

Event if I removed dependency of lambdaworks:
    api (libs["web3j"]){
        exclude group: 'io.reactivex'
        exclude group: 'com.lambdaworks'
    }
Any help?

**Comment by uncleleonfan** [comment]
@dinu88 Try to use lamdaworks lib's Scrypt, I rewrited generateDerivedScryptKey function. It will take more time to decrypt, but it works. And don't forget *.so files.

    private static byte[] generateDerivedScryptKey(
            byte[] password, byte[] salt, int n, int r, int p, int dkLen) throws CipherException {
        if (password == null) {
            throw new IllegalArgumentException("Passphrase P must be provided.");
        }
        if (salt == null) {
            throw new IllegalArgumentException("Salt S must be provided.");
        }
        if (n <= 1) {
            throw new IllegalArgumentException("Cost parameter N must be > 1.");
        }
        // Only value of r that cost (as an int) could be exceeded for is 1
        if (r == 1 && n > 65536) {
            throw new IllegalArgumentException("Cost parameter N must be > 1 and < 65536.");
        }
        if (r < 1) {
            throw new IllegalArgumentException("Block size r must be >= 1.");
        }
        int maxParallel = Integer.MAX_VALUE / (128 * r * 8);
        if (p < 1 || p > maxParallel) {
            throw new IllegalArgumentException("Parallelisation parameter p must be >= 1 and <= " + maxParallel
                    + " (based on block size r of " + r + ")");
        }
        if (dkLen < 1) {
            throw new IllegalArgumentException("Generated key length dkLen must be >= 1.");
        }
        try {
            return SCrypt.scrypt(password, salt, n, r, p, dkLen);
        } catch (GeneralSecurityException e) {
            e.printStackTrace();
        }
        return null;
    }

**Comment by YingJie0712** [comment]
I have a problem: WalletUtils.loadCredentials(password, new File(path)); cause OutOfMemoryError, is there anyone to solve? Give me method to and_chenyingjie@163.com. Thanks!!!!!!!!!!!!!!!!!!!

**Comment by dinu88** [comment]
Thanks, @uncleleonfan , I switched to `geth` for android lib and not interested anymore in this.

**Comment by fishwjy** [comment]
I'm calling WalletUtils.loadCredentials, and out of memory. How to go back to 2.2.1?
I use " compile 'org.web3j:core:2.2.1-android' " in gradle. It failed
And where to get the libscrypt.so file?
Thanks for your reply.

**Comment by uncleleonfan** [comment]
@fishwjy You can get it from imtoken.apk

**Comment by fishwjy** [comment]
@uncleleonfan OK, but I'm failed with synchronizing the 'org.web3j:core:2.2.1-android in gradle. How to fix it?
Synchronization of org.web3j:core:3.3.1-android is OK.

**Comment by fishwjy** [comment]
@uncleleonfan OK, I have solved it, because version 2.2.1 has no android version.
Just load org.web3j:core:2.2.1 is OK.

**Comment by vikulin** [comment]
@uncleleonfan , This is not good to use outdated version. Refer a defects affecting ald version such as:
https://github.com/web3j/web3j/issues/104

**Comment by fishwjy** [comment]
@vikulin Yes, new issue comes. When I compile the 2.2.1 in Android environment, the error comes out:
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> More than one file was found with OS independent path 'META-INF/DEPENDENCIES'
It seems the 2.2.1 can not run on Android OS?

**Comment by fishwjy** [comment]
@vikulin So how to fix the OOM on Android perfectly? Thanks for your reply!

**Comment by vikulin** [comment]
@fishwjy , I used native implementation of the scrypt encryption implementing own WalletNative class. Scrypt slgo also implemeted natively on C.
An example of the native usage see in this project:
https://github.com/wg/scrypt

**Comment by zoeleesss** [comment]
Hey guys. @vikulin @conor10 @nzkozar @comodoro @sathish76 @fishwjy @YingJie0712 @jaycarey 
I magically solved this problem.
This is how i managed to do so.

When you are trying to create a new wallet. 
Try `String filename = WalletUtils.generateLightNewWalletFile(password,new File(filepath));` 👍 
instead of ` String filename = WalletUtils.generateFullNewWalletFile(password,new File(filepath));` 👎 

And when you import an old wallet from ECKeyPair, 
Try `String filename = WalletUtils.generateWalletFile(password,ecKeyPair,new File(filepath),false);` 👍 
instead of `String filename = WalletUtils.generateWalletFile(password,ecKeyPair,new File(filepath),true);` 👎 


Also, you may notice there might be an error on android if you use Infura or https to connect to ethereum  blockchain network: `javax.net.ssl.SSLException: Connection closed by peer`. See my issue here: `https://github.com/web3j/web3j/issues/583`

**Comment by vikulin** [comment]
Light wallet has less encryption strength and higher security risk against
brute force attack.

2018-06-09 8:37 GMT+03:00 zoelee <notifications@github.com>:

**Comment by JoeBarbaro** [comment]
Hi @zoeleesss 

What exactly do you mean with you comment? You have changed library code and compile it again? Or how we can use this commands instead of defaults? I also deal with this problem and nothing works.

Thanks for your reply :smile:

**Comment by zoeleesss** [comment]
Hey @JoeBarbaro 

I meant when you are trying to create a new wallet or import an old wallet. 
Try `String filename = WalletUtils.generateLightNewWalletFile(password,new File(filepath));`
and `String filename = WalletUtils.generateWalletFile(password,ecKeyPair,new File(filepath),false);` respectively. And it will work.

Hope it helps.

**Comment by JoeBarbaro** [comment]
Hi @zoeleesss 

Thank you for your reply :smile:  I didn´t exactly use this methods, but you inspired me with _ecKeyPair_. So I use method ```Credentials.create(String privateKey)``` instead of ```loadCredentials(String password, File source)```. With generated private key it works on Anroid! :smile: Thanks :smiley:

**Comment by vikulin** [comment]
Beware! String privateKey *is an unencrypted private key!*

2018-06-19 15:48 GMT+03:00 JoeBarbaro <notifications@github.com>:

**Comment by lhalcyon** [comment]
see https://lhalcyon.com/blockchain-eth-unlock-android/
