### ISSUE TITLE
Code generation of function calls for non constants

### ISSUE THREAD

**Issue by juanfranblanco** [web3j/web3j#30]
Scenario:

You want to use call a contract function that is not a constant, which you may or not have control of it, but the function call is not declared as constant.

If using the wrapper service, you will be forced to modified the wrapper and / or create a different class.

**Comment by conor10** [comment]
I'd prefer to leave as it - otherwise, there's going to be a lot more code generated for every smart contract wrapper.

Happy to revisit if members of the community feel strongly about this.
