### ISSUE TITLE
java generated code do not compile due to List<BigInteger>.class

### ISSUE THREAD

**Issue by flefevre** [web3j/web3j#303]
Dear web3j community,
when generated the java code from the following solidity file, the java code do not compile due to the following error.

solidity
`pragma solidity ^0.4.18;

/**
 * 
 * version 0.3 
 */
contract Predictor {

    /* this runs when the contract is executed */
    function Predictor() public {
        // initialize the variables
    }
    
    // returns an int array by adding to all its elements a scalar value "a"
    function subtractScalar(int[] self, int a) public pure returns (int[] s) {
        s = new int[](self.length);
        for (uint i = 0; i < self.length; i++)
            s[i] = self[i] - a;
    }
    
} // contract Predictor
`

java
`package org.aa;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;
import org.web3j.abi.TypeReference;
import org.web3j.abi.datatypes.DynamicArray;
import org.web3j.abi.datatypes.Function;
import org.web3j.abi.datatypes.Type;
import org.web3j.abi.datatypes.generated.Int256;
import org.web3j.crypto.Credentials;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.RemoteCall;
import org.web3j.tx.Contract;
import org.web3j.tx.TransactionManager;

/**
 * <p>Auto generated code.
 * <p><strong>Do not modify!</strong>
 * <p>Please use the <a href="https://docs.web3j.io/command_line.html">web3j command line tools</a>,
 * or the org.web3j.codegen.SolidityFunctionWrapperGenerator in the 
 * <a href="https://github.com/web3j/web3j/tree/master/codegen">codegen module</a> to update.
 *
 * <p>Generated with web3j version 3.2.0.
 */
public class Predictor extends Contract {
    private static final String BINARY = "6060604052341561000f57600080fd5b61019e8061001e6000396000f3006060604052600436106100405763ffffffff7c0100000000000000000000000000000000000000000000000000000000600035041663565e4fa18114610045575b600080fd5b341561005057600080fd5b610096600460248135818101908301358060208181020160405190810160405280939291908181526020018383602002808284375094965050933593506100e992505050565b60405160208082528190810183818151815260200191508051906020019060200280838360005b838110156100d55780820151838201526020016100bd565b505050509050019250505060405180910390f35b6100f1610160565b600083516040518059106101025750595b90808252806020026020018201604052509150600090505b8351811015610159578284828151811061013057fe5b906020019060200201510382828151811061014757fe5b6020908102909101015260010161011a565b5092915050565b602060405190810160405260008152905600a165627a7a723058203e18d289e9965866ad9c2ae0c6c3d5b0564358f16041265d6b6aec7c2b2755610029";

    protected Predictor(String contractAddress, Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit) {
        super(BINARY, contractAddress, web3j, credentials, gasPrice, gasLimit);
    }

    protected Predictor(String contractAddress, Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit) {
        super(BINARY, contractAddress, web3j, transactionManager, gasPrice, gasLimit);
    }

    public RemoteCall<List<BigInteger>> subtractScalar(List<BigInteger> self, BigInteger a) {
        Function function = new Function("subtractScalar", 
                Arrays.<Type>asList(new org.web3j.abi.datatypes.DynamicArray<org.web3j.abi.datatypes.generated.Int256>(
                        org.web3j.abi.Utils.typeMap(self, org.web3j.abi.datatypes.generated.Int256.class)), 
                new org.web3j.abi.datatypes.generated.Int256(a)), 
                Arrays.<TypeReference<?>>asList(new TypeReference<DynamicArray<Int256>>() {}));
        return executeRemoteCallSingleValueReturn(function, List<BigInteger>.class);
    }

    public static RemoteCall<Predictor> deploy(Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit) {
        return deployRemoteCall(Predictor.class, web3j, credentials, gasPrice, gasLimit, BINARY, "");
    }

    public static RemoteCall<Predictor> deploy(Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit) {
        return deployRemoteCall(Predictor.class, web3j, transactionManager, gasPrice, gasLimit, BINARY, "");
    }

    public static Predictor load(String contractAddress, Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit) {
        return new Predictor(contractAddress, web3j, credentials, gasPrice, gasLimit);
    }

    public static Predictor load(String contractAddress, Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit) {
        return new Predictor(contractAddress, web3j, transactionManager, gasPrice, gasLimit);
    }
}`

error
`Predictor.java:[43,78] <identifier> expected
`
linking to
return executeRemoteCallSingleValueReturn(function, List<BigInteger>.class);

I would appreciate your help.
Francois from france

**Comment by bluen** [comment]
See https://github.com/web3j/web3j/issues/238

**Comment by flefevre** [comment]
Your workaround is working for me. waiting for your final patch. Thanks a lot for your reactivity!

**Comment by conor10** [comment]
Please can you confirm if this issue is fixed in web3j 3.3.1? Please reopen this issue if not.
