### ISSUE TITLE
wrong error throw on Filter.pollFilter() method 

### ISSUE THREAD

**Issue by ZhiyuHelloWorld** [web3j/web3j#304]
https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/protocol/core/filters/Filter.java#L113

should change to ?
```
            throwException(ethLog.getError());
```  
Since we check 
```
if (ethLog.hasError()) {
...
}
```

**Comment by eepstein** [comment]
I think you're correct.
Want to open a PR? 

(And while you're at it, I'm looking at line # 138 of the same file and it too should change a bit, in particular if there's no error it should create one and pass it in as that's the check for the filter having been correctly uninstalled.)
