### ISSUE TITLE
SafeVarargs & OOM

### ISSUE THREAD

**Issue by ChenLiheng** [web3j/web3j#312]
When I used the 3.1.1 version, an error occurred `Error:trouble processing "java/lang/SafeVarargs.class":`。
Then I switched to 3.0.1 when creating the wallet...OOM.So I want to know if there is a perfect version.
thanks!

**Comment by eepstein** [comment]
The current version is 3.2.0
Try upgrading to that.

(Also, in general to report an issue, it's best to include a stack trace and detailed information about how to reproduce the issue.)

**Comment by conor10** [comment]
This should be fixed in 3.3.1 if using Android.
