### ISSUE TITLE
org.web3j.protocol.exceptions.TransactionException: Error processing request: unknown transaction

### ISSUE THREAD

**Issue by luoshushua** [web3j/web3j#318]
I am  calling a transfer method on an ERC20 contract like this:
```
>  Credentials credentials = null;
>         try {
>             this.initWeb3Client();
>             credentials = WalletUtils.loadCredentials(pwd, path);
>             MyToken mt =  MyToken.load(ADDRESS,web3j,
>                     credentials, BigInteger.valueOf(20_000_000_000L),BigInteger.valueOf(4_300_000L));
>             TransactionReceipt tr = oso.transfer(address,value).send();
>             System.out.println("hash:"+tr.getTransactionHash());
>         } catch (IOException e) {
>             e.printStackTrace();
>         } catch (CipherException e) {
>             e.printStackTrace();
>         } catch (Exception e) {
>             e.printStackTrace();
>         }
```
The transaction was successful and confirmed at Rinkeby, but an exception was returned

```
org.web3j.protocol.exceptions.TransactionException: Error processing request: unknown transaction
	at org.web3j.tx.response.TransactionReceiptProcessor.sendTransactionReceiptRequest(TransactionReceiptProcessor.java:32)
	at org.web3j.tx.response.PollingTransactionReceiptProcessor.getTransactionReceipt(PollingTransactionReceiptProcessor.java:37)
	at org.web3j.tx.response.PollingTransactionReceiptProcessor.waitForTransactionReceipt(PollingTransactionReceiptProcessor.java:29)
	at org.web3j.tx.TransactionManager.processResponse(TransactionManager.java:72)
	at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:51)
	at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:70)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:223)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:207)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:201)
	at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$3(Contract.java:240)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
	at com.novel.balbit.ports.contract.MyTokenTest.transfer(MyTokenTest.java:358)
	at com.novel.balbit.ports.contract.MyTokenTest.main(MyTokenTest.java:396)
```

**Comment by allquantor** [comment]
The problem is indeed inside `TransactionReceiptProcessor`
when inside `waitForTransactionReceipt` 
`web3j.ethGetTransactionReceipt(transactionHash).send()` is called.  The transaction is maybe successfully be send to the network, but not reached the state where the client can find it to generate a `TransactionReceipt`.
You can get a workaround depends on what information you need after the transaction, if it is just the transactionhash you can do something like this
```
Web3j web3 = Web3j.build(new HttpService());  // defaults to http://localhost:8545/
Credentials credentials = WalletUtils.loadCredentials("password", "/path/to/walletfile");

// get the next available nonce
EthGetTransactionCount ethGetTransactionCount = web3j.ethGetTransactionCount(
             address, DefaultBlockParameterName.LATEST).sendAsync().get();
BigInteger nonce = ethGetTransactionCount.getTransactionCount();

// create our transaction
RawTransaction rawTransaction  = RawTransaction.createEtherTransaction(
             nonce, <gas price>, <gas limit>, <toAddress>, <value>);

// sign & send our transaction
byte[] signedMessage = TransactionEncoder.signMessage(rawTransaction, credentials);
String hexValue = Hex.toHexString(signedMessage);
// FROM here you can get the tx hash.
EthSendTransaction ethSendTransaction = web3j.ethSendRawTransaction(hexValue).send();
```
Although if you find a way to set 
```
   public static final int DEFAULT_POLLING_ATTEMPTS_PER_TX_HASH = 40;
   public static final long DEFAULT_POLLING_FREQUENCY = 1000 * 15;
```
inside `TransactionManager` to increase the probability to get the txhash.

**Comment by eepstein** [comment]
I've used an extension to inject my own TX manager into the construction of generated code that extends the Contract class.  And the injected TX manager uses different timeouts than the default.

IF that's of interest or use to others I could see about getting the code into the web3j spring module, but I'd need to noodle on the best way to do the wiring in that case - in my case I just inject the Tx Manager into the methods that create the contract instances, which are all spring "beans" in my app, so the wiring is trivial.  But that wouldn't be the best for a general case solution

**Comment by allquantor** [comment]
The best way would be do decouple the receipt getting functionality from the one that returns a transaction hash. So you could compose two async operations with separate callbacks. This re-pulling strategy is inefficient since it do CPU work for nothing.

**Comment by luoshushua** [comment]
I called web3j.ethSendTransaction(transaction).sendAsync().get() to get transaction hash,
then I used transaction hash to waitForTransactionReceipt;

Thanks for your reply, a great help for me！ @allquantor @eepstein

**Comment by amyodov** [comment]
I’m afraid there may be deeper problem requiring to be resolved and this issue reopened.

I have the similar problems with `Error processing request: unknown transaction`, except what I am using is not a `transfer`, but the SolidityFunctionWrapperGenerator-generated wrappers for some contract.

Trying to call a method like `public RemoteCall<TransactionReceipt> bulkTransfer(String token, List<String> toAddresses, List<BigInteger> values)`, I get this problem.

Deep inside the chain of calls, I see that web3j, inside `TransactionManager.processResponse`, does the following:

        String transactionHash = transactionResponse.getTransactionHash();

        return transactionReceiptProcessor.waitForTransactionReceipt(transactionHash);

If I understand the comment from allquantor properly, this means that at this point web3j, for some reason, may be in the state when it cannot handle `waitForTransactionReceipt`; but until it is fixed, *this makes any smart contract method calls from web3j virtually useless*.

**Comment by flefevre** [comment]
Dear all,
it seems I have exactly the same basic problem

I am starting my ethreum node via
`geth --identity="Node01" --datadir="../Node01" -verbosity 6 --port 30301 -rpc --rpcport 8545 --rpcaddr localhost --rpccorsdomain "*" --rpcapi "db,eth,net,web3" --networkid="12345" --nodiscover console 2>> ./../target/Node01.log
`

Then the following code is working

`HttpService httpService = new HttpService("http://localhost:8545");
		Web3j web3 = Web3j.build(httpService);
		Web3ClientVersion web3ClientVersion;
		try {
			web3ClientVersion = web3.web3ClientVersion().sendAsync().get();
			String clientVersion = web3ClientVersion.getWeb3ClientVersion();
			System.out.println(clientVersion);
		} catch (InterruptedException | ExecutionException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}`

But when I call a smart contract coded in solidity and encapsulated via web3j-maven-plugin

I am getting the same error
`Credentials credentials = AccountManager.getInstance().getCredentials(0);
		// https://github.com/web3j/web3j/issues/117
		BigInteger GAS_PRICE = BigInteger.valueOf(20_000_000_000L);
		BigInteger GAS_LIMIT = BigInteger.valueOf(4_700_000);
		// BigInteger initialEtherValue = BigInteger.valueOf(0);
		this.dataQualifier = DataQualifier.deploy(Ethereum.getInstance().getWeb3j(), credentials, GAS_PRICE, GAS_LIMIT)
				.send();`


Error message:
 `java.lang.RuntimeException: org.web3j.protocol.exceptions.TransactionException: Error processing request: unknown transaction
	at org.web3j.tx.Contract.deploy(Contract.java:283)
	at org.web3j.tx.Contract.lambda$deployRemoteCall$5(Contract.java:315)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
	at com.cea.licia.blockchainergy.client.AbstractTestScenario.deployContracts(AbstractTestScenario.java:60)
	at com.cea.licia.blockchainergy.client.TestVoting.testScenario(TestVoting.java:36)
	at com.cea.licia.blockchainergy.client.TestVoting.<init>(TestVoting.java:30)
	at com.cea.licia.blockchainergy.client.TestVoting.main(TestVoting.java:22)
Caused by: org.web3j.protocol.exceptions.TransactionException: Error processing request: unknown transaction
	at org.web3j.tx.response.TransactionReceiptProcessor.sendTransactionReceiptRequest(TransactionReceiptProcessor.java:32)
	at org.web3j.tx.response.PollingTransactionReceiptProcessor.getTransactionReceipt(PollingTransactionReceiptProcessor.java:37)
	at org.web3j.tx.response.PollingTransactionReceiptProcessor.waitForTransactionReceipt(PollingTransactionReceiptProcessor.java:29)
	at org.web3j.tx.TransactionManager.processResponse(TransactionManager.java:72)
	at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:51)
	at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:70)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:223)
	at org.web3j.tx.Contract.create(Contract.java:252)
	at org.web3j.tx.Contract.deploy(Contract.java:281)
	... 6 more`

Any idea will be well come!

**Comment by amyodov** [comment]
@flefevre , I have (unconfirmed) suspicion that it may happen with recent Geth versions (1.8.0 and above). I recall I’ve seen my code working with 1.7.3/Rinkeby, while the same code fails completely with all such smart contract method calls on 1.8.0/Rinkeby (and I think, fails on 1.8.0/Mainnet as well).

What geth version are you using? This may be either some temporary issue in 1.8.0 (so it will be resolved later); or, if it is “a new geth way of life”, web3j may need to be updated to handle this; cause at the moment they are basically incompatible.

**Comment by flefevre** [comment]
hello,
personnaly, i was on geth 1.8.0
i have downloaded the git repository today and test with lastest version
INFO [02-02|21:07:28] Starting peer-to-peer node               instance=Geth/v1.8.0-unstable-fdb34b7a/linux-amd64/go1.8.3

I am still experiencing the problem.
I do not if it help you to determine where it comes but if I switch to the new UnixIpcService(GETH_IPC_PATH), it works. It seems to be specific to the new HttpService("http://localhost:8545")

I am sorry not to have additional idea, do not hesitate to ask me to test whatever you want.
Have a good week-end

**Comment by niyuelin1990** [comment]
I Have this problem too!!  I do  Contract  or Transaction   having this problem。  And  I used geth 1.7.2 or 1.7.3 or leater,   web3j 3.2.0  !   I  can not solve

**Comment by duvalCC** [comment]
Same problem .I start a private chain ,and run the [sample-project-gradle](https://github.com/web3j/sample-project-gradle) to integrate with it. Code like:

`TransactionReceipt transferReceipt = Transfer.sendFunds(
                web3j, credentials,
                "0xe80fbabee07b259fe36a950ef384abf401806eef",  // you can put any address here
                BigDecimal.ONE, Convert.Unit.WEI)  // 1 wei = 10^-18 Ether
                .send();
`
The transfer was successful. And an exception was returned as followed:

`D:\Java\java8\bin\java "-javaagent:E:\itellij\IntelliJ IDEA 2017.1.2\lib\idea_rt.jar=49712:E:\itellij\IntelliJ IDEA 2017.1.2\bin" -Dfile.encoding=UTF-8 -classpath D:\Java\java8\jre\lib\charsets.jar;D:\Java\java8\jre\lib\deploy.jar;D:\Java\java8\jre\lib\ext\access-bridge-64.jar;D:\Java\java8\jre\lib\ext\cldrdata.jar;D:\Java\java8\jre\lib\ext\dnsns.jar;D:\Java\java8\jre\lib\ext\jaccess.jar;D:\Java\java8\jre\lib\ext\jfxrt.jar;D:\Java\java8\jre\lib\ext\localedata.jar;D:\Java\java8\jre\lib\ext\nashorn.jar;D:\Java\java8\jre\lib\ext\sunec.jar;D:\Java\java8\jre\lib\ext\sunjce_provider.jar;D:\Java\java8\jre\lib\ext\sunmscapi.jar;D:\Java\java8\jre\lib\ext\sunpkcs11.jar;D:\Java\java8\jre\lib\ext\zipfs.jar;D:\Java\java8\jre\lib\javaws.jar;D:\Java\java8\jre\lib\jce.jar;D:\Java\java8\jre\lib\jfr.jar;D:\Java\java8\jre\lib\jfxswt.jar;D:\Java\java8\jre\lib\jsse.jar;D:\Java\java8\jre\lib\management-agent.jar;D:\Java\java8\jre\lib\plugin.jar;D:\Java\java8\jre\lib\resources.jar;D:\Java\java8\jre\lib\rt.jar;E:\技术资料\区块链\以太坊\sample-project-gradle\build\classes\main;E:\技术资料\区块链\以太坊\sample-project-gradle\build\resources\main;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\org.web3j\core\3.2.0\345c11e2c606eb056758924a6c7f0b06e22f6bf7\core-3.2.0.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\ch.qos.logback\logback-core\1.2.3\864344400c3d4d92dfeb0a305dc87d953677c03c\logback-core-1.2.3.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\ch.qos.logback\logback-classic\1.2.3\7c4f3c474fb2c041d8028740440937705ebb473a\logback-classic-1.2.3.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\org.web3j\abi\3.2.0\883947fbfe3647b19991d7995efe203f241d0517\abi-3.2.0.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\org.web3j\crypto\3.2.0\61fd9988e11475add81ad49bb7e97874dd3ae112\crypto-3.2.0.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\org.web3j\tuples\3.2.0\eb104bc7334af167bc05bfcc931428066dff1dad\tuples-3.2.0.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\com.github.jnr\jnr-unixsocket\0.15\caac6379cbcac9cfb5b63d719907b43861e8ac19\jnr-unixsocket-0.15.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\com.squareup.okhttp3\okhttp\3.8.1\4d060ca3190df0eda4dc13415532a12e15ca5f11\okhttp-3.8.1.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\com.squareup.okhttp3\logging-interceptor\3.8.1\feab46062803513d6a8307c74b0084265855de1a\logging-interceptor-3.8.1.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\io.reactivex\rxjava\1.2.4\522cfb00b6c015b72c64ee60054b4f6338880858\rxjava-1.2.4.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.25\da76ca59f6a57ee3102f8f9bd9cee742973efa8a\slf4j-api-1.7.25.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\org.web3j\utils\3.2.0\b4051cbc725de0d98156066ed33024303f73b32c\utils-3.2.0.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\org.web3j\rlp\3.2.0\f166db3343890d8f5356c5dc9422ad39b9118c98\rlp-3.2.0.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-databind\2.8.5\b3035f37e674c04dafe36a660c3815cc59f764e2\jackson-databind-2.8.5.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\com.github.jnr\jnr-ffi\2.1.2\627fff71439402c4b697a03026b1d733140a6b19\jnr-ffi-2.1.2.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\com.github.jnr\jnr-constants\0.9.6\84955256aa28919f12b6c7c9437ed65d814a3c0c\jnr-constants-0.9.6.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\com.github.jnr\jnr-enxio\0.14\a33f125337b270c9ba4cf1e84b40af405c5380f3\jnr-enxio-0.14.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\com.github.jnr\jnr-posix\3.0.33\86dd65d4c33c4a6c8c260ee256bfcfecd8c45bee\jnr-posix-3.0.33.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\com.squareup.okio\okio\1.13.0\a9283170b7305c8d92d25aff02a6ab7e45d06cbe\okio-1.13.0.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk15on\1.54\1acdedeb89f1d950d67b73d481eb7736df65eedb\bcprov-jdk15on-1.54.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-annotations\2.8.0\45b426f7796b741035581a176744d91090e2e6fb\jackson-annotations-2.8.0.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.8.5\60d059f5d2930ccd1ef03535b713fd9f933d1ba7\jackson-core-2.8.5.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\com.github.jnr\jffi\1.2.14\c5928f546442090dba86cd7bdc2b7561c3deb3aa\jffi-1.2.14.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\com.github.jnr\jffi\1.2.14\d8b010006d29b2db8fa4c498d6c3e508ad06b24a\jffi-1.2.14-native.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm\5.0.3\dcc2193db20e19e1feca8b1240dbbc4e190824fa\asm-5.0.3.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-commons\5.0.3\a7111830132c7f87d08fe48cb0ca07630f8cb91c\asm-commons-5.0.3.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-analysis\5.0.3\c7126aded0e8e13fed5f913559a0dd7b770a10f3\asm-analysis-5.0.3.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-tree\5.0.3\287749b48ba7162fb67c93a026d690b29f410bed\asm-tree-5.0.3.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-util\5.0.3\1512e5571325854b05fb1efce1db75fcced54389\asm-util-5.0.3.jar;C:\Users\Duval\.gradle\caches\modules-2\files-2.1\com.github.jnr\jnr-x86asm\1.0.2\6936bbd6c5b235665d87bd450f5e13b52d4b48\jnr-x86asm-1.0.2.jar org.web3j.sample.Application
14:53:32.862 [main] INFO  org.web3j.sample.Application - Connected to Ethereum client version: Geth/TestNode/v1.8.0-unstable-4dedde7b/linux-amd64/go1.8.3
14:53:35.125 [main] INFO  org.web3j.sample.Application - Credentials loaded
14:53:35.143 [main] INFO  org.web3j.sample.Application - Sending 1 Wei (0.000000000000000001 Ether)
Exception in thread "main" org.web3j.protocol.exceptions.TransactionException: Error processing request: unknown transaction
	at org.web3j.tx.response.TransactionReceiptProcessor.sendTransactionReceiptRequest(TransactionReceiptProcessor.java:32)
	at org.web3j.tx.response.PollingTransactionReceiptProcessor.getTransactionReceipt(PollingTransactionReceiptProcessor.java:37)
	at org.web3j.tx.response.PollingTransactionReceiptProcessor.waitForTransactionReceipt(PollingTransactionReceiptProcessor.java:29)
	at org.web3j.tx.TransactionManager.processResponse(TransactionManager.java:72)
	at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:51)
	at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:70)
	at org.web3j.tx.Transfer.send(Transfer.java:65)
	at org.web3j.tx.Transfer.send(Transfer.java:49)
	at org.web3j.tx.Transfer.lambda$sendFunds$20(Transfer.java:76)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
	at org.web3j.sample.Application.run(Application.java:81)
	at org.web3j.sample.Application.main(Application.java:51)

`

Here is the command that I start my private chain : 

`geth --identity "TestNode" --rpc --rpcapi "db,personal,eth,net,web3" --rpcaddr="0.0.0.0" --rpcport "8545" --rpccorsdomain "http://remix.ethereum.org" --datadir ./data  --port "30304" --networkid 2222 console 2>>my.log
`

**Comment by amyodov** [comment]
I got rid of this problem getting back to geth 1.7.3 stable; too bad that all the build procedures for go language assume building the master branch and thus build the 1.8.0 unstable only.

**Comment by duvalCC** [comment]
@amyodov When I change to  geth 1.7.3 stable , It works ! Thank you a lot!

**Comment by ucwong** [comment]
1.8.0 is not working well

**Comment by Daantie** [comment]
I upgraded geth to 1.8.1-stable, but also get the same error while using Transfer.sendFunds(). Geth v1.8.* doesn't seem to have a lot of features/bugfixes added over 1.7.3. Can anyone tell me the downsides of using the older 1.7.3 instead of 1.8.*?

**Comment by fcorneli** [comment]
The only way around this is to extend PollingTransactionReceiptProcessor yourself to retrieve the transactionHash of the newly deployed smart contract later on.
```
MyTransactionReceiptProcessor transactionReceiptProcessor = new MyTransactionReceiptProcessor(admin);
TransactionManager transactionManager = new ClientTransactionManager(admin, account, transactionReceiptProcessor);
MyContract.deploy(admin, transactionManager, MyContract.GAS_PRICE, MyContract.GAS_LIMIT, "hello world").sendAsync();
String transactionHash = null;
while (null == transactionHash) {
    transactionHash = transactionReceiptProcessor.getTransactionHash();
    Thread.sleep(1000);
}
```

It should definitely be easier than the above to deploy a contract and get its transaction hash.

**Comment by Daantie** [comment]
Just tested what @allquantor has pointed out: constructing the transaction manually and this works (at least for sending Ether) without errors. @duvalCC This will help you too!

**Comment by fcorneli** [comment]
@Daantie "constructing the transaction manually"... so what's the point of the wrappers then?

**Comment by chernikovmaksym** [comment]
I faced the same problem on 1.8.* geth. Works fine with 1.7.2.

**Comment by mawenpeng** [comment]
In geth 1.8.0/1.8.1, eth.getTransactionReceipt() returns "Error: unknown transaction" instead of null if the transaction is not mined. This make web3j throws exception.
Filed an issue to go-ethereum: https://github.com/ethereum/go-ethereum/issues/16213
@conor10 Any ideas? Thanks.

**Comment by Daantie** [comment]
@fcorneli in this case they're useless, I was just pointing at a workaround. The current Web3j version (v3.2.0 - mid Dec) is older than the v1.8.* Geth (new since 2 weeks). I guess you should stick with Geth 1.7.3 if you want to work with the wrappers and wait for new Web3j version, or use the workaround and go for Geth 1.8.*.

**Comment by mawenpeng** [comment]
We may pull the fix in https://github.com/ethereum/go-ethereum/pull/16217

**Comment by amyodov** [comment]
ethereum/go-ethereum#16217 indeed seems to resolve this issue completely.

**Comment by fcorneli** [comment]
@amyodov yep... also verified it already. Can properly use contract wrappers again now.
