### ISSUE TITLE
Not receiving mined transactions on transactionObservable until Parity is restarted

### ISSUE THREAD

**Issue by vn-linescode** [web3j/web3j#322]
Hello all!

I'm having an issue with the transactionObservable request. I don't receive transaction message untill I restart Parity.

How to replicate the issue:
1. Create an ewallet
2. Credit some ether
3. Subscribe to pendingTransactionObservable()
4. Subscribe to transactionObservable()
5. Send a transaction
6. You will receive a pending transaction to pendingTransactionObservable() callback
7. Transaction is mined and confirmed
8. Wait a reasonable time
9. You will not receive the transaction to transactionObservable() callback
10. Restart Parity
11. You will not receive the transaction to transactionObservable() callback

This seems very strange, i'm not getting why this happen, and if it is a bug of web3j or Parity.

I hope we can solve the issue together, thank you so much in advance.

My code:
```
Subscription subscription = web3j.transactionObservable().subscribe(tx -> {
	... my code here ...
});

Subscription subscription2 = web3j.pendingTransactionObservable().subscribe(tx -> {
	... my code here ...
});
```

**Comment by vn-linescode** [comment]
Using geth as RPC provide this issue is not in place. I'm pretty sure parity caused the issue.

**Comment by AlexandrouR** [comment]
Is this still an issue ?

**Comment by AlexandrouR** [comment]
Issue closed due to inactivity.
