### ISSUE TITLE
Support for async transaction signing.

### ISSUE THREAD

**Issue by benjumanji** [web3j/web3j#328]
Hi would you be open to a pull request that allowed keypair to complete a signature with a callback?

Use case: Using hashicorp vault's transit backend to do signing.

Obviously I can write this code myself, but if I did it might be nice to have in  web3j directly.

**Comment by conor10** [comment]
Hey Ben, absolutely.

**Comment by benjumanji** [comment]
Thanks! Expect a pr in the next week or so.
