### ISSUE TITLE
How do I retrieve the logs of a transaction?

### ISSUE THREAD

**Issue by lxjhk** [web3j/web3j#329]
Given a random block, I would like to retrieve the logs corresponding to each transaction contained in the block. Does anyone know if the current implementation of Web3j supports this?

It seems that the JSON-RPC method `eth_getTransactionReceipt` supports this but I could not find the corresponding method calls in Web3j.

https://github.com/paritytech/parity/wiki/JSONRPC-eth-module#eth_gettransactionreceipt

**Comment by iikirilov** [comment]
`EthGetTransactionReceipt transactionReceipt = web3j.ethGetTransactionReceipt(transactionHash).send();`
