### ISSUE TITLE
Git mess in shipit build folder

### ISSUE THREAD

**Issue by oscarguindzberg** [web3j/web3j#337]
Files were pushed twice

https://github.com/web3j/web3j/tree/2c877d7c72e1b2d7dfded521e9ac271e892bf144/codegen/src/test/resources/solidity/shipit/build

<img width="777" alt="screen shot 2018-01-25 at 13 15 43" src="https://user-images.githubusercontent.com/1145132/35398990-039f4442-01d2-11e8-84d2-6ece9ef8b98e.png">

**Comment by oscarguindzberg** [comment]
There is ShipIt with uppercase I and Shipit with lowecase i

**Comment by iikirilov** [comment]
duplicate #364
