### ISSUE TITLE
How could I inject metamask in a java web project?

### ISSUE THREAD

**Issue by littleredhat1997** [web3j/web3j#339]
I know web3.js can inject metamask(a google's ethereum plugin) very easy, but I couldn't find a way to inject metamask in web3j......
If web3j do not have this function, how can user provide their wallet from browser.....upload the wallet file or just run the web porject in local host?

**Comment by eepstein** [comment]
You mean like in a Java Applet running in a browser?  (I'm having flashbacks to 1996.)

Web3j is for Java.  Java is mostly used for server side and desktop apps at this point.  
MetaMask is a browser plugin.
What you probably want is to connect to the systems that are behind MetaMask, namely the Infura services.  And connecting to those from Web3j are, in the immortal words of K-9: piece of cake, Doctor.

**Comment by eepstein** [comment]
If you're using something like GWT (or Vaadin) then you'd want to wrap web3.js (JavaScript) and interact with that.

**Comment by littleredhat1997** [comment]
@eepstein oh, thanks, let me study the Infura's document.
