### ISSUE TITLE
Restore private key from seed

### ISSUE THREAD

**Issue by 6epreu** [web3j/web3j#340]
Hello web3j dev team,

Im wondering if library has ability to restore private key from seed/phrase. (or any plans on future)
Now WalletUtils provides only ability to restore private key from exported file ( if Im not mistaking it's a MIST's file format)

Also IMHO right now WalletUtils has not enough functions in interface to restore private key. 
F.e. I can only restore from file
`credentials = WalletUtils.loadCredentials("1234qwer/", file.getAbsoluteFile());`

I would like ability to restore it from string also ( maybe InputStream and other popular java input interfaces)

Thanks in advance for response.

**Comment by conor10** [comment]
Mnemonics are now supported as of web3j 3.3.1, see MnemonicUtils for details.
