### ISSUE TITLE
OOM while generateFullNewWalletFile 

### ISSUE THREAD

**Issue by 6epreu** [web3j/web3j#342]
ScreenShot will describe all
Also please provide documentation what it difference between generating lightNewWallet and FullNewWallet 
![2018-01-29_17-29-17](https://user-images.githubusercontent.com/1928745/35515355-fcf393aa-0519-11e8-8848-3c97777f651a.png)

**Comment by 6epreu** [comment]
Additional info
Huawei p10 lite 
Android 7.0

**Comment by Jevis** [comment]
How did you solve it？

**Comment by 6epreu** [comment]
I have started to generate lightWallet

**Comment by yuriymyronovych** [comment]
You can't use FullNewWallet generation on android, it requires a proper PC with good CPU & RAM. That's the reason lightNewWallet was created. It uses different settings for key derivation algo that requires less CPU/RAM.

**Comment by MartinWang2** [comment]
If i import the full wallet, what can i do?

**Comment by yuriymyronovych** [comment]
Just get a private key and import it, dont use file.
