### ISSUE TITLE
WalletUtils.generateBip39Wallet fails when library is used as .jar in a project

### ISSUE THREAD

**Issue by Zurvarian** [web3j/web3j#343]
I've testing the recently new added functionality to allow creation of Wallets from BIP39 mnemonics, and during testing I've found that there is an issue with loading the list of words from the file.

Problem is that current piece of code

~~~
private static List<String> populateWordList() {
        URL url = Thread.currentThread().getContextClassLoader()
                .getResource("en-mnemonic-word-list.txt");
        try {
            return Files.readAllLines(Paths.get(url.toURI()));
        } catch (Exception e) {
            return Collections.emptyList();
        }
    }
~~~

Is trying to load the file as if it is a system file, which if contained inside a .jar won't work.

I've created an alternative snippet of code, I'm using Java 8 so not sure if 100% compatible with Android, that works:

~~~
InputStream inputStream = Thread.currentThread().getContextClassLoader().getResourceAsStream("en-mnemonic-word-list.txt");
        try (Scanner scanner = new Scanner(inputStream, StandardCharsets.UTF_8.name())) {

            List<String> lines = new ArrayList<String>();
            while (scanner.hasNext()) {
                lines.add(scanner.nextLine());
            }

            System.out.println(lines);
        }
~~~

**Comment by conor10** [comment]
New release for Java and Android has gone out with this support.

**Comment by dhruvi1kosmos** [comment]
@conor10 i have used implementation 'org.web3j:core:3.3.1-android' still i m facing issue .MnemonicUtils.class is not updated in jar.kindly help
