### ISSUE TITLE
can't find wallet file on Mac OSX

### ISSUE THREAD

**Issue by minhphuong1894** [web3j/web3j#344]
Hi web3j
i have a problem with use web3j library in android
when i use web3j wallet create on terminal , i enter password and keystore
and i get : 
Please enter a destination directory location [/Users/minhphuong/Library/Ethereum/testnet/keystore]: 111111
Wallet file UTC--2018-01-31T04-38-39.422000000Z--90508afce56b37b39288e5e66d045097a7593c44.json successfully created in: 111111
but i don't know where i can find it
to intergate with 
credentials =WalletUtils.loadCredentials(
                            "111111", "/path/to/UTC--2018-01-31T04-38-39.422000000Z--90508afce56b37b39288e5e66d045097a7593c44.json");
please , help me !
thanks so much

**Comment by 6epreu** [comment]
/Users/minhphuong/Library/Ethereum/testnet/keystore 
I think this is a correct path

**Comment by minhphuong1894** [comment]
i try to connect /Users/minhphuong/Library/Ethereum/testnet/keystore
but i can't see wallet file ? it's just empty

**Comment by kiingGma** [comment]
You woke up so early？

**Comment by minhphuong1894** [comment]
i don't understand you say ?
can you explain for me ?

**Comment by kiingGma** [comment]
you can try to remove .json

**Comment by minhphuong1894** [comment]
i can't find the xx.json on folders ? i show folders hide but not have

**Comment by iikirilov** [comment]
Could you try loading from `"/path/to/UTC--2018-01-31T04-38-39.422000000Z--90508afce56b37b39288e5e66d045097a7593c44"` - without `.json` at the end

**Comment by conor10** [comment]
Please reopen if you are still facing issues.
