### ISSUE TITLE
Any equivalent methods to eth.accounts.sign?

### ISSUE THREAD

**Issue by tempofeng** [web3j/web3j#347]
Hi, I'm trying out webj3 and wondering if there is anything equivalent to **eth.accounts.sign** in web3js?
what I want to do is signing a message like:
```
web3.eth.accounts.sign('Some data', '0x4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318');
> {
    message: 'Some data',
    messageHash: '0x1da44b586eb0729ff70a73c326926f6ed5a25f5b056e7f47fbc6e58d86871655',
    v: '0x1c',
    r: '0xb91467e570a6466aa9e9876cbcd013baba02900b8979d43fe208a4a4f339f5fd',
    s: '0x6007e74cd82e037b800186422fc2da167c747ef045e5d18a5f5d4300f8e1a029',
    signature: '0xb91467e570a6466aa9e9876cbcd013baba02900b8979d43fe208a4a4f339f5fd6007e74cd82e037b800186422fc2da167c747ef045e5d18a5f5d4300f8e1a0291c'
}
```
Thanks!!

**Comment by iikirilov** [comment]
Refer to the documentation [here](https://docs.web3j.io/transactions.html#signing-transactions).

**Comment by tempofeng** [comment]
@iikirilov this is signing of a raw transaction, but what I want to know is signing of a block of text.

**Comment by iikirilov** [comment]
@tempofeng I can't find a corresponding JSON RPC call that will fulfill this function. 

[This](https://github.com/ethereum/wiki/wiki/JSON-RPC) is where those JSON RPCs are defined. The closest is eth_sign which is supported `web3j.ethSign(String address, String sha3HashOfDataToSign)` however this takes different arguments.

Also from reading [here](https://ethereum.stackexchange.com/questions/35425/web3-js-eth-sign-vs-eth-accounts-sign-producing-different-signatures?rq=1) it seems that eth_sign will not produce the correct signature. Either way, it will not return the extra signature values that eth.accounts.sign will.

Parity also provides a personal_signMessage which is also supported but I assume it works the same way as eth_sign.

**Comment by tempofeng** [comment]
@iikirilov Thanks for the explanation. Will probably implement it on my own and send a PR after I figure out what's the difference between them. 👍

**Comment by qoire** [comment]
Hi, is this feature still being worked on? I'm also interested in getting something like this implemented.

Also to note the article @iikirilov linked, it seems that the reverse is actually true. It seems that web3.eth.accounts.sign() uses an implementation from eth-lib, which defaults to the original ``v`` values of ``27``, ``28``.

https://github.com/MaiaVictor/eth-lib/blob/d959c54faa1e1ac8d474028ed1568c5dce27cc7a/lib/account.js#L38-L43

**Comment by tempofeng** [comment]
@qoire No, sorry I don't have time to work on this yet.
