### ISSUE TITLE
Failed to connect to localhost/127.0.0.1:8545

### ISSUE THREAD

**Issue by minhphuong1894** [web3j/web3j#348]
i run 
 Admin web3j = AdminFactory.build(new HttpService());  // defaults to http://localhost:8545/
        PersonalUnlockAccount personalUnlockAccount = null;
        try {
            personalUnlockAccount = web3j.personalUnlockAccount("0xf59301d89054ed72402346b49f6b9f593613e280", "phuong0").sendAsync().get();
            Toast.makeText(this, personalUnlockAccount.getId()+"", Toast.LENGTH_SHORT).show();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        }
        if (personalUnlockAccount.accountUnlocked()) {
            // send a transaction
        }
but web3j can't  connect to localhost/127.0.0.1:8545
i work on android studio 
please help me,
thanks so much

**Comment by conor10** [comment]
What client are you using, and what arguments did you use to start it?

**Comment by cweiers** [comment]
I have a similar situation: I try to connect from a Spring Boot service to a local ganache chain on 127.0.0.1:8545 (ganache version 1.3.0).
I use 
`web3j = Web3j.build(new HttpService());`
to build my web3 object.
This results in the following output:

 

> 2019-02-26 10:11:57.725 ERROR 1 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
> 
> java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8545
>         at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:225) ~[okhttp-3.8.1.jar!/:na]
>         at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149) ~[okhttp-3.8.1.jar!/:na]
>         at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195) ~[okhttp-3.8.1.jar!/:na]
>         at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121) ~[okhttp-3.8.1.jar!/:na]
>         at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100) ~[okhttp-3.8.1.jar!/:na]
>         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[okhttp-3.8.1.jar!/:na]
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:na]
>         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.8.1.jar!/:na]
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:na]
>         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.8.1.jar!/:na]
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
>         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) ~[okhttp-3.8.1.jar!/:na]
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:na]
>         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) ~[okhttp-3.8.1.jar!/:na]
>         at okhttp3.RealCall.execute(RealCall.java:69) ~[okhttp-3.8.1.jar!/:na]
>         at org.web3j.protocol.http.HttpService.performIO(HttpService.java:151) ~[core-4.1.1.jar!/:na]
>         at org.web3j.protocol.Service.send(Service.java:34) ~[core-4.1.1.jar!/:na]
>         at org.web3j.protocol.core.Request.send(Request.java:72) ~[core-4.1.1.jar!/:na]
>         at org.web3j.tx.RawTransactionManager.getNonce(RawTransactionManager.java:77) ~[core-4.1.1.jar!/:na]
>         at org.web3j.tx.RawTransactionManager.sendTransaction(RawTransactionManager.java:95) ~[core-4.1.1.jar!/:na]
>         at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:49) ~[core-4.1.1.jar!/:na]
>         at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:87) ~[core-4.1.1.jar!/:na]
>         at org.web3j.tx.Contract.executeTransaction(Contract.java:291) ~[core-4.1.1.jar!/:na]
>         at org.web3j.tx.Contract.executeTransaction(Contract.java:275) ~[core-4.1.1.jar!/:na]
>         at org.web3j.tx.Contract.executeTransaction(Contract.java:269) ~[core-4.1.1.jar!/:na]
>         at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$3(Contract.java:321) ~[core-4.1.1.jar!/:na]
>         at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30) ~[core-4.1.1.jar!/:na]
> 

If I change it up a bit and try to build my web3 object like this:
`web3j = Web3j.build(new HttpService("http://127.0.0.1:8545/"));`
I get "Failed to connect to /127.0.0.1:8545"

Connecting to an infura endpoint works without any problems. 

If you need any other logging/tests/output, let me know.

**Comment by hd51515** [comment]
i have the same issue with my application which uses infura node. all components except web3j are UP. looks like the error message is coming from https://github.com/web3j/web3j-spring-boot-starter/blob/master/src/test/java/org/web3j/spring/autoconfigure/Web3jAutoConfigurationTest.java: testHealthCheckIndicatorDown() method

"web3j": {
            "status": "DOWN",
            "details": {
                "error": "java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8545"
            }

**Comment by AlexandrouR** [comment]
Is this still an issue with using the latest version ?

**Comment by AlexandrouR** [comment]
Issue closed due to inactivity.

**Comment by srdharan** [comment]
> Issue closed due to inactivity.

I have this oissue with latest version

**Comment by bishwas7** [comment]
Instead using this  <http://localhost:8545/> try your ip address which is in your computer such as  <192.168.123.1> and the port number

**Comment by JackBekket** [comment]
same problem

**Comment by jpgpuyo** [comment]
It is difficult to understand why the issue is closed if the issue is still present...

**Comment by MrGrizz** [comment]
I had the same problem and finally founded this issue, and thanks to @bishwas7 I realized that I try to connect to Ganache from docker container. Maybe it help someone else - if you run your app in docker and use localhost:8545 it doesn't work because inside docker container localhost refer to container itself. The best approach in this case is to run Ganache also as a docker container.
