### ISSUE TITLE
Obserables throw an Invalid Response Error

### ISSUE THREAD

**Issue by allquantor** [web3j/web3j#350]
Getting
```
Invalid response received: okhttp3.internal.http.RealResponseBody@b967d04
```
By trying to use of
```
web3Client.pendingTransactionObservable ...
or 
web3Client.transactionObservable...
```
Testing on ropsen infura testnetwork. Non-reactive calls that does not involve RxJava work well.
Any ideas on this?

**Comment by yanyanho** [comment]
I encountered this too. 
Yet I call this function ,
 web3j.catchUpToLatestTransactionObservable(new DefaultBlockParameterNumber(2576860)).subscribe(block -> System.out.println("*+observer+getblock" + block.getBlockNumber()));
It works

**Comment by allquantor** [comment]
It is possible, that infura ropsten network have a limit for only one client. Following scenario:
- Use exclusively one Infura Web3j Client instance in your code
- Get Infura Token by registering at infura homepage  
- User the client only for subscribing 
= Works for me.
Another good solution is to bring up your own Geth node.
