### ISSUE TITLE
Incorrect events filtering by indexed fields

### ISSUE THREAD

**Issue by 4ntoine** [web3j/web3j#354]
If i have 2 fields marked as indexed, no event is fired (found in tx).
https://stackoverflow.com/questions/48630389/multiple-indexed-event-fields-are-not-supported-by-web3j

**Comment by conor10** [comment]
This is a known [issue](https://github.com/web3j/web3j/issues/209). You can work around it by ensuring all indexed fields are stated before non-indexed.

**Comment by 4ntoine** [comment]
Thanks
