### ISSUE TITLE
any reference to use this for iOS Project

### ISSUE THREAD

**Issue by Abhishek-NickelFox** [web3j/web3j#357]

**Comment by iikirilov** [comment]
This is a Java project. If you can figure out how to write iOS apps in Java, then you can read the documentation [here](https://docs.web3j.io).

This [Multi-OS-Engine](https://github.com/multi-os-engine/multi-os-engine) for writing cross-platform apps in Java is a good starting point.

Alternatively, you can check out [web3swift](https://github.com/MercuryProtocol/web3.swift) which is probably more appropriate.
