### ISSUE TITLE
How to create new account using web3j ?

### ISSUE THREAD

**Issue by RakeshSainiRk** [web3j/web3j#358]
is see there is no class for (web3.personal.newAccount()) ... am i missing somthing or its not there ? if not then what can be the alternative ?

**Comment by iikirilov** [comment]
This is possible. Refer to the documentation [here](https://docs.web3j.io/management_apis.html).

You can also use the CLI to do this. Refer [here](https://docs.web3j.io/command_line.html#wallet-tools).

**Comment by RakeshSainiRk** [comment]
thank you so much @iikirilov

**Comment by wjrmffldrhrl** [comment]
I want same things but there are no information

did you solved it?
