### ISSUE TITLE
(org.web3j.codegen) Unnecessary *.bin file requirement in order to generate Wrapper for the contract

### ISSUE THREAD

**Issue by yuriymyronovych** [web3j/web3j#360]
Hello, if I am not mistaken .bin file is not necessary in order to generate contract Wrapper(org.web3j.codegen), it is only needed to deploy the contract. I believe there should be a way/option for org.web3j.console.Runner to generate wrapper based on abi in order to interact with remote contract that you don't have code for.

I can think of 3 ways how this can be achieved, can you let me know which one you prefer?
1. make *.bin optional and, if not provided, than 'deploy' method won't be generated
2. remove *.bin from input params and always generate 'deploy' method that would take File (path to bin) as an input param.
3. split existing generated Wrapper into 2 classes - one for interacting with remote contract(bin not needed) and another one for deploying(bin required)

anything I missed?

I am happy to work on PR for this change. Let me know what do you think guys(@conor10 ).

**Comment by conor10** [comment]
Sounds good.

I think go with option 1 for now to maximise backward compatibility.
