### ISSUE TITLE
Unlock wallet address with private key

### ISSUE THREAD

**Issue by redserpent7** [web3j/web3j#362]
Hi,

I am checking the WalletUtils class and I can only see a way to open password locked wallet files. Is there a way to open existing mainnet wallets using the private key?

**Comment by lasrie** [comment]
Hi,

Sure, you can just create a new ECKeypair, which you then use to create a new wallet file.
E.g:

`ECKeyPair keypair = ECKeyPair.create(privateKey)
WalletUtils.generateWalletFile("SUPERSAFEPASSWORD", keypair, new File(WALLETSAVEPATH), true)
`

**Comment by iikirilov** [comment]
Please use [gitter](https://gitter.im/web3j/web3j?utm_source=share-link&utm_medium=link&utm_campaign=share-link) for usage questions.
