### ISSUE TITLE
Resource conflict with other libraries

### ISSUE THREAD

**Issue by liorregev** [web3j/web3j#365]
I believe you should avoid having resources in the root of the 'resources' directory since it is not specific to you library and a class-loader could fetch the wrong one if multiple libraries do this.

For example: your 'version.properties' resource conflict with the one in https://github.com/ethereum/ethereumj and therefore causes NullPointerException 
I have opened a similar [issue](https://github.com/ethereum/ethereumj/issues/1008) on that repo, but I think it should be fixed in both

**Comment by iikirilov** [comment]
Thanks for bringing up this issue. It was resolved in ethereumj with [this](https://github.com/ethereum/ethereumj/pull/988/commits/ebffb20b8a43ac3cfc71ce3e2cd051ecf3e617ab) commit.
@conor10 any other thoughts on this?

**Comment by fcorneli** [comment]
Maybe rename "version.properties" to "web3j-version.properties" to prevent conflicts with yet other libraries too?
