### ISSUE TITLE
Generated Contract Java File Error

### ISSUE THREAD

**Issue by skajake** [web3j/web3j#369]
The generated java code from the command line tool contains lines with parameterized List.class references which produce compile errors:

`return executeRemoteCallSingleValueReturn(function, List<BigInteger>.class);`

> List cannot be resolved to a variable
> BigInteger cannot be resolved to a variable

**Comment by iikirilov** [comment]
Could you provide steps to reproduce this?

**Comment by skajake** [comment]
In my case I compiled a truffle contract, but I got the same result using the .bin and .abi files.

`truffle generate build/contracts/MyContract.json -o java/ -p com.myorg`

The contract contains method which return arrays of uint256 like this:

`{
      "constant": true,
      "inputs": [
        {
          "name": "index",
          "type": "uint256"
        }
      ],
      "name": "myData",
      "outputs": [
        {
          "name": "_myData",
          "type": "uint256[10]"
        }
      ],
      "payable": false,
      "stateMutability": "view",
      "type": "function"
    }`

This method signature, and any other methods which return arrays of numbers generate the following line of code in the generated java file:

`return executeRemoteCallSingleValueReturn(function, List<BigInteger>.class);`

**Comment by skajake** [comment]
I think the error is caused by type erasure, it seems like any contract method that returns an array will suffer this fate.

**Comment by mawenpeng** [comment]
Please see #303 #238

**Comment by conor10** [comment]
Please can you confirm if this is still an issue with web3j 3.3.1, and reopen if so.

**Comment by mawenpeng** [comment]
I don't see such issues with 3.3.1.
