### ISSUE TITLE
Android Ethereum Node

### ISSUE THREAD

**Issue by VictorAlbertos** [web3j/web3j#37]
Hi @conor10. Thanks for this amazing library.

I have a question. This isn't a light node designed to be run on Android devices, right? You will need to connect to a centralized node hosted in some remote server. 

Thanks.

**Comment by conor10** [comment]
Thanks for your kind words @VictorAlbertos.

That's correct it's an integration layer that supports Java & Android, but you still need a centralised node to connect to. Infura is great for this if you don't require filter support.

**Comment by VictorAlbertos** [comment]
Thanks for the explanation :)
