### ISSUE TITLE
Advice: how to explore a transaction

### ISSUE THREAD

**Issue by flefevre** [web3j/web3j#370]
Dear web3j community,
I did''t find any example where given a transaction hash we can explore the content of the transcation with web3j (from, to, ether, input data etc...)
Is there any example?

My goal is given a blocknumber, list all transactions, and display for each of them the from, to and also the data sent.

/Thanks

**Comment by iikirilov** [comment]
```
EthBlock.Block b = web3j.ethGetBlockByNumber(
        DefaultBlockParameter.valueOf(
                BigInteger.valueOf(1000)),
                true)
        .send().getBlock();

b.getTransactions().forEach(transactionResult -> {
    Transaction transaction = (Transaction) transactionResult;
    System.out.println(transaction.getFrom());
    ...
});
```

**Comment by flefevre** [comment]
Thanks a lot for your answer.
Thanks for your reactivity !

Perhaps we could add these lines in the basic documentaiton of web3j

Have a good day.

**Comment by iikirilov** [comment]
Please post usage question in [gitter](https://gitter.im/web3j/web3j)
