### ISSUE TITLE
Deploy Newest Version of Android Library

### ISSUE THREAD

**Issue by coreycaplan3** [web3j/web3j#379]
The current deployed version of the Android library (org.web3j:core:3.1.1-android) does not have some of the functionality I need. Specifically, creating/recovering a  Bip39 wallet and other features that have already been merged into the master branch.

When can we expect to see the newest version deployed on Android?

**Comment by CosimoSguanci** [comment]
I also need this feature.

**Comment by iikirilov** [comment]
Release will come on Monday :100:

**Comment by coreycaplan3** [comment]
Great, I'll close this issue when you make the release.

**Comment by coreycaplan3** [comment]
@iikirilov Was that release for Android, or just the core library?

**Comment by iikirilov** [comment]
@coreycaplan3 sorry for delay, core and android are being released right now. I blame the snow.

**Comment by coreycaplan3** [comment]
@iikirilov What's the version number? I can close the issue afterward then!

**Comment by coreycaplan3** [comment]
@iikirilov Sorry being a pain. I can see that you released the core version today. What's going on with the Android version? Its last update is still 2 months ago.

**Comment by HaiChecker** [comment]
@iikirilov When is it possible to have a new version?

**Comment by conor10** [comment]
v3.3.1-android has been released.
