### ISSUE TITLE
Decode transaction input data

### ISSUE THREAD

**Issue by mantoshelis** [web3j/web3j#380]
Is there any way to decode input data provided by Parity trace because I can't find any utilities in Web3j to do so.

For example, If i have this: 
`"input":"0xa9059cbb000000000000000000000000003b10c657f494d17bac0ec3df32f5ac2de86df900000000000000000000000000000000000000000000000000000000000000c8"`

I would like it to decode to readable format (json or other):
```
Function: transfer(address _to, uint256 _value)

MethodID: 0xa9059cbb
[0]:000000000000000000000000003b10c657f494d17bac0ec3df32f5ac2de86df9
[1]:00000000000000000000000000000000000000000000000000000000000000c8
```

**Comment by iikirilov** [comment]
Please submit usage questions in [gitter](https://github.com/web3j/web3j/blob/master/geth/src/main/java/org/web3j/protocol/geth/Geth.java)
