### ISSUE TITLE
How to execute miner.start() using web3j?

### ISSUE THREAD

**Issue by IcyLemon** [web3j/web3j#381]
Hi,
My environment is:
geth client node: Windows 10, 64
geth version: 1.7.3-stable
web3j version: 3.2.0

I encountered a problem, When I deploy a smart contract using web3j as follows:
```
// deploy a contract called counter
Counter counter = Counter.deploy(web3j, credentials, GAS_PRICE, GAS_LIMIT).send();
// get the address of contract
String contractAddress = counter.getContractAddress();
```
I found that once Counter.deploy(...) was executed, the following messages appeared on the console of the geth client node web3j connected:
> INFO [02-23|16:38:01] Submitted contract creation              fullhash=0x06fd8da755e0f46824f777a034bef97ae264608310bc3a88a181a38664e1bb65 contract=0xE0919e456ED15a0d59a13f56931039eDA3E9514a

Then the web3j java code blocked. **Only after I manually executed the following command on the console of the geth client node, the contract was deployed successfully**:
> miner.start(1);admin.sleepBlocks(1);miner.stop();

So my question is that **how to execute miner.start() in web3j so that I need not to manually execute it on the console of the geth client node** ?

Thanks a lot.

**Comment by IcyLemon** [comment]
Hi iikirilov,
Thank you for your prompt reply!

I found that there were 3 parameters in parity.ethSubmitWork():
`parity.ethSubmitWork(String nonce, String headerPowHash, String mixDigest)
`
What do these parameters mean, and how to use this API to implement the function of miner.start()/stop, could you tell me the more details ? 

Additionally, I read Geth.java you provided but don‘t find the related built-in miner API:
```
public Request<?, PersonalImportRawKey> personalImportRawKey(String keydata, String password);
public Request<?, BooleanResponse> personalLockAccount(String accountId);
public Request<?, PersonalSign> personalSign(String message, String accountId, String password);
public Request<?, PersonalEcRecover> personalEcRecover(String message, String signiture);
```
Thanks.

**Comment by iikirilov** [comment]
@IcyLemon Just to clarify, you are using a private blockchain to test this where no other node is mining?

Parity does not have a miner so you need to install a third-party app. More info [here](https://github.com/paritytech/parity/wiki/Mining).

Geth has a `miner_start` function. This need to be implemented in web3j from the class noted above. More info [here](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#miner). It would be useful to implement all the functions in the `miner` namespace.

**Comment by IcyLemon** [comment]
@iikirilov 
Yes, I use a private blockchain and only one node to test, as follows:
`geth --rpc --rpccorsdomain "*" --datadir "data" --port "34567" --rpcapi "personal,db,eth,net,web3" --networkid 100000 console`

I will try according to your advice immediately.

Thanks a lot.

**Comment by IcyLemon** [comment]
@iikirilov
According to your advice, I implemented miner.start()/stop() in web3j as follows:
```
public class MyWeb3jImpl extends JsonRpc2_0Web3j implements MyWeb3j {
    public MyWeb3jImpl(Web3jService web3jService) {
        super(web3jService);
    }
    
    @Override
    public Request<?, MinerStartResponse> minerStart(int threadCount) {
        return new Request<>(
                "miner_start",
                Arrays.asList(threadCount),
                web3jService,
                MinerStartResponse.class);
    }
    
    @Override
    public Request<?, BooleanResponse> minerStop() {
        return new Request<>(
                "miner_stop",
                Collections.<String>emptyList(),
                web3jService,
                BooleanResponse.class);
    }
```
Currently they worked fine!

**Comment by iikirilov** [comment]
Please open a PR so we can add this to the project with all of the `miner` function and include tests. It would make sense to add this directly to the `Geth` interface and `JsonRpc2_0Geth` implementation as these functions are specific to geth.

**Comment by mushketyk** [comment]
Hi @IcyLemon, are you still working on this?

**Comment by 0642himanshu** [comment]
> @iikirilov
> According to your advice, I implemented miner.start()/stop() in web3j as follows:
> 
> ```
> public class MyWeb3jImpl extends JsonRpc2_0Web3j implements MyWeb3j {
>     public MyWeb3jImpl(Web3jService web3jService) {
>         super(web3jService);
>     }
>     
>     @Override
>     public Request<?, MinerStartResponse> minerStart(int threadCount) {
>         return new Request<>(
>                 "miner_start",
>                 Arrays.asList(threadCount),
>                 web3jService,
>                 MinerStartResponse.class);
>     }
>     
>     @Override
>     public Request<?, BooleanResponse> minerStop() {
>         return new Request<>(
>                 "miner_stop",
>                 Collections.<String>emptyList(),
>                 web3jService,
>                 BooleanResponse.class);
>     }
> ```
> Currently they worked fine!

hii @IcyLemon 
I have implemented this as follows

public class CustomMiner extends JsonRpc2_0Web3j implements Geth {
    public CustomMiner(Web3jService web3jService) { 
        super(web3jService);
    }
    
    @Override
    public Request<?, MinerStartResponse> minerStart(int threadCount) {
        return new Request<>(
                "miner_start",
                Arrays.asList(threadCount),
                web3jService,
                MinerStartResponse.class);
    }
}

buts its not working

**Comment by tjanson** [comment]
@0642himanshu Details on how it doesn’t work? What client are you using (geth?) and how are you starting it? Are you sure the mining API is available? (Can you start it using `geth attach`?)

**Comment by 0642himanshu** [comment]
@tjanson 
I am using geth Client
CustomMiner cus = new CustomMiner(new Httpservice("httpprovider"));
cus .minerStart(2).send();

but not working

how we can get mining API?

**Comment by iikirilov** [comment]
Please do not revive closed threads. This issue has been solved and Pr has been merged to that effect. If you have further issues people open a new one.
