### ISSUE TITLE
Fail to connect to NOT localhost node using new HttpService("ip:8545") ?

### ISSUE THREAD

**Issue by IcyLemon** [web3j/web3j#382]
My code is as below:
`Web3j web3j = Web3j.build(new HttpService());`
It works fine because defaults to localhost:8545

But when I try to connect to another node(e.g. 11.177.51.101:8545) as follows:
`Web3j web3j = Web3j.build(new HttpService("http://11.177.51.101:8545")`
The error occured:
java.lang.RuntimeException: java.net.ConnectException: Failed to connect to /11.177.51.101:8545

I am sure that I can ping 11.177.51.101 and the port 8545 is opened in the firewall and the geth client node in 11.177.51.101 started normally with HTTP endpoint opened: http://127.0.0.1:8545

BTW: 11.177.51.101 is CentOS 7.2 64, web3j is in Windows 10 64.

So what's wrong with that?

Hope your help, thanks.

**Comment by iikirilov** [comment]
can you do `geth attach http://11.177.51.101:8545` on the same machine you are trying to run web3j and let me know if you can connect

**Comment by IcyLemon** [comment]
@iikirilov 
Yes, the node can be connected using attach, Thank you very much!
I found the following can also wokr：
`geth --rpcaddr 11.177.51.101 `
or 
`geth  --rpcaddr 0.0.0.0 `

**Comment by iikirilov** [comment]
This should not be causing problems. I need more information to help you out. 
1. What is the command you used to start the geth node on CentOS?
2. Could you provide the full stacktrace of the error you get when trying to connect via web3j?
3. Can you confirm you run `geth attach http://11.177.51.101:8545` on the Windows machine?

**Comment by iikirilov** [comment]
Refer to the documentation for the correct params to start your node [here](https://web3j.readthedocs.io/en/latest/getting_started.html#start-a-client).
Ofcourse you should change `--rinkeby` flag to your network config.

**Comment by vishaladke** [comment]
geth attach http://127.0.0.1:9999  
The above command is not working on Windows machine. Could you please assist me on this ?

**Comment by vishaladke** [comment]
I am trying to connect using Java Code Web3J

**Comment by ken830624** [comment]
> @iikirilov
> Yes, the node can be connected using attach, Thank you very much!
> I found the following can also wokr：
> `geth --rpcaddr 11.177.51.101 `
> or
> `geth --rpcaddr 0.0.0.0 `

Disable SELinux then you should be able to connect.

**Comment by iikirilov** [comment]
is this still an issue?
