### ISSUE TITLE
Create Wallet from username & password

### ISSUE THREAD

**Issue by idoor88** [web3j/web3j#399]
Hi All,
I am newbie with web3j, but I like to use java API to develop a wallet application so each user can sign in and send ETH or other tokens, ether.js has wallet api, which allows a user to create wallet from their user name and password, and this wallet will be the same if it is created with the same name and password each time, so it is easy to restore it,  I could not find similar approach from web3j, and web3j uses keyfile, so each user needs to create keyfile on the machine which hosts my wallet web application, if there are thousands of users, that is not practical.
Anybody has any suggestions on this topic?
Thanks

Wallet . fromBrainWallet ( username , password [ , progressCallback ] )
    Generate a wallet from a username and password
https://docs.ethers.io/ethers.js/html/api-wallet.html

**Comment by lasrie** [comment]
Hi idoor88,

Thanks for asking this question, I actually learned quite a bit by researching it:
It turns out, that ethers.js is using the scrypt algorithm to calculate the brain wallet
You can see it in their code here: (Taken from https://github.com/ethers-io/ethers.js/blob/master/wallet/wallet.js)

```
utils.defineProperty(Wallet, 'fromBrainWallet', function(username, password, progressCallback) {
    if (progressCallback && typeof(progressCallback) !== 'function') {
        throw new Error('invalid callback');
    }

    if (typeof(username) === 'string') {
        username =  utils.toUtf8Bytes(username, 'NFKC');
    } else {
        username = utils.arrayify(username, 'password');
    }

    if (typeof(password) === 'string') {
        password =  utils.toUtf8Bytes(password, 'NFKC');
    } else {
        password = utils.arrayify(password, 'password');
    }

    return new Promise(function(resolve, reject) {
        scrypt(password, username, (1 << 18), 8, 1, 32, function(error, progress, key) {
            if (error) {
                reject(error);

            } else if (key) {
                resolve(new Wallet(utils.hexlify(key)));

            } else if (progressCallback) {
                return progressCallback(progress);
            }
        });
    });
});
`

For the calculation of the actual private key they are using scrypt-js, which you can try out here: http://ricmoo.github.io/scrypt-js/
There are also java implementations out there, so you could probably use something like this: https://github.com/wg/scrypt

However, I do not think that this approach is secure for the purpose you are describing of actually using it as a longer term storage, but I would love to see an implementation of this to see the impact on user experience and security.

If you have any further questions, please feel free to ask :)
Best Regards,
Lasse
