### ISSUE TITLE
Truffle not generating JSON

### ISSUE THREAD

**Issue by MotassemJa** [web3j/web3j#400]
As described in the README file, and since I am still testing with truffle, I ran the following commands
```
truffle compile
truffle deploy
```
The problem is I can't find the generated JSON file (If any).
I even tried directly with solidity and a Java class representing the Contract was generated. But when trying to run the android app, it will faild because of unresolved method naming in the contract file.

What could be the problem? And is it a must to use the truffle commands if I wrote my contracts with the help of truffle, or can I use solidity to generate the wrappers?

**Comment by AlexandrouR** [comment]
This issue is no longer relevant there are a few ways to generate the wrappers in web3j and web3j-cli
