### ISSUE TITLE
 java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by badboy-tian** [web3j/web3j#403]
```
 val wallet = WalletUtils.generateBip39Wallet(password, fileDir)
                val seed = MnemonicUtils.generateSeed(wallet.mnemonic, password)
                val credentials = Credentials.create(ECKeyPair.create(sha256(seed)))
                Log.e("", Numeric.encodeQuantity(credentials.ecKeyPair.privateKey))
```

```
 W/System.err: java.lang.IndexOutOfBoundsException: Index: 1595
03-03 14:15:36.498 28860-28860/com.i7play.qunwallet W/System.err:     at java.util.Collections$EmptyList.get(Collections.java:4500)
03-03 14:15:36.498 28860-28860/com.i7play.qunwallet W/System.err:     at org.web3j.crypto.MnemonicUtils.generateMnemonic(MnemonicUtils.java:61)
03-03 14:15:36.498 28860-28860/com.i7play.qunwallet W/System.err:     at org.web3j.crypto.WalletUtils.generateBip39Wallet(WalletUtils.java:95)
03-03 14:15:36.498 28860-28860/com.i7play.qunwallet W/System.err:     at com.i7play.qunwallet.MainActivity$onCreate$1.onClick(MainActivity.kt:43)
03-03 14:15:36.498 28860-28860/com.i7play.qunwallet W/System.err:     at android.view.View.performClick(View.java:6256)
03-03 14:15:36.498 28860-28860/com.i7play.qunwallet W/System.err:     at android.view.View$PerformClick.run(View.java:24701)
03-03 14:15:36.498 28860-28860/com.i7play.qunwallet W/System.err:     at android.os.Handler.handleCallback(Handler.java:789)
03-03 14:15:36.498 28860-28860/com.i7play.qunwallet W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
03-03 14:15:36.498 28860-28860/com.i7play.qunwallet W/System.err:     at android.os.Looper.loop(Looper.java:164)
03-03 14:15:36.498 28860-28860/com.i7play.qunwallet W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)
03-03 14:15:36.498 28860-28860/com.i7play.qunwallet W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-03 14:15:36.498 28860-28860/com.i7play.qunwallet W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
03-03 14:15:36.498 28860-28860/com.i7play.qunwallet W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by tianqiujie** [comment]
in android,  i guess the problem is the en-mnemonic-word-list.txt in MnemonicUtils.java 
```
URL url = Thread.currentThread().getContextClassLoader()
                .getResource("en-mnemonic-word-list.txt");
```

**Comment by githubityu** [comment]
In android, I also met the same problem, the debug found populateWordList the returned list is empty.Don't know how to modify.

**Comment by tianqiujie** [comment]
@githubityu I modify the code in MnemonicUtils. 
```
private fun populateWordList(): List<String> {
        try {
            val fis = App.instance?.assets?.open("en-mnemonic-word-list.txt")
            return readAllLines(fis!!)
        } catch (e: IOException) {
            e.printStackTrace()
        }

        return emptyList()
    }
```

Use the android assetManager open the file

**Comment by iikirilov** [comment]
Thanks for you input. It would be appreciated if you could submit a PR with this fix so other users can benefit.

Cheers!

**Comment by githubityu** [comment]
@tianqiujie Thank you, the problem has been fixed

**Comment by githubityu** [comment]
How to through the secret key or mnemonic words change the password, I find for a long time, didn't find the corresponding API

**Comment by comodoro** [comment]
Also the method silently returns empty list on failure. At least a log would be a minimum, I guess the proper way is to declare and throw an exception.

**Comment by masich** [comment]
```
private static List<String> populateWordList() {
    InputStream inputStream = Thread.currentThread().getContextClassLoader()
            .getResourceAsStream("en-mnemonic-word-list.txt");
    try {
        return readAllLines(inputStream);
    } catch (Exception e) {
        return Collections.emptyList();
    }
}

public static List<String> readAllLines(InputStream inputStream) throws IOException {
    BufferedReader br = new BufferedReader(new InputStreamReader(inputStream));
    List<String> data = new ArrayList<>();
    for (String line; (line = br.readLine()) != null; ) {
        data.add(line);
    }
    return data;
}
```
It works for me on Android and pure Java.

**Comment by comodoro** [comment]
@masich Have you considered making it a PR, or may I? I am using my fork via Jitpack as a temporary solution. In case you do, please do something about the swallowing of the exception and returning unusable empty list (which only delays the error)

**Comment by masich** [comment]
@comodoro Do you mean to print a stack-trace and return an empty list in case of an exception?

**Comment by comodoro** [comment]
I would think even RuntimeException, but then the word list population has to be moved from the static initializer and done on demand. Something like [this](https://github.com/comodoro/web3j/blob/47779480d53fab297e6a0501f086a6631e8ca068/crypto/src/main/java/org/web3j/crypto/MnemonicUtils.java#L48-L50), but it depends, maybe some should comment, @iikirilov ?

**Comment by masich** [comment]
@comodoro OK. If you want, you can take my changes and do as you see fit and send PR)

**Comment by iikirilov** [comment]
Thanks for submitting the PR, please discuss changes on the PR or open a new issue. Cheers.

**Comment by ArikWork5** [comment]
Hello, I'd be happy to get help here.
My project is written in Android.
I know how to fix the bug in the MnemonicUtils.java file,
but how can i do that , because it is an external library file that i can't edit ,

Do I need to copy the files from external library to my project?
I don't think it's an effective way,
I have also read that i can use ASSETS ?

How can I do it in a right way?
Thank you !
