### ISSUE TITLE
Contract Address Must Be Trimmed In EthFilter

### ISSUE THREAD

**Issue by cerberus17** [web3j/web3j#405]
Web3j Version: 3.3.1
TestRPC: 4.1.3

Subscribing to events using an EthFilter created with a contract address does not receive any events.

```
Web3j web3j = Web3j.build(new HttpService());

SimpleContract contract = SimpleContract.load(...);

EthFilter filter = new EthFilter(DefaultBlockParameterName.EARLIEST, DefaultBlockParameterName.LATEST, contract.getContractAddress());

web3j.ethLogObservable(filter).subscribe(log -> System.out.println(log.toString()));
```

Nothing will be printed when activity occurs in the contract.

However, if you change the EthFilter creation to below, the events are correctly logged.

```
EthFilter filter = new EthFilter(DefaultBlockParameterName.EARLIEST, DefaultBlockParameterName.LATEST, contract.getContractAddress().substring(2));
```

It appears that when a non-null address is provided to EthFilter, there is an attempt to add '0x' to the beginning somewhere which is causing the filter to not match any results.

**Comment by tjanson** [comment]
Thanks. I think this is an important issue because apparently many people run into it (see StackOverflow) and there’s no clear error message (in fact, no indication that anything’s gone wrong at all).

I suppose simply calling `cleanHexPrefix` in the [EthFilter constructor](https://github.com/web3j/web3j/blob/6160282a5912ba1f35394312e6e783e040da4af3/core/src/main/java/org/web3j/protocol/core/methods/request/EthFilter.java#L26) would do the trick.

Or is this behavior intentional in order to enforce some spec? @conor10
In that case it would be good to add this caveat to the [documentation](https://docs.web3j.io/filters.html#topic-filters-and-evm-events). (It correctly omits the "0x" prefix – but that may not be obvious.)

**Comment by tjanson** [comment]
Apparently this does not affect all clients, so it might be “their fault” (e.g., Truffle’s ganache-cli). But regardless it would be helpful to deal with this issue in Web3j.

**Comment by tjanson** [comment]
I’ve now noticed that `geth` *requires* the `0x`; without it, I get this:

```
org.web3j.protocol.core.filters.FilterException: Invalid request: invalid argument 0: invalid address at index 0: hex string without 0x prefix
```

**Comment by ice09** [comment]
It would be great if this get fixed OR is mentioned somewhere, this would be fine as well.
But as the webj-maven-plugin generates sources with the wrong EthFiler creation, so this is misleading and costs people a lot of time.

Just to sum up:
Versions: web3j: 3.5, 3.6
web3j-maven-plugin: 0.3.5, 0.3.7

With TestRPC/Ganache, the address submitted to EthFilter _must exclude_ the beginning "0x", for Geth it _must include_ "0x".

The problem with the Maven generated sources is the inclusion of "0x" in the specific filter add method, so the method 
`(DefaultBlockParameter startBlock, DefaultBlockParameter endBlock)`
will never work with Ganache/TestRPC, but
`(EthFilter)`
has to be used as the address (with beginning "0x" or not) must be added on filter cretation.

This might even be a bug in Ganache/TestRPC, but it should be noted somewhere in web3j or the Maven plugin.

**Comment by tjanson** [comment]
I think ganache-cli is misbehaving.

Here are relevant quotes from the spec:

> When encoding UNFORMATTED DATA (byte arrays, **account addresses**, hashes, bytecode arrays): encode as hex, **prefix with "0x"**, two hex digits per byte. [[1]](https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding)

> **address: DATA**|Array, 20 Bytes - (optional) Contract address or a list of addresses from which logs should originate. [[2]](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter)
> ```js
> "address": "0x8888f1f195afa192cfee860698584c030f4c9db1",
> ```

I’ll take it to the truffle guys, should be an easy fix.

**Comment by tjanson** [comment]
While trying to look into this I discovered that `ganache-cli v6.2.x` doesn’t seem to have the problem anymore, though I don’t immediately see what changed.
I probably won’t look into this further.

Also, unrelatedly: they changed something about the txHash algorithm which makes transactions throw.

**Comment by ice09** [comment]
No, tested with Ganache-1.3.1 and both versions (with prefix "0x" and without) do work now.

**Comment by adneerav** [comment]
Hello,

Not sure why but I am facing same issue with web3j. I tried by using contract addres 0x prefix and without it and result same error

```
val filter: EthFilter =
            EthFilter(
                DefaultBlockParameterName.EARLIEST,
                DefaultBlockParameterName.LATEST,
                CONTRACT_ADDRESS_HERE
            )
                .addOptionalTopics("logs", "log", "StatusCallbackEvent", "PrintLog").addSingleTopic("PrintLog")
        val filterResponse = BaseApplication.instance.web3j?.ethLogFlowable(filter)?.subscribeOn(Schedulers.io())
            ?.observeOn(AndroidSchedulers.mainThread())
            ?.subscribe({ logdata ->
                Log.e("StatusCallbackEvent", logdata.data)
            }, { throwable ->
                Log.e("StatusCallbackEvent", throwable.message)
            }
            )
```
Tried address with 0x : `0x163897f32f08cdf177126ba47e1d156e667e1392` 
And without 0x : `163897f32f08cdf177126ba47e1d156e667e1392`

Always getting error in  `throwable`

Android Web3j Version : `'org.web3j:core:4.2.0-android'`
Geth Version : `Geth/v1.8.27-stable-4bcc0a37/linux-amd64/go1.10.4`

I am not using ganache or any wrapper.

Contracts methods are executing successfully. But the logs which I've added in methods are getting cached in above source.Fetching transaction details working fine as per below 
```
 val subscription = EVM.web3jObj?.transactionFlowable()?.subscribeOn(Schedulers.io())
            ?.observeOn(AndroidSchedulers.mainThread())?.subscribe { tx ->
                Log.e("TransactionDetails", tx.toString()) // Working
            }
```

I am not using ganache or any wrapper.

Can anyone please help me or guide me to make this working?

Thanks
