### ISSUE TITLE
support more parity rpc calls

### ISSUE THREAD

**Issue by p-s-dev** [web3j/web3j#406]
I see some parity rpc calls are implemented, like `parity_allAccountsInfo`.  

There seem to be a few that aren't implemented, when looking at this list:
https://github.com/paritytech/parity/wiki/JSONRPC-parity-module

Is there a policy about which to implement?  Or are all valid to implement, but just haven't been coded yet?

**Comment by conor10** [comment]
Feel free to add any you need. The reason they haven't all been added is due to the overhead of implementing, supporting and testing them.
