### ISSUE TITLE
Invalid response received: okhttp3.internal.http.RealResponseBody@41f30eb2

### ISSUE THREAD

**Issue by idoor88** [web3j/web3j#411]
Hi,
I used the following code and run it in a separate java thread, then connect to mainnet.infura.io/my_token, but I got Invalid response received exception, also from the httpService log, it shows 405 Method Not Allowed, any clue?

Thanks

CountDownLatch countDownLatch = new CountDownLatch(EVENT_COUNT);
        CountDownLatch completedLatch = new CountDownLatch(EVENT_COUNT);

        Subscription subscription = observable.subscribe(
        			x -> {
        				countDownLatch.countDown();
        				logger.debug("Monitoring enter run. observable x: " + x);
        			},
                	e -> {
                		logger.error("exception occurred in subscription tx", e);
                    },
	                () -> {
	                	completedLatch.countDown();
	                }
                
        );

**Comment by idoor88** [comment]
I also tried with ropsten.infura.io, but still the same exception, also tried this code and get the same error:

Subscription subscription = web3j.blockObservable(false).subscribe(block -> {
    		    System.out.println("Sweet, block number " + block.getBlock().getNumber() + " has just been created");
    		}, Throwable::printStackTrace);
    		 
    		TimeUnit.MINUTES.sleep(2);
    		subscription.unsubscribe();

**Comment by iikirilov** [comment]
These methods use filters in the background that are not supported by Infura. Please refer to the [docs](https://web3j.readthedocs.io/en/latest/getting_started.html#filters) for more info.
