### ISSUE TITLE
How to get all subscribed transaction events continuously until the program is stopped

### ISSUE THREAD

**Issue by idoor88** [web3j/web3j#412]
Hi All,
I am trying to use the following code to subscribe latest transaction events and hope to see my log window keep rolling, but I saw the same block with the same block number printed out for 25 times, then nothing else happened anymore, no more blocks printed for more than an hour, I connected to https://mainnet.infura.io/my_token, and my following code is in a separate java thread run method, I did the same testing with ether.js, and the runtime results came out as expected, any clue? also why the same block printed out for 25 times?
I am using web3j 3.3.1.

Thanks

EthBlock ethBlock = web3j.ethGetBlockByNumber(DefaultBlockParameterName.LATEST, false)
                    .send();
            BigInteger latestBlockNumber = ethBlock.getBlock().getNumber();
    		 logger.debug("latestBlockNumber: " + latestBlockNumber);
    		 
    		 web3j.catchUpToLatestTransactionObservable(new DefaultBlockParameterNumber(latestBlockNumber.subtract(BigInteger.ONE))).subscribe(block ->
    		 {
    			 System.out.println("*+observer+getblock: " + block.getBlockNumber());
    			 logger.debug("block getFrom: " + block.getFrom());
    			 logger.debug("block getGasPriceRaw: " + block.getGasPriceRaw());
    			 logger.debug("block getNonceRaw: " + block.getNonceRaw());
    			 logger.debug("block getHash: " + block.getHash());
    			 logger.debug("block getTo: " + block.getTo());
    			 logger.debug("block getInput: " + block.getInput());
    			 logger.debug("block getCreates: " + block.getCreates());
    			 
    			 
    		 },
         	e -> {
         		logger.error("exception occurred in subscription: ");
        		logger.error("exception occurred in subscription tx", e);
            },
            () -> {
            	 logger.debug("block complete: ");
            }
    		 );

**Comment by iikirilov** [comment]
That observable returns transactions and not blocks. You get 25 results because there were 25 transactions in the block and subsequent blocks the observable emitted.

Please use the [gitter](https://gitter.im/web3j/web3j) channel for usage questions.
