### ISSUE TITLE
filter dont give response

### ISSUE THREAD

**Issue by cubo1123** [web3j/web3j#414]
Hi, im android developer and am trying to get all the transfer events from a certain contract, when i dont pass an filter give me all the events, but when i pass a filter with the name of the event dont return anythig. someone can told me what am doing wrong.
Its kotlin code
```
val event = Event("Transfer", Arrays.asList(), Arrays.asList<TypeReference<*>>(object TypeReference<Address>() {}, object : TypeReference<Uint256>() {}))

val encodedEventSignature = EventEncoder.encode(event)

val http = HttpService("url of the node")

val web3 = Web3jFactory.build(http)

val filter = EthFilter(DefaultBlockParameterName.EARLIEST, DefaultBlockParameterName.LATEST, "address from the contract").addSingleTopic(encodedEventSignature)

val ethLog = web3.ethGetLogs(filter).send()

Log.e("1123",ethLog.toString())
```

**Comment by iikirilov** [comment]
Are you using Infura?

**Comment by cubo1123** [comment]
i do it with a infura node and with other node that i am developing, in both cases give me the same result

**Comment by iikirilov** [comment]
Filters are not supported with Infura. This is a limitation with Infura. What command do you use to start your "other" node?

**Comment by cubo1123** [comment]
we are developing a private blockchain mount on node js with a library call node-geth,this is the line than the library run 
/usr/local/bin/geth --networkid 33333 --port 60303 --rpc --rpcport 8545 --rpccorsdomain * --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3 --maxpeers 0 --nodiscover --minerthreads 1 --lightkdf --cache 16 --datadir /Users/macbook/Desktop/MasterNode-master/BowheadChain --etherbase 0xebb31748a9bb070782f5d8e7f941a532ec6a166f

sorry if i look like a noob i am starting

**Comment by iikirilov** [comment]
Is there a node mining on that network when you try the test case? I would suggest you use a local node connected to rinkeby to test this functionality. Also referring to the [docs](http://web3j.readthedocs.io/en/latest/) is a good starting point. For general usage questions you can ask in the [gitter](https://gitter.im/web3j/web3j) channel.

**Comment by cubo1123** [comment]
yes, there are a node mining. in rinkenby found the filter events?
Thank you so much

**Comment by iikirilov** [comment]
@cubo1123 did you resolve this issue?
