### ISSUE TITLE
How to get the return value of smart contract method in web3j? 

### ISSUE THREAD

**Issue by IcyLemon** [web3j/web3j#416]
Hi
Suppose I have a smart contract(.sol) as follows:
```
pragma solidity ^0.4.10;

contract Calculator {
    ......
    function add(uint32 x, uint32 y) returns (uint32) {
        return x + y;
    }
}
```
The Java code(.java) generated by web3j command line tool is as follows:
```
public class Calculator extends Contract {
    ......
    public RemoteCall<TransactionReceipt> add(BigInteger x, BigInteger x) {
        ......
    }
}
```

When I invoke this method as follows:
```
// load the contract
Calculator  calc = ....

// invoke add method: 1+2
RemoteCall<TransactionReceipt> result = calc.add(BigInteger.valueOf(1L), BigInteger.valueOf(2L)).send();

// mine and commit 
......
```
My question is that **how to get the return value from TransactionReceipt** ? That is , I want to get 3. I searched all of the APIs of TransactionReceipt but not find related API which can get return value. 

Thank a lot.

**Comment by iikirilov** [comment]
This is a Solidity related question. Have a look at the Solidity [docs](https://solidity.readthedocs.io/en/v0.4.20/).

I believe you do not get variables return like this via smart contract. The TransactionReceipt is merely a receipt that you called this contract method. I think the output could be written in the data field of the transaction. I am sure you can also emitt an Event with the value aswell.

Good Luck!

**Comment by IcyLemon** [comment]
@iikirilov 
In fact I also think that data field or event in contract can do this. According to your explanation, I confirmed it.
Many thanks.
