### ISSUE TITLE
change the password web3j

### ISSUE THREAD

**Issue by githubityu** [web3j/web3j#418]
How to through the secret key or mnemonic words change the password, I find for a long time, didn't find the corresponding API

**Comment by lasrie** [comment]
Hi,
Assuming that you already have the private key, you can simply create a new wallet file with the private key.
E.g:
``` 
ECKeyPair keypair = ECKeyPair.create(YOURPRIVATEKEY);
WalletUtils.generateWalletFile("SUPERSAFENEWPASSWORD", keypair,new File(WALLETSAVEPATH), true)
```

**Comment by githubityu** [comment]
@lasrie Thank you very much, I try

**Comment by chenhao597** [comment]
How to throught the mnemonic words to change the password???
