### ISSUE TITLE
web3j.transactionObservable().subscribe(tx -> {

### ISSUE THREAD

**Issue by githubityu** [web3j/web3j#423]
A transaction occurs, how to get this deal how many has confirmed the piece.thank you

**Comment by fcorneli** [comment]
Number of confirming blocks on a transaction:
```
EthGetTransactionReceipt getTransactionReceipt = 
      this.web3.ethGetTransactionReceipt(transactionHash).send();
Optional<TransactionReceipt> transactionReceiptOptional = 
      getTransactionReceipt.getTransactionReceipt();
TransactionReceipt transactionReceipt = transactionReceiptOptional.get();
BigInteger transactionBlockNumber = transactionReceipt.getBlockNumber();

BigInteger latestBlockNumber = this.web3.ethBlockNumber().send().getBlockNumber();

BigInteger blocksOnTop = latestBlockNumber.subtract(transactionBlockNumber).add(BigInteger.ONE);
System.out.println("number of confirming blocks: " + blocksOnTop);
```

**Comment by githubityu** [comment]
@fcorneli  hank you I try my best to try

**Comment by githubityu** [comment]
After I use the following code execution, transactionReceipt1 always null.I don't know why 

`Web3j web3 = getWeb3j();
        if(web3==null){
            return BigInteger.valueOf(0);
        }
        EthGetTransactionReceipt getTransactionReceipt =
                web3.ethGetTransactionReceipt(transactionHash).send();
        TransactionReceipt transactionReceipt1 = getTransactionReceipt.getTransactionReceipt();

        BigInteger blockNumber = transactionReceipt1!=null?transactionReceipt1.getBlockNumber():BigInteger.valueOf(0);
        BigInteger latestBlockNumber = web3.ethBlockNumber().send().getBlockNumber();
        BigInteger blocksOnTop = latestBlockNumber.subtract(blockNumber).add(BigInteger.ONE);
        LogUtil.e("number of confirming blocks: " + blocksOnTop);
        return blocksOnTop;`

**Comment by fcorneli** [comment]
@githubityu Maybe the transaction is still pending within the network?

**Comment by iikirilov** [comment]
Please use the issues for actual issues with web3.

Please drop usage question in [gitter](https://gitter.im/web3j/web3j?utm_source=share-link&utm_medium=link&utm_campaign=share-link)
