### ISSUE TITLE
API WalletUtils.generateBip39Wallet(String password, File destinationDirectory) Question

### ISSUE THREAD

**Issue by why168** [web3j/web3j#426]
The generated mnemonic does not match the wallet address in the newly generated KeyStore. 
What is the problem? 

I used the mnemonic to import other wallets and found that the wallet address changed. Why?

## Code
``` Kotlin
 val generateBip39Wallet = WalletUtils.generateBip39Wallet("12345678", file)
 val filename = generateBip39Wallet.filename
 val mnemonic = generateBip39Wallet.mnemonic

 Logger.e("钱包路径 = $filename")
 Logger.e("助记词 = $mnemonic")
```
## Log

```Log
filename = UTC--2018-03-14T04-19-53.010--38e967e5e2212887c0ae3dfa867a55aa4addda7d.json

mnemonic = cement space verify resemble nut access shield mean february cricket globe oil

keyByPath = DeterministicKey{pub=0269a0714d6ac10f92add89a2d2e071636d1e91b946b5e2f17b08893925df10728, chainCode=fabe9569a70909cd6d7df99108a5538a32a7a200be7b4abd02dffdb332adc9b1, path=M/44H/60H/0H/0/0, isEncrypted=false, isPubKeyOnly=false}
```

## Json File

```Json
{
  "address": "38e967e5e2212887c0ae3dfa867a55aa4addda7d",
  "crypto": {
    "cipher": "aes-128-ctr",
    "cipherparams": {
      "iv": "94eeab6e785e5e093071282cf6d939a0"
    },
    "ciphertext": "7a06699454d1b5185022cd387227e59012b09d1008c058e91a1eb5cf7d21220b",
    "kdf": "scrypt",
    "kdfparams": {
      "dklen": 32,
      "n": 4096,
      "p": 6,
      "r": 8,
      "salt": "e00621c89653b609ff1d2ded46604ed591ba89c28d6c37853cfff4502e85c78b"
    },
    "mac": "ba43db713131f23bcbfa5161aa6ec437ca160aa2f310a9fadb49d3b67cd30858"
  },
  "id": "45cbd551-23c5-44c0-bbd1-ec8a4aa83ad6",
  "version": 3
}
```

**Comment by TOTOROYang** [comment]
i use WalletUtils.generateBip39Wallet 
throw
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1034
at java.util.Collections$EmptyList.get(Collections.java:4454)
at org.web3j.crypto.MnemonicUtils.generateMnemonic(MnemonicUtils.java:59)
at org.web3j.crypto.WalletUtils.generateBip39Wallet(WalletUtils.java:96)

**Comment by iikirilov** [comment]
related #403 #420

**Comment by why168** [comment]
@TOTOROYang   你用Java平台还是Android平台？ 主要是获取的那个文件不存在所以导致这个问题，你可以修改下源码就行了啊

**Comment by mivanzhang** [comment]
@why168 Android版本，修改源码之后，如何打包？一直打包失败，android版本和java版本打包命令不同？
@iikirilov hi，I fix this bug locally ,how I can publish to my local maven in ? I tried  ./gradlew publishToMavenLocal ,but this not work ,**I want to an android version jar or a**ar,please give me some help

**Comment by yuanxi90** [comment]
@mivanzhang have you sovled this ?

**Comment by mivanzhang** [comment]
I found a way to fix the issue ,but I don't have the right to push my code

**Comment by iikirilov** [comment]
@mivanzhang you need to create fork of this project, make the changes and then submit a pull request to merge your changes with this project. :)

**Comment by lihjchain** [comment]
问下我这边为什么获取到的助记词是空的，源码中报错了。MnemonicUtils里面的
 private static final List<String> WORD_LIST = populateWordList();  WORD_LIST  是空的。版本是3.3.1

**Comment by dhruvi1kosmos** [comment]
@mivanzhang  have u pushed ur change?  i have same issue can u help

**Comment by dhruvi1kosmos** [comment]
@mivanzhang  did you find jar and is issue is resolved ?

**Comment by mivanzhang** [comment]
https://github.com/clowdrgn/ethereum-wallet-core.git    have a try 
@iikirilov @why168

**Comment by mivanzhang** [comment]
If you want fix the bug ,you need to fix source code  to load WORD_LIST yourself,first you need to move wordlist into directory src/asset

**Comment by why168** [comment]
Thank you

**Comment by ArikWork5** [comment]
Hello, I'd be happy to get help here.
My project is written in Android.
I know how to fix  the **MnemonicUtils.java** file,
but how can i do that , because it is an external library file i can't edit it ,
 How can I do it in a right way?
Thank you !

**Comment by dhruvi1kosmos** [comment]
@ArikWork5  one way is u came your custom class for MnemonicUtils and use that class instead of library class or u can extend that class and override methods. or you can use below link till repo is updated (bug is fixed in this )
https://jitpack.io/#esoxjem/web3j/v3.3.3-android

**Comment by ArikWork5** [comment]
Great solutions , thank you so much ! @dhruvi1kosmos

**Comment by ArikWork5** [comment]
Do i need to switch the implplimnitaon from "org.web3j:core:3.3.1-android"
to  "com.github.esoxjem.web3j:abi:v3.3.3-android" ?

For some reason Web3J does not work for me :(
@dhruvi1kosmos

**Comment by chenhao597** [comment]
@why168 问题解决了吗/是不是助记词`m/44'/60'/0'/0/0`的原因

**Comment by iikirilov** [comment]
@why168 is this still an issue with web3j 4.0.0-alpha-1

**Comment by AlexandrouR** [comment]
Closing as duplicate of #919. Please follow the link for a resolution and to track progress of this issue.
