### ISSUE TITLE
Change Hex.toHexString(signedMessage) to Numeric.toHexString(signedMessage) in examples.

### ISSUE THREAD

**Issue by M0N3** [web3j/web3j#427]
Hello!
In your examples to send raw transaction you use Hex.toHexString(signedMessage) to create hexValue, this method returns value without '0x' prefix at the start, and EthSendTransaction.error returns this: "invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go value of type hexutil.Bytes".
If we change line Hex.toHexString(signedMessage) to Numeric.toHexString(signedMessage) then all works fine.
Sorry, if this issue is duplicated, or i said something wrong.

**Comment by iikirilov** [comment]
@M0N3 would be awesome if you could submit a PR to fix this :smile:

**Comment by AlexandrouR** [comment]
The [documentation](https://docs.web3j.io/transactions.html#signing-transactions) shows the Numeric.toHexString(signedMessage).

**Comment by iikirilov** [comment]
Reopening because the above response by @AlexandrouR has not been verified by @M0N3
