### ISSUE TITLE
erc20 token "Transfer Topic filters" didn't work with indexed field 

### ISSUE THREAD

**Issue by xmkane** [web3j/web3j#435]
I'm testing "Topic filters" with web3j 3.3.1 client and local private Geth 1.7.2 chain, But I meet with topic log didn't return with the code below:

"Transfer" in contract:
`    // This generates a public event on the blockchain that will notify clients
    event Transfer(address indexed from, address indexed to, uint256 value);`

` // local private net erc20 token contract: 0x8cea15cc3b8a7697cd351eb2aa7c928282944748
  EthFilter filter = new EthFilter(DefaultBlockParameterName.EARLIEST, 
                                                     DefaultBlockParameterName.LATEST,
                                                     "0x8cea15cc3b8a7697cd351eb2aa7c928282944748");
//filter.addSingleTopic(EventEncoder.encode(TRANSFER_EVENT));
//filter.addSingleTopic("0x000000000000000000000000928dfb23f58d48131fb1043091af127a48ad4fcd");`

when I use the line

`filter.addSingleTopic(EventEncoder.encode(TRANSFER_EVENT));`

the raw logs returns below:

`Log{removed=false, logIndex='0x0', transactionIndex='0x0', transactionHash='0x5cdec46f2867678ba5c2037761cd827704d88e5f4d3735c950ef9c48b9c41b1e', blockHash='0x4947b604114d0b1ae3945b4db469a9f749c644682f8311156faf3dd52d138f5f', blockNumber='0xecc', address='0x8cea15cc3b8a7697cd351eb2aa7c928282944748', data='0x0000000000000000000000000000000000000000000000000001c64ae810b800', type='null', topics=[0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef, 0x000000000000000000000000928dfb23f58d48131fb1043091af127a48ad4fcd, 0x000000000000000000000000c21a51df5aca966879842081c4e637da25686f7c]}`

but when I use one of the real log topics, the observable didn't return any topic logs

`filter.addSingleTopic("0x000000000000000000000000928dfb23f58d48131fb1043091af127a48ad4fcd");`

any suggestions of my problem?

**Comment by ghareeb-falazi** [comment]
What works for me is always including the topic representing the event signature as "addSingleTopic" and then add ALL the topics representing the indexed parameters either as "addOptionalTopics" or as "addNullTopic" depending on whether you want to filter based on the corresponding parameter or not:
for your case you can write
```
fitler
.addSingleTopic(EventEncoder.encode(TRANSFER_EVENT))
.addOptionalTopics("0x000000000000000000000000928dfb23f58d48131fb1043091af127a48ad4fcd",
"0x000000000000000000000000c21a51df5aca966879842081c4e637da25686f7c");
```
