### ISSUE TITLE
Support for 712 standard. signTypedData

### ISSUE THREAD

**Issue by vikmeup** [web3j/web3j#437]
Do you guys plan to support for https://github.com/ethereum/EIPs/pull/712?

What's the easiest way to implement this?

**Comment by vikmeup** [comment]
@conor10 can you guide?

**Comment by ice09** [comment]
To add to the request, I did this manually here: https://github.com/ice09/onboarding-eip712/blob/master/src/main/java/de/ice09/safesigs/services/SignatureService.java  

In general, this should be quite easy to do, as for `encode` and `encodePacked` the rules are similar: https://medium.com/@libertylocked/what-are-abi-encoding-functions-in-solidity-0-4-24-c1a90b5ddce8  

Of course, convenience methods for `ecrecover`y of EIP-712 signed data would be huge plus for web3j.

**Comment by jopasserat** [comment]
There're [a few PRs](https://github.com/gjeanmart/eth_signTypedData/pulls) and [evolving codebase](https://github.com/gjeanmart/eth_signTypedData) here FWIW.

Would definitely be great to see that landing in web3j

**Comment by drortirosh** [comment]
web3 is still missing eip-712 support. Can only be supported by external provider (e.g. metamask, portis), which is a shame..

**Comment by Serpivskyi** [comment]
Any news about eip-712 support?

**Comment by saulgiordani** [comment]
This should be definitely be included...

**Comment by davidcalap** [comment]
Any news here? Thanks!
