### ISSUE TITLE
Error processing transaction request: exceeds block gas limit

### ISSUE THREAD

**Issue by githubityu** [web3j/web3j#445]
Error processing transaction request: exceeds block gas limit at org.web3j.tx.Contract.deploy(Contract.java:325)
``
 public static TutorialToken deploy(String fromAccount, String pwd){
        Credentials credentialsFromPwd = getCredentialsFromPwd(pwd, fromAccount);
        if(credentialsFromPwd==null){
            return null;
        }
        try {
            TutorialToken send = TutorialToken.deploy(getWeb3j(),credentialsFromPwd, GAS_PRICE, BigInteger.valueOf(Contract.GAS_LIMIT.longValue()*2)).send();
            return send;
        } catch (IOException e) {
            e.printStackTrace();
        } catch (CipherException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

**Comment by saurabhsingh121** [comment]
@githubityu Did you get the solution?
