### ISSUE TITLE
How can i use web3j to transfer erc20 tokens to other adress

### ISSUE THREAD

**Issue by stephenie** [web3j/web3j#452]
i noly found method  transfer eth to another account,how can i do transfering erc20 tokens  like eos using web3j??

**Comment by pvn-khanh-bui** [comment]
the same

**Comment by AlexandrouR** [comment]
you can take a look here 
https://docs.web3j.io/smart_contracts.html?highlight=token
in order to transfer tokens you must call the appropriate transfer function on the contract.
