### ISSUE TITLE
how to getTransactionHash() as soon as possible

### ISSUE THREAD

**Issue by xtuyaowu** [web3j/web3j#457]
hi everyone ,
    i want to know how to getTransactionHash() as soon as possible as transaction send,no matter this transaction is success or fail,now too slow,should wait for more than 60s.
   thanks!

**Comment by talkera** [comment]
In fact you have to wait...
At first you have to wait your transaction to be mined. Then you can get the hash immediataly.
However, the block holds you transaction may be discarded in a short time. If this happend, the hash you have got will be invalid, and you will have to send your transaction again.
If you want to get a valid hash, you have to wait enought blocks mined after you transaction mined.

**Comment by fcorneli** [comment]
If you have a signed raw transaction, you can calculate the transaction hash directly. Even before sending the transaction to a client node.

**Comment by githubityu** [comment]
@fcorneli  How to calculate the transaction hash directly  thanks

**Comment by fcorneli** [comment]
```
String transactionHash = Hash.sha3(rawTransaction);
```

**Comment by githubityu** [comment]
@fcorneli  thanks

**Comment by githubityu** [comment]
@fcorneli  Decoding transaction input data with web3j (Java)

**Comment by radek1st** [comment]
If you'd like to get the hash without calculating it yourself, you can set a transaction manager which will not poll for the block being mined. If you use something like the following, you will get the transaction hash immediately:

>         NoOpProcessor processor = new NoOpProcessor(web3j);
>         TransactionManager txManager = new FastRawTransactionManager(web3j, credentials, processor);
>         ERC20Interface token = ERC20Interface.load(TOKEN_CONTRACT_ADDRESS, web3j, txManager, gasPrice, gasLimit);
>         String tx = token.transfer(wallet, tokenAmount).send().getTransactionHash();

**Comment by marcuzzu** [comment]
Hi all, I'm using the send asynk function of smart contract, now ceck the log and the RPC of the node send the transaction hash at the first request but it is not possible to retrive it before the transaction succed or fail. I check inside the lib and in the class  org.web3j.tx.Contract at line number 275, the transaction hash is available soon after the submit whitout wait the end of the transaction. exist a way to retrive this value whitout wait?

**Comment by AlexandrouR** [comment]
@marcuzzu please open a new issue with more detail to you question or problem.
