### ISSUE TITLE
No API to send additional data with the Transfer class

### ISSUE THREAD

**Issue by bluesunrise** [web3j/web3j#459]
I need to send additional data like on ManagedTransaction.java:

https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/tx/ManagedTransaction.java
where there is a protected method to send data on the second parameter:

protected TransactionReceipt send(
            String to, **String data**, BigInteger value, BigInteger gasPrice, BigInteger gasLimit)
            throws IOException, TransactionException {

I don't see a way to send additional data using the recommended (in web3j documentation) api to transfer:

https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/tx/Transfer.java

**Comment by p-s-dev** [comment]
Maybe this?
https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/tx/RawTransactionManager.java#L77

Or this?
https://web3j.readthedocs.io/en/latest/transactions.html#transacting-with-a-smart-contract

**Comment by bluesunrise** [comment]
Tried your first example, two thing went wrong:

1. the transaction doesn't log in the geth console, making me think it never got there
2. the transaction receipt is null

            EthGasPrice ethGasPrice = (EthGasPrice)web3j.ethGasPrice().send();
            BigInteger gasPrice = ethGasPrice.getGasPrice();
            RawTransactionManager rawTransactionManager =  new RawTransactionManager(web3j ,credentials,100,1000 * 15);
            EthSendTransaction send = rawTransactionManager.sendTransaction(gasPrice, Transfer.GAS_LIMIT, payKey, "3", BigInteger.valueOf(transferAmount));
            String hash = send.getTransactionHash();
            log.info("hash = " + hash);

**Comment by bluesunrise** [comment]
ah its getting an error "intrinsic gas too low"

**Comment by bluesunrise** [comment]
An observation, in Transfer.java, the data field is set to ""
Transfer.java, line 39:
            return this.send(resolvedAddress, "", weiValue.toBigIntegerExact(), gasPrice, gasLimit);

Using the standard Transfer.sendFunds method like in the docs, this works fine (except for throwing an exception on retrieving the receipt as documented here 

https://github.com/web3j/web3j/issues/318

However If I change the Transfer source code to:

            return this.send(resolvedAddress, "42", weiValue.toBigIntegerExact(), gasPrice, gasLimit);

then I get the error back from geth "intrinsic gas too low" and the request is not processed

Do I need to format the data parameter or add more gas to process data?

**Comment by bluesunrise** [comment]
increased my gas limit to 200_000L and the transaction went through. Not sure why

**Comment by Defozo** [comment]
I don't understand how did you do this? Did you have to make some changes to the web3j?

**Comment by AlexandrouR** [comment]
is this still an issue with the latest web3j version ?

**Comment by AlexandrouR** [comment]
Issue closed due to inactivity.
