### ISSUE TITLE
How to add web3j to android project as module?

### ISSUE THREAD

**Issue by M0N3** [web3j/web3j#461]
Hi!
How can I add web3j project to my android project as module?
Using standard android studio import modules dosn't work clear because web3j have submodules.
Any examples?

**Comment by mitfik** [comment]
Why you can't use gradle? 
In [README](https://github.com/web3j/web3j#gradle) you have all details how to integrate it.

In short in your `build.gradle` add:

    compile 'org.web3j:core:3.1.1-android` 

Keep in mind that version can change.

**Comment by M0N3** [comment]
@mitfik  Because me need too use modified version of library.

**Comment by ehanoc** [comment]
@M0N3 I wanted the same. Managed to do so by flagging web3j's modules as java plugins with "'apply plugin: 'java-library' "

Check the **diff** of my fork https://github.com/ehanoc/web3j/tree/android

The **integration** i have in a sample project of mine : https://github.com/ehanoc/kotleth.git

Should easy now to import only the **individual** modules that you want. And you can now test and work on web3j tree as well if you want to change it. 

Play attention to **settings.gradle**, **app/build.gradle** and root **build.gradle**.

On the root build.gradle there's a bit of repetition with the libs versions from web3j/build.gradle file. If anyone as a better idea that works, that would be welcomed.

**Comment by AlexandrouR** [comment]
Closed due to inactivity.
