### ISSUE TITLE
 Caused by: java.lang.OutOfMemoryError: Failed to allocate a 268435472 byte allocation with 5218752 free bytes and 251MB until OOM, max allowed footprint 10437504, growth limit 268435456

### ISSUE THREAD

**Issue by guangxingmao** [web3j/web3j#469]
{"address":"74ce668fdc363cdc986dd9c3f190c169f7f54d21","crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"f8919c1a897fa90cbbce33d92620f6f8"},"ciphertext":"1c621a822db6814b64d0bdb44b06911364c24e30840fbecddbfb742e205a3845","kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"a2ab4d385f53a4a8730c95a981e75bb89a1e43b7ccb9782eeb57c6f3c5840809"},"mac":"80012a4fa9e8667e7ada79351c2f27e633d592b3a5a02aa589cf03f1250603ca"},"id":"e6bd8bbb-f633-458d-af6a-81051d65c198","version":3}

this is my test keystore, n is 262144(so big)，when i import 
 `derivedkey = SCrypt.scrypt(password.getBytes(), decode, n, r, p, dkLen)`
will be oom
and i use ` compile 'com.lambdaworks:scrypt:1.4.0'`

**Comment by AlexandrouR** [comment]
Hey is this still and issue ?
If so please reformat you code using ```

**Comment by guangxingmao** [comment]
now is ok, if n is so big, only use c++ to scrypt .
