### ISSUE TITLE
Signatures differ in web3J and the console use web3js 

### ISSUE THREAD

**Issue by xxmfypp** [web3j/web3j#476]
Hello,  When I sign the same raw message (it's simply string like "111111" for now) I get different signatures using web3js i web3j. The signature from web3js is valid (and web3j is not), I test it using solidity ecrecover function. It's worth to mention that hashes as you can see in the snippets are the same.

**Java snippet:**
```java
        String GETH_PREFIX = "\\x19Ethereum Signed Message:\n";
        
        Credentials credentials = Credentials.create("c008c11cd5b82377ca23197663085099f490d84232d8593e7095f9e29f4bb6b");

        System.out.println("address:"+credentials.getAddress());

        String hash = Hash.sha3(Numeric.toHexStringNoPrefix("111111".getBytes()));
        
        String message = GETH_PREFIX+hash.length()+hash;
        
        Sign.SignatureData signatureData = Sign.signMessage(message.getBytes(), credentials.getEcKeyPair());
        
        System.out.println("R: " + Numeric.toHexString(signatureData.getR()));
        
        System.out.println("S: " + Numeric.toHexString(signatureData.getS()));
        
        System.out.println("V: " + signatureData.getV());
```
**Java Result:**
```java
address:0xc3147e57154aef33bfd8196fd5475247cf130dd9
R: 0x5532637a39ec592c980da40cd2ba7f20e4fdfd3b74a8e2780a325f6b31b36e33
S: 0x05d6817d54e7b2b4dacde85788d4572c66712faba3986be7d795628b54c86792
V: 28
```
**JavaScript snippet:**
```javascript
> eth.accounts[1]
"0xc3147e57154aef33bfd8196fd5475247cf130dd9"
> var msgHash =web3.sha3('111111')
> console.log(msgHash)
0x9eee2d27a15c93ea945b2de2611ae121b747246520024b79f4ecb3dfe9d9b57f
> var signature = eth.sign(eth.accounts[1],msgHash)
> var r = signature.slice(0,66);
> var s = '0x'+signature.slice(66,130);
> var v = '0x'+signature.slice(130,132);
> v = web3.toDecimal(v);
27
> console.log(r)
0xc3c2664c437676b54528fac58ddfe8af453ebb4e8720f5177ea438e730921eb1
> console.log(s)
0x33902cf67f84127c1d9cf92bd95789b6cfcf45ac7b15d47e49275abe985b91c3
```

I saw the issues #208 ，

No problem is found

**Comment by inmyth** [comment]
Also have the same issue despite #208 . 
I'm not using web3js but https://www.myetherwallet.com/signmsg.html to sign and verify. The result from that website can be verified but the one from web3j cannot.  
I create the the full signature from SignatureData by adding R,S,V together :
```
SignatureData sd= Sign.signMessage(message.getBytes(), credentials.getEcKeyPair());
String s = Numeric.toHexString(sd.getR)} 
+ Numeric.toHexString(sd.getS).substring(2) 
+"%02X".format(sd.getV).toLowerCase();

```

**Comment by ashishonmobile** [comment]
> Also have the same issue despite #208 .
> I'm not using web3js but https://www.myetherwallet.com/signmsg.html to sign and verify. The result from that website can be verified but the one from web3j cannot.
> I create the the full signature from SignatureData by adding R,S,V together :
> 
> ```
> SignatureData sd= Sign.signMessage(message.getBytes(), credentials.getEcKeyPair());
> String s = Numeric.toHexString(sd.getR)
> + Numeric.toHexString(sd.getS).substring(2) 
> +"%02X".format(sd.getV).toLowerCase();
> ```

Did you get any solution till date?

**Comment by jsdavis28** [comment]
See my posts [here](https://github.com/web3j/web3j/issues/208#issuecomment-444518001). Hopefully it helps!
