### ISSUE TITLE
Java 7 support

### ISSUE THREAD

**Issue by jtakalai** [web3j/web3j#48]
Hi,

I'd like to use web3j in a Java 7 project. Any chance you have a version without Futures and Observables etc.? Or maybe could point me to an old commit that had a working RPC client but none of that Java 8 goodness?

Otherwise I'll probably have to manually cull the async stuff...

**Comment by conor10** [comment]
The Android [branch](https://github.com/web3j/web3j/tree/android) is 1.6 compatible with all functionality offered by the Java 8 version, bar Java 8 specific features. It's one release behind currently, but I'll bring it in line with the master branch over the next week or so.
