### ISSUE TITLE
[Empty transaction receipt, only transaction hash is available] during contract creation

### ISSUE THREAD

**Issue by kalinchuk-borys** [web3j/web3j#480]
Receiving exception bellow during contract deployment via Contract wrapper. 
```
java.lang.UnsupportedOperationException: Empty transaction receipt, only transaction hash is available
	at org.web3j.tx.response.EmptyTransactionReceipt.unsupportedOperation(EmptyTransactionReceipt.java:31) ~[core-3.3.1.jar:na]
	at org.web3j.tx.response.EmptyTransactionReceipt.getContractAddress(EmptyTransactionReceipt.java:107) ~[core-3.3.1.jar:na]
	at org.web3j.tx.Contract.create(Contract.java:273) ~[core-3.3.1.jar:na]
	at org.web3j.tx.Contract.deploy(Contract.java:323) ~[core-3.3.1.jar:na]
```
I can see in Contract.java code that throws exception but not sure why it's needed **as contract is anyway deployed**. 
```
        String contractAddress = transactionReceipt.getContractAddress();
        if (contractAddress == null) {
            throw new RuntimeException("Empty contract address returned");
        }
```
I'm using FastRawTransactionManager with NoOpProcessor  and 3.3.1 web3j version. 
Advice is needed.

**Comment by AlexandrouR** [comment]
is this still an issue in the latest version ?

**Comment by AlexandrouR** [comment]
The NoOpProcessor does not return the transaction receipt only the transaction hash.
Is it possible for you to use `PollingTransactionReceiptProcessor` ?

**Comment by abies** [comment]
Problem is still present with NoOpProcessor and QueuingTransactionReceiptProcessor. Workaround is to subclass them and add something like:

`public TransactionReceipt waitForTransactionReceipt(String transactionHash) throws IOException, TransactionException {
                super.waitForTransactionReceipt(transactionHash);

                TransactionReceipt tr = new TransactionReceipt();
                tr.setTransactionHash(transactionHash);
                return tr;
            }`

Still, this should be handled in basic library - currently, NoOpProcessor and QueuingTransactionReceiptProcessor are just unusable.
