### ISSUE TITLE
Web3J Sign VS Web3JS - different results

### ISSUE THREAD

**Issue by relaxbao** [web3j/web3j#486]
hello, I'm using Web3J version 3.3.1。when I sign the same message(eg:"TEST"), I wondered why i get diffierent signatures using web3js and web3j.  the verify function in the contract are different. .

**java snippet**
```
        String message = "TEST";
        String prefix =  "\u0019Ethereum Signed Message:\n" + message.length();
        byte[] data = Hash.sha3((prefix + message).getBytes());
        System.out.println("data: " + Numeric.toHexString(data));
        Sign.SignatureData signature = Sign.signMessage(data, credentials.getEcKeyPair());
```
**verify function in the contract**
```
   function verify( bytes32 hash, uint8 v, bytes32 r, bytes32 s) constant returns(address retAddr) {
      bytes32 prefixedHash = sha3(hash);
      return ecrecover(prefixedHash, v, r, s);
    }
```

**JavaScript snippet**
```
var msgHash =web3.sha3('TEST')
var signature = eth.sign(eth.accounts[1],msgHash)
```
**verify function in the contract**
```
function verify( bytes32 hash, uint8 v, bytes32 r, bytes32 s) constant returns(address retAddr) {
      bytes memory prefix = "\x19Ethereum Signed Message:\n32";
      bytes32 prefixedHash = sha3(prefix, hash);
      return ecrecover(prefixedHash, v, r, s);
    }
```
I saw the issues #208 #476 , and the following test:
https://github.com/web3j/web3j/blob/51f88364b8899ff8d89fd7bb3671d7b3624afe4d/crypto/src/test/java/org/web3j/crypto/ECRecoverTest.java.
how can I use the same **verify** function in contract no matter web3j or web3js? Thank you!

**Comment by ChocolateSlayer** [comment]
See my answer there https://github.com/web3j/web3j/issues/208 if still relevant.
That's how I can use the same verify function in contract for signatures created by web3j and web3js

**Comment by AlexandrouR** [comment]
is this still an issue ?

**Comment by AlexandrouR** [comment]
Issue closed due to inactivity.
