### ISSUE TITLE
How to get pending transaction with web3j

### ISSUE THREAD

**Issue by minhphuong1894** [web3j/web3j#487]
Hi everybody
i have a problem with web3j.
when i send eth to another eth , i check rinkeby.etherscan.io a saw pending transaction.
how i get it ?
i try to use get transaction api rinkeby but not success ! rinkeby don't show transaction pending for me
please, help me !
thanks so much !

**Comment by TOTOROYang** [comment]
u can use web3j.pendingTransactionObservable() to listen new tx commit

**Comment by AlexandrouR** [comment]
Hey is this still and issue ?
