### ISSUE TITLE
How can i create account with web3j-3.3.1

### ISSUE THREAD

**Issue by lihjchain** [web3j/web3j#488]
In web3j-2.2.1 I can create account with Parity now in web3j-3.3.1 how can I create account

**Comment by lihjchain** [comment]
O  I see in the Admin class

**Comment by GWELL52** [comment]
How do it?
i use `personalNewAccount()` return null

**Comment by GWELL52** [comment]
Thank you, It's because i didn't set `--rpcapi “personal”`.

**Comment by lihjchain** [comment]
@GWELL52 OK. I use the cmd geth --rpcapi personal,db,eth,net,web3 --rpc --testnet to connection the testnet ,why qurey the balance return 0?do you know?

**Comment by TOTOROYang** [comment]
this testnet node is youself? is it sync complete？ if not the balance is always 0.

**Comment by lihjchain** [comment]
sync  one day until now has not complete

**Comment by GWELL52** [comment]
How to configure the computer？try to use `--syncmode fast`?

**Comment by AlexandrouR** [comment]
Closed due to inactivity
