### ISSUE TITLE
How to Decoding transaction input data

### ISSUE THREAD

**Issue by githubityu** [web3j/web3j#489]
https://www.queryoverflow.gdn/query/decoding-transaction-input-data-with-web3j-java-29_31351.html

**Comment by relaxbao** [comment]
i have the same question

**Comment by ghqgfj** [comment]
Hope below code snippet will help you
` String inputData = "0xa9059cbb0000000000000000000000005c5212ed85cc957c6b656d209a7be8812ab00e330000000000000000000000000000000000000000000000008d8dadf544fc0000";
        String method = inputData.substring(0,10);
        System.out.println(method);
        String to = inputData.substring(10,74);
        String value = inputData.substring(74);
        Method refMethod = TypeDecoder.class.getDeclaredMethod("decode",String.class,int.class,Class.class);
        refMethod.setAccessible(true);
        Address address = (Address)refMethod.invoke(null,to,0,Address.class);
        System.out.println(address.toString());
        Uint256 amount = (Uint256) refMethod.invoke(null,value,0,Uint256.class);
        System.out.println(amount.getValue());`

**Comment by githubityu** [comment]
@ghqgfj thanks

**Comment by penuel-leo** [comment]
@githubityu I got some input data that length less than 74

**Comment by nicoflores95** [comment]
> Espero que el código siguiente te ayude
> 
> ```
>  String inputData = "0xa9059cbb0000000000000000000000005c5212ed85cc957c6b656d209a7be8812ab00e330000000000000000000000000000000000000000000000008d8dadf544fc0000";
>         String method = inputData.substring(0,10);
>         System.out.println(method);
>         String to = inputData.substring(10,74);
>         String value = inputData.substring(74);
>         Method refMethod = TypeDecoder.class.getDeclaredMethod("decode",String.class,int.class,Class.class);
>         refMethod.setAccessible(true);
>         Address address = (Address)refMethod.invoke(null,to,0,Address.class);
>         System.out.println(address.toString());
>         Uint256 amount = (Uint256) refMethod.invoke(null,value,0,Uint256.class);
>         System.out.println(amount.getValue());
> ```

@ghqgfj 

If I wanted to pass it to string it would be like that?

String cadena = (String)refMethod.invoke(null,to,0,String.class);

**Comment by dekinsq** [comment]
public static List<Type> decodeInputData(String inputData,
                                             String methodName,
                                             List<TypeReference<?>> outputParameters) {
        Function function = new Function(methodName,
                Collections.<Type>emptyList(),
                outputParameters
        );
        List<Type> result = FunctionReturnDecoder.decode(
                inputData.substring(10),
                function.getOutputParameters());
        return result;
    }

invoke demo:

List<Type> result = decodeInputData(inputData, "deposit",
                Arrays.asList(
                        new TypeReference<Uint256>() {
                        },
                        new TypeReference<Address>() {
                        },
                        new TypeReference<Uint256>() {
                        }
                )
        );

**Comment by monperrus** [comment]
For this task, https://github.com/rvullriede/evm-abi-decoder/ is good.
