### ISSUE TITLE
Default Type values

### ISSUE THREAD

**Issue by thedoctor** [web3j/web3j#49]
Invoking contract functions with optional parameters (i.e. parameters that may be null, not overloaded functions, which are another issue) could be simplified by providing a zero-arg constructor or public `DEFAULT` constant. 

e.g. I have a contract with the function:
```
function foo(bytes32 bar) returns (bytes32) {
    if (bar == bytes32(0)) return bar;
    // otherwise do meaningful stuff
    // ...
}
```

So far I haven't found a better way to invoke this contract using the web3j wrapper with a null value than to do something like this:
```
byte[] raw = new byte[32];
Arrays.fill(raw, (byte) 0);
contract.foo(new Bytes32(raw));
```
where I would much prefer something like:
```
contract.foo(new Bytes32());
// OR
contract.foo(new Bytes32(null));
// OR (my personal preference)
contract.foo(Bytes32.DEFAULT);
```

I think this will be valuable for a lot situations – if others agree, I'm happy to do the PR; just wanted to make sure it wouldn't be wasted effort before I started.

PS: Optionally, we could also trade some explicit type safety for convenience by teaching the FunctionEncoder to translate `null` `inputParameter` values to their Type's `DEFAULT`, allowing users to do `contract.foo(null);` but that's likely to be more controversial and would require some changes in the way Type introspection done, which would probably be invasive.

**Comment by conor10** [comment]
Hey Matt, thanks for getting in touch. A DEFAULT, or perhaps EMPTY constant sounds useful. 

Regarding null translations to defaults, I think it's best to keep args explicit for the time being.

Cheers.

**Comment by thedoctor** [comment]
Cool I agree, I'll make a PR as soon as I can get a chance to finish & clean things up.
