### ISSUE TITLE
how to get All Transaction with web3j

### ISSUE THREAD

**Issue by minhphuong1894** [web3j/web3j#490]
Hi Conor
i wanna get all transaction with web3j
now use etherscan API to get all it. it's ok but i want to use web3j to call it ?
can't you help me ?
thanks so much !

**Comment by WilliamLann** [comment]
try this
EthBlock.Block ethblock = web3j.ethGetBlockByNumber(num, true).send().getBlock();
List<TransactionResult> txlist = ethblock.getTransactions();

**Comment by minhphuong1894** [comment]
Thanks so much
but i don't know how to set address Eth to EthBlock get correct transaction history with this address ?

**Comment by AlexandrouR** [comment]
@minhphuong1894 is this still something you are trying to do ? If so did you find your answer or do you need additional information?

**Comment by AlexandrouR** [comment]
Issue closed due to inactivity.
