### ISSUE TITLE
Event filtering using web3j not working for private transaction

### ISSUE THREAD

**Issue by Purbaja** [web3j/web3j#492]
My sample contract::::
contract Notification{    
    event Notify(bytes32 txnHash);    
    function triggerEvent(bytes32 _txnHash) public returns (bool){
        Notify(_txnHash);
        return true;
    }    
}
I have deployed the contract as private and done a private transaction for the 'triggerEvent' function.
Now when trying to filter the event using web3j not able to get the event logs. The same is working fine for public transaction.

Below is my piece of code ->
final Event event = new Event(eventName, Collections.EMPTY_LIST,
				Arrays.<TypeReference<?>>asList(new TypeReference<Bytes32>() {
				}));

		EthFilter filter = new EthFilter(DefaultBlockParameterName.EARLIEST, DefaultBlockParameterName.LATEST,
				contractAddress);
		filter.addSingleTopic(EventEncoder.encode(event));
		Admin web3j = Admin.build(new HttpService(nodeUrl));		
			web3j.ethLogObservable(filter).subscribe(new Action1<Log>() {
				@Override
				public void call(Log log) {					
					System.out.println("************" + log.getData);
				}
			});

The dependency for web3j used ->
<dependency>
    <groupId>org.web3j</groupId>
    <artifactId>quorum</artifactId>
    <version>0.8.0</version>
</dependency>

**Comment by AlexandrouR** [comment]
Hi, is this still an issue with the latest version of web3j ?

**Comment by AlexandrouR** [comment]
Please create a new issue in [web3j-quorum](https://github.com/web3j/quorum).  The core library does not support quorum private transactions.
