### ISSUE TITLE
Sign.java signMessage isHashed logic backwards

### ISSUE THREAD

**Issue by aleksajovanovic** [web3j/web3j#495]
Hi all,
I am working on an android app that signs arbitrary data and sends it and I noticed this piece of code in the signMessage function:
`if (isHashed) {
            messageHash = Hash.sha3(message);
        } else {
            messageHash = message;
        }`

Shouldn't the logic for this if be the reverse? If the message is hashed then it should not be hashed again or am I missing something?

**Comment by conor10** [comment]
Agree - it is confusing. Happy to have a PR with the change.

**Comment by fcorneli** [comment]
https://github.com/web3j/web3j/pull/504
