### ISSUE TITLE
Create Wallet with Bip39 not correct ?

### ISSUE THREAD

**Issue by minhphuong1894** [web3j/web3j#496]
Hi conor
i use your library to create new wallet eth with bip39 but it's not show correct address and private key like https://coinomi.com/recovery-phrase-tool.html
can you help me, it's very important for me !
![we](https://user-images.githubusercontent.com/12869086/38724317-0d5eaaba-3f2e-11e8-9f42-3b069ef2d874.png)

**Comment by TOTOROYang** [comment]
password = "";

**Comment by ARechitsky** [comment]
Bip39 does not specify creating wallet, it's only about generating seed from mnemonic. Web3j does not support bip32+bip44, hierarchy deterministic keys. It generates exactly one key pair instead of hierarchy, where you can get "m/44'/60'/0'/0" path

**Comment by shorani** [comment]
Are you going to add support bip44?

**Comment by wl-tsui** [comment]
how to create hd wallet from mnemonic with web3j?

**Comment by AlexandrouR** [comment]
Closing as this is duplicate of #919 - please go to that issue for updated
