### ISSUE TITLE
How does web3j support multiple node connection?

### ISSUE THREAD

**Issue by qimiaoguo** [web3j/web3j#500]
when created web3j instance
`Web3j web3j = Web3j.build(new HttpService());`
it only host one node or http service, can it support multiple Web3jServices for failover?

**Comment by IcyLemon** [comment]
In my opinon blockchain is a decentralized fashion so  there is no concept of failover which only existed in the traditional server cluster..
On the other hand, web3j only connect to a single node and interact with it , suppose follow operations using web3j:
```
miner.start(1);
...
miner.stop();
```
If multiple nodes are supported in one web3j,  miner.start(1) maybe corresponds to one node and miner.stop() corresponds to another node. That's not what you want.

**Comment by AlexandrouR** [comment]
I think @IcyLemon explained it quite nicely but you could do something like this 
```
Web3j ganache = Web3j.build(new HttpService());
Web3j infura = Web3j.build(new HttpService("https://rinkeby.infura.io/v3/TOKEN"));

Web3ClientVersion web3ClientVersionGanache = ganache.web3ClientVersion().send();
Web3ClientVersion web3ClientVersionInfura = infura.web3ClientVersion().send();
System.out.println("Client Version from Ganache" + web3ClientVersionGanache.getWeb3ClientVersion());
System.out.println("Client Version from Infura" + web3ClientVersionInfura.getWeb3ClientVersion());
```

**Comment by AlexandrouR** [comment]
After speaking with @iikirilov we wanted to keep web3j as light as possible and this functionality is not required by everyone. It is up to to manage multiple instances of web3j similar to the snippet above.

Closing because because there is no further action we will take on this.
