### ISSUE TITLE
Android application using smart contracts not only for Ether transfer

### ISSUE THREAD

**Issue by adonnini** [web3j/web3j#501]
Hi,

I apologize in advance for using this forum for asking this question. I was not sure which would be the best forum to ask it. If this is not the right place, I would appreciate it fi you could let me know where I should ask this question (see below).

I want to use blockchain as the vehicle for users of my Android location tracking and positioning app to sell their location information. Blockchain is the ideal vehicle for doing this.

I have already implemented integration with bigchaindb. However, it is not clear how strong that community's commitment to java support is.

I started looking into using your software. My question is whether you think your software is suitable/can be used as is to implement general purpose smart contracts in addition to being used for Ether transfer.

Thank you,

Alex Donnini

**Comment by AlexandrouR** [comment]
> My question is whether you think your software is suitable/can be used as is to implement general purpose smart contracts

The library is not used for `implementing` smart contracts. The library can manage smart contract. You would need to implement your smart-contract in Solidity and then use our tools to generate a Java smart-contract wrapper which can then be used in your Android application to manage (deploy/call functions) the contract.

> used for Ether transfer

Web3j supports Ether transfers.

For more information check out the [docs](https://docs.web3j.io/)
For information on smart-contract support click [here](https://docs.web3j.io/smart_contracts.html)

We also have a gradle plugin that can autogenerate your code [check it out here](https://github.com/web3j/web3j-gradle-plugin)

If you have another question you can ask us on [![Gitter](https://badges.gitter.im/web3j/web3j.svg)](https://gitter.im/web3j/web3j?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
