### ISSUE TITLE
Valid private key range not enforced

### ISSUE THREAD

**Issue by rootmos** [web3j/web3j#502]
According to the yellow paper (version: `72dde18`, 2018-04-07) it's specified that the private key should be in the range `1 <= p_r < secp256k`. These egde cases are not enforced:
* `ECKeyPair.create(new BigInteger("0"))`
* `ECKeyPair.create(new BigInteger("115792089237316195423570985008687907852837564279074904382605163141518161494337"))`

both evaluate  and able to sign transactions just fine, i.e. invalidly according to `Appendix F`.

**Comment by allquantor** [comment]
@conor10 any feedback on this?
