### ISSUE TITLE
Deployed contract doesn't seem to work.

### ISSUE THREAD

**Issue by akscanb** [web3j/web3j#51]
Hi, 
I have been working on implementing a simple token contract using web3j, but when it comes to actually deploying the contract by using the generated contract wrappers. I can't seem to mine that transaction properly. I am currently running a private geth 1.5.8 unstable version node, and I can see that a transaction has been put through, but when I check the contract at the address it was generated the transactionhash is null. Even after I confirmed that the block the transaction was part of was mined. 
Below is my token deployment
MyToken asset = MyToken.deploy(web3, credentials, BigInteger.valueOf(2000000000), BigInteger.valueOf(9000000), BigInteger.valueOf(420), new Uint256(BigInteger.valueOf(1000000)), new Utf8String("asset"), new Uint8(BigInteger.valueOf(10)), new Utf8String("smt")).get();
where each parameter is:
MyToken.deploy(web3j, credentials, gasPrice, gasLimit, initialValue, initialSupply, tokenName, decimalUnits, tokenSymbol)
respectively.

Here is my geth console output:
Tx(c6143262606f20cc3216a6f2f742890c193c98e4c3ad9a97f8420c5fbbb7dd97) created: 0d0eba273e4f0213773e16602b5a915b36936daf

with eth.getTransaction("0xc6143262606f20cc3216a6f2f742890c193c98e4c3ad9a97f8420c5fbbb7dd97") 
giving me:
{
  blockHash: "0x7def5bacd197c4abe198f214df89da123d46a76484a449c59c4a2ca2ab79bca3",
  blockNumber: 499,
  from: "0x0a4a12963693bbf8f5439639a7908c90980c0e8a",
  gas: 9000000,
  gasPrice: 2000000000,
  hash: "0xc6143262606f20cc3216a6f2f742890c193c98e4c3ad9a97f8420c5fbbb7dd97",
  input: "0x6060604052604060405190810160405280600981526020017f546f6b656e20302e31000000000000000000000000000000000000000000000081525060009080519060200190828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106200008857805160ff1916838001178555620000b9565b82800160010185558215620000b9579182015b82811115620000b85782518255916020019190600101906200009b565b5b509050620000e191905b80821115620000dd576000816000905550600101620000c3565b5090565b5050346200000057604051620014e3380380620014e3833981016040528080519060200190919080518201919060200180519060200190919080518201919050505b33600560006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555083600660003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002081905550836004819055508260019080519060200190828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f10620001fd57805160ff19168380011785556200022e565b828001600101855582156200022e579182015b828111156200022d57825182559160200191906001019062000210565b5b5090506200025691905b808211156200025257600081600090555060010162000238565b5090565b50508060029080519060200190828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f10620002a657805160ff1916838001178555620002d7565b82800160010185558215620002d7579182015b82811115620002d6578251825591602001919060010190620002b9565b5b509050620002ff91905b80821115620002fb576000816000905550600101620002e1565b5090565b505081600360006101000a81548160ff021916908360ff1602179055505b505050505b6111b180620003326000396000f300606060405236156100ce576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806306fdde03146100e0578063095ea7b31461017657806318160ddd146101ca57806323b872dd146101ed578063313ce567146102605780635a3b7e421461028957806370a082311461031f57806379c65068146103665780638da5cb5b146103a257806395d89b41146103f1578063a6f9dae114610487578063a9059cbb146104ba578063cae9ca51146104f6578063dd62ed3e1461058d575b34610000576100de5b610000565b565b005b34610000576100ed6105f3565b604051808060200182810382528381815181526020019150805190602001908083836000831461013c575b80518252602083111561013c57602082019150602081019050602083039250610118565b505050905090810190601f1680156101685780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b34610000576101b0600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091908035906020019091905050610691565b604051808215151515815260200191505060405180910390f35b34610000576101d761071f565b6040518082815260200191505060405180910390f35b3461000057610246600480803573ffffffffffffffffffffffffffffffffffffffff1690602001909190803573ffffffffffffffffffffffffffffffffffffffff16906020019091908035906020019091905050610725565b604051808215151515815260200191505060405180910390f35b346100005761026d610a1e565b604051808260ff1660ff16815260200191505060405180910390f35b3461000057610296610a31565b60405180806020018281038252838181518152602001915080519060200190808383600083146102e5575b8051825260208311156102e5576020820191506020810190506020830392506102c1565b505050905090810190601f1680156103115780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b3461000057610350600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091905050610acf565b6040518082815260200191505060405180910390f35b34610000576103a0600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091908035906020019091905050610ae7565b005b34610000576103af610c9e565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34610000576103fe610cc4565b604051808060200182810382528381815181526020019150805190602001908083836000831461044d575b80518252602083111561044d57602082019150602081019050602083039250610429565b505050905090810190601f1680156104795780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b34610000576104b8600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091905050610d62565b005b34610000576104f4600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091908035906020019091905050610e03565b005b3461000057610573600480803573ffffffffffffffffffffffffffffffffffffffff1690602001909190803590602001909190803590602001908201803590602001908080601f01602080910402602001604051908101604052809392919081815260200183838082843782019150505050505091905050610fe0565b604051808215151515815260200191505060405180910390f35b34610000576105dd600480803573ffffffffffffffffffffffffffffffffffffffff1690602001909190803573ffffffffffffffffffffffffffffffffffffffff16906020019091905050611160565b6040518082815260200191505060405180910390f35b60018054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156106895780601f1061065e57610100808354040283529160200191610689565b820191906000526020600020905b81548152906001019060200180831161066c57829003601f168201915b505050505081565b600081600760003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002081905550600190505b92915050565b60045481565b600081600660008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054101561077357610000565b600660008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205482600660008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205401101561080057610000565b600760008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205482111561088957610000565b81600660008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000828254039250508190555081600660008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000828254019250508190555081600760008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600082825403925050819055508273ffffffffffffffffffffffffffffffffffffffff168473ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef846040518082815260200191505060405180910390a3600190505b9392505050565b600360009054906101000a900460ff1681565b60008054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610ac75780601f10610a9c57610100808354040283529160200191610ac7565b820191906000526020600020905b815481529060010190602001808311610aaa57829003601f168201915b505050505081565b60066020528060005260406000206000915090505481565b600560009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141515610b4357610000565b80600660008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000828254019250508190555080600460008282540192505081905550600560009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1660007fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef836040518082815260200191505060405180910390a38173ffffffffffffffffffffffffffffffffffffffff16600560009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef836040518082815260200191505060405180910390a35b5050565b600560009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60028054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610d5a5780601f10610d2f57610100808354040283529160200191610d5a565b820191906000526020600020905b815481529060010190602001808311610d3d57829003601f168201915b505050505081565b600560009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141515610dbe57610000565b80600560006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505b50565b80600660003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020541015610e4f57610000565b600660008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205481600660008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054011015610edc57610000565b80600660003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000828254039250508190555080600660008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600082825401925050819055508173ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef836040518082815260200191505060405180910390a35b5050565b60006000849050610ff18585610691565b15611157578073ffffffffffffffffffffffffffffffffffffffff16638f4ffcb1338630876040518563ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020018481526020018373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001806020018281038252838181518152602001915080519060200190808383600083146110fa575b8051825260208311156110fa576020820191506020810190506020830392506110d6565b505050905090810190601f1680156111265780820380516001836020036101000a031916815260200191505b5095505050505050600060405180830381600087803b156100005760325a03f1156100005750505060019150611158565b5b509392505050565b60076020528160005260406000206020528060005260406000206000915091505054815600a165627a7a7230582033c88a69b67b64d4b2f2b9790d6594cde7b81fd342257c1ee62a3da48e9d32d1002900000000000000000000000000000000000000000000000000000000000f42400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000561737365740000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003736d740000000000000000000000000000000000000000000000000000000000",
  nonce: 14,
  r: "0xb89b4c90d8f2cd30c7c714bde68dc04659ffe319e28758a5f97452128bae980c",
  s: "0x280567341b59e0448b7dd6a6a0fea410166f1465a63d9435732d44b9d79e9d5a",
  to: null,
  transactionIndex: 0,
  v: "0x1c",
  value: 420
}
So it looks it was properly mined.
However when I set up eth.contract(MyToken.abi)
to equal my contract instance at the address given above, none of the parameters are returning correctly, and more importantly the transactionhash is null.

**Comment by conor10** [comment]
The gasLimit looks too high - it's larger then the block gas limit.

See https://github.com/web3j/web3j/blob/master/src/main/java/org/web3j/tx/Contract.java#L35 for details.
