### ISSUE TITLE
It is very slow in creating or loading credentials on Android platform

### ISSUE THREAD

**Issue by relaxbao** [web3j/web3j#511]
hi, when I **creating** credentials on **Android platform** , it costs me over **40s** , when I **loading* credential  on **Android platform** , it costs me over **20s** . I think it spends too much time on loading or creating credentials, because on **java platform** it costs me only little than **1s** .  Looking forward to your reply~ thank you ^_^

** relevant dependency to my project** 
```
compile 'org.web3j:core:3.3.1-android'
```
**Android code**
```
new Thread(new Runnable() {
    @Override
    public void run() {
        MELog.e("generateWalletFile", "generateWalletFile");
        try {
            String fileName = WalletUtils.generateNewWalletFile(secretKey, tempFilePath, false);
            Credentials credentials1 = WalletUtils.loadCredentials(secretKey, tempFilePath.getAbsoluteFile() + "/" + fileName);
            MELog.e("publicKey:", credentials1.getEcKeyPair().getPublicKey().toString());
            MELog.e("privateKey:", credentials1.getEcKeyPair().getPrivateKey().toString());
            MELog.e("address:", credentials1.getAddress());
            Map<String, Object> returnDat = new HashMap<>();
            returnDat.put("privateKey", credentials1.getEcKeyPair().getPrivateKey());
            returnDat.put("publicKey", credentials1.getEcKeyPair().getPublicKey());
            returnDat.put("address", credentials1.getAddress());
            if (blockChainCallBack != null) {
                blockChainCallBack.completeCallBack(0, returnDat, "" + fileName);
            }
        } catch (Exception e) {
            e.printStackTrace();
            if (blockChainCallBack != null) {
                blockChainCallBack.completeCallBack(-1, null, "" + e.getMessage());
            }
        }
        MELog.e("generateWalletFile finished", "generateWalletFile finished");
        lockOfMakeKey = false;
    }
}).start();
``` 
**result**
![result](https://user-images.githubusercontent.com/19773804/39172944-dde05346-47d5-11e8-90a9-44b9543f6bd0.jpg)

**Comment by SeedZheng** [comment]
I had the same problem on Windows10 64 ,web3j 3.2.0。

**Comment by SeedZheng** [comment]
兄弟，才看到你是中国人，方便给个联系方式么，我也有还多问题，还望指教啊~

**Comment by relaxbao** [comment]
要不你加我微信吧，xiao_bao_happy

**Comment by vasa-develop** [comment]
@SeedZheng @relaxbao If you have solved the problem then can you share your solution?

**Comment by weixuefeng** [comment]
generateDerivedScryptKey is too slow on Andorid Platform

**Comment by weixuefeng** [comment]
https://lhalcyon.com/blockchain-eth-unlock-android/  resolve my ploblem

**Comment by herl3n** [comment]
> 
> 
> https://lhalcyon.com/blockchain-eth-unlock-android/ resolve my ploblem

Hello weixuefeng, 

Can you please explain about that link you have provided? I cannot understand because it is written in Chinese. 

My Android Application is also loading the credentials so slowly... (~1-2 mins)

**Comment by emanuelcanha** [comment]
Disabling **Instant Run** on Android Studio worked for me. This issue is related to #119

**Comment by AlexandrouR** [comment]
@relaxbao is this still an issue with web3j 4.3.1 ?
