### ISSUE TITLE
how to get remark from tx

### ISSUE THREAD

**Issue by githubityu** [web3j/web3j#521]
`public static String transfer(Web3j web3j,String toaddress,Credentials credentials){
        final TransactionManager transactionManager = new RawTransactionManager(web3j, credentials );
        try {
            EthSendTransaction ethSendTransaction = transactionManager.sendTransaction(GAS_PRICE, GAS_LIMIT, toaddress, "remark", new BigInteger("20"));
           return ethSendTransaction.getTransactionHash();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return "";
    }`

how to getremark from tx?? thanks

**Comment by iikirilov** [comment]
you should generate the smart contract wrapper and call `contract.remark()` (assuming remark is a global variable), else you can manually encode the function call
