### ISSUE TITLE
create private key 63 char

### ISSUE THREAD

**Issue by lelence** [web3j/web3j#522]
def getAuth: (String, String) = {
    val ecKeyPair = Keys.createEcKeyPair();
    val privateKeyInDec = ecKeyPair.getPrivateKey();
    //      Wallet.createStandard(password, ecKeyPair)
    val aWallet = Wallet.createStandard(java.util.UUID.randomUUID().toString, ecKeyPair);
    val sAddress = aWallet.getAddress()

    ("0x" + sAddress, Numeric.toHexStringNoPrefix(privateKeyInDec))
  }

or use test

@Test
	public void test() throws Exception {

		for (int i = 0; i < 100; i++) {
			ECKeyPair ecKeyPair = Keys.createEcKeyPair();
			String pk = ecKeyPair.getPrivateKey().toString(16);
			assertThat(pk.length(), is(64));
		}
	}

it`s my code, i get PrivateKey sometimes 63 char, the test will throw an exception

**Comment by lelence** [comment]
I found the way, when privateKey lenth equals 63, add "0" at front

**Comment by jackchendong** [comment]
I'll give it a try.

**Comment by jackchendong** [comment]
thanks
