### ISSUE TITLE
Is anyone app crash when receive error response from RPC ?

### ISSUE THREAD

**Issue by YYwishp** [web3j/web3j#526]
I have use version 3.3.1 android web3j in my app ,sometimes i send Transaction with web3j  , my app reports some error like this.      so I would like to know what's this problem, can anyone help me,thankyou!!
It seems data is object ，and web3j can not analysis.

# app report some error：
<com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
com.gyx.bitcoinwalletdemo W/System.err:     at [Source: buffer(okhttp3.internal.http1.Http1Codec$ChunkedSource@3872a2e2).inputStream(); line: 1, column: 200] (through reference chain: org.web3j.protocol.core.methods.response.EthSendTransaction["error"]->org.web3j.protocol.core.Response$Error["data"])
com.gyx.bitcoinwalletdemo W/System.err:     at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)>

# This is what i receive from rpc
![1dc04251c742f9dc2d7dabc4112c09d6](https://user-images.githubusercontent.com/16057737/39624577-718fc218-4fcc-11e8-9dec-45150f86502d.png)
{"id":7,"jsonrpc":"2.0","error":{"message":"sender doesn't have enough funds to send tx. The upfront cost is: 250000000000000 and the sender's account only has: 145000000000000","code":-32000,"data":{"stack":"Error: sender doesn't have enough funds to send tx. The upfront cost is: 250000000000000 and the sender's account only has: 145000000000000\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib/runTx.js:93:1\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:3947:1\n at o (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1031:1)\n at f (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:998:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:966:1\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:4079:1\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/internal/eachOfLimit.js:3:1\n at l (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/internal/eachOfLimit.js:16:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/internal/eachOfLimit.js:28:39\n at t.default (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/eachLimit.js:20:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/internal/slice.js:3:1\n at g.n.emit (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async-eventemitter/lib/AsyncEventEmitter.js:58:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib/runTx.js:88:1\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:3947:1\n at o (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1031:1)\n at f (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:998:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:966:1\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:4079:1\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib/runTx.js:85:1\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:3947:1\n at o (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1031:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1032:1\n at Ae (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1038:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1049:10\n at ua (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:3873:6)\n at Object.Ta [as series] (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:4849:1)\n at g.e.exports [as runTx] (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib/runTx.js:68:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib/runBlock.js:104:1\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:3204:1\n at o (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1031:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1032:1\n at Ut (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:3245:1)\n at Object. (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1049:10)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib/runBlock.js:84:1","name":"Error"}}}

**Comment by YYwishp** [comment]
@Brotherhood94  thanks，but，i just want to know if users input error data like address,either amount  to send,(if the user don't have  enough money), the rpc will response some error information. And Now i receive the error json, the web3J can not analysis the json. I just want to know how to analysis the error json data. And Then get the error message field，thank you！！！

**Comment by pgreze** [comment]
JSON mapping is only considering a success answer, and is failing when an error is returned.

We should have access to a basic error handler like access to the raw content from server, because it's nearly impossible to debug error cases for now.

**Comment by YYwishp** [comment]
@pgreze Thank you very much, I do not know it's nearly impossible to debug error cases before you told me ,  Thank you
