### ISSUE TITLE
WalletUtils.generateBip39Wallet return null

### ISSUE THREAD

**Issue by lihjchain** [web3j/web3j#528]
I use the WalletUtils.generateBip39Wallet("123456789",new File("/usr/local"));
in the MnemonicUtils   function populateWordList() return null;
I use the 3.3.1 version

**Comment by lihjchain** [comment]
OK In the version 3.4.0 the bug is solved

**Comment by weixuefeng** [comment]
is there have version 3.4.0 for android?

**Comment by dhruvi1kosmos** [comment]
@lihjchain  I m getting error- Failed to resolve: org.web3j:core:3.4.0-android
