### ISSUE TITLE
Compiling contract inside Java code

### ISSUE THREAD

**Issue by matthiaszimmermann** [web3j/web3j#53]
I'd like to compile a contract from within the Java code starting with Solidity source code. For this I was looking at your method CoreIT.testEthCompileSolidity and using TestRPC. 

```
@Test
public void testEthCompileSolidity() throws Exception {
	String sourceCode = "pragma solidity ^0.4.0; contract test { function multiply(uint a) returns(uint d) { return a * 7; } }";
	EthCompileSolidity ethCompileSolidity = web3.ethCompileSolidity(sourceCode)
				.send();
	Assert.assertNotNull(ethCompileSolidity.getCompiledSolidity());
	Assert.assertEquals(ethCompileSolidity.getCompiledSolidity().getTest().getInfo().getSource(), sourceCode);
}
```
unfortunately ethCompileSolidity.getCompiledSolidity() returns null. Testing the same solidity code with curl does produce some meaningful output: 

```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_compileSolidity","params":["pragma solidity ^0.4.0; contract test { function m
ultiply(uint a) returns(uint d) { return a * 7; } }"],"id":1}' 192.168.99.100:8545
{"id":1,"jsonrpc":"2.0","result":{"code":"0x6060604052346000575b60458060156000396000f3606060405260e060020a6000350463c6888fa18114601c575b6000565b346000576029600435603
b565b60408051918252519081900360200190f35b600781025b91905056","info":{"source":"pragma solidity ^0.4.0; contract test { function multiply(uint a) returns(uint d) { re
turn a * 7; } }","language":"Solidity","languageVersion":"0.4.6+commit.2dabbdf0.Emscripten.clang","compilerVersion":"0.4.6+commit.2dabbdf0.Emscripten.clang","abiDefi
nition":[{"constant":false,"inputs":[{"name":"a","type":"uint256"}],"name":"multiply","outputs":[{"name":"d","type":"uint256"}],"payable":false,"type":"function"}],"
userDoc":{"methods":{}},"developerDoc":{"methods":{}}}}}
```
From this output I conclude that my TestRPC installation does seem to work and must have access to solc as well. So why does the JUnit test fail? 

What am I missing?

**Comment by conor10** [comment]
Ok, so there's two issues here.

Firstly testrpc does not provide the compiled contract name in the result, which differs from geth. I've raised the following [issue](https://github.com/ethereumjs/testrpc/issues/254) requesting this is addressed.

Secondly, there is a bug in web3j whereby it does not process the map of <contract name> -> <contract metadata> correctly.

I have a fix which I'll check in tonight for this, so will be included in the 1.2.0 release which is imminent.

**Comment by matthiaszimmermann** [comment]
thanks much for looking into this and opening the bug against testrpc!

**Comment by HamzaYasin1** [comment]
Hey @conor10 !
I'm facing the same problem while using Web3j 2.3.0 , method ethCompileSolidity() isn't compiling code although it gives a null.
![1](https://user-images.githubusercontent.com/30287193/30064847-6e1969ea-926c-11e7-9c98-0d4cf730f6cf.PNG)

![2](https://user-images.githubusercontent.com/30287193/30064859-7726430a-926c-11e7-9881-a70051393eab.PNG)

This Piece of code returns Null.

I'll be appreciated if you help me to get rid out of it.
Thanks.

**Comment by russdanner** [comment]
I have the same issue 2.3.1 but haven't yet determined if it's a bug or just my use of the code :)

**Comment by sanjanabrid** [comment]
Tried running " solc Greeter.sol --bin --abi --optimize -o ../build" in terminal(went upto directory where greeter.sol is stored). But i got error saying solc-command not found on terminal. I have already installed solc globally. Can you please help??
