### ISSUE TITLE
how do i know wether a transaction is a erc20' transfer method?

### ISSUE THREAD

**Issue by beykery** [web3j/web3j#531]
i have 1 transaction hash :0x750207ec9db9a1661013c14968d8ecf47b1115987acee7d697f8cc71217a152e

and how i will know this hash result from an erc20 contract method transfer?

**Comment by TOTOROYang** [comment]
see transactionReceipt logs

**Comment by fatemehramezanli** [comment]
> see transactionReceipt logs

**Comment by ddekob15-boop** [comment]
A
