### ISSUE TITLE
Set GasLimit and Gas Price on Android

### ISSUE THREAD

**Issue by minhphuong1894** [web3j/web3j#535]
i wanna change default gas of web3j android
default it's have gaslimit 21000 and gasprice 1
how i set change it before i send eth ?
please help me ! it's very important with me
thanks so much

**Comment by csseryang** [comment]
GasLimit and GasPrice are just BigIntegers, you can define them when loading a contract. 

e.g
```
private static final BigInteger CUSTOM_GAS_PRICE = Convert.toWei("8", Convert.Unit.GWEI).toBigInteger();

 Greeter contract = Greeter.deploy(
                web3j, credentials,
                CUSTOM_GAS_PRICE, Contract.GAS_LIMIT,
                "Hello blockchain world!").send();
```
