### ISSUE TITLE
Events not returning when using observable filter from web3j wrapper in Android

### ISSUE THREAD

**Issue by jbsantana2010** [web3j/web3j#536]
```
contract.tradeRegisteredEventObservable(DefaultBlockParameterName.EARLIEST,DefaultBlockParameterName.LATEST).subscribe(tradeRegisteredEventResponse ->  {

                   System.out.println("An event:" + tradeRegisteredEventResponse.amount.toString());                   

               });
```
I am attempting to get all registered events by using the observable filter created by web3j wrapper as illustrated above.
My contract is valid and when I trigger the observable it does interact with my local blockchain made in ganache. But android doesn't return any of the event values. I get no error.
Am I missing something? It is my first time working with rxjava so any help would be greatly appreciated. Thanks.

**Comment by vpriscan** [comment]
I have the same issue on PC. Events are never being emitted.

**Comment by iikirilov** [comment]
Closed due to inactivity
