### ISSUE TITLE
web3j solidity generate creates wrong deploy() in new sol with "constructor" instead of contract name

### ISSUE THREAD

**Issue by buzzm** [web3j/web3j#537]
This will produce a proper Java `deploy()` sig with transaction and creds and gas followed by a string and a BigInteger:
```
contract foo {
   function foo(string a, uint b) {
   }
}

public static RemoteCall<Ticket1> deploy(Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit, String _greeting, BigInteger amt) {
    String encodedConstructor = FunctionEncoder.encodeConstructor(Arrays.<Type>asList(new org.web3j.abi.datatypes.Utf8String(a),
            new org.web3j.abi.datatypes.generated.Uint256(b)));
    return deployRemoteCall(Ticket1.class, web3j, credentials, gasPrice, gasLimit, BINARY, encodedConstructor);
}
```

But the new solc (v0.4.22) deprecates the constructor-as-same-name in favor of a special function "constructor":
```
contract foo {
   function constructor(string a, uint b) {
   }
}
```
web3j generate will generate a default constructor only, i.e. it does not pick up `string a` and `uint b`.

**Comment by AlexandrouR** [comment]
You are correct but you can sill pass the values you want to the contract using something like this 
` Foo contract =Foo.deploy(web3j,credentials,contractGasProvider,"test",BigInteger.valueOf(50)).send();`

The test string and the BigInteger are the values that you need to pass into the constructor.
Let me know if this solved your issue.

**Comment by AlexandrouR** [comment]
Is this still an issue with the latest version ?
