### ISSUE TITLE
Generate keywords with Mnemonic web3j

### ISSUE THREAD

**Issue by minhphuong1894** [web3j/web3j#538]
i update my gradle with 3.3.1 web3j
i use MnemonicUtils to generate keywords for my wallet
![123](https://user-images.githubusercontent.com/12869086/39861288-5564f9bc-546a-11e8-8325-d35b8a522f03.png)

i have question for this:
1. i don't know byte[] initialEntropy so i new byte and input it 16
2 . iterations =12 it's mean i have 12 keywords right ?
3. mnemonicBuilder.append(WORD_LIST.get(index)); i get index = 0 => crash 
and i got the message java.lang.IndexOutOfBoundsException: Index: 0
please help me,

**Comment by pgreze** [comment]
I believe the IndexOutOfBoundsException is due to:
```
private static final List<String> WORD_LIST = populateWordList();
```
Because populateWordList is silently failing when en-mnemonic-word-list.txt is not found.

Moreover for Android it will never work.

**Comment by rohfosho** [comment]
Why will it never work for Android? Are there plans to get it working with Android?

**Comment by mnl-assasin** [comment]
Looking for answer as well. I'm stuck in this part too. Thanks
I can see the en-mnemonic-word-list.txt file inside the jar

**Comment by ehanoc** [comment]
I had the same issue. There was a previous PR to solve this, it was merged into master. The android branch had some different dependencies that created problems too. 

Test PR #598, it's working for me now
