### ISSUE TITLE
ethLogObservable never emitting events

### ISSUE THREAD

**Issue by vpriscan** [web3j/web3j#543]
**Scenario to reproduce:**
1. Start ganache-cli (**v6.1.0**) to simulate an ethereum node, make sure you have an account with some ether.
2. Create a simple contract containing one function that that makes changes to the blockchain (increments stored uint or something) and then emits one event.
3. Compile it using solc (**v0.4.23**) and use web3j (**v3.4.0**) to generate contract java wrapper.
4. Connect web3j (**v3.4.0**) to ganache. Also make sure you have an account with enough ether.
5. Deploy the contract.
6. Subscribe to transaction log events, topic filter not needed, or subscribe to concrete event observable using contract wrapper.
7. Call the contract function that emits an event. 

**Result:** No events were received by the subscriber, I waited for 10 minutes.

**Subscribing to transaction log:**
```
        val ethFilter = EthFilter(DefaultBlockParameterName.EARLIEST,
                DefaultBlockParameterName.LATEST, contractAddress)
        
        val subscribe = web3j.ethLogObservable(ethFilter).subscribe {
            println("Received something...")
        }
```
**Used contract:**
```
pragma solidity ^0.4.23;

contract SomeContract {
    uint someNumber = 0;
    event SomeEvent(string someData);

    function doSomething() public {
        someNumber++;
        emit SomeEvent("someData...");
    }
}

```

Update: tried using truffle develop (**v4.1.8**) instead of ganache, still no events are received by the subscriber.

**Comment by AlexandrouR** [comment]
@vpriscan  Is this still an issue ?

**Comment by vpriscan** [comment]
@AlexandrouR, I haven't tried it since. Will try in the following days and report back.

**Comment by AlexandrouR** [comment]
@vpriscan  Thanks
