### ISSUE TITLE
Transacting with a smart contract Can't get  TransactionHash

### ISSUE THREAD

**Issue by xxmfypp** [web3j/web3j#548]
Where I to transact with an existing smart contract,I want to get  the TransactionHash.but transactionResponse return null.I got the an Error Message : unknown account

**Java snippet:**
```java
        Web3j web3j = Web3j.build(new HttpService("http://192.168.110.244:8545"));
        Credentials credentials = Credentials.create(ECKeyPair.create(new BigInteger("110804339409980840097210254512645733622087756400378670270053111692154636375575")));
        String set_contract_Address = "0x6413edb5511387ec23df3cefcb69fdb635862e05";
        Function function = new Function(
                "setstring",
                Arrays.<Type>asList(new org.web3j.abi.datatypes.Utf8String("111")),
                Collections.<TypeReference<?>>emptyList());

        EthGetTransactionCount ethGetTransactionCount = web3j.ethGetTransactionCount(credentials.getAddress(),DefaultBlockParameterName.LATEST).send();
        BigInteger count =ethGetTransactionCount.getTransactionCount();

        String encodedFunction = FunctionEncoder.encode(function);

        Transaction transaction = Transaction.createFunctionCallTransaction(
                credentials.getAddress(),count, ManagedTransaction.GAS_PRICE, Contract.GAS_LIMIT, set_contract_Address,  encodedFunction);

        EthSendTransaction transactionResponse = web3j.ethSendTransaction(transaction).sendAsync().get();

        System.out.println(transactionResponse.getError().getMessage());
        String transactionHash = transactionResponse.getTransactionHash();
        System.out.println(transactionHash);
```

**Java Result**
```java
Error Message:unknown account
TransactionHash:null
```

**solidity script**
```javascript
pragma solidity ^0.4.0;
contract set {
    string storedData;
    function set() public {
    }
    function setstring(string data) {
        storedData = data;
    }
    function get() public constant returns (string) {
        return storedData;
    }
}
```

The version of the jar is ：3.4.0 ，Where is my mistake? help please.

**Comment by haldhar** [comment]
Hi Dude,

I have done some modification on top of your contract.
pragma solidity ^0.4.0;
contract Set {
    string storedData;
    function set() public {
    }
    function setstring(string data) {
        storedData = data;
    }
    function get() public constant returns (string result) {
        return storedData;
    }
}

below simple code to execute the above transaction
Web3j web3j = Web3j.build(new HttpService("http://localhost:22000"));
Credentials credentials = Credentials.create("0x7ca02fe4a8c5f81784805d908f3b0a81a1bd1c79");
Set set = new Set("0x3bc51982a6cf3c5b84fd4596556686e692cfd2f8",web3j,credentials,Contract.GAS_PRICE,Contract.GAS_LIMIT);
TransactionReceipt transactionResponse = set.setstring("HELLO JAVA").send();
System.out.println(transactionResponse.getTransactionHash());
String result = set.get().send();
System.out.println("GET VALUE " + result);

**Comment by haldhar** [comment]
Hi Dude,

I have done some modification on top of your contract.
pragma solidity ^0.4.0;
contract Set {
string storedData;
function set() public {
}
function setstring(string data) {
storedData = data;
}
function get() public constant returns (string result) {
return storedData;
}
}

below simple code to execute the above transaction
Web3j web3j = Web3j.build(new HttpService("http://localhost:22000"));
Credentials credentials = Credentials.create("0x7ca02fe4a8c5f81784805d908f3b0a81a1bd1c79");
Set set = new Set("0x3bc51982a6cf3c5b84fd4596556686e692cfd2f8",web3j,credentials,Contract.GAS_PRICE,Contract.GAS_LIMIT);
TransactionReceipt transactionResponse = set.setstring("HALDHAR SETH").send();
System.out.println(transactionResponse.getTransactionHash());
String result = set.get().send();
System.out.println("GET VALUE " + result);

**Comment by NixerSo5** [comment]
> 在我与现有智能合约进行交易的地方，我想得到 TransactionHash.but transactionResponse 返回 null。我收到一条错误消息：未知帐户
> 
> **Java 代码段：**
> 
> ```java
>         Web3j web3j = Web3j.build(new HttpService("http://192.168.110.244:8545"));
>         Credentials credentials = Credentials.create(ECKeyPair.create(new BigInteger("110804339409980840097210254512645733622087756400378670270053111692154636375575")));
>         String set_contract_Address = "0x6413edb5511387ec23df3cefcb69fdb635862e05";
>         Function function = new Function(
>                 "setstring",
>                 Arrays.<Type>asList(new org.web3j.abi.datatypes.Utf8String("111")),
>                 Collections.<TypeReference<?>>emptyList());
> 
>         EthGetTransactionCount ethGetTransactionCount = web3j.ethGetTransactionCount(credentials.getAddress(),DefaultBlockParameterName.LATEST).send();
>         BigInteger count =ethGetTransactionCount.getTransactionCount();
> 
>         String encodedFunction = FunctionEncoder.encode(function);
> 
>         Transaction transaction = Transaction.createFunctionCallTransaction(
>                 credentials.getAddress(),count, ManagedTransaction.GAS_PRICE, Contract.GAS_LIMIT, set_contract_Address,  encodedFunction);
> 
>         EthSendTransaction transactionResponse = web3j.ethSendTransaction(transaction).sendAsync().get();
> 
>         System.out.println(transactionResponse.getError().getMessage());
>         String transactionHash = transactionResponse.getTransactionHash();
>         System.out.println(transactionHash);
> ```
> 
> **Java Result**
> 
> ```java
> Error Message:unknown account
> TransactionHash:null
> ```
> 
> **坚固性脚本**
> 
> ```js
> pragma solidity ^0.4.0;
> contract set {
>     string storedData;
>     function set() public {
>     }
>     function setstring(string data) {
>         storedData = data;
>     }
>     function get() public constant returns (string) {
>         return storedData;
>     }
> }
> ```
> 
> 罐子的版本是：3.4.0，我的错误在哪里？请帮忙。

i get the same error  how to fix it ?
