### ISSUE TITLE
Android: ParameterizedTypeImpl not found

### ISSUE THREAD

**Issue by repfuesch** [web3j/web3j#55]
In the android library, I get the exception: 
java.lang.NoClassDefFoundError: Failed resolution of: Lsun/reflect/generics/reflectiveObjects/ParameterizedTypeImpl in the class "org.web3j.abi.TypeReference" 

It seems that the class does not reference the correct implementation of "ParameterizedType". I think the correct class in android is "libcore.reflect.ParameterizedTypeImpl"

Best regards

**Comment by conor10** [comment]
This should be addressed in the 2.0 Android release which I'm about to get out - see the following PR https://github.com/web3j/web3j/pull/46/files.

Please reopen this issue if you still encounter the problem.
