### ISSUE TITLE
Decoding the Smart Contract Transaction Data

### ISSUE THREAD

**Issue by rsalvadg** [web3j/web3j#553]
Hi,

I use the web3j 3.4.0 API and I have tho decode the information that I send in the Transaction Data field. For example:
Transaction Data Field = 0x6587f6ec0000000000000000000000000000000000000000000000000000000000000064

I know that the "0x6587f6ec" is the Method ID (ABI) and the next 32 bytes "0000000000000000000000000000000000000000000000000000000000000064" is the argument sent in the Smart Contract method.

But my problem is to decode this information in String with the web3j API:
- 0x6587f6ec = play(uint)
- 0000000000000000000000000000000000000000000000000000000000000064 = 100

Can anyone help me please?

Best Regards,

**Comment by haldhar** [comment]
Hi rsalvadg,

you can use below code for decode your hex value
TypeDecoder.decodeNumeric(           "0000000000000000000000000000000000000000000000000000000000000064",
                Uint64.class
                )

**Comment by rsalvadg** [comment]
Hi @haldhar,

I tried to implement what you pass me, but it says that "TypeDecoder.decodeNumeric" is a not visible method, I tried the "TypeDecoder.decode" and the result is the same :(

Any other option?

Best Regards

**Comment by codebazz** [comment]
> Hi @haldhar,
> 
> I tried to implement what you pass me, but it says that "TypeDecoder.decodeNumeric" is a not visible method, I tried the "TypeDecoder.decode" and the result is the same :(
> 
> Any other option?
> 
> Best Regards

Because it is private to that package. any  solution  please?

**Comment by mehranshakeri** [comment]
Same issue. 
Actually I expected that Web3j can provide me the decoder for my smart contract since it already wrapped it in a Java class and knows all function names and their arguments.
Now that I'm trying to write the decoder by myself, I see almost all the TypeDecoder functions are package private. Is there any reason to not make them public? Otherwise I need to copy/paste the whole class :/

**Comment by codebazz** [comment]
> Same issue.
> Actually I expected that Web3j can provide me the decoder for my smart contract since it already wrapped it in a Java class and knows all function names and their arguments.
> Now that I'm trying to write the decoder by myself, I see almost all the TypeDecoder functions are package private. Is there any reason to not make them public? Otherwise I need to copy/paste the whole class :/

no luck for me

**Comment by AlexandrouR** [comment]
The solution here is to make the TypeDecoder functions public. PR is welcome.

**Comment by mehranshakeri** [comment]
@AlexandrouR I might find some time to create PR. 
Should I make all the functions public? except the ones which are explicitly marked as private.

**Comment by RealDeanZhao** [comment]
Workaround: use FunctionReturnDecoder
```
final List<TypeReference<?>> typeReferences = Arrays.asList(
                new TypeReference<Utf8String>() {
                },
                new TypeReference<Utf8String>() {
                },
                new TypeReference<Utf8String>() {
                },
                new TypeReference<Utf8String>() {
                }
        );

        final String txData = transaction.getInput().substring(10);

        return FunctionReturnDecoder
                .decode(txData, Utils.convert(typeReferences));
```

**Comment by gtebrean** [comment]
Now there is the methods decodeEventParameter decodeFunctionResult that can be used.
