### ISSUE TITLE
How do I tightly pack arguments for Hash.sha3()

### ISSUE THREAD

**Issue by aleksajovanovic** [web3j/web3j#559]
Hey guys,

I'm having some trouble getting the same sha3 hash with web3j as I am with web3-utils sha3. 

The web3-utils hash has been checked against an ecrecover function so i know its correct. The problem I am having is concatenating my arguments in java before passing them to `Hash.sha3()`. Right now I'm doing this:

`String message = userPreferenceManager.getPaymentChannelAddr() + nonce.toString() + amount.toString();`

`byte[] hexMessage = Hash.sha3(message.getBytes());`

Cheers

**Comment by ice09** [comment]
It's not as easy as that, maybe take a look at these samples

- https://gist.github.com/ice09/33b46d31c4be7b434f299c0bcacbee56#file-uraiden-java
- https://github.com/ice09/onboarding-eip712/blob/master/src/main/java/de/ice09/safesigs/services/SignatureService.java

which might help. In general, packing/concat in Solidity and Java is different, Solidity (and therefore the web3-utils) allow for several arguments, which are then "packed". The web3j method allows for only one argument. In recent Solidity versions this behaviour has changed: https://medium.com/@libertylocked/what-are-abi-encoding-functions-in-solidity-0-4-24-c1a90b5ddce8

**Comment by AlexandrouR** [comment]
Closed due to inactivity.
