### ISSUE TITLE
web3j solidity News 65535 bytes

### ISSUE THREAD

**Issue by githubityu** [web3j/web3j#560]
but   private static final String BINARY="";
  Error:(32, 14) java: The type generates a string that requires more than 65535 bytes to encode in Utf8 format in the constant pool

**Comment by Pashkou** [comment]
I have the same issue. Do you have may be some workaround?

**Comment by AlexandrouR** [comment]
Is this will an issue if so please provide more information about what is going on or what you want to do.

**Comment by asuarezgrupobme** [comment]
I am having the same issue here. I believe it is a problem with the binary string in the generated code being longer than 65535 bytes.
