### ISSUE TITLE
Deploy, transact and call smart contract without generating wrapper code 

### ISSUE THREAD

**Issue by nicolasgnr** [web3j/web3j#563]
QQ Is there a way to deploy or call a smart contract without using the autogenerated wrappers? I need to interact with a smart contract but just having the `ABI` and web3j. Could someone point me to an example? Thanks!

**Comment by conor10** [comment]
Yes - see the following docs for details https://docs.web3j.io/transactions.html#creation-of-a-smart-contract.

**Comment by nicolasgnr** [comment]
Thanks @conor10!
