### ISSUE TITLE
Address checksum check implemented in Web3j?

### ISSUE THREAD

**Issue by codingyourlife** [web3j/web3j#568]
In web3**JS** there is an [isAddress() check](https://web3js.readthedocs.io/en/1.0/web3-utils.html?highlight=isAddress#isaddress) method that considers the checksum in case Address is upper and lowercase. Is something like that implemented in web3**J** too? I expected this check to occur by passing a string to new Address() but it only seems to checks basic things

```
@Test
public void testAddressValidity() throws Exception {
    Web3j web3 = new Web3jProvider(SettingsSingleton.getInstance().getJsonRpcUrl(), SettingsSingleton.getInstance().getHttpServiceProvider()).get();

    Address validAddress = new Address("0xCd2a3d9f938e13Cd947eC05ABC7fe734df8DD826");
    Exception occuredException = null;

    Address invalidAddress = new Address(validAddress.toString().replace("a", "b")); //does not fail :/

    String aha = Keys.toChecksumAddress(validAddress.toString());

    try {
        String ahaB = Keys.toChecksumAddress(invalidAddress.toString());
    } catch (Exception e) {
        occuredException = e;
    }

    Assert.assertNotEquals(null, occuredException); //this fails :(
}
```

Also see [EIP-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md)

**Comment by codingyourlife** [comment]
Okay you can just say toChecksumAddress() and compare it with the original address to work around this problem...

**Comment by Gelassen** [comment]
In [this PR](https://github.com/web3j/web3j/pull/134) it was told ```WalletUtils.isValidAddress``` should work too.
