### ISSUE TITLE
There is no Web3j.build() function on Android

### ISSUE THREAD

**Issue by myeveryheart** [web3j/web3j#570]
`package org.web3j.protocol;

import org.web3j.protocol.core.Ethereum;
import org.web3j.protocol.rx.Web3jRx;

/**
 * JSON-RPC Request object building factory.
 */
public interface Web3j extends Ethereum, Web3jRx {

}`

**Comment by weixuefeng** [comment]
may be you should use Web3jFactory.build() on Android.

**Comment by snazha-blkio** [comment]
Hi @myeveryheart 
That's correct - please use Web3jFactory.

I will close this issue; feel free to re-open it if needed.
