### ISSUE TITLE
RuntimeException have  problem in web3j

### ISSUE THREAD

**Issue by ghost** [web3j/web3j#579]
java.lang.RuntimeException: Error processing transaction request: replacement transaction underpriced.

when have the exception ,we can't get it .and I find the function has no RuntimeException in the web3j .

**Comment by TOTOROYang** [comment]
This error information should in response error msg. 
I have see "replacement transaction underpriced" in send transaction response.

**Comment by kay07** [comment]
At the bottom of the call, it exists. but the middle is not thrown, resulting in the last failure to catch.

**Comment by AlexandrouR** [comment]
Is this still an issue ? if so please provide steps to reproduce.

**Comment by AlexandrouR** [comment]
Closed due to inactivity if this is still a problem please open a new issue using the instructions.
