### ISSUE TITLE
How to catch smart contract exception in web3j

### ISSUE THREAD

**Issue by haldhar** [web3j/web3j#581]
I am executing below contract set method by passing 121 and the transaction reverted internally.
How can i capture the revert(); and send to end user.
while executing the transaction i am getting only txn hash fro the hash unable to find the revert() condition.

pragma solidity ^0.4.23;
contract SampleStorage {
    uint storedData;
    bytes32 newData;
    bool res;
    event print(uint storedData);
    event print1(bytes32 storedData1);
    event print2(bool storedData2);
    modifier throwData(uint val){
        if(val != 100)
            revert();
            _;
    }
    function set(uint x) public throwData(x) {         
        storedData = x;
        emit print(storedData);
    }
    function get() public constant returns (uint) {             
        return storedData;
    }
}

**Comment by AlexandrouR** [comment]
Revert takes a string argument passed by the user such as revert("val is 100") this will be returned to you. You can read more about error handling [here](https://solidity.readthedocs.io/en/v0.5.10/control-structures.html#revert)
