### ISSUE TITLE
Export My private key is too slow on android device.

### ISSUE THREAD

**Issue by weixuefeng** [web3j/web3j#582]
When i use /crypot/Wallet.java to decrypt my keystore and export mnemonic on Android devices,   it spents 48 seconds.. Could you help me ?

**Comment by TOTOROYang** [comment]
turn down keystore N P params. It can be fast. decrypt keystore and create keystore cost much CPU power

**Comment by weixuefeng** [comment]
i resolve it by geth/mobile/account -> Keystore.exportPrivateKey
maybe i'd know the different of their algorithms..
