### ISSUE TITLE
How to convert Iban account to ether address

### ISSUE THREAD

**Issue by w2282346548** [web3j/web3j#589]
How to convert Iban account to ether address

**Comment by YYwishp** [comment]
I have the same problem too,And I want to konw how to convert ether address to iban account.

**Comment by TOTOROYang** [comment]
[see my project](https://github.com/ethjava/web3j-sample/blob/master/src/main/java/com/ethjava/IBAN.java)

**Comment by YYwishp** [comment]
@TOTOROYang thank you very much, I have already find your project before you told me , thanks!!!

**Comment by AlexandrouR** [comment]
Is this still an issue ?
