### ISSUE TITLE
[WIP][New Feature] Support for batch requests

### ISSUE THREAD

**Issue by ali-sharif** [web3j/web3j#593]
Batch JSON-RPC support exists for all mainstream Ethereum clients:
https://github.com/ethereum/wiki/wiki/JSON-RPC#json-rpc-support

The Javascript Web3 client has fairly stable support for batch requests:
https://web3js.readthedocs.io/en/1.0/web3.html#batchrequest

Having gone through the Ethereum client implementations for batch JSON-RPC calls, they all implement the following spec (more or less):
http://www.jsonrpc.org/specification#batch

I have a quick implementation for this feature that I have running in project (snippet appended as a comment in this thread)

**Open Questions to Maintainers:**
1. I need a quick opinion and guidance from maintainers of this project regarding what would their ideal change to the public-facing API (as defined in [Web3jService.java](https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/protocol/Web3jService.java)) would look like (see my proposal in the snippet in the comments)
2. What would it take in terms of tests & verification for me to get a PR with this change accepted 

Once I get an idea on these things, I'll submit a PR

**Comment by ali-sharif** [comment]
## Quick outline of proposed implementation: 

Add to **[Service.java](https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/protocol/Service.java)**
```
public static class BatchRequest {
    private List<Request<? extends Response<?>>> requests;
    private Map<Request<?>, Response<?>> responses;

    public BatchRequest() {
        requests = new ArrayList<>();
        responses = new HashMap<>();
    }

    public void addRequest(Request<?> request) {
        requests.add(request);
    }

    public void addAllRequests(List<Request<?>> requests) {
        this.requests.addAll(requests);
    }

    public <T extends Response<?>> Optional<T> getResponse(Request<T> request) {
        return Optional.ofNullable(request.getResponseType().cast(responses.get(request)));
    }
}

public boolean sendBatch(BatchRequest batch) throws IOException {
    String payload = objectMapper.writeValueAsString(batch.requests);

    try (InputStream result = performIO(payload)) {
        if (result != null) {
            List<JsonNode> jsonResponse = objectMapper.readValue(result, new TypeReference<List<JsonNode>>(){});
            for (int i = 0; i < jsonResponse.size(); i++)
                batch.responses.put(batch.requests.get(i), objectMapper.treeToValue(jsonResponse.get(i),
                        batch.requests.get(i).getResponseType()));

            return true;
        }
    }

    return false;
}
```

Add to **[Web3jService.java](https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/protocol/Web3jService.java)**
```
<T extends Response> T sendBatch(BatchRequest batch) throws IOException;
```

**Comment by ali-sharif** [comment]
Or something along those lines ... 

If the maintainers can chime in with some opinions on this, I can hammer this out and make a PR.

**Comment by illya-havsiyevych** [comment]
any progress on this ?

CC: @yuriytkach

**Comment by zacscoding** [comment]
@AlexandrouR  ali-sharif any progress on this ? we need this function :)

**Comment by IvanRF** [comment]
@zacscoding how can `BatchRequest` be used for `RemoteFunctionCall`s?

I was able to use `BatchRequest` for calls like `web3j.ethGetBlockByNumber(...)`.

However, I can't find how to use it with functions from a `Contract` created by a wrapper generator since all return `RemoteFunctionCall` objects.

Should I create a new feature request?

**Comment by jgranil21** [comment]
Hi @IvanRF can you share your code on the batchRequest?

**Comment by saulgiordani** [comment]
> @zacscoding how can `BatchRequest` be used for `RemoteFunctionCall`s?
> 
> I was able to use `BatchRequest` for calls like `web3j.ethGetBlockByNumber(...)`.
> 
> However, I can't find how to use it with functions from a `Contract` created by a wrapper generator since all return `RemoteFunctionCall` objects.
> 
> Should I create a new feature request?

If you navigate the remotecall invocation you will arrive to RawTransactionManager.sendCall, inside this method there is a call to web3j.ethCall that actually creates a Request that can be added to the BatchRequest.

A method to retrieve the Request from the RemoteFuncionCall should be definitely added.
