### ISSUE TITLE
IndexOutOufBoundsException in MnemonicUtils.java in android branch version 3.3.1

### ISSUE THREAD

**Issue by mnl-assasin** [web3j/web3j#595]
Hi everyone, 

I applied the fixed from master branch in the issue of returning an empty set of WORD_LIST
https://github.com/web3j/web3j/pull/594

Got the changes from here:
https://github.com/web3j/web3j/blob/master/crypto/src/main/java/org/web3j/crypto/MnemonicUtils.java

I only actually copied and pasted that in android branch and send a pull request.
I also think that it was only forgotten to applied it in the android branch

Thanks, hope you can review and approved my PR

**Comment by mnl-assasin** [comment]
Hey there,

My PR only contains MnemonicUtils.java from master branch copied to android branch. 
If my PR fails for unknown reason. Can someone fixed the issue why it fails and send new PR?

We can't use generateMnemonic(byte[] initialEntropy) method because it throws a IndexOutOfBoundsException probably because WORD_LIST returns an empty list

Solution comes from here:
https://github.com/web3j/web3j/issues/403

**Comment by ehanoc** [comment]
@mnl-assasin  i had the same problem. I've merged MnemonicUtils from the master branch into android and fixed the import issues; spongycastle (android) vs bouncycastle(master)

**Comment by AlexandrouR** [comment]
seems this was addressed in the 4.1.0
