### ISSUE TITLE
android web3j Empty value (0x) returned from contract

### ISSUE THREAD

**Issue by pencilso** [web3j/web3j#597]
The same contract calls the same function
but android web3j is error 
Java SpringBoot Project is Success 
why?
"
        org.web3j.tx.exceptions.ContractCallException: Empty value (0x) returned from contract
        at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:194)
        at org.web3j.tx.Contract$2.call(Contract.java:257)
        at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:31)
"

**Comment by relaxbao** [comment]
I have the same problem, the same `sol` file build and can be called successfully in `remix`, but it returned `
Exception in thread "main" org.web3j.tx.exceptions.ContractCallException: Empty value (0x) returned from contract` when I deployed the contract throw web3j,and  called it through web3j

**Comment by kay07** [comment]
@relaxbao I agree with you .the result is not the same as remix

**Comment by chi3tidel** [comment]
i have the same issue
did you solve the it?

**Comment by Bobavince** [comment]
Don't know if it can help out, but I had the same issue and in my wrapped compiled solidity script, it was : 

    private static final String BINARY = "[{\"constant\":true,\"inputs\":[],\"name\":\"chars\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}, ( ... )se,\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"constructor\"}]";

instead of : 

    private static final String BINARY = "608060405234801561001057600080fd5b5060008054600160a060020a0319163317815560015561027f806100356000 (...) ffffffffffffffffffff163314156102515760005473ffffffffffffffffffffffffffffffffffffffff16ff5b5600a165627a7a72305820545e60010ee0d4b8f1315f9743499c370f058e1ab280aab90d9795cd074ff9e60029";

Which means, that web3j or solidity compiler does not correctly do its job. 
Personal issue, but it was not obvious.
