### ISSUE TITLE
doc: String responseValue

### ISSUE THREAD

**Issue by MaxBinnewies** [web3j/web3j#6]
Hello,

in the doc, chapter 3.2.13 "Querying the state of a smart contract" you are calling the method FunctionReturnDecoder.decode(...) with the String variable "responseValue". However, that variable was never declared nor assigned in the code snippet. Where is that value coming from?

Thanks,
Max

**Comment by conor10** [comment]
It should read:

```java
List<Type> someTypes = FunctionReturnDecoder.decode(
                response.getValue(), function.getOutputParameters());
```

I've committed a fix. This updated will be reflected on the docs, as soon as RTD have resolved by build issues as per https://github.com/rtfd/readthedocs.org/issues/2476.

**Comment by MaxBinnewies** [comment]
Thanks
