### ISSUE TITLE
Contract creation uses all gas

### ISSUE THREAD

**Issue by repfuesch** [web3j/web3j#60]
I'm using the android library and I try to deploy a simple purchase contract. 
[purchase.txt](https://github.com/web3j/web3j/files/817285/purchase.txt)
Everything seems to work fine. Contract is created and contract address returned when invoking Contract.deploy() with a gas price of 50000000000 and a gas limit of 4500000. 
I noticed that sometimes (~50% of all cases) after deployment, all function calls return null. In these cases all gas is used by the transaction according to the transaction hash, but I don't get any out of gas exception. In the successfull cases, a lot less gas (~500 000) is used.

I'm using geth in dev mode for testing with the following params:
geth --rpc --rpcaddr "0.0.0.0" --rpcport 8545 --rpcapi personal,db,eth,net,web3  --rpccorsdomain="*" -datadir /home/flo/.ethereum/ --dev --gpomin "20000000000" --gpomax "500000000000"

Any ideas what could be the problem?

**Comment by repfuesch** [comment]
Found the problem: An exception was thrown in the constructor and that seems to cause that out of gas problem.

**Comment by conor10** [comment]
Ok - was this an exception that you were ignoring in your code or a silent exception in web3j?

**Comment by repfuesch** [comment]
No this was an exception that was thrown on the contract in the blockchain. I learned that such code that throws uses all gas of the transaction. 
However in web3j, no exception is thrown when a transaction runs out of gas. I think it would be good to add this in the future.
Best regards
----Ursprüngliche Nachricht----
Von : notifications@github.com
Datum : 04/03/2017 - 03:04 (CET)
An : web3j@noreply.github.com
Cc : flo.schuepfer@bluewin.ch, state_change@noreply.github.com
Betreff : Re: [web3j/web3j] Contract creation uses all gas (#60)
Ok - was this an exception that you were ignoring in your code or a silent exception in web3j?
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.
  
  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/web3j/web3j","title":"web3j/web3j","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/web3j/web3j"}},"updates":{"snippets":[{"icon":"PERSON","message":"@conor10 in #60: Ok - was this an exception that you were ignoring in your code or a silent exception in web3j?"}],"action":{"name":"View Issue","url":"https://github.com/web3j/web3j/issues/60#issuecomment-284118264"}}}

**Comment by conor10** [comment]
Good idea, see https://github.com/web3j/web3j/issues/62
