### ISSUE TITLE
Request: Getter for signer address in TransactionManager interface

### ISSUE THREAD

**Issue by androlo** [web3j/web3j#61]
It would be great if one could get the signer address, so it doesn't have to be stored in multiple places. Getting the address works with the `RawTransactionManager` of course, through the credentials, but it is not possible from a `ClientTransactionManager`. At least not in version `2.0.2`.

I guess a special accessor directly on ClientTransactionManager would work too but seems a bit clunky, since one of the main uses of the sender address is pre-conditions that guard against sending sure-to-fail transactions (e.g. transactions to permissioned contracts), and those generally depend only on the address and not the transaction method that happen to be used.

Fantastic library btw.

**Comment by conor10** [comment]
Fixed in https://github.com/web3j/web3j/releases/tag/v2.1.0.
