### ISSUE TITLE
[Question] How to check that transactions are pending?

### ISSUE THREAD

**Issue by KimiWu123** [web3j/web3j#615]
I have a background program to send transactions and then record them in DB. Every time I restart my program (no matter crash or update) and I'll query transaction hashes from DB and to get transaction receipts to see these transactions are mined or not. However, if transactions are pending, the transaction receipts are null. I can't tell a transaction hash is invalid or is pending. I tried pendingTransactionObservable, but I can't get pending transactions before my program start. 
So, my question is how can I check if the transactions are pending by transaction hashes? 
Any help would be appreciate.

**Comment by AlexandrouR** [comment]
I think this will help you
https://docs.web3j.io/trouble.html#i-m-submitting-a-transaction-but-it-s-not-being-mined
Is the transaction receipt null when you get it from your DB or when you call the ethGetTransactionReceipt ?

**Comment by KimiWu123** [comment]
@AlexandrouR , Thanks.

**Comment by pipepi** [comment]
same question , pls any help

**Comment by p00temkin** [comment]
Not sure if this is what you are looking for, but a simple method to check if you have pending txs is to compare the nonce:

EthGetTransactionCount ethGetTransactionCount_pending = _connector.getProvider_instance().ethGetTransactionCount(_address, DefaultBlockParameterName.PENDING).send();
BigInteger nonce_pending =  ethGetTransactionCount_pending.getTransactionCount();

EthGetTransactionCount ethGetTransactionCount_latest = _connector.getProvider_instance().ethGetTransactionCount(_address, DefaultBlockParameterName.LATEST).send();
BigInteger nonce_latest =  ethGetTransactionCount_latest.getTransactionCount();

if (nonce_pending.compareTo(nonce_latest) == 0) ...
