### ISSUE TITLE
[Android] Failed resolution of: Lorg/web3j/protocol/http/HttpService

### ISSUE THREAD

**Issue by relaxbao** [web3j/web3j#619]
Hi ,
When I call function in contract , it  was occasionally found  Error 
```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/web3j/protocol/http/HttpService;
```
This will crash my APP. Do you know why, and how can I fix it , thank you ~
These are logs
![logs](https://user-images.githubusercontent.com/19773804/42195973-13bc03e8-7eae-11e8-90aa-d30c6bd7a992.jpg)

web3j version
```
<dependency>
  <groupId>org.web3j</groupId>
  <artifactId>core</artifactId>
  <version>3.3.1-android</version>
</dependency>
```

**Comment by AlexandrouR** [comment]
Is this an issue with the latest version of web3j ?

**Comment by AlexandrouR** [comment]
Issue closed due to inactivity.
