### ISSUE TITLE
Throw exception if contract deployment or transaction runs out of gas

### ISSUE THREAD

**Issue by conor10** [web3j/web3j#62]
On transactions the following check is required:

```
if (transactionReceipt.getGasUsed().equals(GAS_LIMIT)) {
    throw ...
}
```

**Comment by Oduig** [comment]
I don't think that works in all cases. If the transaction succeeds on the last unit of gas, all the gas has been used but the transaction was successful. See https://ethereum.stackexchange.com/questions/6007/how-can-the-transaction-status-from-a-thrown-error-be-detected-when-gas-can-be-e

**Comment by mushketyk** [comment]
A more robust method is to check the result status as described here: https://ethereum.stackexchange.com/a/28078/33645

I've used it in my PR: https://github.com/web3j/web3j/pull/444
