### ISSUE TITLE
3.4.0 android?

### ISSUE THREAD

**Issue by 640774n6** [web3j/web3j#623]
Is there a 3.4.0 release for android available? I would like to use the TransactionDecoder and SignedRawTransaction classes but they are not available in 3.3.1-android.

**Comment by conor10** [comment]
Hi, the release hasn't been done yet.

For each Android release, the master needs to be merged to the android branch which requires a bit of cleanup with generics and lambdas to be Java 1.6 compliant. I've now got funding to bring someone onboard full-time to work on web3j, but I'm still looking for someone.

In the mean time, if you want to submit a PR with the merge with the 1.6 changes, I'd be happy to get a release out.

**Comment by TOTOROYang** [comment]
@conor10  i can help when i after work

**Comment by 640774n6** [comment]
Ah ok that makes sense. I'll see if I can do the merge and cleanup. I'll send a PR if I'm able to make it happen. Thanks for the replies!

**Comment by void-main** [comment]
I merged code from master to android branch, please review it: #626 

@conor10 @TOTOROYang @640774n6

**Comment by snazha-blkio** [comment]
4.1.0-android has been released.
