### ISSUE TITLE
How to make multiple transaction in web3j

### ISSUE THREAD

**Issue by codebazz** [web3j/web3j#624]
How do I set the nonce and make multiple transaction in a for-loop so that I can send multiple transaction without waiting for previous transaction confirmation?
I want the solution for web3j
https://stackoverflow.com/questions/49623968/how-to-make-multiple-transaction-in-web3js
https://ethereum.stackexchange.com/questions/2496/how-do-i-set-the-nonce-for-raw-transactions

**Comment by iikirilov** [comment]
@codebazz it would be useful to post your solution so other people can see how you achieved this

**Comment by codebazz** [comment]
Actually I did not achieve that. Firstly I was trying send multiple transaction using **sendAsc()** to send a lot a transaction without delaying in a loop But it does not work as each transaction requires current **nonce** which becomes invalid in **sendAsc()**. So I had to go back to "send()" for transaction and wait for each successive transaction.
