### ISSUE TITLE
web3j 3.4.0 contract.load() function always returns invalid contract and throws Empty value (0x) returned from contract 

### ISSUE THREAD

**Issue by glomarch** [web3j/web3j#625]
Web3j 3.4.0

public void deploy() throws Exception
{
log.info("Deploying smart contract");
String greetMessage = "Hi this is a greeter app";
gasPrice=BigInteger.valueOf(100);

    this.contract = Greeter.deploy(web3j, credentials, gasPrice, gasLimit, greetMessage).send();

    log.info("contract deployed "  );
String gr = this.contract.greet().send();
}
works fine.
however
log.info("loading contract");
this.contract = (Greeter) Greeter.load(
this.contactAddress, web3j, credentials, gasPrice, gasLimit);
String gr = this.contract.greet().send();
always return the above error.
Eventhough the contract binary returned from both contract are the same.
This is reproducible from many ethereum networks

this.contract = (Greeter) Greeter.load(
			this.contractAddress, web3jAdmin, credentials, gasPrice, gasLimit);
	log.info("isContractValid=" + contract.isValid());
while the contract returned from deploy worked just fine, the loaded contract always has contract.isValid() false,
isContractValid=false
the
String gr = this.contract.greet().send();
always through the following exceptions:
I have tried a variety of ethereum testnet and local private networks, single or multiple.
It must be a bug. Please fix it.
Exception in thread "main" org.web3j.tx.exceptions.ContractCallException: Empty value (0x) returned from contract
at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:230)
at org.web3j.tx.Contract.lambda$executeRemoteCallSingleValueReturn$1(Contract.java:297)
at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)

**Comment by abdusamed91** [comment]
I have this exact same issue -> https://github.com/web3j/web3j/issues/653

**Comment by AlexandrouR** [comment]
is this still an issue in the latest version ?

**Comment by AlexandrouR** [comment]
Closed due to inactivity. @glomarch  if this is still a problem please open a new issue following the instructions and please use ``` to indent all the code it makes things easier, thank you
