### ISSUE TITLE
Bip39 Wallet using  Derived Path

### ISSUE THREAD

**Issue by iamsahilarora** [web3j/web3j#629]
i am implemented  generateBip39 Wallet using WalletUtil class. but is not using any HD derived path  
same library i am using in IOS development which is Web3Swift (https://github.com/BANKEX/web3swift) which is using  class Bip32Keystore 
and derived path "m/44/60/0". but  both apps giving different privateKey and Address using same Mnemonic and Password 
In this i also didn't find how to create wallet using Bip32 and using HD Derived Path 
can anyone help me out in this

**Comment by iamsahilarora** [comment]
can anyone help me out in this as this is Urgent for me.
Thanks

**Comment by GioIniguez** [comment]
i have the same issue, if you find a solution, could you share it here, please.

**Comment by AlexandrouR** [comment]
You can take a look the solution provided by @razzbee in #919

**Comment by AlexandrouR** [comment]
Closing as this a duplicate. Please follow the progress in #919
