### ISSUE TITLE
Java smart contract wrappers does not support ABI with type of "address[] storage"

### ISSUE THREAD

**Issue by 18618172132** [web3j/web3j#63]
Here is the a contract code:
++++++++++++++++++++++++++++++++
```
pragma solidity ^0.4.4;
library Lib1{
    function findAddress(address a, address[] storage arry) returns (int){
        for (uint i = 0 ; i < arry.length ; i++){
            if(arry[i] == a){return int(i);}
        }
        return -1;
    }
    function removeAddress(uint i, address[] storage arry){
        uint lengthMinusOne = arry.length - 1;
        arry[i] = arry[lengthMinusOne];
        delete arry[lengthMinusOne];
        arry.length = lengthMinusOne;
    }
}
```
++++++++++++++++++++++++++++++++

When we try to generate the wrapper code using web3j's Command line tools:
++++++++++++++++++++++++++++++++
`web3j solidity generate in/Lib1.bin in/Lib1.abi -o out/src/main/java -p com.vianet.blockchain.web3j.support.wrappers`
++++++++++++++++++++++++++++++++

error is reported:
++++++++++++++++++++++++++++++++
`Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported type encountered: address[] storage`
++++++++++++++++++++++++++++++++
![image](https://cloud.githubusercontent.com/assets/18653619/23689372/03eaf9ea-03f5-11e7-99d1-dd61aad00a55.png)

**Comment by androlo** [comment]
Hey sorry for "injecting" myself - putting storage modifier in the JSON interface seems like a Solidity error to me rather then web3j, since the only references you can create through an external call is to calldata  memory (in case it is a non-external function). I can't remember how this is treated in libraries since i never call those externally, but im guessing those functions should probably be omitted from the JSON ABI entirely.

**Comment by conor10** [comment]
Are you able to provide an ABI file extract? It may make sense to get web3j to ignore.

**Comment by 18618172132** [comment]
Hell conor,

The ABI is here:
`[{"constant":false,"inputs":[{"name":"i","type":"uint256"},{"name":"arry","type":"address[] storage"}],"name":"removeAddress","outputs":[],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"a","type":"address"},{"name":"arry","type":"address[] storage"}],"name":"findAddress","outputs":[{"name":"","type":"int256"}],"payable":false,"type":"function"}]`

File is uploaded(you can rename it to Lib1.abi):

[Lib1.abi.txt](https://github.com/web3j/web3j/files/832938/Lib1.abi.txt)

**Comment by conor10** [comment]
Fine - so web3j should ignore these when specified.

**Comment by conor10** [comment]
Fixed.
