### ISSUE TITLE
IllegalStateException on Android while reading word list

### ISSUE THREAD

**Issue by esoxjem** [web3j/web3j#633]
This happens when calling `WalletUtils.generateBip39Wallet("password", file)` on version `3.3.1-android`

https://github.com/web3j/web3j/blob/973f23773a87b531228e0a9c8f12161376d90a78/crypto/src/main/java/org/web3j/crypto/MnemonicUtils.java#L173

**Comment by iamsahilarora** [comment]
you need to change in MnemonicUtils.Java  PopulateWordList() Method and Copy and Paste World list in your Asset Folders 

here is Code 

` private static List<String> populateWordList() {
        try {
            return readAllLines(MyApplication.getAppContext().getAssets().open("en-mnemonic-word-list.txt"));
        } catch (Exception e) {
            return Collections.emptyList();
        }
    }`

**Comment by dhruvi1kosmos** [comment]
@iamsahilarora  I am using jar how can i change ?

**Comment by esoxjem** [comment]
@dhruvi1kosmos here's the fix:
https://github.com/esoxjem/web3j/commit/35182725e855a8ea664cd494a7f757dc79af414c

Till the repo is updated, you can use this
https://jitpack.io/#esoxjem/web3j/v3.3.3-android

**Comment by ggeorgip** [comment]
I am experiencing the same bug.

**Comment by iamsahilarora** [comment]
you can do copy code of that class and do changes accordingly i do change code and get it from resources from raw and  copy wordlist file to raw.

**Comment by ggeorgip** [comment]
Even better:

Just for fun, in Kotlin:

`class PatchWeb3jMnemonicUtils {

    companion object {
        fun patch() {
            ReflectionMagic.modifyPrivateStaticField(MnemonicUtils::class.java,
                    "WORD_LIST", readWeb3jWordList())
        }

        fun readWeb3jWordList(): List<String> {
            return populateWordList()
        }

        // Copied from https://github.com/web3j/web3j/blob/master/crypto/src/main/java/org/web3j/crypto/MnemonicUtils.java

        private fun populateWordList(): List<String> {
            val inputStream = Thread.currentThread().contextClassLoader
                    .getResourceAsStream("en-mnemonic-word-list.txt")
            try {
                return readAllLines(inputStream)
            } catch (e: Exception) {
                throw IllegalStateException(e)
            }

        }

        @Throws(IOException::class)
        private fun readAllLines(inputStream: InputStream): List<String> {
            val br = BufferedReader(InputStreamReader(inputStream))
            val data = mutableListOf<String>()
            while(true) {
                val line : String = br.readLine() ?: break
                data.add(line)
            }

            return data
        }

    }
}
`

And another class, this time in Java:

`public class ReflectionMagic {

    static void modifyPrivateStaticField(Class c, String fieldName, List<String> mockList) {
        try {
            Field f = c.getDeclaredField(fieldName);
            f.setAccessible(true);
            f.set(null, mockList);
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
}`

... and then just before you need to use the library:

`PatchWeb3jMnemonicUtils.patch() // FIXME: Remove me in the future`

**Comment by AlexandrouR** [comment]
Is this still an issue ?

**Comment by AlexandrouR** [comment]
Issue closed due to inactivity.
