### ISSUE TITLE
[Question] Filtering blocks on basis of transaction logs

### ISSUE THREAD

**Issue by Himanshu-Pandey** [web3j/web3j#640]
I want to filter blocks on the basis of a log present inside transactions. How can I do that?
I don't have any contract address and want to filter all the blocks generated by all the contracts.
Thanks :)

**Comment by AlexandrouR** [comment]
@Himanshu-Pandey  first i would suggest you take a look at [this](https://docs.web3j.io/filters.html?highlight) if you don't find what you are looking for please try to be a bit more descriptive in terms of what you are trying to do.

You could try doing something like this 
```
Subscription subscription = web3j.replayTransactionsFlowable(
        <startBlockNumber>, <endBlockNumber>)
        .subscribe(tx -> {
            ...
}); 
```
Please let me know if you have a more specific use-case
