### ISSUE TITLE
Library use causes isValid to return false

### ISSUE THREAD

**Issue by 9607835** [web3j/web3j#644]
pragma solidity ^0.4.18;
    
    contract Con {
      int64 public value = 0;
      
      function Con() public {
      }
      function updateValue_withoutLibrary(int64 a, int64 b) public returns (bool success) {
        value = a+b;
        return true;
      }
    }

this code works fine... `contract.isValid()` returns `true` and `contract.value().send().getValue()` after calling `contract.updateValue_withoutLibrary()` shows the updated value.

    pragma solidity ^0.4.18;
    
    library SafeMath {
      function safeAdd(int64 a, int64 b) pure public returns (int64) {
        int64 r = a+b;//whatever
        return r;
      }
    }
    contract Con {
      int64 public value = 0;
      
      function Con() public {
      }
      function updateValue_withoutLibrary(int64 a, int64 b) public returns (bool success) {
        value = a+b;
        return true;
      }
      function updateValue_withLibrary(int64 a, int64 b) public returns (bool success) {
        value = SafeMath.safeAdd(a, b);
        return true;
      }
    }

this code *almost* works fine... `contract.isValid()` returns `false` and `contract.value().send().getValue()` after calling `contract.updateValue_withoutLibrary()` shows the updated value.

***However***, `contract.value().send().getValue()` after calling `contract.updateValue_withLibrary()` does *not* show the updated value.

**Comment by tjanson** [comment]
Did you solve `isValid` being false or figure out what exactly was going on?

**Comment by 9607835** [comment]
> Did you solve `isValid` being false or figure out what exactly was going on?

I closed it because it was something I was overlooking and noticed just after posting this issue, I don't remember what it was.  It could be a few weeks before I deal with this code again to give a better answer.  Are you having the same issue?

**Comment by tjanson** [comment]
Yeah, I am. That said, it’s no big deal — I’m just ignoring it with no ill effects. So don’t worry about it. But if you happen to remember please let me know, I’m very curious. ;)

**Comment by 9607835** [comment]
I don't think this was the same issue, however I do remember that our geth process was slow (low memory causing disk thrashing I think) and ethereum blocks were only being generated once a minute and for some reason geth was failing to adjust the difficulty to compensate.  So transactions confirm and everything works, but isValid returned false.  I edited the geth source code and forced the difficulty to a constant low difficulty (now blocks are generated every 2 seconds :) )

**Comment by tjanson** [comment]
That’s interesting, because I’m doing exactly the same thing with geth. However, I’m currently using ganache, and the issue occurs. (And AFAIK the method compares the contract bytecode, which should be unrelated to any mining settings.)
Anyway, I’ll keep ignoring it.
