### ISSUE TITLE
Invalid package reference in library; not included in Android: javax.naming. Referenced from org.spongycastle.jce.provider.X509LDAPCertStoreSpi. [InvalidPackage]

### ISSUE THREAD

**Issue by wangzhikk** [web3j/web3j#645]
Invalid package reference in library; not included in Android: javax.naming. Referenced from org.spongycastle.jce.provider.X509LDAPCertStoreSpi. [InvalidPackage]

**Comment by AlexandrouR** [comment]
Is this still and issue ?  please provide additional information

**Comment by AlexandrouR** [comment]
Issue closed due to inactivity.
