### ISSUE TITLE
Transaction object is not serializable, nor the TransactionResult. Can we marshal these object somehow??

### ISSUE THREAD

**Issue by ayushvasu** [web3j/web3j#646]

**Comment by AlexandrouR** [comment]
What do you mean by `serializable` in this context? Do you mean RLP encoding? Web3j provides methods to RLP encode a transaction. You can read about it in the [docs](https://docs.web3j.io/rlp.html?highlight=rlp#transaction-encoding).

**Comment by AlexandrouR** [comment]
Issue closed due to inactivity.
