### ISSUE TITLE
when i use BigInteger.toString method to get privateKey is deleting leading 0 in android

### ISSUE THREAD

**Issue by pengbs** [web3j/web3j#647]
I use code :
`
ECKeyPair ecKeyPair = Keys.createEcKeyPair();
Numeric.toHexStringWithPrefix(ecKeyPair.getPrivateKey());
`
I expect privateKey is 0x0692ff2e880394b9c4abb79887346b498765cecc04494b8a83c2e37e7ae72521, but get 0x692ff2e880394b9c4abb79887346b498765cecc04494b8a83c2e37e7ae72521

**Comment by TOTOROYang** [comment]
u can use Numeric.toHexStringWithPrefixZeroPadded method .

**Comment by pengbs** [comment]
thank you, it works fine

**Comment by BBLabPawanMaurya** [comment]
What is the value of size in this methos
