### ISSUE TITLE
How to change logging level on org.web3j.protocol.http.HttpService

### ISSUE THREAD

**Issue by JohnMagnusson** [web3j/web3j#652]
Currently doing some work with a java client that monitors a smart contract. 
The issue that i am havning is that the org.web3j.protocol.http.HttpService keeps spamming my console with its https request making it really hard to read and debug from the console. 
Any suggestion on how to solve this is appreciated.

Exampel when i connect to my local network and load some dummy credentials: 

11:57:31.040 [main] DEBUG org.web3j.protocol.http.HttpService - --> POST http://127.0.0.1:8545/ http/1.1
11:57:31.054 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json; charset=utf-8
11:57:31.054 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 66
11:57:31.056 [main] DEBUG org.web3j.protocol.http.HttpService - 
11:57:31.057 [main] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":0}
11:57:31.057 [main] DEBUG org.web3j.protocol.http.HttpService - --> END POST (66-byte body)
11:57:31.130 [main] DEBUG org.web3j.protocol.http.HttpService - <-- 200 OK http://127.0.0.1:8545/ (73ms)
11:57:31.130 [main] DEBUG org.web3j.protocol.http.HttpService - Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
11:57:31.130 [main] DEBUG org.web3j.protocol.http.HttpService - Access-Control-Allow-Origin: *
11:57:31.130 [main] DEBUG org.web3j.protocol.http.HttpService - Access-Control-Allow-Methods: *
11:57:31.130 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json
11:57:31.130 [main] DEBUG org.web3j.protocol.http.HttpService - Date: Mon, 30 Jul 2018 09:57:31 GMT
11:57:31.130 [main] DEBUG org.web3j.protocol.http.HttpService - Connection: keep-alive
11:57:31.130 [main] DEBUG org.web3j.protocol.http.HttpService - Transfer-Encoding: chunked
11:57:31.131 [main] DEBUG org.web3j.protocol.http.HttpService - 
11:57:31.131 [main] DEBUG org.web3j.protocol.http.HttpService - {"id":0,"jsonrpc":"2.0","result":"EthereumJS TestRPC/v2.1.5/ethereum-js"}
11:57:31.131 [main] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (73-byte body)
Connected to Ethereum client version: EthereumJS TestRPC/v2.1.5/ethereum-js
Successfully  loaded credentials from file UTC--2018-07-26T11-23-01.979000000Z--44d2015bc16bcf40425009d77a91a16fe416337b.json
11:57:34.259 [main] DEBUG org.web3j.protocol.http.HttpService - --> POST http://127.0.0.1:8545/ http/1.1
11:57:34.260 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json; charset=utf-8
11:57:34.260 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 110
11:57:34.260 [main] DEBUG org.web3j.protocol.http.HttpService - 
11:57:34.260 [main] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"eth_getCode","params":["43dC6a4Ad4Ee2b49C26daA40FfF2e4cf884A88ad","latest"],"id":1}
11:57:34.260 [main] DEBUG org.web3j.protocol.http.HttpService - --> END POST (110-byte body)
11:57:34.266 [main] DEBUG org.web3j.protocol.http.HttpService - <-- 200 OK http://127.0.0.1:8545/ (6ms)
11:57:34.266 [main] DEBUG org.web3j.protocol.http.HttpService - Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
11:57:34.266 [main] DEBUG org.web3j.protocol.http.HttpService - Access-Control-Allow-Origin: *
11:57:34.266 [main] DEBUG org.web3j.protocol.http.HttpService - Access-Control-Allow-Methods: *
11:57:34.266 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json
11:57:34.266 [main] DEBUG org.web3j.protocol.http.HttpService - Date: Mon, 30 Jul 2018 09:57:34 GMT
11:57:34.266 [main] DEBUG org.web3j.protocol.http.HttpService - Connection: keep-alive
11:57:34.266 [main] DEBUG org.web3j.protocol.http.HttpService - Transfer-Encoding: chunked
11:57:34.266 [main] DEBUG org.web3j.protocol.http.HttpService - 
11:57:34.266 [main] DEBUG org.web3j.protocol.http.HttpService - {"id":1,"jsonrpc":"2.0","result":"0x0"}
11:57:34.266 [main] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (39-byte body)

**Comment by xiaods** [comment]
same here.

**Comment by xaviarias** [comment]
You can use [Logback configuration](https://logback.qos.ch/manual/configuration.html) file, e.g.:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <!-- Change to DEBUG to log protocol messages -->
    <logger name="org.web3j.protocol" level="INFO"/>

    <root level="INFO">
        <appender-ref ref="STDOUT" />
    </root>
</configuration>
```

**Comment by xiaods** [comment]
thanks fine
