### ISSUE TITLE
usage say "solidity generate .... --output ..." while code uses "--outputDir"

### ISSUE THREAD

**Issue by didier-durand** [web3j/web3j#656]
In line 23 of https://github.com/web3j/web3j/blob/master/codegen/src/main/java/org/web3j/codegen/SolidityFunctionWrapperGenerator.java, USAGE mentions "--output" as parameter definition while line 71 parses for "--outputDir".

So, using --output in "web3j solidity generate ... --output .... " generates an error while "--outputDir" is ok.

Either USAGE String or parsing shall be fixed. Thanks!

**Comment by taivokasper** [comment]
I suggest the above fix ([PR 660](https://github.com/web3j/web3j/pull/660)). Looking at git history it seems usage string and actual usage have never been in sync.

I found that [TruffleJsonFunctionWrapperGenerator.java](https://github.com/web3j/web3j/blob/master/codegen/src/main/java/org/web3j/codegen/TruffleJsonFunctionWrapperGenerator.java) has this same problem.
