### ISSUE TITLE
web3j throws exception at Android 4.4 (API Level 19)

### ISSUE THREAD

**Issue by danielksan81** [web3j/web3j#66]
Hi,
trying the web3j lib on Android on 4.4 (19) leads to the following exception:
 java.lang.NoClassDefFoundError: org.web3j.protocol.http.HttpService

at line
`Web3j web3 = Web3jFactory.build(new HttpService(NODE_1)); `

Dependency:
`compile 'org.web3j:core-android:2.1.0'`

Switching to Android 6 (API 23) and everything is working fine.
I used the normal Android images from the latest AndroidStudio.
Is there a way to get it run on 4.4?

Regards
Daniel

**Comment by conor10** [comment]
The integration tests work fine when I run in Android Studio 2.2.2 using an API version of 19.

Are you able to try running one with one of the earlier 1.x version of web3j?

**Comment by danielksan81** [comment]
Hi,
I have the newest version of Android Studio 2.3.
I tried it with version 1.1.0, but it is the same behaviour and exception.
I deployed the app also to a Galaxy S4 Mini with 4.4.2, still the same.

**Comment by conor10** [comment]
So it's only when you deploy to the device you get this problem? Not in Android Studio?

**Comment by danielksan81** [comment]
In the studio everyything is fine, no red markers etc. It also compiles.
Only if it is started / deployed to an image / device.

**Comment by conor10** [comment]
Thanks - is this reproducable in the Android Emulator, or only when on a physical device? If so which device are you using?

**Comment by danielksan81** [comment]
Hi,
It is reproducible using the emulator.

Am 19.03.2017 22:25 schrieb "Conor Svensson" <notifications@github.com>:

**Comment by fooock** [comment]
I can't reproduce this using android emulator with images `19 (4.4)`and `23 (6.0)`. Library version:
```grade
compile 'org.web3j:core-android:2.1.0'
```
@danielksan81, have you solved the problem??

**Comment by xiabing082** [comment]
@danielksan81  this problem ，I have solved it，  when the the project is running ，show this ，
Android on 4.4 (19) leads to the following exception:java.lang.NoClassDefFoundError: ，，
I find  the methods over 65535 in my project , so solve it

**Comment by danielksan81** [comment]
We switched to at least level 23 (6.0)
