### ISSUE TITLE
Loading eth.coinbase account on private blockchain and use it as Credentials

### ISSUE THREAD

**Issue by fede977** [web3j/web3j#662]
I was trying to build a simple application on a local machine where I have my private block-chain and I wanted to deploy and load a simple smart contract.
Since I don't have a Wallet Account I was trying to use the account present on my block-chain, I managed to get the address but I cannot use it as credentials.
Is it possible to do it or I must use a Wallet Account?

**Comment by fede977** [comment]
Found the issue.

**Comment by tjanson** [comment]
I’d like to do the same thing (at least if I understand you correctly): Use an account that’s unlocked in the Ethereum client, rather than using a wallet file. Could you share your solution?

**Comment by tjanson** [comment]
I see now that you can just use `Credentials.create(PRIVATE_KEY)`.
