### ISSUE TITLE
How to create credentials from mnemonics

### ISSUE THREAD

**Issue by xxLestadxx** [web3j/web3j#663]
Hello. I am a newbie developer and I was wondering how can I create credentials with public key and mnemonics ?

**Comment by dimitrileite** [comment]
> Hello. I am a newbie developer and I was wondering how can I create credentials with public key and mnemonics ?

Try this link: https://kauri.io/creating-a-web3j-wallet-from-a-mnemonic-code-seed/a33a03fb66d14920896bb3e7ab77fba7/a
