### ISSUE TITLE
What the password is in loadBip39Credentials function

### ISSUE THREAD

**Issue by cliff-ck** [web3j/web3j#668]
I try to use as follow:

```
String seedCode = "little coffee nation fish burden volcano battle over rough upper brass host";
//pk export from ganache
String pwd="971997...";
Credentials credentials = WalletUtils.loadBip39Credentials(pwd, seedCode);
System.out.println(credentials.getAddress());
```

But I can't get the same address as Ganache address.

Is there something i've miss?

I've try to put pwd="",it still dosn't work..

**Comment by TOTOROYang** [comment]
password loadBip39Credentials is ""

**Comment by cliff-ck** [comment]
@TOTOROYang I've try to put password to "",But it still can't generate same address as Guanche

**Comment by TOTOROYang** [comment]
what is Guanche or Ganacha?
Are u sure it use bip39 not bip44

**Comment by cliff-ck** [comment]
@TOTOROYang  sorry,It's Ganache~
![image](https://user-images.githubusercontent.com/12390790/44016031-e4d703f2-9f05-11e8-81de-29c6483a4b06.png)
I'm sure it is use bip39.I can get the same address when I import the mnemonic into MetaMask

**Comment by TOTOROYang** [comment]
Ganache is bip44 . u can see the path m/44'/60'/0/0/index

**Comment by chenhao597** [comment]
How can I use mnemonic recovery me wallet without password?
`Credentials credentials = WalletUtils.loadBip39Credentials("", mnemonic);`  The code need password but metamask or imtoken wallet app they don't need password.
How can I use mnemonic by java to get my wallet's privatekey???

**Comment by TOTOROYang** [comment]
the password here is not  necessary.

**Comment by iikirilov** [comment]
@cliff-ck is this still an issue?

**Comment by koptan** [comment]
i am having the same issue , i am getting different address from ganache ??

**Comment by Philipinho** [comment]
@Koptan Ganache is bip44.

**Comment by razzbee** [comment]
I am using meta mask seed code but I get a different account when I load it using web3j, I don't know what's wrong, if I am missing something

**Comment by iikirilov** [comment]
#739
