### ISSUE TITLE
TransactionResult has not getters to get the params of a transaction

### ISSUE THREAD

**Issue by Swarmxcy** [web3j/web3j#67]
We can get List<TransactionResult> after calling EthBlock.getBlock().getTransactions() or EthBlock.getResult().getTransactions(). However, It seems that we can get nothing from an TransactionResult object. There is no getter to get the "input, from, to" params of a transaction.

**Comment by conor10** [comment]
Are you requesting full transaction objects in your requests? i.e. 

```
EthBlock ethBlock = web3j.ethGetBlockByHash("0x...", true)
```

**Comment by conor10** [comment]
Closing as no further information provided.

**Comment by andrewnguyen22** [comment]
I'm also having a similar issue. Anyone able to figure this out?

**Comment by Daantie** [comment]
@andrewnguyen22 you have to call the get() method on the TransactionResult object and cast the return object to org.web3j.protocol.core.methods.response.Transaction:

`Transaction tx = (Transaction) transactionResult.get();`
