### ISSUE TITLE
Events after wrapping with web3j command line tools, miss an argument

### ISSUE THREAD

**Issue by xxLestadxx** [web3j/web3j#670]
Hello 

There is a strange behavior with the Events. So the line below gives me an error when I write on IntelliJ IDEA, however, in NetBeans, the line works without adding anything.  
```
public static final Event SETALLOWEDACCESS_EVENT = new Event("SetAllowedAccess",
            Arrays.<TypeReference<?>>asList(new TypeReference<Address>() {}, new TypeReference<Bool>() {}));
    ;
```
To work on IntelliJ you should add the same argument again like this : 
```
public static final Event SETALLOWEDACCESS_EVENT = new Event("SetAllowedAccess",
            Arrays.<TypeReference<?>>asList(new TypeReference<Address>() {}, new TypeReference<Bool>() {}),
            Arrays.<TypeReference<?>>asList(new TypeReference<Address>() {}, new TypeReference<Bool>() {}));
    ;
```

**Comment by abdusamed91** [comment]
Can confirm. I had the exact same bug with event. I had to remove the entire event from Solidity for the Java Wrapper code to completely compile.

**Comment by abdusamed91** [comment]
I fixed my issue by compiling the bin, abi & java code on Ubuntu. Wrapper on windows was giving me issues.

**Comment by xxLestadxx** [comment]
I was using 3.4.0, in 3.5.0 it is fixed.
