### ISSUE TITLE
Fix smart contract code generators using 

### ISSUE THREAD

**Issue by conor10** [web3j/web3j#671]
With the gas provider changes made to web3j, there are issues with smart contract wrappers missing additional constructors.

Currently smart contract wrappers only have two generated constructors (example taken from [HumanStandardToken](https://github.com/web3j/web3j/blob/master/integration-tests/src/test/java/org/web3j/generated/HumanStandardToken.java):

```java
    protected HumanStandardToken(String contractAddress, Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit) {
        super(BINARY, contractAddress, web3j, credentials, gasPrice, gasLimit);
    }

    protected HumanStandardToken(String contractAddress, Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit) {
        super(BINARY, contractAddress, web3j, transactionManager, gasPrice, gasLimit);
    }
```

You need to update the [SolidityFunctionWrapper](https://github.com/web3j/web3j/blob/master/codegen/src/main/java/org/web3j/codegen/SolidityFunctionWrapper.java) to generate the following methods in addition to the above (example using HumanStandardToken generated code - see [build.sh](https://github.com/web3j/web3j/blob/master/codegen/src/test/resources/solidity/build.sh)):

```java
    protected HumanStandardToken(String contractAddress, Web3j web3j, Credentials credentials, ContractGasProvider gasProvider) {
        super(BINARY, contractAddress, web3j, credentials, gasProvider);
    }

    protected HumanStandardToken(String contractAddress, Web3j web3j, TransactionManager transactionManager, ContractGasProvider gasProvider) {
        super(BINARY, contractAddress, web3j, transactionManager, gasProvider);
    }
```

The following constructor should also be added to the [Contract](https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/tx/Contract.java) class:

```java
    protected Contract(String contractBinary, String contractAddress,
                       Web3j web3j, TransactionManager transactionManager,
                       ContractGasProvider gasProvider) {
                this(contractBinary, contractAddress, web3j, new RawTransactionManager(web3j, credentials), gasProvider);
    }
```

**Comment by franz-see** [comment]
Added a pull request to fix address issues - https://github.com/web3j/web3j/pull/672

**Comment by franz-see** [comment]
@conor10 Added a pull request to fix address issues - #672

**Comment by conor10** [comment]
Thanks!

There were some details I realised I should have included:

The `deploy<contractName>` and `load<contractName` methods should also be updated to use the defaultGasProvider.

This has made me think that it's probably better to remove the deprecated constructors for generated contracts, and just use the defaultGasProvider everywhere.

**Comment by franz-see** [comment]
@conor10 Thanks for the feedback. Can you expound on your comments? 

Comment (a.)
> The deploy<contractName\> and load<contractName\> methods should also be updated to use the defaultGasProvider.

Comment (b.)
> This has made me think that it's probably better to remove the deprecated constructors for generated contracts, and just use the defaultGasProvider everywhere.

.
.
.

### Comment (a.) - The deploy<contractName\> and load<contractName\> methods should also be updated to use the defaultGasProvider.

I dont see any deploy<contractName> and load<contractName> methods, but I do see the following:

(_example, from `HumanStandardToken`_)
```
    public static RemoteCall<HumanStandardToken> deploy(
            Web3j web3j, 
            Credentials credentials, 
            BigInteger gasPrice, 
            BigInteger gasLimit, 
            BigInteger _initialAmount, 
            String _tokenName, 
            BigInteger _decimalUnits, 
            String _tokenSymbol) {
        ...
    }

    public static RemoteCall<HumanStandardToken> deploy(
            Web3j web3j, 
            TransactionManager transactionManager, 
            BigInteger gasPrice, 
            BigInteger gasLimit, 
            BigInteger _initialAmount, 
            String _tokenName, 
            BigInteger _decimalUnits, 
            String _tokenSymbol) {
        ...
    }

    public static HumanStandardToken load(
            String contractAddress, 
            Web3j web3j, 
            Credentials credentials, 
            BigInteger gasPrice, 
            BigInteger gasLimit) {
        ...
    }

    public static HumanStandardToken load(
            String contractAddress, 
            Web3j web3j, 
            TransactionManager transactionManager, 
            BigInteger gasPrice, 
            BigInteger gasLimit) {
        ...
    }
```

Do you mean deprecate those methods above and add methods that use `ContractGasProvider` instead?

Something like...

```
    @Deprecated
    public static RemoteCall<HumanStandardToken> deploy(
            Web3j web3j, 
            Credentials credentials, 
            BigInteger gasPrice, 
            BigInteger gasLimit, 
            BigInteger _initialAmount, 
            String _tokenName, 
            BigInteger _decimalUnits, 
            String _tokenSymbol) {
        ...
    }

    @Deprecated
    public static RemoteCall<HumanStandardToken> deploy(
            Web3j web3j, 
            TransactionManager transactionManager, 
            BigInteger gasPrice, 
            BigInteger gasLimit, 
            BigInteger _initialAmount, 
            String _tokenName, 
            BigInteger _decimalUnits, 
            String _tokenSymbol) {
        ...
    }

    @Deprecated
    public static HumanStandardToken load(
            String contractAddress, 
            Web3j web3j, 
            Credentials credentials, 
            BigInteger gasPrice, 
            BigInteger gasLimit) {
        ...
    }

    @Deprecated
    public static HumanStandardToken load(
            String contractAddress, 
            Web3j web3j, 
            TransactionManager transactionManager, 
            BigInteger gasPrice, 
            BigInteger gasLimit) {
        ...
    }

    public static RemoteCall<HumanStandardToken> deploy(
            Web3j web3j, 
            Credentials credentials, 
            ContractGasProvider gasProvider,
            BigInteger _initialAmount, 
            String _tokenName, 
            BigInteger _decimalUnits, 
            String _tokenSymbol) {
        ...
    }

    public static RemoteCall<HumanStandardToken> deploy(
            Web3j web3j, 
            TransactionManager transactionManager, 
            ContractGasProvider gasProvider, 
            BigInteger _initialAmount, 
            String _tokenName, 
            BigInteger _decimalUnits, 
            String _tokenSymbol) {
        ...
    }

    public static HumanStandardToken load(
            String contractAddress, 
            Web3j web3j, 
            Credentials credentials, 
            ContractGasProvider gasProvider) {
        ...
    }

    @Deprecated
    public static HumanStandardToken load(
            String contractAddress, 
            Web3j web3j, 
            TransactionManager transactionManager, 
            ContractGasProvider gasProvider) {
        ...
    }
```

(_Also, Im guessing by `defaultGasProvider`, you're referring to `ContractGasProvider`_)

.
.
.

### Comment (b.) - This has made me think that it's probably better to remove the deprecated constructors for generated contracts, and just use the defaultGasProvider everywhere.

There are only 2 constructors on the generated classes

```
    protected HumanStandardToken(String contractAddress, Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit) {
        ...
    }

    protected HumanStandardToken(String contractAddress, Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit) {
        ...
    }
```

There are no deprecated constructors in the generated contracts. Or do you mean to deprecate the constructors that use `gasPrice` and `gasLimit` and add 2 more constructors that use `ContractGasProvider` instead?

Something like ...

```
    @Deprecated
    protected HumanStandardToken(String contractAddress, Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit) {
        ...
    }

    @Deprecated
    protected HumanStandardToken(String contractAddress, Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit) {
        ...
    }

    protected HumanStandardToken(String contractAddress, Web3j web3j, Credentials credentials, ContractGasProvider gasProvider) {
        ...
    }

    protected HumanStandardToken(String contractAddress, Web3j web3j, TransactionManager transactionManager, ContractGasProvider gasProvider) {
        ...
    }
```

Thanks!

**Comment by yuriymyronovych** [comment]
Sorry guys, saw this issue only now, @franz-see let me know if you will need any help with that fix(I will check PR now). I feel responsible for that feature :)

**Comment by franz-see** [comment]
@yuriymyronovych The pull request for this is still valid (no conflicts). But @conor10 did have an additional comment that I needed verification on.

Kindly see https://github.com/web3j/web3j/issues/671#issuecomment-412697442 for the clarifications that I need :)

**Comment by yuriymyronovych** [comment]
@franz-see I believe @conor10 meant to simply remove gas limit/gas price from everywhere(constructors & deploy/load) and just use GasPriceProvider, it would totally make sense to me, there will be 4.0 anyway with quite a few of new api changes.

It seems they are a bit overwhelmed right now, lets give them time to come back on this one.
