### ISSUE TITLE
Duplicate filed in generated java code if contract has two function with the same name but different case

### ISSUE THREAD

**Issue by huangyg11** [web3j/web3j#680]
When i have two functions in contract with the same name but different case, the contract pass compile but web3j failed to generate valid java code.

example:

in contract : 
```
contract A{
    string public constant NAME           = "A";

    function name()
    public
    pure
    returns (string)
    {
        return NAME;
    }
}
```

generated java : 
```
public class A extends Contract {
    public static final String FUNC_NAME = "name";
    public static final String FUNC_NAME = "NAME";   // duplicate field
}
```

**Comment by kostind** [comment]
I completely agree with you about the naming convention.
The issue was marked as a bug, so I've tried to solve it and investigate code generation in web3j.

**Comment by AlexandrouR** [comment]
#989 was merged. Closing issue.
