### ISSUE TITLE
web3j

### ISSUE THREAD

**Issue by stocketCheng** [web3j/web3j#681]
i use web3j the method ### Credentials credentials = WalletUtils.loadCredentials("password", "/path/to/walletfile"); Could not get any response.  web3j version 3.3.1 .

**Comment by flefevre** [comment]
Log the error with:

'''
Credentials credentials = null;
		try {
			credentials = WalletUtils.loadCredentials(SmartContractUtil.PASSWORD, new File(SmartContractUtil.BC_GETH_ADMINWALLET));
		} catch (IOException e) {
			logger.error("credentials "+e.getMessage());
			e.printStackTrace();
		} catch (CipherException e) {
			logger.error("credentials "+e.getMessage());
			e.printStackTrace();
		}
'''

are you sure the geth client have your account defined in the genesis file for instance?

**Comment by snazha-blkio** [comment]
Closing - no user feedback provided.
