### ISSUE TITLE
How to reconnect when use websocket service

### ISSUE THREAD

**Issue by summer00** [web3j/web3j#682]
Hi, 

Is there a way to reconnect when i use WebsocketService?
If the websocket connection break, no new block to `my code` and no exception to `handle exception`. What should i do when the connection break?
```java
WebSocketService web3jService = new WebSocketService("wss://mainnet.infura.io/ws", false);
web3jService.connect();
Web3j web3j = Web3j.build(web3jService);

web3j.catchUpToLatestAndSubscribeToNewBlocksObservable(start)
   .subscribe(block -> {
      // my code
   }, e --> {
    // handle exception
   })
```
And is there any doc about the websocket support?

**Comment by Viktor-stack** [comment]
There is a problem WebSocketService after a long connection after an indefinite time throws an Exception about Connect
