### ISSUE TITLE
Bitsize must be 8 bit aligned, and in range 0 < bitSize <= 256

### ISSUE THREAD

**Issue by kanliyong** [web3j/web3j#685]
TXID:0xb3646e0e845acc5cd59b55729865ff5ecc585d35dad85e0ab45fddfc4d361fe4
addressHex: 0000000000000000000000ff1a85eb6d4c45d025634ea7a07d8818aedd3b9d8d

```java
String to = new Address(addressHx).getValue();
```

Throw UnsupportedOperationException  :Bitsize must be 8 bit aligned, and in range 0 < bitSize <= 256

How to do with this ?

**Comment by iikirilov** [comment]
@kanliyong an address is `0x` + 40 characters. I am not sure where you are getting the addressHex value. Maybe from a log topic? - It is not in a valid format.

Please reopen if this is still an issue
