### ISSUE TITLE
Calls on contract hang after event subscription

### ISSUE THREAD

**Issue by repfuesch** [web3j/web3j#69]
Hello,
I'm using the Android library v2.1 and I want to subscribe to events on a contract and notify observers when the contract state changes.
I'm deriving from the Contract base class and have a static deploy method from which I call the "registerContractEvents" method before I return the contract object. After the subscription, no interactions (calls/transactions) with the contract are possible anymore. The calling thread is blocked indefinitely.
I have tested this code successfully with the Java8 library. So this problem occurs only with the android library.

    protected void registerContractEvents() {
        Event event = new Event("purchaseConfirmed", new ArrayList<TypeReference<?>>(), new ArrayList<TypeReference<?>>());
        registerEvent(event);
        event = new Event("aborted", new ArrayList<TypeReference<?>>(), new ArrayList<TypeReference<?>>());
        registerEvent(event);
        event = new Event("itemReceived", new ArrayList<TypeReference<?>>(), new ArrayList<TypeReference<?>>());
        registerEvent(event);
    }

    private void registerEvent(final Event event)
    {
        String encodedEventSignature = EventEncoder.encode(event);
        EthFilter filter = new EthFilter(DefaultBlockParameterName.EARLIEST, DefaultBlockParameterName.LATEST, getContractAddress()).addSingleTopic(encodedEventSignature);

        //After this subscription no calls/transactions on the contracts are possible anymore
        Subscription observable = web3j.ethLogObservable(filter).subscribe(
                new Action1<Log>() {
                    @Override
                    public void call(Log log) {
                        notifyObservers(event.getName(), null);
                    }
                });
    }

**Comment by conor10** [comment]
Do you know how many CPUs are available on the target device?

In the Android library, the ExecutorService uses a fixed thread pool, details [here](https://github.com/web3j/web3j/blob/android/src/main/java/org/web3j/utils/Async.java#L17).

You can also  override the ExecutorService used in a number of the Async calls via [JsonRpc2_0Web3j](https://github.com/web3j/web3j/blob/android/src/main/java/org/web3j/protocol/core/JsonRpc2_0Web3j.java#L87)

**Comment by conor10** [comment]
@repfuesch is this still an issue?

**Comment by repfuesch** [comment]
Yes the issue still exists in the current version. 
I solved it by re-implementing the Filter base class. I used a ScheduledExecutorService to periodically execute the polling of the events on the eth client instead of a while(true) loop with a Thread.sleep(). The problem is that by using a fixed ThreadPool and the busy wait approach, the ExecutorService runs out of threads and its queue grows. I suspect that this leads to a complete blocking of the app process in android systems, since it uses too much resources.
I attached my implementation of the Filter class. Please note that I only tested this with a few contracts with 3 events each. So far I don't have any problems, but I haven't tested this solution throughly. 
Best regards,
repfuesch 
----Ursprüngliche Nachricht----
Von : notifications@github.com
Datum : 24/03/2017 - 11:53 (CET)
An : web3j@noreply.github.com
Cc : flo.schuepfer@bluewin.ch, mention@noreply.github.com
Betreff : Re: [web3j/web3j] Calls on contract hang after event subscription (#69)
@repfuesch is this still an issue?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
  
  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/web3j/web3j","title":"web3j/web3j","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/web3j/web3j"}},"updates":{"snippets":[{"icon":"PERSON","message":"@conor10 in #69: @repfuesch is this still an issue?"}],"action":{"name":"View Issue","url":"https://github.com/web3j/web3j/issues/69#issuecomment-288991563"}}}

**Comment by conor10** [comment]
I can't see the attachment - are you able to submit as a PR against the Android branch?

**Comment by conor10** [comment]
@repfuesch any chance you could provide the mentioned changes?

**Comment by conor10** [comment]
Thanks for highlighting this issue, and a potential solution. Fix has been checked in.
