### ISSUE TITLE
Getting error: Empty value (0x) returned from contract when using string[] as a parameter

### ISSUE THREAD

**Issue by kelheor** [web3j/web3j#691]
I'm getting this error `org.web3j.tx.exceptions.ContractCallException: Empty value (0x) returned from contract` when I'm trying to execute this function:

```
pragma solidity ^0.4.23;
pragma experimental ABIEncoderV2;
...
function stringArrayTest(string[] inputValue) public pure returns(string) {        
        return "Success";
}
```

I'm using Infura. Any ideas on how to fix this error?

**Comment by kelheor** [comment]
Still actual...

**Comment by xiaods** [comment]
same here

**Comment by iikirilov** [comment]
@kelheor can you submit a PR with a breaking test for this please?

**Comment by kelheor** [comment]
It's hard for me to create tests inside web3j sources(don't know even where to better place those tests), so I uploaded example project (IntelliJ Idea) to the attachments.
Look at StringIssueApplicationTests class.
[StringIssue.zip](https://github.com/web3j/web3j/files/2583463/StringIssue.zip)

**Comment by AlexandrouR** [comment]
ABIEncoderV2 is not supported in web3j. Closing as this is duplicate of #935. Please go there to track the progess of this issue
