### ISSUE TITLE
Deploy contract with NoOpProcessor can never success

### ISSUE THREAD

**Issue by taihucao** [web3j/web3j#693]
i try to deploy contract with a ClientTransactionManager based on NoOpProcessor, but always get "Caused by: java.lang.UnsupportedOperationException: Empty transaction receipt, only transaction hash is available".
it may caused by follow codes:
Contract.java
```
private static <T extends Contract> T create(
            T contract, String binary, String encodedConstructor, BigInteger value)
            throws IOException, TransactionException {
        TransactionReceipt transactionReceipt =
                contract.executeTransaction(binary + encodedConstructor, value, FUNC_DEPLOY);


        String contractAddress = transactionReceipt.getContractAddress();
        if (contractAddress == null) {
            throw new RuntimeException("Empty contract address returned");
        }
        contract.setContractAddress(contractAddress);
        contract.setTransactionReceipt(transactionReceipt);

        return contract;
    }
```
when NoOpProcessor is in use, only txHash can be generated and got, so the transactionReceipt is acturally an EmptyTransactionReceipt object, and it never supports a getContractAddress operation.

This create function can not be used for an async contract deploy.

**Comment by iikirilov** [comment]
@taihucao can you provide a PR to fix this?

**Comment by AlexandrouR** [comment]
I will try to replicate this to better understand where the error is being thrown before proposing a solution.

**Comment by iikirilov** [comment]
The NoOp processor should not be used in the smart contract wrapper as it does not return a receipt with the contract address. There is no fix here - the behavior is as expected. Closing issue.
