### ISSUE TITLE
Generate wallet from Ganache test account private key

### ISSUE THREAD

**Issue by vbledar** [web3j/web3j#697]
### Wallet directly from private key

I want to use Ganache. When Ganache starts it will generate some test accounts. I would like to create a Wallet instance using the private key string representation that Ganache provides.

This is sample private key as Ganache represents it:

e7fea27e20b072381b80b391a32b57c4fa144adbe8cb435edc2aa9e4271e3290

This is the address associated with the above private key:

0x8f6Eff1FB2b24bAE17d62d4f41D1aCFe8AAB3C1f

Based on the documenation [https://docs.web3j.io/transactions.html#creating-and-working-with-wallet-files](url) it is possible, but I'm able to find the appropriate API.

Can anyone help me on how to achieve that?

### Workaround

I have been able to import the private key in my geth installation and use the wallet file generated, but it is to cumbersome and mandates a geth installation.

Geth command:

`./geth --datadir "./ethereumdev" account import wallet-private-key`

**wallet-private-key**: is a file which contains the private key

In my case I'm able to retrieve the wallet json file from:

> ./ethereumdev/keystore/UTC--2018-09-05T20-53-37.840069791Z--a130658a3b1a8cf58fe86841e2a4e72115234aa8

**Comment by iikirilov** [comment]
I would recommend you approach this from the opposite direction. Pick a set of private keys and hard-code them in your web3j application. You can start ganache via the cli with a flag to generate accounts from a list of user-specified private keys.

**Comment by rajkumarbhaji** [comment]
Hi currently we are using springboot Java, some how we lossed private keys from the DB. Is it possible to retrieve the private key which was created using same system ? Where the physical file of WalletFile will get stored in linux System?
Thank you in advance.
