### ISSUE TITLE
access to data member in RawTransaction.createEtherTransaction()

### ISSUE THREAD

**Issue by elizur-cartasense** [web3j/web3j#698]
I've been trying to send a message to an account by sending 0 Ethers and putting the (short) message in the data part of the transaction. but...
RawTransaction.createEtherTransaction() does not provide access to the data field.
I tried using RawTransaction.createTransaction() but the resulting transaction is interpreted as a contract creation on blockchain.
could you allow access to data field in RawTransaction.createEtherTransaction()?

thanks

**Comment by iikirilov** [comment]
Does #702 resolve your issue?
