### ISSUE TITLE
SolidityFunctionWrapperGenerator creates return statement for void-methods

### ISSUE THREAD

**Issue by MaxBinnewies** [web3j/web3j#7]
Hello,

the title basically says it all. SolidityFunctionWrapperGenerator actually checks if outputParameterType.isEmpty() but then creates a return-statement anyways. I believe line 214 needs to be deleted.

Other than that its amazing! So far, I have only tried querying the blockchain, without modifying it, but I am optimistic that I can use web3j in my project, so far it has been nothing but wunderful! :-)

Max

**Comment by conor10** [comment]
Glad you're getting on well with the library and thanks for highlighting this.

I've just started work on updating enhancing the code generator to support transactions, so I'll address this issue with that work.

If you want to write the code manually to work with a more complex smart contract, please see the following integration test https://github.com/web3j/web3j/blob/master/src/integration-test/java/org/web3j/protocol/scenarios/HumanStandardTokenIT.java which supports a EIP-20 smart contract implementation.

The next version of the code generator should provide all of the functionality demonstrated in this test.

**Comment by conor10** [comment]
This should now be fixed. Please reopen if you are still seeing issues.
