### ISSUE TITLE
listening to event

### ISSUE THREAD

**Issue by yfhuang521** [web3j/web3j#700]
need help bro,Is there any function of Web3j monitoring smart contract events?

**Comment by summer00** [comment]
Hi,
there are some step you need to do to listen a smart contract:
1. build your smart contranct as java class. see [this](https://docs.web3j.io/smart_contracts.html)
2. create a instance using the contract address
3. invoke the method like xxObservable to listen the coming event

**Comment by iikirilov** [comment]
Get in touch on [![Gitter](https://badges.gitter.im/web3j/web3j.svg)](https://gitter.im/web3j/web3j?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) for further usage qns
