### ISSUE TITLE
topic filter gives no response

### ISSUE THREAD

**Issue by w1397800** [web3j/web3j#704]
when i try to listen the evnet of "Transfer" in the contract of  ["cryptokitties"](https://etherscan.io/token/0x06012c8cf97bead5deae237070f9587f8e7a266d) on the public chain, the topic filter gives no respose.  but i can get response from my private chain using same code. 
here is my program:
`import java.util.Arrays;
import java.util.List;

import org.web3j.abi.EventEncoder;
import org.web3j.abi.TypeReference;
import org.web3j.abi.datatypes.Address;
import org.web3j.abi.datatypes.Event;
import org.web3j.abi.datatypes.generated.Uint256;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.DefaultBlockParameterNumber;
import org.web3j.protocol.core.methods.request.EthFilter;
import org.web3j.protocol.http.HttpService;

public class ContractEvent {
	private static String contractAddress = "0x06012c8cf97bead5deae237070f9587f8e7a266d";
	private static Web3j web3j;

	public static void main(String[] args) throws Exception {
		web3j = Web3j.build(new HttpService("http://192.168.1.9:8545"));//a ethereum node in public chain

		DefaultBlockParameterNumber from = new DefaultBlockParameterNumber(6312293);
		DefaultBlockParameterNumber to = new DefaultBlockParameterNumber(6312309);
		EthFilter filter = new EthFilter(from, to, contractAddress);

		Event event = new Event("Transfer", 
				Arrays.<TypeReference<?>>asList(new TypeReference<Address>() {}, new TypeReference<Address>() {},new TypeReference<Uint256>() {})
				);
		String topicData = EventEncoder.encode(event);
		filter.addSingleTopic(topicData);
		System.out.println(topicData);
		
		web3j.ethLogObservable(filter).subscribe(log -> {
			System.out.println(log.getBlockNumber());
			System.out.println(log.getTransactionHash());
			List<String> topics = log.getTopics();
			for (String topic : topics) {
				System.out.println(topic);
			}
		});
	}
}`

**Comment by tjanson** [comment]
Does it work if you remove the "0x" from `contractAddress`? I had the same issue (and found [Adam Kipnis StackOverflow answer](https://ethereum.stackexchange.com/a/41606/39148) mentioning this).

**Comment by w1397800** [comment]
it does not.  actually my ethereum node has not downloaded  the block 6312309 at that time. and thanks for your reply.
