### ISSUE TITLE
web3j send tx 10 times ,but geth recieve 4 

### ISSUE THREAD

**Issue by lantianqiongfeng** [web3j/web3j#705]
I am use web3j 3.5.0,I send tx like this:
 TransactionReceiptProcessor trp= new PollingTransactionReceiptProcessor(web3j,100,8);
            FastRawTransactionManager fastRawTxMgr =new FastRawTransactionManager(web3j, credentials, trp);
            BigInteger GAS_PRICE = BigInteger.valueOf(0l);
            Transfer transfer = new Transfer(web3j,fastRawTxMgr);
            transfer.sendFunds(toAddress,value, Convert.Unit.WEI,GAS_PRICE,GAS_LIMIT).sendAsync();

I send tx 10 times,but QUORUM recieve 4 
![image](https://user-images.githubusercontent.com/4092651/45414116-3c2d4f80-b6ad-11e8-9354-f8c1ba6d3c78.png)

why?

**Comment by flefevre** [comment]
Bonjour
Did you put a wait at this end of your code to be able to catch
asynchronuous transaction or your program stops as soon as it arrives at
the end of transaction ?
François

**Comment by lantianqiongfeng** [comment]
I use cath Exception like this
![image](https://user-images.githubusercontent.com/4092651/45462197-5ca2eb80-b739-11e8-8a71-818260a7bdf7.png)
but when use 2 threads to send tx,quorum always recieve enough tx
