### ISSUE TITLE
Attempt to invoke virtual method 'org.web3j.protocol.core.methods.response.TransactionReceipt org.web3j.tx.TransactionManager.executeTransaction(java.math.BigInteger, java.math.BigInteger, java.lang.String, java.lang.String, java.math.BigInteger)' on a null object reference

### ISSUE THREAD

**Issue by monkey1992** [web3j/web3j#707]
I use FastRawTransactionManager and NoOpProcessor, sometimes the TransactionManager object may be null, I get the transaction manager by the method:
```
private fun getFastRawTransactionManager(): FastRawTransactionManager {
        return FastRawTransactionManager(web3j, credentials, NoOpProcessor(web3j))
}
```
Normally，the transaction should not be null, but in fact it is, I don't know the detail reason, can anyone help me?

**Comment by iikirilov** [comment]
Please provide details on how to reproduce.

**Comment by AlexandrouR** [comment]
Closed due to inactivity. If the problem persists please open a new issue detailing the steps required to reproduce.
