### ISSUE TITLE
HttpService cause http connection leak

### ISSUE THREAD

**Issue by ciferliu** [web3j/web3j#710]
application log
=================
okhttp3.OkHttpClient - A connection to http://localhost:8545/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

==============
okhttp3 java doc
okhttp3.ResponseBody

A one-shot stream from the origin server to the client application with the raw bytes of the response body. Each response body is supported by an active connection to the webserver. This imposes both obligations and limits on the client application.

The response body must be closed.
Each response body is backed by a limited resource like a socket (live network responses) or an open file (for cached responses). Failing to close the response body will leak resources and may ultimately cause the application to slow down or crash.

**Comment by iikirilov** [comment]
Please provide information to reproduce

**Comment by antonydenyer** [comment]
This is caused when an error is returned (okhttp throws an error if it's not 2xx) from the rpc endpoint. 

https://github.com/square/okhttp/issues/2311

**Comment by antonydenyer** [comment]
This is still an open issue. The change I made didn't solve the issue and was reverted.

**Comment by iikirilov** [comment]
This was auto-closed from the merge.

**Comment by andrii-kl** [comment]
@ciferliu  fixed in commit 6d5b2feb7ba96f71dc02f4f02e177d71ca474676
