### ISSUE TITLE
web3j maven-plugin not a valid name: this 

### ISSUE THREAD

**Issue by nach40** [web3j/web3j#717]
The contract version is "pragma solidity 0.4.24";
in remix all is compiled well with no errors and I was able to run the contract and successfully to test any function.

Using:  
web3j core 3.5.0
web3j-maven-plugin 0.3.5 

It happens when I am trying to build java files with: ">mvn web3j:generate-sources"

Error:
Failed to execute goal org.web3j:web3j-maven-plugin:0.3.5:generate-sources (default-cli) on project doc-updater: Execution default-cli of goal org.web3j:web3j-maven-plugin:0.3.5:generate-sources failed: not a valid name: this -> [Help 1]

**Comment by tjanson** [comment]
Is it possible to share the contract code? In any case, my guess is that you have declared an `event` with an unnamed parameter (as is legal in Solidity). Web3j doesn’t seem to support this (which is a bug).

**Comment by iikirilov** [comment]
please use web3j 3.6.0 and let me know if this is still an issue

**Comment by snazha-blkio** [comment]
No user feedback provided, closing.

**Comment by elenson** [comment]
Failed to execute goal org.web3j:web3j-maven-plugin:4.6.5:generate-sources (generate-sources-web3j) on project coin: Execution generate-sources-web3j of goal org.web3j:web3j-maven-plugin:4.6.5:generate-sources failed: not a valid name:

**Comment by CodingBen** [comment]
> Is it possible to share the contract code? In any case, my guess is that you have declared an `event` with an unnamed parameter (as is legal in Solidity). Web3j doesn’t seem to support this (which is a bug).

If I still want read event thte event with web3j， what should i do？
