### ISSUE TITLE
When we will release the new version for Android?

### ISSUE THREAD

**Issue by fishwjy** [web3j/web3j#722]
There is some errors in generating Java Wrapper by 3.4.0, so I use 3.5.0 to generate wrapper. But the wrapper generated by 3.5.0 can not be used in 3.3.1-android.
So may be we can upgrade code of 3.3.1-android to catch up 3.5.0 Java version ?
And it will coming soon ? Thanks a lot!

**Comment by snazha-blkio** [comment]
Hi @fishwjy 

We are currently working on this, we will keep you posted on this.

**Comment by iikirilov** [comment]
#769
