### ISSUE TITLE
transactionReceipt.getContractAddress() return null

### ISSUE THREAD

**Issue by nach40** [web3j/web3j#729]
using infura as a provider: https://rinkeby.infura.io.
web3j version 0.3.5

...................
TransactionReceipt transactionReceipt = contract.createTest(name).sendAsync().get();
...................
or using
...................
TransactionReceipt transactionReceipt = contract.createTest(name).send();
..................
log.info("contractAddress: "+transactionReceipt.getContractAddress());

INFO: contractAddress: null

If I am using events and set the new created contract address I will have the address, but because of the for cycle is not very convenient.

for (Builder.CreateTestEventResponse event : contract.getCreatedTestEvents(transactionReceipt)) {
            log.info("Created Test: " + event.newTestAddress + ", name: " + event.name + ",testId: " + event.id);
}

Here I get the new address : "event.newTestAddress";

**Comment by iikirilov** [comment]
The contract call does not return a TransactionReceipt - instead, it returns whatever the function call returns.

If you have a look at the smart contract wrapper you can see the return type.

Also, you should use web3j 3.6.0
