### ISSUE TITLE
Clear publication of signing keys for releases

### ISSUE THREAD

**Issue by benjumanji** [web3j/web3j#732]
The latest release is signed by a different user, and the key has no relation to the previous key being used. This kind of signing discipline makes signing almost worthless.

I'd love a dedicated signing master that signs delegated keys that are trusted to do releases (or similar) and for that key to be hosted somewhere owned by the project.

**Comment by iikirilov** [comment]
@conor10 @snazha-blkio

**Comment by snazha-blkio** [comment]
This is a valid request, we already have a ticket to set up automated build and release processes and this will be addressed there.
I will update that ticket with our comment and close this off, thanks.
Ref: https://github.com/web3j/web3j/issues/737
