### ISSUE TITLE
Exception when pass empty list to the smart contract

### ISSUE THREAD

**Issue by Hirama** [web3j/web3j#733]
Contract with `function addAddresses(address point, address[] list) external;`

When I try to execute contract method.
```
public RemoteCall<TransactionReceipt> addAddresses(String point, List<String> list) {
        final Function function = new Function(
                FUNC_ADDADDRESSES, 
                Arrays.<Type>asList(new Address(point),
                new DynamicArray<Address>(
                        org.web3j.abi.Utils.typeMap(list, Address.class))),
                Collections.<TypeReference<?>>emptyList());
        return executeRemoteCallTransaction(function);
    }
```

I got exception `java.lang.IndexOutOfBoundsException: Index: 0, Size: 0`

![image](https://user-images.githubusercontent.com/2853815/46742392-9969f000-ccaf-11e8-8c2d-b46bdb0d5845.png)
Problem is in this part of the code when trying to get the type from the first element of the empty list.

**Comment by MarkOSullivan94** [comment]
@Hirama curious what you are wanting done here
