### ISSUE TITLE
android release required, impossible to compile code build for web3j core on android 

### ISSUE THREAD

**Issue by yuriymyronovych** [web3j/web3j#734]
android release required, impossible to compile code build for web3j core on android as API difference is to big now(v3.6 vs v3.3.1), we need to keep android and java releases up to date.

**Comment by yuriymyronovych** [comment]
I am fine to work on preparing release core-android-3.6, but I need to know that you will approve it guys

**Comment by yuriymyronovych** [comment]
@conor10 @snazha-blkio @iikirilov

**Comment by snazha-blkio** [comment]
Hi @yuriymyronovych 
Sorry for the delay, we have raised #769 for this. As you can see it's a fair bit of work but it is on the radar and we do see the need for it!

If you have capacity please let us know.

**Comment by yuriymyronovych** [comment]
@conor10 @snazha-blkio I believe I managed to get full web3j core working on android(min sdk 24), seems the best approach to me so far, we are still testing it, if any issues will see it soon. 
I started with full web3j because whole approach of trying to adapt web3j code to android everytime is probably unmaintable on the long run. I will keep this thread updated on further progress.

**Comment by iikirilov** [comment]
is this still an issue with android release 4.3.0 ?

**Comment by YuriyWintermute** [comment]
@iikirilov, I think it have been resolved. thanks!
