### ISSUE TITLE
why mnemonic keywords are different?

### ISSUE THREAD

**Issue by SteadyAction** [web3j/web3j#739]
When I use mnemonic keywords generated by web3j in Metamask, it's different.
And it's also different from web3.swift library.
web3.swift library and metamask works together but Web3j doesnt work...how do i fix it?

**Comment by iikirilov** [comment]
[![Gitter](https://badges.gitter.im/web3j/web3j.svg)](https://gitter.im/web3j/web3j?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by razzbee** [comment]
Facing the same problem, metamask seed phrase gives a different account,any help here??

**Comment by iikirilov** [comment]
```

**Comment by jambestwick** [comment]
very well

**Comment by mohamedelshami** [comment]
Assume this complete
