### ISSUE TITLE
How to customize GAS_PRICE and GAS_LIMIT for web3j quorum?

### ISSUE THREAD

**Issue by priyasam9** [web3j/web3j#742]
I am trying to send a transaction to quorum network from an android app using web3j. While doing that, I am getting **transaction failure with status 0x0 not enough gas**. At first I was using **DefaultGasProvider.GAS_PRICE** and **DefaultGasProvider.GAS_LIMIT**. But my guess is as my transaction is quite large so I am getting "not enough gas" error. Then I tried to change my GAS_PRICE to 0 following the document https://web3j.readthedocs.io/en/latest/smart_contracts.html#smart-contract-wrappers [Dynamic gas price and limit] using **ContractGasProvider** instead of **DefaultGasProvider**. Now I am constantly geeting error "System.err: java.lang.NullPointerException: Attempt to invoke interface method 'java.math.BigInteger org.web3j.tx.gas.ContractGasProvider.getGasPrice(java.lang.String)' on a null object reference".  Can anyone please point out what should I write instead? I have added my code for reference. Thank you in advance.

private class DoBlockThreadTask extends AsyncTask<Void,Void,Void> {

        Quorum quorum = Quorum.build(new HttpService("http://157.56.178.153:22000"));
        ContractGasProvider gasProvider;
        // Quorum quorum = Quorum.build(new HttpService("10.100.152.34:22000"));
        @Override
        protected Void doInBackground(Void... voids) {
            ClientTransactionManager transactionManager = new ClientTransactionManager(
                    quorum, "0xed9d02e382b34818e88b88a309c7fe71e65f419d", Arrays.asList());
            System.out.println(">>Before Transaction");
            Ewitness contract= null;
            try {
              
                System.out.println("Gas Price "+ DefaultGasProvider.GAS_PRICE);
                System.out.println("Gas Limit "+DefaultGasProvider.GAS_LIMIT);
           contract=Ewitness.load("0x064f860b6683223b03b38252853d5d2c210cce19",quorum,transactionManager, gasProvider.getGasPrice(Ewitness.FUNC_SET),gasProvider.getGasLimit(Ewitness.FUNC_SET));

                contract.setGasProvider(new DefaultGasProvider(){
                    @Override
                    public BigInteger getGasPrice(String contractFunc) {
                        switch (contractFunc){
                            case Ewitness.FUNC_SET:return BigInteger.valueOf(00_000_000_000L);
                        }
                        return super.getGasPrice(contractFunc);
                    }

                    @Override
                    public BigInteger getGasLimit(String contractFunc) {
                        switch (contractFunc){
                            case Ewitness.FUNC_SET:return BigInteger.valueOf(4_500_000);
                        }
                        return super.getGasLimit(contractFunc);
                    }

                });
     
                System.out.println(">> Make transaction");
                TransactionReceipt transactionReceipt=contract.set(cd,hex,timeStamp,certificate, value).send();

                System.out.println(">> After wait");
                System.out.println("Block Hash "+transactionReceipt.getBlockHash());
                System.out.println("Transaction Hash "+transactionReceipt.getTransactionHash());
            } catch (Exception e) {
                e.printStackTrace();
            }

            return null;
        }

**Comment by iikirilov** [comment]
This issue is better to be in the web3j-quorum repo

**Comment by iikirilov** [comment]
Here is an example to deploy a contract on quorum

```
Equipment.deploy(quorum, clientTransactionManager,
                BigInteger.ZERO, DefaultGasProvider.GAS_LIMIT).send()
```
