### ISSUE TITLE
Transaction status is null: What does it mean?

### ISSUE THREAD

**Issue by pgacirane** [web3j/web3j#744]
Hi everyone.
I am new to ethereum, I have adopted web3j as the library to use in my java app. I am performing some transaction in my private geth blockchain where the transaction status I get is null. What does this mean? Transaction receipt I am getting after performing the line  of code: 
**TransactionReceipt transactionReceipt=forVoter1.register("0xd4815e596093488d64298024d147ceb69da2091e").send();
System.out.println("Transaction receipt is:"+transactionReceipt.toString());**

is

TransactionReceipt{
transactionHash='0xf5c3c9aa8aed318c093053088768d32ebb610c7531c4b258223322f1ff67dc97', transactionIndex='0x0', blockHash='0xea6719f841e572e3f1aac5120436ec8c40e21884762c8132d2cffbf7edf5ec02', blockNumber='0x3df', 
cumulativeGasUsed='0xbf51', 
gasUsed='0xbf51', 
contractAddress='null', root='0xb4fc6b69796b60286ffef2d45519b7e845a64cd14703769ed612a2393dca3c49', 
**status='null',** 
from='0xe2d3507bff33c98dae958470dfb53e8c90fd9bfb', to='0x06fdbbeec191a6fe6e9fa44cdfcdf2f27b3e3142', logs=[], logsBloom='0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'}

**Comment by iikirilov** [comment]
What client and what version are you using? It is possible that your client does not return a status so it is populated with null by web3j.

With newer clients - if the status is 0 the transaction was successful - if the status is 1 the transaction was unsuccessful

**Comment by snazha-blkio** [comment]
Closing - no user feedback.
