### ISSUE TITLE
Wrapper errors

### ISSUE THREAD

**Issue by ArthurHoeke** [web3j/web3j#745]
After some trail & error I was able to generate the warapper with the abi & binary using the etherscan information of my contract
I was able to generate it but for some reason I've got 3 errors that I can't seem to fix, one of them having to do with

 protected Test(String contractAddress, Web3j web3j, Credentials credentials, ContractGasProvider contractGasProvider) {
        super(BINARY, contractAddress, web3j, credentials, contractGasProvider);
    }

It gives me the error 'The constructor Contract(String, String, Web3j, Credentials, ContractGasProvider) is undefined'
Also, it gives me errors for 2 of the 4 RemoteCall functions 'The method deployRemoteCall(Class<T>, Web3j, Credentials, BigInteger, BigInteger, String, String) in the type Contract is not applicable for the arguments (Class<Test>, Web3j, Credentials, ContractGasProvider, String, String)'

Haven't been able to figure out why I get these errors since with other people generating these Java files they don't seem to be having any issues.

Complete Java code of the generated file: https://pastebin.com/ng6dA9CU﻿

**Comment by stang-l** [comment]
Hello,

Did you solve the problem ?

**Comment by seanpenney** [comment]
I'm having the same issue, was there a fix?

**Comment by stang-l** [comment]
> I'm having the same issue, was there a fix?

Hello,

I figured out how to make the contract compile by replacing the call to 
super(BINARY, contractAddress, web3j, credentials, contractGasProvider);
by
super(BINARY, contractAddress, web3j, new RawTransactionManager(web3j, credentials), contractGasProvider);

moreover, calls to 
deployRemoteCall(Helloworld.class, web3j, credentials, contractGasProvider, BINARY, "");
should be replaced by 
deployRemoteCall(Helloworld.class, web3j, credentials, contractGasProvider.getGasPrice(), contractGasProvider.getGasLimit(), BINARY, "");

**Comment by iikirilov** [comment]
Please use web3j 3.6.0 - this has been resolved in #725 - please reopen if this issue persists.
