### ISSUE TITLE
Does Wallet.createLight() still as secure as createStandard() to create wallet file ? What is the difference between them?

### ISSUE THREAD

**Issue by Diorrr** [web3j/web3j#747]
Could someone explain me the difference between useFullScrypt or not by method WalletUtils.generateWalletFile() ?
For web verion of the project I use true param and get creation by Wallet.createStandard(). But for android app it makes problems and that is why I'm using false param and as corresponding Wallet.createLight(). What is the difference ? Still it as secure as previously?

**Comment by iikirilov** [comment]
[![Gitter](https://badges.gitter.im/web3j/web3j.svg)](https://gitter.im/web3j/web3j?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by AlexandrouR** [comment]
Hey, is this still an issue do you require addition information on the matter ?

**Comment by AlexandrouR** [comment]
closed due to inactivity.
