### ISSUE TITLE
Java wrapper class generator silently ignored error and successfully completed without certain class generation

### ISSUE THREAD

**Issue by kelheor** [web3j/web3j#755]
So I have a contract with the following declaration:
contract EtherPetToken is ERC721, ERC721Enumerable, ERC721Metadata

I'm using web3j-maven-plugin to generate java wrapper classes.
For a contract with such declaration wrapper class won't be generated and no errors will be generated in output (main problem - hard to figure out what's wrong).

The issue can be fixed by adding this constructor to the contract:
constructor(string name, string symbol) ERC721Metadata(name, symbol)
    public
    {
    }

I think it's bad that I didn't receive any errors if wrapper classes can't be generated.

**Comment by iikirilov** [comment]
Cannot reproduce.

Can you please provide more information so I can replicate this. A simple version of your EtherPetToken will be fine. I also need you ERC721, ERC721Enumerable and ERC721Metadata.

**Comment by kelheor** [comment]
ERC721, ERC721Enumerable and ERC721Metadata can be found here: https://github.com/OpenZeppelin/openzeppelin-solidity/tree/master/contracts/token/ERC721

A simple version of EtherPetToken:

```
contract EtherPetToken is ERC721, ERC721Enumerable, ERC721Metadata {

    string public constant name = "EtherPet";
    string public constant symbol = "EP";
    uint8 public constant decimals = 0;

}
```

**Comment by iikirilov** [comment]
I cannot reproduce with web3j 3.6.0 or web3j 4.0.0-alpha - checkout the attached zip which is generated with 3.6.0.
[erc721.zip](https://github.com/web3j/web3j/files/2561515/erc721.zip)

**Comment by kelheor** [comment]
Try to remove the constructor from your SampleERC721 contract. I wrote that with constructor there is no issue if you will add ERC721Metadata. But if you will miss constructor, the described issue will happen.

**Comment by kelheor** [comment]
Because I tested now your SampleERC721 and be able to reproduce an issue, I guess you may be right - there might be an issue with maven plugin itself. I attached a sample Idea project to demonstrate an issue.
[ERC721Test.zip](https://github.com/web3j/web3j/files/2561738/ERC721Test.zip)

**Comment by iikirilov** [comment]
closing as not related to web3j - please open a new issue in the web3j maven plugin repo
