### ISSUE TITLE
use web3j deploy a smart conctract,but in my ethereumwallet can't find this contract?

### ISSUE THREAD

**Issue by lishidetainan** [web3j/web3j#758]
hello, I have userd web3j deploy a smart contract and I have got the hash,  after I have use this method (ethGetTransactionByHash) query the transaction and I have the correct result,   but  user Ethereumwallet 0.11 release,  I can't find the contract, my deploy code is:

Credentials credentials = WalletUtils.loadCredentials("", filePath);
	
		RemoteCall<Coin> deploy = Coin.deploy(web3j, credentials, BigInteger.valueOf(100), BigInteger.valueOf(3041592));
		/*RemoteCall<TokenERC20> deploy = Coin.deploy(web3j, credentials,
				Convert.toWei("10", Convert.Unit.GWEI).toBigInteger(),
				BigInteger.valueOf(3000000),
				BigInteger.valueOf(5201314),
				"0xF287bF936F5173beeA2Be2c1d26837d0353B47E3", "mt");
			Coin coin = deploy.send();	
			coin.isValid();

**Comment by lishidetainan** [comment]
ok, thanks. I will try.

**Comment by iikirilov** [comment]
I am marking as solved - feel free to reopen if you feel this is an issue with web3j
