### ISSUE TITLE
org.web3j.protocol.core.filters.FilterException: Invalid request: filter not found

### ISSUE THREAD

**Issue by 401825317** [web3j/web3j#760]
![image](https://user-images.githubusercontent.com/19526136/47604543-e7ac1c80-da2d-11e8-95ae-7987113bab24.png)
can you help me?

**Comment by 401825317** [comment]
@ligi @psylinse @jorpic @matthewleon  my block server is OK

**Comment by iikirilov** [comment]
[![Gitter](https://badges.gitter.im/web3j/web3j.svg)](https://gitter.im/web3j/web3j?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

Web3j should be able to handle this case for you since version 3.6.0. Which version are you using?

**Comment by AlexandrouR** [comment]
Hey, Is this still an issue ?

**Comment by AlexandrouR** [comment]
Closes due to inactivity.
