### ISSUE TITLE
same nonce

### ISSUE THREAD

**Issue by mzob** [web3j/web3j#765]
I'm working with web3j v3.6.0
I sent some transations,but got "nonce too low" error.Because getNonce() return same nonce
` TransactionReceipt transactionReceipt = transfer.sendFunds(
                toAddress,  
                BigDecimal.valueOf(value), Convert.Unit.ETHER,gasPrice,gasLimit) 
                .send();`
`
        System.out.println(
                "Funds transfer completed, transaction hash: " +
                        transactionReceipt.getTransactionHash() +
                        ", block number: " +
                        transactionReceipt.getBlockNumber()+",gas used: "+transactionReceipt.getGasUsed());
`

**Comment by snazha-blkio** [comment]
Closing - no user feedback.
