### ISSUE TITLE
Array.valid methods implemented wrongly

### ISSUE THREAD

**Issue by esocode** [web3j/web3j#771]
While looking over some source code of the project (I'm not yet using web3j) and noticed that the implementation of the `valid()` methods in the class `org.web3j.abi.datatypes.Array` is wrong. The code incorrectly uses logical `OR` expressions where a logical `AND` would be appropriate:

```java
return values != null || values.length != 0 || type != null
```
Aside from the wrong test this code will fail with a NPE if `values` is NULL. 

In addition, the code is duplicated in two `valid` methods with only slightly different signatures, as is the actual verification in the constructors that throws an exception on failed checks. Furthermore the check is incomplete as it handles the case `type == null` the same as an empty array. I would suggest to change the code to a single check method like the following that is then invoked by the varargs constructor with `Arrays.asList(values)`:

```java
    private void checkValid(String type, List<T> values) {

    	Objects.requireNonNull(type);
   
        if (values == null || values.size() == 0) {
            throw new UnsupportedOperationException(
                "If empty list is provided, use empty array instance");
        }
    }
```

I'm not familiar with the project development and branch handling, otherwise I would have prepared a PR.

**Comment by iikirilov** [comment]
This is a private method used internally in web3j. It must be set up like this because there are two constructors - one that takes in varags of type T i.e. `new Array(type, t1, t2, t3, ...)` which is treated as an array in the constructor and one that takes a list.

This method is not intended to be used by consumers of the library.

**Comment by esocode** [comment]
That is not the point - the implementation is wrong. If values is NULL the test will run into values.length and that will then throw a NPE. At least the or condition needs to be converted to and.
