### ISSUE TITLE
3rd party ENS registry support

### ISSUE THREAD

**Issue by MarkOSullivan94** [web3j/web3j#772]
Currently there are three registry contract address' supported in the project. It would be great if there was an option to integrate with a 3rd party ENS registry.

**Comment by iikirilov** [comment]
Sounds like a plan - can you provide more detail on what needs to be changed to implement this?

I have not used the ENS support in web3j.

**Comment by andrii-kl** [comment]
@MarkOSullivan94 I would recommend to take a look on a new ENS approach EIP-3668. 
We are in the process of implementation it, so I think it can cover some your cases. 
Let me know please, if it's not enough for you.

https://github.com/web3j/web3j/issues/1603

**Comment by andrii-kl** [comment]
[https://github.com/web3j/web3j/issues/1603](url)

**Comment by andrii-kl** [comment]
#https://github.com/web3j/web3j/issues/1603

**Comment by andrii-kl** [comment]
@MarkOSullivan94 If you still have a problem with a new web3j version and ENS, just create a new issue.
