### ISSUE TITLE
How do I correctly filter specific contract logs with filter?

### ISSUE THREAD

**Issue by 401825317** [web3j/web3j#774]
RT
That's what I write now:

`
             EthFilter filter = new EthFilter(DefaultBlockParameter.valueOf(startBlock),
DefaultBlockParameterName.LATEST, ed0588ae6ad1e5abd1957cc77f4aded77ab425ae);
//						consts.getECOMCONTRACTADDRESS());
		Event event = new Event("Transfer", Arrays.<TypeReference<?>> asList(new TypeReference<Address>() {
		}, new TypeReference<Address>() {
		}), Arrays.<TypeReference<?>> asList(new TypeReference<Uint256>() {
		}));

		String topicData = EventEncoder.encode(event);
		filter.addSingleTopic(topicData);
		log.debug("start block.........................:{}",startBlock);
		
			EthLog ethlog=web3j.ethGetLogs(filter).send();
			System.out.println(com.github.ltsopensource.core.json.JSON.toJSONString(ethlog));
			web3j.ethLogObservable(filter).subscribe(eventlog -> {
String eventlogstr = JSON.toJSONString(eventlog);
				log.debug("Transfer log:{}", eventlogstr);
})
`

**Comment by 401825317** [comment]
@ligi @psylinse @jorpic @matthewleon thanks

**Comment by 401825317** [comment]
I can't receive any news now.

**Comment by tjanson** [comment]
The code you posted contains syntax errors, e.g., in this line:

```java
Event event = new Event("Transfer", Arrays.<TypeReference> asList(new TypeReference() { }, new TypeReference() { }), Arrays.> asList(new TypeReference() {}));
                                                                                                                        // ^--------
```

Aside from the missing `<TypeReference`, you did not actually specify the **type**. What is the signature of the event (in Solidity)?

As an example, if it’s `event Transfer(bytes32 indexed a, bytes32 indexed b);`, the event arguments would be the following:

```java
List<TypeReference<?>> eventArguments = Arrays.asList(new TypeReference<Bytes32>() {}, new TypeReference<Bytes32>() {});
```

**Comment by psylinse** [comment]
Hey @401825317, I'm not sure why you keep including me on these issues. I am not a contributor to this repository in any meaningful way, so I'm unlikely to be able to help you. Sorry!

Also, I believe there's a fairly active gitter that may be more appropriate to get this sort of help on: https://gitter.im/web3j/web3j.

**Comment by iikirilov** [comment]
Drop me a message on gitter :)

**Comment by 401825317** [comment]
I have received the response normally, because only filter related logs will have messages.
Thank you!
