### ISSUE TITLE
Bug: inverted logical condition in abi.datatypes.Array.valid()

### ISSUE THREAD

**Issue by esocode** [web3j/web3j#780]
There is a severe bug in the methods `abi.datatypes.Array.valid()`. The logical condition by which the tests are combined is inverted. Instead of an AND condition it uses an OR condition, making the current code defective:
```java
return values != null || values.length != 0 || type != null
```
This code will either not check the other conditions if values is not NULL or fail with an NPE if it is. This error is duplicated in the two almost identical implementations of the method, so both need to be fixed!

This was already reported in #771 which was simply closed with the argument that the method is private (which obviously doesn't prevent the bug). That report also included a hint how to restructure the code to prevent such error duplication and to better state the purpose of the code.

**Comment by esocode** [comment]
I can provide the fix as a PR. I assume such development occurs on the `develop` branch?

Regarding the refactoring: the extra computation for wrapping a varargs with `Arrays.asList()` is really negligible as the list will just be backed by the varargs array. From my experience it is much more problematic to have duplicate code, especially if it contains errors like in this example.

**Comment by snazha-blkio** [comment]
> I can provide the fix as a PR. I assume such development occurs on the `develop` branch?
> 
> Regarding the refactoring: the extra computation for wrapping a varargs with `Arrays.asList()` is really negligible as the list will just be backed by the varargs array. From my experience it is much more problematic to have duplicate code, especially if it contains errors like in this example.

Hi @esocode 
Please branch of master
