### ISSUE TITLE
Missing contribution guidelines

### ISSUE THREAD

**Issue by iikirilov** [web3j/web3j#781]
There should be contribution guidelines specified to make it easier and clearer for contributors on how to make effective PRs. This will make it easier for maintainers to address those PRs appropriately.

**Comment by iikirilov** [comment]
Thoughts on using [this](https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md) as a template?

**Comment by snazha-blkio** [comment]
Look like a good start given we don't have a template yet!
