### ISSUE TITLE
How do I pass bytes32 to a solidity function call?

### ISSUE THREAD

**Issue by qnimate** [web3j/web3j#80]
I create a Bytes32 instance this way:

`new org.web3j.abi.datatypes.generated.Bytes32(hash.getBytes())`

But I am getting this exception

`input byte array must be in range 0 < M <= 32 and length must match type`

My solidity function is of this type

`function hasProof(bytes32 proof) constant returns (bool) {}`

**Comment by qnimate** [comment]
@conor10 @thedoctor Can you please answer this?

**Comment by thedoctor** [comment]
@qnimate `hash.getBytes()` is going to give you a java `byte[]` – you can convert that to a `Bytes32` if and only if it has a length == 32. Check the length of `hash.getBytes()`. Depending on what kind of object `hash` is, `getBytes()` might not be what you want to call.

**Comment by qnimate** [comment]
`hash` is a Java string. My `hash` length is not 32. It's a sha256 hash. So how can I pass a Java string as an 'bytes32' solidity type.

**Comment by thedoctor** [comment]
Okay, yeah that's not what you want. If `hash` is a string, then `getBytes` will give you the byte encoding of the string in whatever your default charset is (probably utf8).

I'm guessing your hash is hex encoded? If so, you want to decode the hex to a byte array –– lots of ways to do that, here's one from ethereumJ that handles the `0x` prefix:
```
new Bytes32(org.ethereum.jsonrpc.TypeConverter.StringHexToByteArray(hash))
```

**Comment by qnimate** [comment]
@thedoctor anyway to do it without using ethereumJ?

**Comment by thedoctor** [comment]
Yes, many:
https://stackoverflow.com/questions/8890174/in-java-how-do-i-convert-a-hex-string-to-a-byte
https://stackoverflow.com/questions/140131/convert-a-string-representation-of-a-hex-dump-to-a-byte-array-using-java
https://commons.apache.org/proper/commons-codec/
https://google.github.io/guava/releases/16.0/api/docs/com/google/common/io/BaseEncoding.html

Note: if your hash has a `0x` prefix, you'll have to strip it first if you use any of those methods.

**Comment by qnimate** [comment]
@thedoctor  I am using this to convert `byte[] b = new BigInteger(s,16).toByteArray();`

If the string length is 64 then the byte[] length shows as 33 but when the string length is 63 then the byte[] length shows as 32. Not sure what's wrong. Any idea?

The sha256 hash in should be a 64 length string right?

**Comment by qnimate** [comment]
@thedoctor seems like this is the issue http://stackoverflow.com/questions/33536253/java-the-length-of-the-byte-array-seems-to-be-wrong-from-converting-a-string-of

**Comment by qnimate** [comment]
Found solution 

`Arrays.copyOfRange(new BigInteger(hash, 16).toByteArray(), 1, 33)`

@thedoctor Thanks a lot for the help.

**Comment by thedoctor** [comment]
Ahhhh, actually @qnimate that will eventually give you problems. You shouldn't use the BigInteger conversion method (as it says in the most-upvoted answer to the question you got that from) because it doesn't work with leading zeros.

If you want a quick one-liner with no dependencies, do this: 
```
    javax.xml.bind.DatatypeConverter.parseHexBinary(hash);
```

General advice: When you're handling cryptographic primitives, even if they're not sensitive, it's worth your time to investigate thoroughly the proper way to handle them. Copying from SO without understanding what's happening is not advised.

**Comment by conor10** [comment]
@qnimate - web3j already has a number of helper functions for conversions betwen hex strings, BigIntegers and byte arrays. See https://github.com/web3j/web3j/blob/master/src/main/java/org/web3j/utils/Numeric.java#L157 for converting a hex string to a byte array.
@thedoctor - thanks for chipping in here.

**Comment by thedoctor** [comment]
Huh, look at that. I actually looked in that package for something that would avoid external dependencies last night – but I only checked `Bytes` `Convert` and `Strings`

**Comment by wannamit** [comment]
This worked for me... Is there any better method?

String to Bytes32:

    public static Bytes32 stringToBytes32(String string) {
            byte[] byteValue = string.getBytes();
            byte[] byteValueLen32 = new byte[32];
            System.arraycopy(byteValue, 0, byteValueLen32, 0, byteValue.length);
            return new Bytes32(byteValueLen32);
        }

Bytes32 to String:

    StringUtils.newStringUsAscii(varTypeBytes32.getValue())

**Comment by parin13** [comment]
lets consider i have function whose input parameter is

- bytes32

- bytes32[ ]    // array of type bytes 32

- uint8

 which looks like:

```
 function abc(bytes32 id, bytes32[ ] name,uint8 version) returns(bool)
    {  
        //
     }
```

so now to provoke the function (using remix) you have to pass parameters which looks like:

`"0x12",["0x1262","0x12","0x12"],8`
