### ISSUE TITLE
Unable to retrieve bytes32 static array from solidity using Web3J library

### ISSUE THREAD

**Issue by AbhinabaD** [web3j/web3j#802]
While invoking a function that returns a bytes32 datatype array, Web3J is unable to return the values. It raises an exception 

java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.web3j.abi.FunctionReturnDecoder.build(FunctionReturnDecoder.java:114)
	at org.web3j.abi.FunctionReturnDecoder.decode(FunctionReturnDecoder.java:42)
	at org.web3j.tx.Contract.executeCall(Contract.java:211)
	at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:217)
	at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:228)

After debugging, the issue rises from FunctionReturnDecoder.class, line 114. It is actually parsing an empty string to an Integer which gives rise to the above mentioned exception. 

If anyone suceeded in retrieving values from bytes32 datatype array from solidity by using Web3J, please share. Thanks in advance!

**Comment by anthony-skr** [comment]
I have the same issue (or related)... here my analysis :

ABI : 

>     {
>         "constant":true,
>         "inputs":[
>             {
>                 "name":"otc",
>                 "type":"address"
>             },
>             {
>                 "name":"payToken",
>                 "type":"address"
>             },
>             {
>                 "name":"buyToken",
>                 "type":"address"
>             }
>         ],
>         "name":"getOffers",
>         "outputs":[
>             {
>                 "name":"ids",
>                 "type":"uint256[100]"
>             },
>             {
>                 "name":"payAmts",
>                 "type":"uint256[100]"
>             },
>             {
>                 "name":"buyAmts",
>                 "type":"uint256[100]"
>             },
>             {
>                 "name":"owners",
>                 "type":"address[100]"
>             },
>             {
>                 "name":"timestamps",
>                 "type":"uint256[100]"
>             }
>         ],
>         "payable":false,
>         "stateMutability":"view",
>         "type":"function"
>     }


Generated wrapper :

```
[...]
final Function function = new Function(FUNC_GETOFFERS, 
                Arrays.<Type>asList(new org.web3j.abi.datatypes.Address(otc), 
                new org.web3j.abi.datatypes.Address(payToken), 
                new org.web3j.abi.datatypes.Address(buyToken)), 
                Arrays.<TypeReference<?>>asList(new TypeReference<StaticArray<Uint256>>() {}, new TypeReference<StaticArray<Uint256>>() {}, new TypeReference<StaticArray<Uint256>>() {}, new TypeReference<StaticArray<Address>>() {}, new TypeReference<StaticArray<Uint256>>() {}));
[...]
```

Interpreted by : 
FunctionReturnDecoder.java L116
```
if (StaticArray.class.isAssignableFrom(type)) {
                    int length = Integer.parseInt(type.getSimpleName()
                            .substring(StaticArray.class.getSimpleName().length()));
```

Because StaticArray does not contains size (like StaticArray5, StaticArray10 ...), parseInt receive empty string length and fails.

> Exception in thread "main" java.lang.NumberFormatException: For input string: ""
> 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
> 	at java.lang.Integer.parseInt(Integer.java:592)
> 	at java.lang.Integer.parseInt(Integer.java:615)
> 	at org.web3j.abi.FunctionReturnDecoder.build(FunctionReturnDecoder.java:117)
> 	at org.web3j.abi.FunctionReturnDecoder.decode(FunctionReturnDecoder.java:43)
> 	at org.web3j.tx.Contract.executeCall(Contract.java:227)
> 	at org.web3j.tx.Contract.executeCallMultipleValueReturn(Contract.java:263)

**Comment by AlexandrouR** [comment]
This issue is no longer relevant because the code has changed.
