### ISSUE TITLE
can i send transaction only  by passing method name and params like web3

### ISSUE THREAD

**Issue by yanyanho** [web3j/web3j#804]
what I want is that , can I invoke the smart contract only  by passing method name and params  by using web3j, what I finished is that deploy load contract is successful. However invoke the contract method with many params by reflect is more complex.

**Comment by AlexandrouR** [comment]
Yes you can take a look [here](https://github.com/web3j/sample-project-gradle) in this example after deploying the Greeter contract you can do this 
`TransactionReceipt transactionReceipt = contract.newGreeting("Well hello again").send();`
where newGreeting is a contract method taking a string.
