### ISSUE TITLE
deploy returning null contract address

### ISSUE THREAD

**Issue by slowtokyo** [web3j/web3j#81]
Hi there. I just started using web3j, but really great tool!

I'm not sure if my issue is the same as either #51 or #11, but I believe it may be after I have messed around with Gas Limits (higher and lower).

The problem comes when deploying a contract without a constructor, I am getting the following java code output:

```
    public static Future<DefaultServiceRegistryContract> deploy(Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit, BigInteger initialValue) {
        return deployAsync(DefaultServiceRegistryContract.class, web3j, transactionManager, gasPrice, gasLimit, BINARY, "", initialValue);
    }
```

This may be expected behavior, but I thought I'd ask anyway. Now, this contract is "deployable" in Remix/browser Solidity--i.e., I can create and interact with it. So I'm not sure why the contract address is not returned.

This is frankly a stab in the dark, but I am wondering if the way the binary and constructor is put together in https://github.com/web3j/web3j/blob/master/src/main/java/org/web3j/tx/Contract.java#L233 is affecting how the contract deployment with no parameter constructors (e.g., https://ethereum.stackexchange.com/questions/10862/deploying-contract-with-constructor-arguments-via-geth-rpc).

Thank you for any guidance in advance.

**Comment by slowtokyo** [comment]
I now believe this is an error on my end so am closing while I investigate. Again, thanks for the great tool!

**Comment by slowtokyo** [comment]
It was my error after all.

It was helpful to look at the `create` function again, obviously there is [supposed to be a error caught](https://github.com/web3j/web3j/blob/master/src/main/java/org/web3j/tx/Contract.java#L236) if the returned transaction receipt comes back with `contractAddress == null` but that didn't seem to be caught. This led me to believe that somewhere higher up the contract address lookup function wasn't working properly. It was of course this, where I had a TODO in my own method to return a contract address. Thanks and sorry for the trouble!

**Comment by conor10** [comment]
No problem, I'm glad you got to the bottom of the issue.
