### ISSUE TITLE
Transitive jnr-unixsocket Dependency Using Ambiguous Licensing

### ISSUE THREAD

**Issue by schroedingerscode** [web3j/web3j#810]
Web3j depends on jnr-unixsocket which in turn depends on jnr-posix. The version of jnr-unixsocket currently referenced (0.15) depends on jnr-posix-3.0.33 which is ambiguously licensed under EPLv1/GPLv2/LGPLv2.1. This provides some reservations on library usage for projects licensed under BSD style licenses.

The suggested fix is to upgrade jnr-unixsocket to jnr-unixsocket-0.21 which requires transitive dependency jnr-posix-3.0.45, that is less ambiguously licensed under either EPLv2 OR GPLv2 OR LGPLv2.1, allowing both strong- and weak- copyleft usage in derivative works (such as web3j) with more permissive BSD style licenses.

**Comment by snazha-blkio** [comment]
Released
