### ISSUE TITLE
web3j and parity 

### ISSUE THREAD

**Issue by mr13tech** [web3j/web3j#814]
I have faced few problems then testing web3j and parity;

The [send()](https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/protocol/core/RemoteCall.java#L29) is not sync then using parity; It means If someone deploy a contract using _myGeneretaedSmartContract.deploy(...).send()_  It does not wait till transaction is mined. In general it is not a problem, but  the _send()_ function is sync if another client is used (geth for example) -- waits till transaction is mined. So what is correct behavior? Because it is not possible to use the same code with different clients.

I have tested with few clients, below are some metadata about env;
```
$ uname -a
Linux 4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ parity -v
version Parity-Ethereum/v2.0.9-stable-09f7757-20181028/x86_64-linux-gnu/rustc1.30.0
```
```
$ geth version
Geth
Version: 1.8.19-stable
Git Commit: dae82f098570e15d44584f0d7f350713f4774727
Architecture: amd64
Protocol Versions: [63 62]
Go Version: go1.10.4
Operating System: linux
```
Also tested with infura geth v1.8.17, and the _send()_ invocation is sync;

The lack of sync with parity sometimes  has a result in messing up with `nonce` value of  address:
* start test --> deploy token --> request tokens decimals --> crash because deploy tx is not mined yet(token decimals call return 0x)
* start test --> crash with stack trace:
```
java.lang.RuntimeException: java.lang.RuntimeException: Error processing transaction request: Transaction with the same hash was already imported.

	at org.web3j.tx.Contract.deploy(Contract.java:366)
	at org.web3j.tx.Contract.lambda$deployRemoteCall$7(Contract.java:456)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
```

Tried to update the parity client to latest version, the result is a bit different, but still does not work:
```
$parity -v
version Parity-Ethereum/v2.1.8-stable-3eae1d3-20181130/x86_64-linux-gnu/rustc1.30.1
```

```
java.lang.RuntimeException: java.net.SocketTimeoutException: timeout

	at org.web3j.tx.Contract.deploy(Contract.java:366)
	at org.web3j.tx.Contract.lambda$deployRemoteCall$7(Contract.java:456)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
```

with a new log entry in parity node after deploy transaction attempt:
```
Pending` is deprecated and may be removed in future versions. Falling back to `Latest`
```

**Comment by snazha-blkio** [comment]
Which version of web3j are you using? Have you tried this with the latest release? 4.0.3

**Comment by rad-p** [comment]
With 4.0.1
