### ISSUE TITLE
same nonce if send transaction quickly

### ISSUE THREAD

**Issue by ijustyce** [web3j/web3j#815]
Here is my code
`val ethGetTransactionCount = web3j.ethGetTransactionCount(
                fromAddress,
                DefaultBlockParameterName.PENDING
            ).sendAsync().get()`
I call this method before call ethSendRawTransaction，if send  transaction very quickly，the nonce value will be same.

Can you provide any help, I am no't good at English. Thanks.

**Comment by knakagoe1** [comment]
I had the same problem. 
`web3j.ethGetTransactionCount` doesn't include pending transaction count. 
So I used [parity_nextNonce  JSON-RPC method](https://wiki.parity.io/JSONRPC-parity-module#parity_nextnonce) directly to get the proper next nonce. 
It seems there's no way to execute  parity_nextNonce  in web3j for now.

**Comment by hd51515** [comment]
i have the same problem even after giving 100msec gap between transactions.

**Comment by AlexandrouR** [comment]
Increase the time between the transactions if the transaction is in the transaction pool you will possibly get the same nonce. The is an issue when sending transactions in bulk.
