### ISSUE TITLE
Web3j generate should validate .bin file

### ISSUE THREAD

**Issue by ngbalk** [web3j/web3j#816]
I recently made a mistake where I was copying the entire “binary” JSON object as provided by Remix to my Contract.bin file. The format of the bin file was clearly wrong (as it was JSON) but the generate command succeeded. There should be some basic validation to ensure these files are properly formatted.

Thoughts?

**Comment by AlexandrouR** [comment]
The bin file is generated by the solidity compiler and it up to the user to manipulate it improperly.
In addition a binary file in this context cannot be validated  because it has no format.

**Comment by ngbalk** [comment]
I guess my point is that you could do some simple input validation on this file to catch user error.
