### ISSUE TITLE
Call const function throw error

### ISSUE THREAD

**Issue by codati** [web3j/web3j#82]
hi.
exeption :com.package Identities$1 cannot be cast to org.web3j.abi.TypeReference$StaticArrayTypeReference

os : android

it is throw by FunctionReturnDecoder.java:104

com.package.Identities is a class generated by bin/web3j

error is throw by call to getCertifications of com.package.Identities
abi:https://pastebin.com/iHUZ5fJ6

thx for read

**Comment by codati** [comment]
my classe com.package.contract.Identities
https://pastebin.com/3rTPfUWp

**Comment by codati** [comment]
quick fix : use array dynamique size

**Comment by conor10** [comment]
Hi, are you able to provide the returned data from the contract call? Or a unit test that demonstrates the error?

https://github.com/web3j/web3j/blob/e5632f9776c8b18293932cba612095e536b7631b/src/test/java/org/web3j/abi/FunctionReturnDecoderTest.java#L121

**Comment by conor10** [comment]
Closing as not heard anything further.
