### ISSUE TITLE
Web3j wss://mainnet.infura.io/ws using in Java

### ISSUE THREAD

**Issue by Nasibulloh** [web3j/web3j#822]
Can I use one of them 
wss://mainnet.infura.io/ws
wss://ropsten.infura.io/ws
wss://rinkeby.infura.io/ws
in Java for listening transactions or something else. In NodeJS I can listen it but I need in Java. Is It possible?

**Comment by ESchouten** [comment]
Yes it works, but websocket connections with Infura are fairly unstable at the moment.
See #703

**Comment by Nasibulloh** [comment]
Aha understood. Thanks a lot.
