### ISSUE TITLE
How do you get a working WebSocket request with Infura?

### ISSUE THREAD

**Issue by WarSame** [web3j/web3j#826]
I noticed there are no explicit examples of a working WS request with Infura. This is an example test using Rinkeby(with a Junit assert in there). This also uses the Android logger. Note that there is a connect step between the service and web3j, and that this uses the general infura URL rather than a project specific v3 URL.

```
    static private final String INFURA_URL = "wss://rinkeby.infura.io/ws";
    static private final boolean INCLUDE_RAW_RESPONSES = false;
    WebSocketService webSocketService = new WebSocketService(INFURA_URL, INCLUDE_RAW_RESPONSES);
    webSocketService.connect();
    Web3j web3j = Web3j.build(webSocketService);
    web3j
        .ethGasPrice()
        .flowable()
        .subscribe(
               ethGasPrice -> {
                   assertNotNull(ethGasPrice);
                   Log.i(TAG, ethGasPrice.getGasPrice().toString());
                }
        );
```

**Comment by Zatara7** [comment]
Any news here?

**Comment by AlexandrouR** [comment]
This meeds to be added to the docs.

**Comment by mohamedelshami** [comment]
I believe this tutorial should help https://blog.web3labs.com/web3development/connect-infura-to-web3j
