### ISSUE TITLE
org.web3j.crypto.Sign#signedMessageHashToKey should be a public method

### ISSUE THREAD

**Issue by kongliangzhong** [web3j/web3j#827]
I already have the hash, the signer address and signature, but failed to verify the signature because org.web3j.crypto.Sign.signedMessageHashToKey is a private method.

**Comment by AlexandrouR** [comment]
@iikirilov do you think it is a good idea to make this method public ?

**Comment by iikirilov** [comment]
Yes, it can be made public.
There need to be java docs written for the method.
