### ISSUE TITLE
ECDSA implementation not found in 4.1.0-android

### ISSUE THREAD

**Issue by WarSame** [web3j/web3j#828]
I am getting an exception on Android when trying to generate a new light wallet using 4.1.0-android. This is code that previously used to work:

`this.fileName = WalletUtils.generateLightNewWalletFile(longPassword, getWalletDir(context));`

longPassword is a String, getWalletDir returns a directory to store all of the wallet files in.

```
W/System.err: java.security.NoSuchAlgorithmException: KeyPairGenerator ECDSA implementation not found
        at org.apache.harmony.security.fortress.Engine.notFound(Engine.java:190)
W/System.err:     at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:183)
W/System.err:     at java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:149)
W/System.err:     at java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:122)
        at org.web3j.crypto.Keys.createSecp256k1KeyPair(Keys.java:58)
        at org.web3j.crypto.Keys.createEcKeyPair(Keys.java:75)
        at org.web3j.crypto.Keys.createEcKeyPair(Keys.java:70)
        at org.web3j.crypto.WalletUtils.generateNewWalletFile(WalletUtils.java:61)
W/System.err:     at org.web3j.crypto.WalletUtils.generateLightNewWalletFile(WalletUtils.java:47)
        at com.example.graeme.beamitup.wallet.Wallet.<init>(Wallet.java:43)
W/System.err:     at com.example.graeme.beamitup.wallet.Wallet.<init>(Wallet.java:22)
        at com.example.graeme.beamitup.wallet.Wallet$WalletBuilder.build(Wallet.java:161)
        at com.example.graeme.beamitup.wallet.GenerateWalletTask.handleWalletCreation(GenerateWalletTask.java:74)
        at com.example.graeme.beamitup.wallet.GenerateWalletTask.doInBackground(GenerateWalletTask.java:51)
        at com.example.graeme.beamitup.wallet.GenerateWalletTask.doInBackground(GenerateWalletTask.java:18)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

Googling seems to suggest that it may be due to Bouncy Castle implementing stunted versions of some algorithms for Android, but again, this previously worked on Android 3.4 and I believe web3j uses Spongy Castle to get around BC's problems.

I noticed @sanignucio mentioned this problem [in the sample project](https://github.com/web3j/sample-project-gradle/issues/9) which I cannot build the project to reproduce.

**Comment by nariman-amani** [comment]
I have the same problem. any plan to fix it?

**Comment by nariman-amani** [comment]
as i know the problem is that Spongy Castle changed to Bouncy Castle in version 4.1.0-android and android have problem with bouncy Castle.

**Comment by WarSame** [comment]
@snazha-blkio Thanks for the information.
What follow up do we have? Did @serso test generating a wallet?

**Comment by snazha-blkio** [comment]
@WarSame  there is a test for this functionality, please refer to: https://github.com/web3j/web3j/blob/release/4.1-android/core/src/test/java/org/web3j/crypto/WalletUtilsTest.java#L70

Are you able to run similar code to this in your app?

**Comment by serso** [comment]
@WarSame yes, wallet generation was tested: https://github.com/serso/web3a/blob/4dda74db948f8cbd9a79ba4b9ab456316ea52c4d/app/src/main/java/org/solovyev/android/web3a/MainActivity.java#L431.

**Comment by snazha-blkio** [comment]
Thanks @serso . @WarSame , can you please try the suggested change by @serso and report back?

**Comment by serso** [comment]
@WarSame, @kagile, @nariman-amani have you tried the proposed solution? Did it fix the problem?

**Comment by nariman-amani** [comment]
@serso yes, by adding bouncy castle provider in application, problem solved. 
thanks.

**Comment by WarSame** [comment]
@serso @snazha-blkio Sorry for the delay. Thank you guys, that works! Adding the BC provider in the application onCreate resolved the issue.

**Comment by serso** [comment]
Great! I assume this issue can be closed then.

**Comment by Ayesha742** [comment]
I had the same problem and when I added the bouncy castle, the app crashed. Is there any way to fix this?

**Comment by serso** [comment]
@Ayesha742 providing a stack trace would be beneficial

**Comment by Ayesha742** [comment]
![image](https://user-images.githubusercontent.com/49033457/56681459-c1b4bb80-66e2-11e9-968d-c7ba679930d1.png)

**Comment by serso** [comment]
The stack trace is clearly different. It doesn't even seem to be related to Bouncy Castle or web3j.

**Comment by Ayesha742** [comment]
Here it is:
![image](https://user-images.githubusercontent.com/49033457/56682121-55d35280-66e4-11e9-98cc-73547add47bc.png)

**Comment by Ayesha742** [comment]
Hi, is there anything to fix this?

**Comment by serso** [comment]
@Ayesha742 what's the memory heap size you have on your phone/emulator? OOM exception might be caused by some other component in your app that eats too much RAM.

**Comment by kagile** [comment]
@serso There is no problem with RAM. It is occurring on my device as well with 6gb RAM and no other apps running.

**Comment by serso** [comment]
@kagile @Ayesha742 have you tried running https://github.com/serso/web3a?

**Comment by Ayesha742** [comment]
I created a new android project and used bouncy castle, now it is working

**Comment by nihaoxianghenhaochideyangzi** [comment]
要怎么解决啊.........................
