### ISSUE TITLE
send() does not work (well) in android version

### ISSUE THREAD

**Issue by nschapeler** [web3j/web3j#829]
Hi guys,
Thanks for the great library. However, when working on android with the 4.1.0-android release and binding with an http service over infura and trying to retrieve a web3clientversion instance, I noticed that if i do

`            Web3ClientVersion web3ClientVersion = web3.web3ClientVersion().sendAsync().get();`

everything's fine, while when i do

`            Web3ClientVersion web3ClientVersion = web3.web3ClientVersion().send();
`

it returns all sorts of errors.

**Comment by nschapeler** [comment]
You're correct, thanks!

**Comment by ravi-ranjan-oodles** [comment]
despite of using send() use sendAsync()
