### ISSUE TITLE
high-throughput ABI and RLP (enhancement)

### ISSUE THREAD

**Issue by esaulpaugh** [web3j/web3j#832]
ABI: full signature parsing. has tunable fuzz test.

RLP: new type support: floating point, chars,  booleans, negative integers. has (parsable) json-like RLP object notation. on-demand iterator-based decoding interface

Apache 2.0

https://github.com/esaulpaugh/headlong

**Comment by AlexandrouR** [comment]
Has there been any initial work done on this? We would like to explore how this could work.

We would need a PR with a proposal of integrating your library with web3j.

You can contact @iikirilov on gitter if you have any questions

**Comment by iikirilov** [comment]
@esaulpaugh Yes we would be open to this suggestion but it really depends on how it will be integrated with the library.

Our effort to integrate ABIv2 encoder has gone stale.

**Comment by esaulpaugh** [comment]
The key to a successful integration seems to be decoupling data encoding from transaction creation. I am told this Kotlin snippet was effective in integrating headlong and web3j and was successfully used on a testnet:

```
fun depositTokens(symbol: String, amount: BigDecimal) {
    val token_address = Numeric.toBigInt(getAddressFromSymbol(symbol))
    val f = Function.fromJson("""{ "constant": false, "inputs": [ { "name": "tokenAddress", "type": "address" }, { "name": "amount", "type": "uint256" } ], "name": "depositTokens", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }""")
    val amountInWei = toBigInt(amount, getDecimalsFromSymbol(symbol))
    println("About to deposit ${amountInWei} ${symbol}")
    val preEncode = f.encodeCallWithArgs(token_address, amountInWei)
    val hexString = Numeric.toHexString(preEncode.array())
    println("Hex string data for deposit: ${hexString}")
    val gasDetails = getGasPriceNLimit()
    val gasPrice = gasDetails[0]
    val gasLimit = gasDetails[1]
    val nonce = getWalletNonce()
    val rawTx = RawTransaction.createTransaction(nonce, gasPrice, gasLimit, xxxxxxx_address, BigInteger("0"), hexString )
    val signedTx = TransactionEncoder.signMessage(rawTx, wallet)
    val signedHex = Numeric.toHexString(signedTx)
    println("Signed hex msg ${signedHex}")
    var sendTx = web3.ethSendRawTransaction(signedHex).sendAsync().get()
    var txid = sendTx.transactionHash println("Txid for depositTokens Symbol: ${symbol}, Amount: ${amount} tx: ${txid}")
}
```

Here is a [decode snippet](https://imgur.com/a/pN7cFMy)

What do you think?

**Comment by esaulpaugh** [comment]
If you decide to further explore this I will be happy to collaborate. You will probably want to fork headlong and remove all the things you don't need (e.g. the Keccak impl).

**Comment by esaulpaugh** [comment]
Initially, the idea behind the creation of this issue was to simply add headlong.jar as a dependency so that its API would be available to users of web3j

**Comment by iikirilov** [comment]
> Initially, the idea behind the creation of this issue was to simply add headlong.jar as a dependency so that its API would be available to users of web3j

That is not an option. The library is already too big in my opinion to just add another dependency for the sake of it. If someone prefers to use headlong for RLP encoding/decoding then they can add headlong as a dependency to their project and achieve the same thing.

**Comment by AlexandrouR** [comment]
This is not longer relevant
