### ISSUE TITLE
Get the input data of a transaction with web3j

### ISSUE THREAD

**Issue by nicoflores95** [web3j/web3j#837]
How can I do a java method with web3j, where I can access a transaction through the txHash and thus get the input data.

![image](https://user-images.githubusercontent.com/44265969/50854034-bf606880-1362-11e9-8c51-aae06e385b54.png)

**Comment by MDhondt** [comment]
The `org.web3j.protocol.core.methods.response.Transaction` class has a `getInput()` function which retrieves the input data:

```java
public Optional<String> getTransactionInputByTransactionHash(String transactionHash) {
    try {
        EthTransaction ethTransaction = web3j.ethGetTransactionByHash(transactionHash).send();
        if (ethTransaction != null && ethTransaction.hasError()) {
            LOG.error("Exception while retrieving transaction from geth node: " + ethTransaction.getError().getMessage());
            return Optional.empty();
        }
        return ofNullable(ethTransaction).flatMap(EthTransaction::getTransaction).map(Transaction::getInput);
    } catch (Exception e) {
        LOG.error("Exception while retrieving transaction from geth node", e);
        return Optional.empty();
    }
}
```

**Comment by nicoflores95** [comment]
@MDhondt Thank you very much, I can recommend a method or function of web3j to decode the input data

**Comment by gunslingeratlarge** [comment]
@nicoflores95  hi, do u already find a way to decode input data?  It would be nice if you could share with me

**Comment by gunslingeratlarge** [comment]
@nicoflores95 That's exactly the same thing I did, just I used a js library called ethereum-input-data-decoder instead of web3js. My guess is this could be the best way we can find to address this issue...

**Comment by AlexandrouR** [comment]
Web3j can generate smart-contract wrappers which will do the decoding for you. More information [here](https://docs.web3j.io/smart_contracts.html).

If you need more fine grained control you can have a look at the generated wrappers and figure out how they do the decoding. An example of an ERC20 wrapper can be found [here](https://github.com/web3j/web3j/blob/master/contracts/src/main/java/org/web3j/contracts/eip20/generated/ERC20.java).

**Comment by gouzhiyuan** [comment]
@nicoflores95  nice solution, Thanks a lot
