### ISSUE TITLE
How to get signedTransferHash ?

### ISSUE THREAD

**Issue by GsBala** [web3j/web3j#840]
The below code describe how it's done in IOS.

 NSData *signedTransferHash = [[contractAddress callWithMethod:@"signedTransferHash(address,address,uint256,uint256,uint256)" arguments:@[tokenOwner, to, tokens, fee, nonce] error:&error] next:32 error:&error];

Also, You can check in "https://ropsten.etherscan.io/address/0x362fa7d41a47874cf5231dc12ac7ca1339d1090d#readContract" 

** Check-in 20. signedTransferHash .

So how to create an object of solidity contract in Android (Java)? 

Thanks in Advance.

**Comment by AlexandrouR** [comment]
> So how to create an object of solidity contract in Android (Java)?

Checkout the [docs](https://docs.web3j.io/smart_contracts.html)

**Comment by AlexandrouR** [comment]
In java the process would be

1. create an instance of web3j.
2. create a smart-contract wrapper for the solidity code.
3. call the function.

All the information to do these steps is in the docs linked above. Let me know if you run into any issues.
