### ISSUE TITLE
Using Infura in Android

### ISSUE THREAD

**Issue by nicail18** [web3j/web3j#844]
Is there a tutorial here to use infura in android? and getting metamask in infura. I'm new in ethereum. I trying to deploy contract but I can't get my wallet credentials from metamask. Is there another way to create wallet

**Comment by WarSame** [comment]
Infura: https://github.com/web3j/web3j#start-a-client

Android: https://github.com/web3j/web3j#start-sending-requests

Creating a wallet: https://github.com/web3j/web3j/blob/release/4.1-android/core/src/test/java/org/web3j/crypto/WalletUtilsTest.java#L70

Exporting private key in MetaMask: Menu-> Details -> Export Private Key

**Comment by nicail18** [comment]
I mean how can I access the wallet in metamask using java (android)

**Comment by WarSame** [comment]
They're both using the Ethereum blockchain so just use the same private key on the same blockchain(i.e. mainnet vs. Rinkeby).

**Comment by nicail18** [comment]
my wallet is in ropsten, I tried executing code of getting ethereum account in java(android) but it returns null. Does that mean that I should use rinkeby for testing?

**Comment by WarSame** [comment]
Use whichever network you feel like using. Did you initialize your URL to point to ropsten properly?

Does their basic example work for you?

Web3j web3 = Web3j.build(new HttpService(https://rinkeby.infura.io/)); 
Web3ClientVersion web3ClientVersion = web3.web3ClientVersion().send();
String clientVersion = web3ClientVersion.getWeb3ClientVersion();

Anyway, this is where debugging comes into play. Make unit tests to see if it works. Turn your debugger on and see what is failing or why it is returning null.

**Comment by nicail18** [comment]
yes I did initialize my ropsten url properly I copied the endpoint url in my infura account. but I cant get my eth account when I try executing this code:

Web3j web3 = Web3j.build(new HttpService("https://ropsten.infura.io"));
web3.ethAccounts().send().getAccounts()

it just returns null. I'm sorry if I ask too many questions, but I searched a lot about this problem.
 I really cant findy an answer

**Comment by nicail18** [comment]
Web3j web3 = Web3j.build(new HttpService(https://rinkeby.infura.io/));
Web3ClientVersion web3ClientVersion = web3.web3ClientVersion().send();
String clientVersion = web3ClientVersion.getWeb3ClientVersion();

When I run this code in an AsyncTask. It works. It actually gets the ClientVersion, 
I want to deploy a smart contract using java(android) but I can't access my ropsten account that have an ether so that I can deploy a smart contract

**Comment by WarSame** [comment]
Nice. I'm guessing your error was that you can't use blocking operations(like synchronous methods in web3j) on the main thread.

In order to access your ropsten account you need to export your private key and use it. I haven't done any smart contract stuff so can't help with that.

Example:
```
Credentials mycred = Credentials.create("0xsomeprivatekey");
```

**Comment by nicail18** [comment]
Hi sir! Thank you for your answer. Great help for our thesis project. I successfully accessed my eth account in ropsten by getting the private key thank you very much.
