### ISSUE TITLE
Web3j 4.1.0 - Web3jFactory

### ISSUE THREAD

**Issue by ladinek82** [web3j/web3j#845]
Hello, 
I have a problem with class Web3jFactory. I can't find it in source code and my Android Studio can't find it in library, too. I use version of library 4.1.0 and I write my application in language Kotlin. 

Can you help me? I don't know where is the problem. 

Thank you very much

**Comment by WarSame** [comment]
They have updated it to use the same code as the regular Web3j I believe. Example:

`    private Web3j createWeb3j(){
        WebSocketService webSocketService = new WebSocketService(INFURA_URL, INCLUDE_RAW_RESPONSES);
        try {
            webSocketService.connect();
        } catch (ConnectException e) {
            e.printStackTrace();
        }
        return Web3j.build(webSocketService);
    }
`

**Comment by JoaquimLey** [comment]
@ladinek82 I had the same issue, not sure if this was mistakenly removed from the latest version, my workaround was to create a factory `Java` class to abstract from the static method issue:
Let me know if this works for you too.

```java

import org.web3j.protocol.Web3j;
import org.web3j.protocol.Web3jService;
import org.web3j.protocol.http.HttpService;

import java.util.concurrent.ScheduledExecutorService;

public class Web3jFactory {

    /**
     * Construct a new Web3j instance.
     *
     * @param endpoint web3j service instance - i.e. HTTP or IPC
     * @return new Web3j instance
     */
    public static Web3j build(String endpoint) {
        return Web3j.build(new HttpService(endpoint));
    }

    /**
     * Construct a new Web3j instance.
     *
     * @param web3jService web3j service instance - i.e. HTTP or IPC
     * @param pollingInterval polling interval for responses from network nodes
     * @param scheduledExecutorService executor service to use for scheduled tasks.
     *                                 <strong>You are responsible for terminating this thread
     *                                 pool</strong>
     * @return new Web3j instance
     */
    public static Web3j build(Web3jService web3jService, long pollingInterval,
                       ScheduledExecutorService scheduledExecutorService) {
        return Web3j.build(web3jService, pollingInterval, scheduledExecutorService);
    }
}

```
