### ISSUE TITLE
org.web3j:core:4.1.0-android proguard

### ISSUE THREAD

**Issue by Aleksandr93** [web3j/web3j#847]
What proguard rules I should write for org.web3j:core:4.1.0-android?
I can't find any solution.
Please help me, Thanks!

**Comment by Aleksandr93** [comment]
I solve by this configuration

# Java8 rules
-dontwarn java8.util.**

# JNR Posix rules
-dontwarn jnr.posix.**

# JFFI rules
#-dontwarn com.kenai.**

# BouncyCastle rules
#-keep class org.bouncycastle.**
-dontwarn org.bouncycastle.jce.provider.X509LDAPCertStoreSpi
-dontwarn org.bouncycastle.x509.util.LDAPStoreHelper

# Keep Web3j classes serialized via reflection by Jackson
-keepclassmembers class org.web3j.protocol.** { *; }
-keepclassmembers class org.web3j.crypto.** { *; }
# Keep Web3j types as the library extracts data from type names at runtime (e.g. integer size of Int)
-keep class * extends org.web3j.abi.TypeReference
-keep class * extends org.web3j.abi.datatypes.Type

# Don't warn about Web3j's java.lang.SafeVarargs
#-dontwarn java.lang.SafeVarargs

-dontwarn org.slf4j.**

**Comment by snazha-blkio** [comment]
Thank you @Aleksandr93, I have made this into a wiki page to help others.
https://github.com/web3j/web3j/wiki

**Comment by tentenponce** [comment]
This gives an error:

`-keepclassmembers class org.web3j.protocol.** { ; }`

, I guess it should be (with asterisk (`*`):

`-keepclassmembers class org.web3j.protocol.** { *; }`

**Comment by tentenponce** [comment]
Still this also doesn't solved the problem for me, It still causes the `No static field PUBLIC_ONLY of type...`

This proguard config solves my problem: https://github.com/web3j/web3j/issues/675

```
-dontwarn com.fasterxml.jackson.databind.**
-keep class org.** {;}
-keep class com.fasterxml.jackson.core.** {;}
-keep interface com.fasterxml.jackson.core { ; }
-keep public class * extends com.fasterxml.jackson.core.*
-keep class com.fasterxml.jackson.databind.introspect.VisibilityChecker$Std.
-keep class com.fasterxml.jackson.databind.ObjectMapper.
-keep class com.fasterxml.jackson.databind.** {;}
-keep class com.fasterxml.jackson.databind.introspect.VisibilityChecker${;}
-keep interface com.fasterxml.jackson.databind { ; }
-keep public class * extends com.fasterxml.jackson.databind.*
-keep class com.fasterxml.jackson.annotation.** {;}
-keep interface com.fasterxml.jackson.annotation.** {*;}
```
