### ISSUE TITLE
[Help]Error in java with Web3j, replacement transaction underpriced Output from Server

### ISSUE THREAD

**Issue by nicoflores95** [web3j/web3j#861]
I am registering a batch of 500 transactions in a java application with web3j and after a while it gives me this error:

`java.lang.RuntimeException: Error processing transaction request: replacement transaction underpriced
Output from Server`

And the application code, register transaction in the smartcontract.

        public String CrearCertificado(CareerCertificate careercertificate, String id, String fecha, String nombre, String rutalumno, String instituto, String rutinstituto, String titulo, String totalhash, String fechatitulacion, String registronumber, String codigoV) throws Exception {

            String txhash;
        try{
            txhash = careercertificate
                .createCertificate(id, fecha, nombre, rutalumno, instituto, rutinstituto, titulo, totalhash, fechatitulacion, registronumber, codigoV)
                .send().getTransactionHash();
        if(txhash !=null || !txhash.equals("")){
                return txhash;
        }
        }catch(Exception e){

            System.err.println("Error 222-2 interno en el Metodo CrearCertificado en la clase  Conexion.java: "+e);

        }finally{
            id = null;
            fecha= null; 
            nombre= null; 
            rutalumno= null; 
            instituto= null; 
            rutinstituto= null; 
            titulo= null; 
            totalhash= null; 
            fechatitulacion= null; 
            registronumber= null; 
            codigoV = null;
        }
            return "222-1";
        }

To load the Contract

        private CareerCertificate loadContract(String contractAddress, Web3j web3j, Credentials credentials) {

        return CareerCertificate.load(contractAddress, web3j, credentials, GAS_PRICE, GAS_LIMIT);

    }

**Comment by AlexandrouR** [comment]
This will help you 
https://stackoverflow.com/questions/46349202/rinkeby-replacement-transaction-underpriced

**Comment by the-Mitu** [comment]
I have similar problem. I get the following error:

```
java.lang.RuntimeException: Error processing transaction request: replacement transaction underpriced
	at org.web3j.tx.TransactionManager.processResponse(TransactionManager.java:83) ~[core-4.4.0.jar:na]
	at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:64) ~[core-4.4.0.jar:na]
	at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:97) ~[core-4.4.0.jar:na]
[...]
```

while trying to perform tranasctions to a smart contract. @AlexandrouR , the question linked by you suggests removing the nonce field - however I only call generated class' method - I seem to have no control over the nonce.
