### ISSUE TITLE
How can I add a function of a smart contract in the Raw Transaction data in web3j?

### ISSUE THREAD

**Issue by nicoflores95** [web3j/web3j#863]
I want to add this contract function.

`careercertificate.createCertificate(string data);`

the Raw Transaction code

`    RawTransaction rawTransaction = RawTransaction.createTransaction(
        nonce,
        gasPrice,
        gasLimit,
        contractAddress,
        BigInteger.ZERO,
        data);//here
`

**Comment by AlexandrouR** [comment]
This is related to #908 check the last comment Ivaylo made and the example he gave.
