### ISSUE TITLE
Incorrect decoding of string arrays from contract calls

### ISSUE THREAD

**Issue by alunperkins** [web3j/web3j#867]
Web3J 4.1.1

For a simple smart contract method that returns a `string[] memory`
```
function getStrings() public view returns (string[] memory) {
        string[] memory retvalStrings = new string[](3);

        retvalStrings[0] = "aa";
        retvalStrings[1] = "bb";
        retvalStrings[2] = "cc";

        return retvalStrings;
    }
```
when calling the method with web3j it incorrectly decodes the return value and gives the following three-element list:
```
* ��
* bb
* cc
```

Debugging reveals that the raw input it is decoding is (displayed here as 11 32-byte lines)
```
0000000000000000000000000000000000000000000000000000000000000020
0000000000000000000000000000000000000000000000000000000000000003
0000000000000000000000000000000000000000000000000000000000000060
00000000000000000000000000000000000000000000000000000000000000a0
00000000000000000000000000000000000000000000000000000000000000e0
0000000000000000000000000000000000000000000000000000000000000002
6161000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000002
6262000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000002
6363000000000000000000000000000000000000000000000000000000000000
```
and it seems to parse the first three 32-byte parts as `uint`s, then the next four 32-byte parts as some long string of weird characters, then the next two 32-byte parts as "bb" and the final two 32-byte parts as "cc".

**Comment by iikirilov** [comment]
For context:

This functionality can only be used with `pragma experimental ABIEncoderV2;`

**Comment by iikirilov** [comment]
My gut instinct here is that this does not work because it is an experimental feature - we have not looked at any experimental solidity features in web3j

Someone will need to spend some more time looking at the RLP encoding/decoding features in web3j.

**Comment by iikirilov** [comment]
duplicate of #935
