### ISSUE TITLE
can't connect to blockchain with build.

### ISSUE THREAD

**Issue by compjotr** [web3j/web3j#870]
In newest version, Webfactory.build  is gone, and "build method " gives error messages.
errors:

W/System.err: java.lang.BootstrapMethodError: Exception from call site #59 bootstrap method
        at org.web3j.utils.Async.<clinit>(Async.java:19)
        at org.web3j.utils.Async.defaultExecutorService(Async.java:49)
        at org.web3j.protocol.core.JsonRpc2_0Web3j.<init>(JsonRpc2_0Web3j.java:88)
W/System.err:     at org.web3j.protocol.Web3j.build(Web3j.java:21)
      BlockchainController.web3(BlockchainController.kt:81)
        BlockchainController.getBalance(BlockchainController.kt:85)
        BlockchainController.createWallet(BlockchainController.kt:63)

**Comment by snazha-blkio** [comment]
Can you please take a look at #845? The documentation has been updated in 4.2.0 as Web3jFactory no longer exists.

Feel free to reopen if you are having issues.
