### ISSUE TITLE
web3.eth.estimateGas

### ISSUE THREAD

**Issue by guangxingmao** [web3j/web3j#872]
while i use estimateGas,
 {
	"value": "0x699601492d15a0",
	"from": "0x35bc9e5623306e5a8bb611c1ebf0cb5e5dfda836",
	"to": "0x46f1474ed03031ff40a3b6b37b6ff65ac4afd68d",
	"data": "0x5d73e2bf4132303139303231383030310000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000638363135373236383136343333000000000000000000000000000000000000006f7579616e670000000000000000000000000000000000000000000000000000"
}
from and to（'to' is ERC 20 token contract ） is same, only value and data is different，
while data = 0x5d73e2bf4132303139303231383030310000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000638363135373236383136343333000000000000000000000000000000000000006f7579616e670000000000000000000000000000000000000000000000000000, is ok ,but while data = 0x5d73e2bf4132303139303231383030310000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000438363135373236383136343333000000000000000000000000000000000000006f7579616e670000000000000000000000000000000000000000000000000000 is error。
is About data ?

**Comment by AlexandrouR** [comment]
Can you please provide the error logs.

**Comment by guangxingmao** [comment]
The error is "The execution failed due to an exception."

**Comment by AlexandrouR** [comment]
Please provide a code snippet of what you are trying to do or a way to replicate i cannot know that is 
the difference between 
`0x5d73e2bf4132303139303231383030310000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000638363135373236383136343333000000000000000000000000000000000000006f7579616e670000000000000000000000000000000000000000000000000000`
and 
`0x5d73e2bf4132303139303231383030310000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000438363135373236383136343333000000000000000000000000000000000000006f7579616e670000000000000000000000000000000000000000000000000000`
