### ISSUE TITLE
Contract.isValid() shouldn't compare "Metadata Hash"

### ISSUE THREAD

**Issue by p-s-dev** [web3j/web3j#874]
The "Metadata Hash" is some extra non-executable bytecode near the end of the contract bytecode.  This bytecode represent a hash of info such as the filename of the solidity file that was compiled.  Since it has no impact on the execution of the contract, it should be ignored curing the isValid() check.

here is an example where another code project excludes the metadata hash when checking contract validity.

https://github.com/ConsenSys/bytecode-verifier/blob/master/src/verifier.js#L87

**Comment by fcorneli** [comment]
This would indeed be interesting. A recompilation of the same solidity contract should not mark previous contracts as invalid if the actual bytecode is the same.

**Comment by antonydenyer** [comment]
The only methods that use it are `isValid` and `deploy` so it shouldn't cause any problems. But it would be better if there was a way to represent instances of contracts. e.g I have multiple deployments of the same contract.
