### ISSUE TITLE
How can I update account?

### ISSUE THREAD

**Issue by ssbg2** [web3j/web3j#875]
Hi,
I want to change account password with web3j(already known old password),but I can't find any method in source, am i missing somthing or its not there ? if not then what can be the alternative ?
Thanks.

**Comment by fcorneli** [comment]
See:
https://github.com/e-Contract/ethereum-tool/blob/master/src/main/java/be/e_contract/ethereum/tool/Update.java

**Comment by ssbg2** [comment]
> See:
> https://github.com/e-Contract/ethereum-tool/blob/master/src/main/java/be/e_contract/ethereum/tool/Update.java

thank you,I'll try this and post the result later.
