### ISSUE TITLE
Make word list used for mnemonic configurable

### ISSUE THREAD

**Issue by alessandroponzo** [web3j/web3j#886]
I need to add new mnemonic language word list, so I cloned the web3j locally. I want to import it as module in Android Studio doing File->New->Import Module but I got this error.

``  ERROR: Could not find method compile() for arguments [project ':utils'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
``

**Comment by iikirilov** [comment]
We should make the word list configurable. At the moment it is hard coded.
 See
`MnemonicUtils.populateWordList()`

**Comment by iikirilov** [comment]
Closing as duplicate of #919 

A proposal has been made on the work that needs to be done there
