### ISSUE TITLE
msg.sender not set properly in contract function call

### ISSUE THREAD

**Issue by mawenpeng** [web3j/web3j#89]
I have a contract like this:
_contract SenderTest {
    mapping (address => string) public senderName;
    function setName(string name)
    {
        senderName[msg.sender]=name;
    }
    function getName() constant returns (string)
    {
        return senderName[msg.sender];
    }
}_

I run this contract with code as follows:

_SenderTest senderTest = SenderTest.deploy(web3j, credentials, gasPrice, gasLimit, initialValue).get();
TransactionReceipt txReceipt = senderTest.setName(new Utf8String("Jonathan")).get();
System.out.println("TX Hash: "+txReceipt.getTransactionHash());
Utf8String name=senderTest.getName().get();
System.out.println("From getName(): " + name.getValue());
//get from default public function
name=senderTest.senderName(new Address("0x8e82130455613bb1915ca2fb1e006cda9e1df819")).get();
System.out.println("From senderName(): " + name.getValue());_

The outputs are:

_TX Hash: 0xaaf324233f5842b66beaa1cab8a313a0964999deff0ed77d91c0745532eb65dc
From getName(): 
From senderName(): Jonathan_

Issues:
senderTest.getName() returns nothing, but default public function senderName() returns the right value. 
I also send JSON RPC eth_call by curl to call getName(), the result is positive.
This means the msg.sender is not the right value when running senderTest.getName() in JAVA.

I debugged web3j core code, found that in web3j code, when sending JSON RPC to ethereum node at last, the key "from" was not set properly in JSON payload.
Need to set "from" as the ethereum account address from the credentials.
I saw code from org.web3j.protocol.core.methods.request.Transaction:

_public static Transaction createEthCallTransaction(String to, String data) {
    return new Transaction(null, null, null, null, to, null, data);
}_

The first null is "from".

**Comment by conor10** [comment]
Great spot! Thank you for finding the underlying issue here, I've just checked in a fix.

**Comment by mawenpeng** [comment]
Thanks for the quick fix.
