### ISSUE TITLE
Adding support of hardware wallets to web3j

### ISSUE THREAD

**Issue by aaitor** [web3j/web3j#892]
Hardware wallets are considered the best standard for wallets management because of better security. Supporting the most popular hardware wallets in web3j (Ledger & Trezor) would allow users to take advantage of that security.

**Comment by iikirilov** [comment]
Agreed. We will need to flesh out an approach as this is a significant project. But first, can we discuss how signing happens.

Right now, web3j effectively loads a private key in a `Credentials` object and that is what is used to sign a transaction. From my limited understanding, the Ledger & Trezor can do signing for us and it would be bad practice to expose the private key from the hardware wallet (if that is even possible). So I assume there is some kind of API where we can send an unsigned transaction to the hardware wallet and get back a signed transaction.

Considering the number of changes that will have to take place this feature will be aimed for web3j 5

**Comment by JoaquimLey** [comment]
Just to provide some more context to future readers, it is **not** possible to expose or event fetch the private keys from the HW wallet, that's where the security comes from.

This feature would be awesome to get as it would provide a bigger layer of security, I was searching online and Ledger has a lot of OSS [here on github](https://github.com/LedgerHQ), I haven't read in detail but couldn't find any example/sdk/integration(s).

There is however this repository: 
- https://github.com/m2049r/xmrwallet 

Which has integration with ledger (never tested the app, and haven't had the time to read the code in detail).

**Comment by tjdragon** [comment]
Hi. I agree. It is critical to be able to support this for Web3J. I have started an implementation using Web3J, I have issues with the acceptance of the transaction on-chain though - but the cryptography part seems to be working. I am a bit puzzled - but this is the approach taken: subclass RawTransactionManager and override getNonce & sign:

`    @Override
    public String sign(final RawTransaction rawTransaction) {
        final byte[] encodedTransaction = TxCryptoHelper.encodeTransaction(rawTransaction, chainId);
        final byte[] messageHash = TxCryptoHelper.keccakHash(encodedTransaction);
        final BigInteger[] sig = HSMHelper.signHSM(messageHash, keyId);
        final BigInteger sigR = sig[0];
        final BigInteger sigS = sig[1];

        final byte[] messageHash256 = TxCryptoHelper.sha256Hash(messageHash);

        final BigInteger publicKeyValue = TxCryptoHelper.publicKeyAsBigInt(publicKeyBytes);
        final int recId = TxCryptoHelper.getKeyIndex(sigR, sigS, messageHash256, publicKeyValue);

        final String finalSignedTransaction = TxCryptoHelper.buildSignedTransaction(recId, sigR, sigS, rawTransaction, chainId);
        return finalSignedTransaction;
    }`

signHSM gets the rawSig and we just need to extract R & S:

`final byte[] rawSignature = signResponse.getSignature().toByteArray();

        final BigInteger[] sigComps = toAsn1Primitive(rawSignature);
        final BigInteger sigR = sigComps[0];
        BigInteger sigS = sigComps[1];`

etc. But unfortunately it is rejected on-chain - so I am investigating

**Comment by tjdragon** [comment]
Update on my last comment: I have managed to make it work, ie, integrate Web3J with a HSM! Merry Christmas!

**Comment by tjdragon** [comment]
Great. Thanks
