### ISSUE TITLE
extend web3j method

### ISSUE THREAD

**Issue by mingjingc** [web3j/web3j#894]
I run go-ethereum by POA consensus algorithm, so I want to extend web3j rpc request methods to vote and get vote information. Could I extend web3j like web3 to meet like below the pictures. If not how can I do it. Please can someone  give me a hand? Thanks!

![image](https://user-images.githubusercontent.com/17808422/54577539-2c653e00-4a37-11e9-9263-3db341c68e6f.png)
![image](https://user-images.githubusercontent.com/17808422/54577555-35560f80-4a37-11e9-91af-3bd4b0dcc636.png)

**Comment by iikirilov** [comment]
Yes this is possible. It would make sense to put this in a `poa` module. It would look similar to the `geth` and `parity` modules except it will only hold the poa methods that you need.

**Comment by cunteng008** [comment]
js is easy to do it, but java I think it hard.

**Comment by cunteng008** [comment]
> Yes this is possible. It would make sense to put this in a `poa` module. It would look similar to the `geth` and `parity` modules except it will only hold the poa methods that you need.

**Comment by cunteng008** [comment]
> Yes this is possible. It would make sense to put this in a `poa` module. It would look similar to the `geth` and `parity` modules except it will only hold the poa methods that you need.

js is easy to do it, but java I think it hard.
