### ISSUE TITLE
Error while compiling wrapper class generated from a crowdsale contract extending from RefundablePostDeliveryCrowdsale. Error: cannot override finalize().

### ISSUE THREAD

**Issue by sowmyakannan** [web3j/web3j#896]
I have created a crowdsale contract that extends from RefundablePostDeliveryCrowdsale. web3j generates the wrapper class successfully.  However the wrapper classes do not compile and give an error like so:

Error:(204, 43) java: finalize() in com.reit.resreitsmartcontractwrapper.TokenSale cannot override finalize() in java.lang.Object
  return type org.web3j.protocol.core.RemoteCall<org.web3j.protocol.core.methods.response.TransactionReceipt> is not compatible with void.

I am overriding the finalize() method in my crowdsale contract that extends from RefundablePostDeliveryCrowdsale which extends Finalizable that has a finalize() method to be overridden. 

Any suggestions or workarounds for this issue?

**Comment by iikirilov** [comment]
finalize() is a protected method in `Object.java`. The workaround would be to rename the method in the generated class. It will still call finalize() in the contract.

A long-term solution would be to modify the code generator such that it prepends protected methods from Object.java with an underscore

**Comment by AlexandrouR** [comment]
Looks like this was solved by #776

**Comment by iikirilov** [comment]
#776 is related but `finalize()` is a method and is not covered (i.e. it is not a keyword in java). So this needs to check against the method list of `Object.java` and probably the method list of `Contract.java`

**Comment by AlexandrouR** [comment]
The Object class has a finalize method that is protected. If it is within your control you can change the method name in the contract or write a wrapper around it. This is the only workaround I can think of.
