### ISSUE TITLE
Create walletFile from seed

### ISSUE THREAD

**Issue by mtamburrano** [web3j/web3j#897]
Hi there,

I see that when using a non-Bip39 wallet you can choose between `generateNewWalletFile` (that generates a new `ECKeyPair` and then a new `WalletFile`) and `generateWalletFile` (that accepts an existing `ECKeyPair` and then generates a `WalletFile` from it).
I think the same should be possible with the Bip39 wallets, but at the moment there is only the method `generateBip39Wallet` that doesn't accept as argument an existing seed, so it can only generate a fresh new wallet.
Is there some particular reason why is not possible to create a `WalletFile` from a mnemonic string for a Bip39Wallet? Did I miss something?
If not, are you interested to accept a PR to add this feature?

Thank you

**Comment by mtamburrano** [comment]
@marcello-morena

**Comment by iikirilov** [comment]
@mtamburrano are you looking for `WalletUtils.loadBip39Credentials(String password, String mnemonic)` ?

**Comment by marcello-morena** [comment]
Hi, I'm working with @mtamburrano on this and I'll answer your question. Basically, `WalletUtils.loadBip39Credentials(String password, String mnemonic)` just creates a `Credentials` object. Instead, we need to write a Bip39 wallet file to disk and that wallet file needs to be generated from a mnemonic provided by us. 

If you work with non-Bip39 wallet files,  you've got two choices. You can use `WalletUtils.generateNewWalletFile(String password, File destinationDirectory, boolean useFullScrypt)` and end up with a randomly generated `ECKeyPair` object, or can use `WalletUtils.String generateWalletFile(String password, ECKeyPair ecKeyPair, File destinationDirectory, boolean useFullScrypt)` and provide your own `ECKeyPair` object.

If you work with Bip39 wallet files, instead, you can just use `WalletUtils.generateBip39Wallet(String password, File destinationDirectory)` and end up with a random `ECKeyPair` object, derived from a randomly generated mnemonic. You cannot provide your own mnemonic. This makes impossible to import an existing wallet by just providing its mnemonic, which is what we need.

Did we miss something? Is there any other way to do this? If not, are you interested to accept a PR to add this feature?

Thank you

**Comment by iikirilov** [comment]
I understand. We don't have a function to do this. PR is welcome :)

**Comment by mtamburrano** [comment]
The proposed PR introduces a new method named `generateBip39WalletFromMnemonic`, in addition to the old one `generateBip39Wallet`.
To be consistent with other method names for wallet generation, we should have renamed `generateBip39Wallet` into `generateNewBip39WalletFile` and to name the new method `generateBip39WalletFile`, but we decided to leave the old method name to stay the same for retro-compatibility.
Let us to know if you prefer to rename both methods instead for consistency
