### ISSUE TITLE
ethCallResult.reverts is false if the call is reverted without any message

### ISSUE THREAD

**Issue by jimy74** [web3j/web3j#902]
This boolean should still return true if the call execution been reverted without any message.

(I will implement it myself in Web3j if needed, anyone know how to conclude that the call been reverted?)

**Comment by iikirilov** [comment]
Good spot. A PR is welcome

**Comment by jimy74** [comment]
I still don't know how to conclude that a call to a contract has revert without message.

If the method should return something it's easy, because when it's revert without message it the return value is empty.

 But **if the method should not return anything, then good luck. 

How to detect a revert without message in this case?**

**Comment by iikirilov** [comment]
@jimy74 maybe check the transaction receipt?

**Comment by jimy74** [comment]
A "call" with web3 is made to be not mined at the end.
So there is nothing to do with the transaction receipt I guess unfortunately.

**Comment by iikirilov** [comment]
@jimy74 ofcourse, my bad. This is tricky because on the client side there is no information to indicate whether a call has failed or not if it does not return any values. The node does have this information though - it is not transmitted back to the client. Maybe an EIP is required for this if you have a solid use-case...

**Comment by AlexandrouR** [comment]
What is the use case for using `ethCall` on a function that does not return anything? My understanding is that `ethCall` is used to get contract state - i.e. calling a `view` function which returns a value of a variable in the contract. From this point of view if the function does not return a value then we can never know if the call reverted or not.

Maybe the resolution here is to remove the `reverts` function. What would be the implication of doing this?

**Comment by kostind** [comment]
@AlexandrouR @iikirilov 
We can use ethCall for executing contract methods without transaction and getting the reason for the revert.
It can be done for an already failed transaction using input data.
Please take a look at PR https://github.com/web3j/web3j/pull/1022

**Comment by oasis-zhou** [comment]
The function executeCall of Contract class gets the value which include the revert message,but the decode function ingores the message and returns "".
private List<Type> executeCall(Function function) throws IOException {
        String encodedFunction = FunctionEncoder.encode(function);
        EthCall ethCall = (EthCall)this.web3j.ethCall(Transaction.createEthCallTransaction(this.transactionManager.getFromAddress(), this.contractAddress, encodedFunction), this.defaultBlockParameter).send();
        String value = ethCall.getValue();
        return FunctionReturnDecoder.decode(value, function.getOutputParameters());
    }`

**Comment by oasis-zhou** [comment]
The TransactionReceiptProcessor can't get the revert message when processes the TransactionReceipt,but the TransactionReceipt‘s status isn't OK.
Optional<TransactionReceipt> sendTransactionReceiptRequest(String transactionHash) throws IOException, TransactionException {
        EthGetTransactionReceipt transactionReceipt = (EthGetTransactionReceipt)this.web3j.ethGetTransactionReceipt(transactionHash).send();
        if (transactionReceipt.hasError()) {
            throw new TransactionException("Error processing request: " + transactionReceipt.getError().getMessage());
        } else {
            return transactionReceipt.getTransactionReceipt();
        }
    }
