### ISSUE TITLE
Gas estimate for ERC20 token transfer

### ISSUE THREAD

**Issue by SteadyAction** [web3j/web3j#908]
I am having very hard time to solve my problem :(
I am trying to get gasLimit estimation for ERC20 token transfer
How do I do it?
I tried to use web3j.ethEstimateGas method but it requires a Transaction as a parameter. But I have no idea how I can have a Transaction for ERC20 token transfer.
please help

**Comment by iikirilov** [comment]
[https://github.com/iikirilov/web3j/blob/structparamgen/codegen/src/test/resources/solidity/complexstorage/build/ComplexStorage.abi](https://github.com/iikirilov/web3j/blob/structparamgen/codegen/src/test/resources/solidity/complexstorage/build/ComplexStorage.abi)

**Comment by iikirilov** [comment]
```
Transaction transaction = Transaction.createContractTransaction(
              <from address>,
              <nonce>,
              BigInteger.valueOf(<gas price>),  // we use default gas limit
              "0x...<smart contract code to execute>"
      );
```

**Comment by iikirilov** [comment]
the `<smart contract code to execute>` is the first 4 bytes of the function signature + the rlp encoded parameters

**Comment by SteadyAction** [comment]
@iikirilov can you give an example code? I dont get it. Please help

**Comment by iikirilov** [comment]
@SteadyAction This is the resource you need -> https://solidity.readthedocs.io/en/v0.5.3/abi-spec.html
