### ISSUE TITLE
Synchronization Issues in FastRawTransactionManager

### ISSUE THREAD

**Issue by mawenpeng** [web3j/web3j#91]
I send multi threads requests (20), each thread create a contract object from same contract class. Some requests fail with duplicated nonce. Errors are like "nonce too low".

If I change FastRawTransactionManager to make "nonce" to be static and change getNonce() to synchronize at class level, like:

private static BigInteger nonce = BigInteger.valueOf(-1);
BigInteger getNonce() throws IOException {
synchronized(FastRawTransactionManager.class) {
if (nonce.signum() == -1) {
nonce = super.getNonce();
} else {
nonce = nonce.add(BigInteger.ONE);
}
}
return nonce;
}

It will run well.
Probably, we need to change the code like above.

**Comment by conor10** [comment]
Are you creating a single or multiple FastRawTransactionManager instances?

**Comment by mawenpeng** [comment]
Sorry, my bad. I'm creating multiple FastRawTransactionManager instances. I should use single instance for the same contract.
Thanks for the reply.
