### ISSUE TITLE
No such algorithm: ECDSA for provider BC

### ISSUE THREAD

**Issue by pohonduit** [web3j/web3j#915]
Hi, i'm trying to create/generate wallet on Android P, but found this issue,
any idea what should i do?

`Caused by: java.security.NoSuchAlgorithmException: no such algorithm: ECDSA for provider BC
        at sun.security.jca.GetInstance.getService(GetInstance.java:87)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
        at java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:304)
        at org.web3j.crypto.Keys.createSecp256k1KeyPair(Keys.java:58)
        at org.web3j.crypto.Keys.createEcKeyPair(Keys.java:75)
        at org.web3j.crypto.Keys.createEcKeyPair(Keys.java:70)
        at org.web3j.crypto.WalletUtils.generateNewWalletFile(WalletUtils.java:61)
        at org.web3j.crypto.WalletUtils.generateFullNewWalletFile(WalletUtils.java:40)`

**Comment by Dawnton** [comment]
Try this : Add the code below in your custom Application

` @Override
    public void onCreate() {
        super.onCreate();
        setupBouncyCastle();
    }

    private void setupBouncyCastle() {
        final Provider provider = Security.getProvider(BouncyCastleProvider.PROVIDER_NAME);
        if (provider == null) {
            // Web3j will set up the provider lazily when it's first used.
            return;
        }
        if (provider.getClass().equals(BouncyCastleProvider.class)) {
            // BC with same package name, shouldn't happen in real life.
            return;
        }
        // Android registers its own BC provider. As it might be outdated and might not include
        // all needed ciphers, we substitute it with a known BC bundled in the app.
        // Android's BC has its package rewritten to "com.android.org.bouncycastle" and because
        // of that it's possible to have another BC implementation loaded in VM.
        Security.removeProvider(BouncyCastleProvider.PROVIDER_NAME);
        Security.insertProviderAt(new BouncyCastleProvider(), 1);
    }`

**Comment by iikirilov** [comment]
@pohonduit are you using web3j-android?

**Comment by kartik-karz** [comment]
So, I tried using that and after using the setup function the application is crashing with 
```
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 1040 byte allocation with 1000 free bytes and 1000B until OOM, max allowed footprint 268435456, growth limit 268435456
        at org.bouncycastle.util.Arrays.clone(Unknown Source:5)
        at org.bouncycastle.crypto.generators.SCrypt.SMix(Unknown Source:31)
        at org.bouncycastle.crypto.generators.SCrypt.MFcrypt(Unknown Source:22)
        at org.bouncycastle.crypto.generators.SCrypt.generate(Unknown Source:38)
```

**Comment by pohonduit** [comment]
@Dawnton thanks mate, it works now. @iikirilov  yes i'm using web3j-android, and it solve my problem by adding BouncyCastle

@kartik-karz  you might need to handle the creation of wallet, in my case i used RxJava schedulling it into io, and it works for my case

**Comment by rahulbhatia-rb** [comment]
@pohonduit Can you send the code, I don't have an idea about RX Schedulers.

**Comment by DomAmato** [comment]
I'm runnning into the same problem, I tried adding the code recommended by @Dawnton but have the same problem as @kartik-karz. I would recommend reopening this issue or documenting a way to fix it.

**Comment by DomAmato** [comment]
also this seems to be related to an android Pie issue: https://github.com/square/okhttp/issues/4183

**Comment by DomAmato** [comment]
seems like the fix should be just to remove the specification to BC in this line:
https://github.com/web3j/web3j/blob/64d99e4fb33992f5e71b7f1c3bd8d0ada48553c0/crypto/src/main/java/org/web3j/crypto/Keys.java#L58

**Comment by enuoCM** [comment]
Hi,  why web3j-android uses org.bouncycastle instead of org.spongycastle? Does it replace the package name when building?

**Comment by DomAmato** [comment]
I noticed when doing debugging that the OOM error propagates at this line:

https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/crypto/Wallet.java#L131

Further it only happens when it tries to create a standard wallet like it does here:

https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/crypto/WalletUtils.java#L71

A light wallet will create successfully so something about the parameters sent to Scrypt for standard wallets cause it to crash

**Comment by AlexandrouR** [comment]
Reopening as this issue needs a resolution

**Comment by AlexandrouR** [comment]
> Hi, why web3j-android uses org.bouncycastle instead of org.spongycastle? Does it replace the package name when building?

@enuoCM I am not sure why bouncycastle is used in the android branch. The only related thing I found was #618 which does introduce spongeycastle.

**Comment by DomAmato** [comment]
Stale but not fixed, still an issue

**Comment by FrankyHo** [comment]
@Dawnton remove and insert provider work!

**Comment by hamidbayati** [comment]
@Dawnton  tnx it works

**Comment by harshil64** [comment]
@hamidbayati Did it worked for u in Android , Could you help with the code ? As even I am getting the same ECDSA error while implementing web3j on Android 10
or @FrankyHo @DomAmato @rahulbhatia-rb @pohonduit ,
@kartik-karz Did you got the solution

**Comment by cawfree** [comment]
Setting `android:largeHeap="true"` under your app's `<application>` tag in the `AndroidManifest.xml` seemed to fix this issue for me.

**Comment by siddhpuraamitr** [comment]
> So, I tried using that and after using the setup function the application is crashing with
> 
> ```
> Caused by: java.lang.OutOfMemoryError: Failed to allocate a 1040 byte allocation with 1000 free bytes and 1000B until OOM, max allowed footprint 268435456, growth limit 268435456
>         at org.bouncycastle.util.Arrays.clone(Unknown Source:5)
>         at org.bouncycastle.crypto.generators.SCrypt.SMix(Unknown Source:31)
>         at org.bouncycastle.crypto.generators.SCrypt.MFcrypt(Unknown Source:22)
>         at org.bouncycastle.crypto.generators.SCrypt.generate(Unknown Source:38)
> ```

I have also same issue 

java.lang.OutOfMemoryError: Failed to allocate a 1036 byte allocation with 16777216 free bytes and 29MB until OOM; failed due to fragmentation (required continguous free 16384 bytes for a new buffer where largest contiguous free 12288 bytes)

**Comment by mohamedelshami** [comment]
Looking through the history of #1289 unsure why this fix has not been adopted. Please reopen if this issue still needs to reported.

**Comment by markusbug** [comment]
Just switched from Android 12 to 13, and the setupBouncyCastle method used to work but now it doesn't again. It throws the same error. Any idea why @Dawnton ?

**Comment by marctatham** [comment]
So, here to try help after facing a similar issue. A couple things:
- be very cautious when generating keys that **are** encodable to String/ByteArray, it's always better to use the variants that are NOT encodable to String/ByteArray that are generated by the AndroidKeyStore, if you can use this, then use this.
- of course, life is not one-size fits all, and so if you must manage these keys yourself in some way:

Something along these lines will likely work for you, 
```
    Security.getProviders().forEach { provider ->
        if (provider.name == "BC") {
            Security.removeProvider(provider.name)
        }
    }
    Security.addProvider(BouncyCastleProvider()) 
    val keyPair = Keys.createEcKeyPair()  // 🪄🔑
```

**Comment by vishallandepatil** [comment]
Security.removeProvider(BouncyCastleProvider.PROVIDER_NAME);
    Security.insertProviderAt(new BouncyCastleProvider(), 1);

this work for me
