### ISSUE TITLE
Sending Private key to server side

### ISSUE THREAD

**Issue by koptan** [web3j/web3j#916]
Hi , 

I am trying to build new Dapp application for our startup , I am facing an issue with  with signing the transaction from server side , because i need to  know the private key for the client (wallet) and it's **not best practices** to send the the private key over the network . 

So the question is  : Did anyone solve this issue , or I should keep all the code in frontend-side ?

**Comment by AlexandrouR** [comment]
This is not a web3j issue.

My recommendation is to consult a software design specialist.

In terms of how other apps do it to the best of my knowledge. Either you maintain the private keys of your clients on the server side. I.e. it is a centralised app. You are bearing the risk. You can also delegate the management of the private keys to a third party that specialises in handling private keys.

Alternatively, do the signing of transactions on the client side. The client maintains the keys. The client has the risk. If they loose their keys, they lose everything.

Disclaimer: I take no responsibility for your actions.
