### ISSUE TITLE
A problem with transactions in web3j

### ISSUE THREAD

**Issue by lfrickel** [web3j/web3j#92]
Here is the Java code 

```
import java.math.BigInteger;
import java.util.Arrays;
import java.util.concurrent.ExecutionException;

import org.web3j.abi.FunctionEncoder;
import org.web3j.abi.TypeReference;
import org.web3j.abi.datatypes.Function;
import org.web3j.abi.datatypes.Uint;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.methods.request.Transaction;
import org.web3j.protocol.http.HttpService;

public class SendEvent {
	
	public static String myAddr = "0x00110c50f26af8ebfda8b88d35d2b2e53ad75f28";
	public static String contractAddr = "0xf45e5febd63e5f6225a1b08429fc332f3b231826";


	public static void main(String[] args) {

		try {
//			Parity web3 = Parity.build(new HttpService()); 
			Web3j web3 = Web3j.build(new HttpService());

			String encodedFunction = FunctionEncoder.encode(new Function("triggerEvent", 
					Arrays.asList(new Uint(BigInteger.valueOf(17))),											
					Arrays.asList(new TypeReference<Uint>() {})));
			String from = myAddr;
			
			BigInteger gasPrice = BigInteger.valueOf(20000000000L); 
			BigInteger gasLimit = BigInteger.valueOf(500000L);
			String to = contractAddr;//ParityTestSubsription.contractAddr;
			BigInteger nonce = null;

			Transaction transaction = Transaction.createFunctionCallTransaction(from, nonce, gasPrice, gasLimit, to, encodedFunction);

			org.web3j.protocol.core.methods.response.EthSendTransaction transactionResponse = web3.ethSendTransaction(transaction).sendAsync().get();

			String transactionHash = transactionResponse.getTransactionHash();
			System.out.println("transactionHash: " + transactionHash);
		} catch (InterruptedException e) {
			e.printStackTrace();
		} catch (ExecutionException e) {
			e.printStackTrace();
		}
	}
}

```

that should call the function `triggerEvent` in the contract

```
pragma solidity ^0.4.11;
contract EventTest {                
  event NumberEvent(uint indexed number);   

  function triggerEvent(uint val) returns (uint) { 
    NumberEvent(val);
    return 123;
  }                                 
}
```

Unfortunately, those transactions that the program returns are not visible in the `https://kovan.etherscan.io/tx/<txhash>`

Someone can explain to me: HOW CAN IT BE?

Thankful in advance for the answer!

**Comment by conor10** [comment]
Please can you show the transaction output - see https://docs.web3j.io/trouble.html#i-want-to-see-details-of-the-json-rpc-requests-and-responses if you're not sure on how to log the responses.

You should see a log event returned by the transaction with a value present, such as demonstrated here https://github.com/web3j/web3j/blob/master/src/test/java/org/web3j/protocol/core/filters/LogFilterTest.java#L13.

**Comment by lfrickel** [comment]
@conor10 Thank you for participating.
I found this problem. This was in the test chain KOVAN and in TestRPC. The same actions on the main chain caused a successful result.
I did not want to burden the main chain with test contracts, but I had to.
Thank you all again!

The contrakt: 0x2783318E7C1c6d1Aab46F0773264f74Fd0a8313d

**Comment by lfrickel** [comment]
@conor10 By the way, does web3j work on Android with Parity? At me both variants `Web3j web3 = Web3jFactory.build(new HttpService());` and `Parity web3 = Parity.build(new HttpService());` give out an error. Although on Java (not Android) the second version works correctly, and the first option works correctly on Android with geth.

**Comment by k06a** [comment]
Looks like I have the same issue. Don't see any logs for transaction with `ganache-cli`.

**Comment by iikirilov** [comment]
@k06a This is an unrelated issue. Please open a new issue or seek help on [gitter](https://gitter.im/web3j/web3j?utm_source=share-link&utm_medium=link&utm_campaign=share-link).
