### ISSUE TITLE
Best Practices on Private Key Management

### ISSUE THREAD

**Issue by Struka9** [web3j/web3j#924]
Hi, I'm looking forward implementing web3j in my app but not sure what is the currently accepted best practices when managing private keys on mobile devices, anyone can show me the light on this?

**Comment by AlexandrouR** [comment]
This is not a web3j issue. We do not give advice for security best practice. Consult a security expert.

In terms of storing the private key on a mobile device you can store the wallet file that web3j generates. Please refer to #916 for more context.
