### ISSUE TITLE
Unsupported type encountered: tuple , while generating Contract Wrappers

### ISSUE THREAD

**Issue by araa47** [web3j/web3j#927]
web3j version: 4.2.0 
platfrom: macOS Mojave 

I am trying to interact with a contract that has tuple in its data type, so I start with trying to generate the contract wrapper using the following command. 

```web3j solidity -a Mediator.abi -b Mediator.bin -o java/ -p abc.com.btc ```

I get the following error message: 

``` Unsupported type encountered: tuple```

Tried a contract that doesn't have tuples , and it seems to work without issues. How would i go about building a contract wrapper for this contract?

**Comment by iikirilov** [comment]
related to #935

**Comment by iikirilov** [comment]
Closing as this duplicate. Web3j does not currently support ABIv2 but there is some work. Follow the link in the previous comment to stay up to date.
