### ISSUE TITLE
Maven Plugin to generate Java Classes

### ISSUE THREAD

**Issue by h2mch** [web3j/web3j#93]
I combined the web3j library with the solc library to create a maven plugin. This plugin can create the java wrapper classes directly out of the solidity contract files. 
see: https://github.com/h2mch/web3j-maven-plugin
I can use this plugin as follow:

```
             <plugin>
                 <groupId>com.zuehlke.blockchain</groupId>
                 <artifactId>web3j-maven-plugin</artifactId>
                 <version>1.0-SNAPSHOT</version>
                 <configuration>
                     <soliditySourceFiles>
                     <packageName>com.zuehlke.blockchain.model</packageName>
                     <sourceDestination>src/main/java</sourceDestination>
                         <directory>src/main/resources</directory>
                         <includes>
                             <include>**/*.sol</include>
                         </includes>
                     </soliditySourceFiles>
                 </configuration>
             </plugin>
```

After I execute the goal `web3j:generate-sources` the java classes are created. 

It would be nice, if I could include this maven plugin into the web3j git repo. What do you mean?

**Comment by conor10** [comment]
@h2mch - this is fantastic, it's something I'd had at the back of my mind for a while! I was curious what you were thinking of when you submitted your previous PR :)

My only thoughts are:

1. ethereumj-core has a lot of dependencies - ideally we should just have the solcJ-all dependency (or create our own version if simpler)
2. Hopefully someone will now be inspired to write a gradle version...

I'd suggest a dedicated repo at https://github.com/web3j/ for the project if that works for you?

**Comment by h2mch** [comment]
Before I spent more time into the plugin, I wanted to know if it is an option for you.
So I already removed the ethereum-core library and other dependencies ([see last update](https://github.com/h2mch/web3j-maven-plugin/commit/eefd59af41d8dd28cfbcfa6991fb2cfbf64cf518))

That's fine. Can you create a dedicated repo on https://github.com/web3j?

**Comment by conor10** [comment]
Certainly - you can accept the invitation at https://github.com/web3j/web3j-maven-plugin/invitations. I've made you an admin, so you can add any additional users.

**Comment by conor10** [comment]
@h2mch it makes sense for this to be pushed as an artifact to Maven central. For an idea of the settings, you can refer to https://github.com/web3j/web3j/blob/master/build.gradle#L202.

**Comment by h2mch** [comment]
It is on my "roadmap". It is the first time I'm publishing artifact to a public maven repo. So, it could take some time. So, thank you for the hint.

**Comment by berlinguyinca** [comment]
would there be any chance to have a truffle version of this amazing plugin?

**Comment by flefevre** [comment]
it will be great to have a truffle version :-)
