### ISSUE TITLE
private key create error!!

### ISSUE THREAD

**Issue by boy-good** [web3j/web3j#934]
If the generated private key starts with 0x0, in fact the first 0 will be deleted, resulting in the private key being incorrect. For example, 0x00124564... The final result is 0x124564

i use this fun:
Numeric.toHexStringNoPrefix(ecKeyPair.getPrivateKey())

**Comment by boy-good** [comment]
![image](https://user-images.githubusercontent.com/39320533/58019784-f0368280-7b38-11e9-9f23-7c4443d98a1b.png)

like this key

One less, in fact, there is a 0 in front.

**Comment by AlexandrouR** [comment]
Hey in the example you provided i don't think that there should be a 0 in from because you called toHexStringNoPrefix if you take a look inside the function you will see what happens when the withPrefix is false. If this is still an issue please let me know

**Comment by boy-good** [comment]
> 嘿，在你提供的例子中，我不认为应该有一个0 in因为你调用了toHexStringNoPrefix，如果你看看函数内部你会看到当withPrefix为false时会发生什么。如果这仍然是一个问题，请告诉我

Is the private key fixed at 66?

**Comment by boy-good** [comment]
> Hey in the example you provided i don't think that there should be a 0 in from because you called toHexStringNoPrefix if you take a look inside the function you will see what happens when the withPrefix is false. If this is still an issue please let me know

![image](https://user-images.githubusercontent.com/39320533/60801834-46738980-a1aa-11e9-960d-343ea3e785eb.png)
only “value.toString(16)”
Like the two examples above, The private key at the beginning of 6e6bf9438... cannot be used if it does not fill 0 in front.

**Comment by AlexandrouR** [comment]
i see it seems that when a number starts with zero eg 001 the zeros in front are discarded for example if you try to print 001 it will print 1. One way of getting around this is to catch the length of the key after it is returned from toHexStringNoPrefix and append zeros in front or at a given index.

**Comment by boy-good** [comment]
> i see it seems that when a number starts with zero eg 001 the zeros in front are discarded for example if you try to print 001 it will print 1. One way of getting around this is to catch the length of the key after it is returned from toHexStringNoPrefix and append zeros.

Thank you very much, I just did it.

**Comment by AlexandrouR** [comment]
Sorry just realised there is a function for that, try using toHexStringNoPrefixZeroPadded it should work.
