### ISSUE TITLE
ERC20 getBalance at Block n

### ISSUE THREAD

**Issue by mesudip** [web3j/web3j#936]
I need a snapshot of the ERC20 balance of users at a particular time. 
Is there a way to execute getBalance() at particular block height?

**Comment by AlexandrouR** [comment]
Yes you can, you can use ethCall and pass in the transaction and default block parameter

**Comment by mesudip** [comment]
#### yeh, its possible using ethCall.

But using ethCall means, abiEncoding the function and it's parameters.  What's the point of generating the contractFunctions if you have to resort back to using ethCall? 

I think it should be straightforward like `erc20.balanceof("0xabcd").blockParameter(blockNo).send();`

**Comment by AlexandrouR** [comment]
I don't think that this proposal fits into the architecture. Have a look at #972 

I think this will sort out your issue.
