### ISSUE TITLE
Problems running web3j in container in GCP

### ISSUE THREAD

**Issue by mehranshakeri** [web3j/web3j#938]
I'm working on a Spring boot application which uses Web3j to communicate with Ethereum clients. The result is Dockerized and works fine on my local PC and a private server.
But running _the same docker image_ on Google Cloud Platform fails with the following error.

```
java.lang.NoClassDefFoundError: Could not initialize class org.web3j.crypto.Sign
```

Here is the failing code:
```
Credentials credentials = Credentials.create(pk);
```

My Gradle dependencies include:
```
compile group: 'org.bouncycastle', name: 'bcprov-jdk15on', version: '1.60'
compile group: 'org.web3j', name: 'core', version: '4.3.0'
```

I can see Gradle downloads all the libraries related to Web3j and all are present in the running Docker container (in GCP and local).

```
core-4.3.0.jar
crypto-4.3.0.jar
...
```

I had a look inside the jar files and I see both jar files contain the same package name `org.web3j.crypto`. I doubt if that is the source of issue. But I don't understand why the same docker file can run locally without any problem but it fails in GCP!

This is how I build docker file:
```
gradle wrapper --gradle-version 4.8
./gradlew clean build
tar -zxf build/libs/*.jar -C build/libs/
docker build -t $IMAGE_NAME .
```

And here is the docker file:
```
FROM openjdk:8-jre-alpine

RUN mkdir -p /app/config
ADD "application.yml" /app/config/spring-config.yml

COPY build/libs/BOOT-INF/lib /app/lib
COPY build/libs/META-INF /app/META-INF
COPY build/libs/BOOT-INF/classes /app
ENTRYPOINT ["java","-cp","app:app/lib/*","com/*/*/*/Application", "--spring.config.location=/app/config/spring-config.yml"]
```

I also tried following gradle dependencies (based on issue #539) but it didn't help:
```
    compile group: 'org.bouncycastle', name: 'bcprov-jdk15on', version: '1.60'
    compile('org.web3j:core:4.3.0') {
        exclude group: 'org.web3j', module: 'crypto'
    }
    compile('org.web3j:crypto:4.3.0'){
        exclude group: 'org.web3j', module: 'utils'
    }
    compile('org.web3j:utils:4.3.0'){
        exclude group: 'org.bouncycastle', module: 'bcprov-jdk15on'
    }
```

Anyone facing the same issue? 
Yes, It's a docker file, so I expect it should run the same in all platforms, but it doesn't! :?

Thank you in advance for any hint.

**Comment by iikirilov** [comment]
We do not have access to GCP to replicate this, but we have run web3j in Azure and AWS so this is a strange issue...

**Comment by mehranshakeri** [comment]
I have the same opinion. I rewrote my project using web3js and it's running so far without any issue.

**Comment by bacta22** [comment]
I have the same problem :3 
Anyone facing the same issue?
Yes, It's a docker file, so I expect it should run the same in all platforms, but it doesn't! :?

Thank you in advance for any hint.
