### ISSUE TITLE
RawTransactionManager signAndSend will throw TxHashMismatchException

### ISSUE THREAD

**Issue by Boliang-Lu** [web3j/web3j#939]
RawTransactionManager transactionManager = new RawTransactionManager(web3j, credentials);
                    new Thread(new Runnable() {
                        @Override
                        public void run() {
                            try {
                                EthSendTransaction ethSendTransaction = transactionManager.sendTransaction(BigInteger.valueOf(1000L), BigInteger.valueOf(30000L), acount2, "", BigInteger.valueOf(1000L));
                                String transactionHash = ethSendTransaction.getTransactionHash();
                                System.out.println("transactionHash:" + transactionHash);
                            }catch (Exception e) {
                                e.printStackTrace();
                            }

                        }
                    }).start();

**Comment by AlexandrouR** [comment]
Hey, I tried to replicate using the code snippet you posted and there was no problem.  If this is still an issue can you provide the error logs please.

**Comment by Boliang-Lu** [comment]
Thank you. I've solved it, because the version of the test environment used is too low.
