### ISSUE TITLE
Does web3j work on Android with Parity? 

### ISSUE THREAD

**Issue by lfrickel** [web3j/web3j#94]
Does web3j work on Android with Parity? At me both variants `Web3j web3 = Web3jFactory.build(new HttpService());` and `Parity web3 = Parity.build(new HttpService());` give out an error. Although on Java (not Android) the second version works correctly, and the first option works correctly on Android with geth.

Thanks in advance

**Comment by conor10** [comment]
What's the exception you're seeing?

**Comment by conor10** [comment]
Closing as no further information provided.
