### ISSUE TITLE
Request logging vs provided OkHttpClient 

### ISSUE THREAD

**Issue by hmijail** [web3j/web3j#953]
## Feature description
The web3j request logging is only enabled when web3j creates its own OkHttpClient.
This client is private, so there is no way to customize it afterwards (like eg. setting its timeout value). 
So for example it is impossible to have at the same time a custom OkHttpClient + request logging.   
I can imagine 2 ways to improve on this:
- Give access to the internal client once created
- Add logging to an external client

**Comment by vincentk** [comment]
To a degree, a similar issue was raised (and addressed) in https://github.com/web3j/web3j-spring-boot-starter/pull/4, though I would argue that indeed it would be nice to allow library users to customize the `OKHttpClient` that is being used.

**Comment by SweeXordious** [comment]
Closing. https://github.com/web3j/web3j/pull/1387 merged
