### ISSUE TITLE
Contract wrapper event flowables should use eth_subscribe

### ISSUE THREAD

**Issue by dphilipson** [web3j/web3j#954]
The `someEventFlowable` methods on smart contract wrappers are implemented using `eth_newFilter` and polling. It would be great if instead it used `eth_subscribe` when possible (i.e. when the backing Web3j uses WebSockets) in order to reduce network usage by avoiding polling.

**Comment by AlexandrouR** [comment]
That feature is still experimental. 
https://github.com/ethereum/wiki/wiki/JSON-RPC#json-rpc-api
