### ISSUE TITLE
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

### ISSUE THREAD

**Issue by chrismcgregor** [web3j/web3j#962]
# SSLException thrown for both Infura and Nodesmith

I am getting a SSLException thrown for both Infura and Nodesmith. I am using v4.3.1 of web3j. 

# Infura Example
```
Web3j web3 = Web3j.build(new InfuraHttpService("https://mainnet.infura.io/v3/api-key"));
Web3ClientVersion web3ClientVersion = web3.web3ClientVersion().send();
System.out.println(web3ClientVersion.getWeb3ClientVersion());
```

# Nodesmith Example
```
 String nodesmithUrl = String.format("https://ethereum.api.nodesmith.io/v1/mainnet/jsonrpc?apiKey=%s", apiKey);
Web3j web3 = Web3j.build(new NodesmithHttpService(nodesmithUrl));
 EthBlock.Block block = web3.ethGetBlockByNumber(DefaultBlockParameterName.LATEST, false).send().getBlock();
System.out.printf("The latest block number was %d. It contained %d transactions.\n", block.getNumber(), block.getTransactions().size());
```

**Comment by AlexandrouR** [comment]
Hmm this is interesting i think it is similar to #583  what is your exception message and what android version are you running ?

**Comment by chrismcgregor** [comment]
# Exception message
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

# Environment
**Java 1.8**
**MacOS 10.14.5**

**Comment by iikirilov** [comment]
@chrismcgregor I cannot reproduce - both infura and nodesmith are working.

It is something to do with your network... Maybe you have some firewall issue?

**Comment by iikirilov** [comment]
@josh-richardson could you spend 2 seconds to verify please

**Comment by chrismcgregor** [comment]
I think it something on my side (network or computer). Sorry for the trouble.
