### ISSUE TITLE
WalletUtils.generateNewWalletFile() take InputStream

### ISSUE THREAD

**Issue by chrismcgregor** [web3j/web3j#965]
## WalletUtils.loadCredentials() take InputStream
It would be nice if WalletUtils.loadCredentials() took InputStream as parameter.  This way I can store wallets on AWS S3 and pass the InputStream.

**Comment by iikirilov** [comment]
This is an opinionated enhancement. You can solve this as a user by converting the `InputStream` into a type that is accepted by `WalletUtils.loadCredentials(...)`

At this time we will not be accepting this enhancement.

To make this a more solid proposal we would require a more thorough list of enhancements that would benefit web3j integration with AWS. You would need to be able to justify an `aws` package in web3j.
