### ISSUE TITLE
Revert Reason is not returned depending of the client that is used

### ISSUE THREAD

**Issue by fosgate29** [web3j/web3j#966]
I get different Exception messages when a **revert** happens depending of the client I use. I am running Ubuntu 18.04.2 LTS.
If I run ganache-cli (version `Ganache CLI v6.4.3 (ganache-core: 2.5.5)), I get this Exception:
`ganache-cli`
**VM Exception while processing transaction: revert You must send ether**
>java.lang.RuntimeException: Error processing transaction request: VM Exception while processing transaction: revert You must send ether
	at org.web3j.tx.TransactionManager.processResponse(TransactionManager.java:72)
	at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:52)
	at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:88)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:291)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:275)
	at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$4(Contract.java:326)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
	at TestRevertTest.main(TestRevertTest.java:32)

But when I run same code using Parity, (version `version Parity-Ethereum/v2.5.5-stable-3ebc769-20190708/x86_64-linux-gnu/rustc1.36.0`) I don't get the revert reason. I get a different Exception:
`parity --chain dev`
**Transaction has failed with status: 0x0. Gas used: 4000000. (not-enough gas?)**
>org.web3j.protocol.exceptions.TransactionException: Transaction has failed with status: 0x0. Gas used: 4000000. (not-enough gas?)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:297)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:275)
	at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$4(Contract.java:326)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
	at TestRevertTest.main(TestRevertTest.java:32)

Here are the files used for the tests:
[testRevertWeb3j github](https://github.com/fosgate29/testRevertWeb3j)

**Comment by AlexandrouR** [comment]
@fosgate29 how did you compile the contract ?

**Comment by fosgate29** [comment]
truffle.js:
```javascript
module.exports = {
  // Configure your compilers
  compilers: {
    solc: {
       version: "0.5.10", 
       settings: {
        optimizer: {
          enabled: true,
          runs: 200
        },
       }
    }
  }	
};
```
1st) `truffle compile`
2nd) I use gradlew and Eclipse, but here is: `org.web3j.codegen.TruffleJsonFunctionWrapperGenerator TestRevert.json`

**Comment by AlexandrouR** [comment]
I tested both ganache and parity and i can confirm that this is happening i will look more into it to see what is going on

**Comment by AlexandrouR** [comment]
so i did a bit of digging and found [this](https://github.com/paritytech/parity-ethereum/issues/8068). It looks like the issue is from parity. 
Let me know what you think.

**Comment by kostind** [comment]
The following workaround can be used in JS. It prints transaction revert reason to the console, tested in Kovan.
web3.eth.call - Executes a message call transaction, which is directly executed in the VM of the node, but never mined into the blockchain.

`try {
            await tokenRegistry.methods.methodName(params).send({from: accounts[0]});
        } catch (e) {
            try {
                await tokenRegistry.methods.methodName(params).call({from: accounts[0]});
            } catch (e) {
                let error = JSON.parse("{" + e.message.split("{")[1]);
                let data = error.data;
                console.log(web3.utils.toAscii("0x" + data.replace("Reverted ", "").substr(138)).replace(/\u0000/g, ""));
            }
        }`

I think something similar can be used in Java.
I've tried to use web3j.ethCall, but without any success.

**Comment by kostind** [comment]
web3j.ethCall didn't help.

ganache-cli: VM Exception while processing transaction: revert You must send ether
parity: VM execution error.

**Comment by fosgate29** [comment]
I kept investigating it and Parity doesn't return the Revert Reason yet. 
To be able to get the Revert reason we could replay the transaction. But you have to add extra lines to be able to do that.
My suggestion here would be to add the transaction hash to the exception. 

org.web3j.tx.Contract.java
```java
TransactionReceipt executeTransaction(...)
        (....)
        if (!receipt.isStatusOK()) {
            throw new TransactionException(
                    String.format(
                            "Transaction has failed with status: %s. "
                                    + "Gas used: %d. (not-enough gas?)",
                            receipt.getStatus(),
                            receipt.getGasUsed()));
        }

        return receipt;
    } 
```

Suggested improvement org.web3j.tx.Contract.java - add transaction hash info into the exception
```java
TransactionReceipt executeTransaction(...)
        (....)
        if (!receipt.isStatusOK()) {
            throw new TransactionException(
                    String.format(
                            "Transaction has failed with status: %s. "
                                    + "Gas used: %d. (not-enough gas?)",
                            receipt.getStatus(),
                            receipt.getGasUsed()),
                            receipt.getTransactionHash());
        }

        return receipt;
    } 
```

When you have the transaction hash, you can store it and use it later. Right now it throws and you loose this information.

**Comment by falconwoods** [comment]
It's been almost 2 years and the issue still exists......

**Comment by fosgate29** [comment]
> It's been almost 2 years and the issue still exists......

It is a problem with Parity. Parity is not on development anymore and were archived.
