### ISSUE TITLE
No serializer found for class com.fasterxml.jackson.databind.util.LRUMap and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)

### ISSUE THREAD

**Issue by mbeelal** [web3j/web3j#968]
# _Android Proguard not working_
No serializer found for class com.fasterxml.jackson.databind.util.LRUMap and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.web3j.protocol.core.Request["web3jService"]->org.web3j.protocol.http.HttpService["objectMapper"]->com.fasterxml.jackson.databind.ObjectMapper["_deserializationConfig"]->com.fasterxml.jackson.databind.DeserializationConfig["_base"]->com.fasterxml.jackson.databind.cfg.BaseSettings["_classIntrospector"]->com.fasterxml.jackson.databind.introspect.BasicClassIntrospector["_cachedFCA"])

## Environment
_Describe the environment in which the issue occurs_
- Web3j version - 4.2.0-android
- Java or Android version - 9
- Operating System

## Additional context

Here is proguard file.

-dontobfuscate
-dontpreverify
-dontusemixedcaseclassnames
-printconfiguration
-optimizations !code/simplification/arithmetic,!field/*,!class/merging/*,!code/allocation/variable
-keepattributes *Annotation*, Signature, Exceptions, InnerClasses, SourceFile, LineNumberTable

-dontwarn com.fasterxml.jackson.databind.**
-keep class com.fasterxml.jackson.core.** { *; }
-keep interface com.fasterxml.jackson.core { *; }
-keep class com.fasterxml.jackson.databind.** { *; }
-keep interface com.fasterxml.jackson.databind { *; }
-keep class com.fasterxml.jackson.annotation.** { *; }
-keep interface com.fasterxml.jackson.annotation.** { *; }

-keep class * extends androidx.navigation.NavArgs
-keep class jnr.ffi.provider.FFIProvider

-dontwarn javax.naming.**
-dontwarn org.w3c.dom.bootstrap.**
-dontwarn java.beans.**
-dontwarn build.**
-dontwarn android.test.**
-dontwarn java.lang.management.**
-dontwarn org.slf4j.impl.**
-dontwarn java8.util.**
-dontwarn com.kenai.**
-dontwarn jnr.posix.**
-dontwarn com.crashlytics.android.**

-dontnote java.lang.SafeVarargs
-dontnote junit.framework.**
-dontnote junit.runner.**
-dontnote com.android.org.conscrypt.**
-dontnote dalvik.system.CloseGuard
-dontnote kotlin.internal.**
-dontnote kotlin.reflect.jvm.internal.ReflectionFactoryImpl
-dontnote org.apache.harmony.xnet.provdier.jsse.SSLParametersImpl
-dontnote org.conscrypt.**
-dontnote sun.nio.ch.**
-dontnote sun.misc.**
-dontnote sun.security.ssl.SSLContextImpl
-dontnote com.google.android.gms.**
-dontnote com.google.firebase.**
-dontnote android.widget.Space
-dontnote java8.**

**Comment by AlexandrouR** [comment]
If you disable Proguard and try to recreate is there any issue ?

**Comment by mbeelal** [comment]
@AlexandrouR yes without Proguard it works fine. and also I am able to make it work by removing 
 `-allowaccessmodification` proguard rule

**Comment by AlexandrouR** [comment]
@mbeelal Ok, what can we do in web3j to fix this. Unfortunately we do not have the expertise in this area to be able to propose a solution.

**Comment by Evert0x** [comment]
I'm currently having the same issue. But I removed `proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'` from my build.gradle. And I'm still not able to make it work. Do you have any tips? @mbeelal

Her is my issue. #1202
