### ISSUE TITLE
Handle crypto changes in Android P and onward

### ISSUE THREAD

**Issue by DomAmato** [web3j/web3j#974]
# Google is changing how crypto works in newer version of android
https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html

I discussed this slightly in this issue already: https://github.com/web3j/web3j/issues/915

but since it was a closed issue I felt it needed an actively open issue to bring attention to the problem.

**Comment by AlexandrouR** [comment]
please continue the conversation on #915 as it has all of the context
