### ISSUE TITLE
0x response from ethCall causes array out of bounds exception

### ISSUE THREAD

**Issue by conor10** [web3j/web3j#98]
When a smart contract method is called where a party doesn't have permission to view it, such as in Quorum, an exception is thrown in web3j instead of providing a null/optional value.

**Comment by slowtokyo** [comment]
Hi there, do you mind providing a bit more of an in depth explanation as to why this decision was made? It broke a quarter or so of our Solidity unit tests that were expecting the contract to throw, not return null. Throwing seems more consistent with the [Solidity docs](http://solidity.readthedocs.io/en/develop/frequently-asked-questions.html#when-returning-a-value-of-say-uint-type-is-it-possible-to-return-an-undefined-or-null-like-value).

Is there something in the pipeline or something that you're preparing for?

Either way, thanks as always for a great tool!
