### ISSUE TITLE
Deploy contract using raw transaction

### ISSUE THREAD

**Issue by holyantony** [web3j/web3j#99]
I am trying to deploy a contract using rawTransaction class from an android device using below code

```
List<Type> inputParameters = new ArrayList<>();
inputParameters.add(new Utf8String("10"));

// encode the function with given inputs
String functionEncoder = FunctionEncoder.encodeConstructor(inputParameters);
RawTransaction.createContractTransaction( nonceCount, gasPrice, gasLimit, new BigInteger("1"), contractCode + functionEncoder);
```
The inputParameters which i am sending in createContractTransaction() is not visible in contract(after deployment)

**Comment by conor10** [comment]
What do you mean by not visible? Have you made them accessible in the smart contract?

Also, have you considered using the web3j smart contract wrappers instead? See https://docs.web3j.io/smart_contracts.html#smart-contract-wrappers for details.

**Comment by conor10** [comment]
Closing as no futher comment received.
