### ISSUE TITLE
how to get tokens  balance from address

### ISSUE THREAD

**Issue by githubityu** [web3j/web3j#992]
# _Issue_title_
get tokens blance or Get Address Tokens

## _Issue_description_
I want get tokens balance but I don't know how to do it

Get Address Tokens
Retrieves the tokens this address is holding.

## _Issue_context_
help me

**Comment by AlexandrouR** [comment]
Take a look at the docs [here](https://docs.web3j.io/contracts.html?highlight=erc20).
You can call the balanceOf function that take in the address you want to get the balance.
